### ISSUE TITLE
I found an example of a local file without jQuery

### ISSUE THREAD

**Issue by alexbodn** [mholt/PapaParse#1000]
That's not something I'm asking you to fix, but I'm reporting good functionality:

See the source below, which I found at: https://portalzine.de/dev/importing-csv-files-with-html5-and-papa-parse/

<!DOCTYPE html>
<html>
	<head>
		<script type="text/javascript" charset="utf-8" src="https://unpkg.com/papaparse@latest/papaparse.js">
		</script>
	</head>
	<body>
		<input type="file" name="File Upload" id="txtFileUpload" accept=".csv" />
		<script>
			document.getElementById('txtFileUpload').addEventListener('change', upload, false);

function upload(evt) {
        var data = null;
        var file = evt.target.files[0];
        var reader = new FileReader();
        reader.readAsText(file);
        reader.onload = function(event) {
                var csvData = event.target.result;
                var data = Papa.parse(
                	csvData,
                	{preview: 10}
                );
                console.log(data);
        };
        reader.onerror = function() {
                alert('Unable to read ' + file.fileName);
        };
}
		</script>
	</body>
</html>

thanks again for papaparse!

**Comment by pokoli** [comment]
Sorry but I do not uderstand what is the issue you are reporting. Papaparse can wrok wihtout jQuery, so I do not see any issue here.
