### ISSUE TITLE
Delimiter detection issue with decimal values

### ISSUE THREAD

**Issue by benjaminh** [mholt/PapaParse#1005]
I'm using PapaParse v. 5.3.2.

I have some input data with the following structure and decimal values :
```
X\t\Y\t\Z
120,5\t50,3\t2,35
...
```

When parsing this kind of csv file, Papaparse choose to use the comma as a delimiter instead of the tabulation `\t`.
The first row is then parsed as `Array("X\tY\t\Z", "__extra_parsed")`.

Yet, I don't have the problem with other similar structures :
```
X;Y;Z
120,5;50,3;2,35
...
```

Everything works fine in that case: the file is correctly parsed.

Is this some kind of internal priority within the auto-detection function ?
I'm not sure about whether this is a real issue or an intended feature, but at least this is some edge case to be considered.

Any ideas why tabulation is not used as the delimiter, contrary to semi-colon ?

**Comment by pokoli** [comment]
In such case it is better that you specify the separator instead of letting paparase guess the right delimiter.
