### ISSUE TITLE
Parse string with \n chars

### ISSUE THREAD

**Issue by pawelkowalak** [mholt/PapaParse#1027]
I must be doing something wrong, but I have this input string: "username,verb,object_resource,decision,count\nalice,create,cronjobs,forbid,149" and I can't get papaparse to parse it. Demo page parses it like this:

<img width="335" alt="image" src="https://github.com/mholt/PapaParse/assets/271001/43d88112-1107-4cd4-9791-6ae712c30a48">

What I'm doing wrong? Do I need to replace \n with newlines before parsing?

**Comment by janisdd** [comment]
Yeah, you're doing something wrong...

This works on the demo page, in the browser developer console

```js
Papa.parse("username,verb,object_resource,decision,count\nalice,create,cronjobs,forbid,149")
```

You can see that `\n` is only a new line if it is used in strings, not in text input in HTML fields.
If the user types a new line (Enter), then `\n` is appended to a js variable.
If you enter `\n` in the HTML input fields, `\` is converted to `\\` and then `n` is added to the js variable, resulting in `\\n` (no line break, but a slash and the character `n`)
