### ISSUE TITLE
Header = true not working

### ISSUE THREAD

**Issue by atinyasian** [mholt/PapaParse#1061]
When setting the header in config to "true", the first row will not be interpreted as field names correctly.

`this.#csvParser.parse(this.currentData, {
          delimiter: "",
          newline: "",
          header: true,
          dynamicTyping: false,
          complete: (results) => {
          console.log("Results: ", results.data);
          this.headerRow = results.data.splice(0,1)[0];
          this.csvContent = results.data; 
}`

Result, if header = "true":
<img width="752" alt="error_header_config_result" src="https://github.com/user-attachments/assets/5922cfcb-c24e-4c94-aab1-4930cd723164">

_____

Result, if header = "false":
<img width="405" alt="error_header_config_result_correct" src="https://github.com/user-attachments/assets/3d7615ed-72a6-47fd-b1cd-ba17b11b7836">

This is the csv file:

<img width="482" alt="error_header_config" src="https://github.com/user-attachments/assets/11afd320-dfd8-4fa8-a12a-40a238fcccd8">

**Comment by pokoli** [comment]
What you are posting is the expected behaviour.
