### ISSUE TITLE
dynamicTyping boolean parsing failing

### ISSUE THREAD

**Issue by tristan-fgol** [mholt/PapaParse#108]
Hi,

excel and google spreadsheets when dealing with booleans tend to write the value out as an Uppercase TRUE or FALSE. When then using dynamicTyping: true in PapaParse these values aren't converted to javascript boolean values and instead are just parsed as strings!

Is this intended behaviour?

**Comment by Grovkillen** [comment]
When querying SQL we get boolean values as "False" and "True". Should I need to take care of that myself or is it something for papaparse to handle?

**Comment by pokoli** [comment]
@Grovkillen PapaParse has an option for dynamic typing which will convert booleans into proper types. You should[ set this value on the configuration](https://www.papaparse.com/docs#config).

**Comment by Grovkillen** [comment]
Thanks! It's now working.

**Comment by oliver-dungey** [comment]
I have been using dyanmic typing and had to add this as CSV's tend to end up as `True/TRUE/False/FALSE` i.e. the `dynamicTyping` doesn't seem to handle booleans very well:
```
transform: (value: string, field: string) => {
      if (value.toLowerCase() === 'true') return true;
      if (value.toLowerCase() === 'false') return false;
      return value.length > 0 ? value : undefined;
    },
```

**Comment by ckarsan** [comment]
> I have been using dynamic typing and had to add this as CSV's tend to end up as `True/TRUE/False/FALSE` i.e. the `dynamicTyping` doesn't seem to handle `boolean` very well:
> 
> ```
> transform: (value: string, field: string) => {
>       if (value.toLowerCase() === 'true') return true;
>       if (value.toLowerCase() === 'false') return false;
>       return value.length > 0 ? value : undefined;
>     },
> ```

Would be great to have this and a setting like "TransformStringToBoolean" where this can happen, although understand might hit performance issues on large files, its the only thing that worked for our use case also.
