### ISSUE TITLE
`worker: true` breaks parsing when minified production settings are used

### ISSUE THREAD

**Issue by tony-cocco** [mholt/PapaParse#114]
Hello again!

Ran into another issue. If you'll recall my parse command:

```
Papa.parse(input, {
        header: true,
        dynamicTyping: true,
        worker: true,
        step: function(row) {
          // do stuff...
        },
        complete: function() {
          // stuff
        },
        error: function(err) {
          //stuff
        }
      });
```

Everything works fine until I go with `grunt build` and run in production (node w/ express). When this command gets run from prod I get: 

`Uncaught TypeError: Cannot read property 'defaultView' of undefined`. 

I tried using the papaparse.min.js to determine if it's grunt's uglify that is busting it but that seems to have no effect as the grunt task still concats and uglifies everything together. (I'm using the default gruntfile that the yeoman angular-fullstack-generator creates.)

After a bunch of tests I found that it works again when I comment out `worker: true`. Which is simple enough to do. The only thing I could find that might be related is this [SO](https://stackoverflow.com/questions/3936211/jquery-cannot-read-property-defaultview-of-undefined-error). I know the worker makes the call async, so perhaps some context is being lost somewhere?

I'll be leaving out the worker for the time being, but if you discover a fix that'd be great!

Thanks!

**Comment by no-more** [comment]
Hello,

I know it's old and closed, but when I ugglify the code (gulp-ugglify-1.5.1) I have an error : 
Uncaught TypeError: Cannot read property 'window' of undefined

I don't have it if I disable the webworker, or when not minified.

Thanks.

**Comment by tony-cocco** [comment]
Don't concat it with other files. I assume the gulp task is doing something similar to the grunt one.

**Comment by no-more** [comment]
Hello,

Thanks.
Isn't there a way to handle this in the code (I mean by adding some kind of injection)?

In my config I currently have only one file for all js libs.
