### ISSUE TITLE
Problems parsing escaped quotes mixed with delimiters

### ISSUE THREAD

**Issue by allenlee85** [mholt/PapaParse#121]
I am trying to represent the following data in a CSV row:

<table>
<tr>
<td>1</td><td>cnonce="",nc=""</td><td>2</td>
</tr>
</table>

My CSV is formatted as follows:

<pre>"1","cnonce="""",nc=""""","2"</pre>

However, parsing this CSV row results in the following array:

<table>
<tr>
<td>1</td><td>cnonce=""<td>nc="""""</td><td>2</td>
</tr>
</table>

Issues:

<ol>
<li>Second field is being split into two fields.</li>
<li>Extra quotes are being added in the field containing "nc=".</li>
</ol>

Could you please take a look?

Thanks!

**Comment by medjessy** [comment]
Still experiencing this issue using 4.1.x
