### ISSUE TITLE
result contains empty line even keepEmptyRows or skipEmptyLines defined 

### ISSUE THREAD

**Issue by chandanpasunoori** [mholt/PapaParse#122]
``` javascript
Papa.parse(file, {
    delimiter: ",",
    header: true,
    keepEmptyRows:false,
    skipEmptyLines: true,
    complete: function(results) {
        console.log(results.data);
        $rootScope.$apply(function(){
            $rootScope.rowCollection = results.data;
            $rootScope.showTable = true;
        });
    }
});
```

I have changed configs true/false, and also removing but nothing seems to me working

may be I'm wrong 

![capture](https://cloud.githubusercontent.com/assets/3172168/5217120/5bf6f184-7662-11e4-9e4f-c582f720ef78.PNG)
![capture2](https://cloud.githubusercontent.com/assets/3172168/5217119/5bf65224-7662-11e4-95d3-2640b8b76de7.PNG)
![capture3](https://cloud.githubusercontent.com/assets/3172168/5217121/5bf70192-7662-11e4-883a-865c2d653fce.PNG)

**Comment by bluej100** [comment]
I would vote for incorporating some allFieldsEmpty logic. I think most people would probably expect that behavior from a skipEmptyLines flag.

**Comment by mholt** [comment]
There are merits to both. The counter-argument to this is two-fold: 1) that "empty" becomes ambiguous, and 2) that removing or skipping "non-empty" lines after-the-fact isn't the job of the parser.

I could see just as much value in the case where only a certain field (like an identifier or status field) is empty, and you would skip it all the same.

In 2.x and prior, Papa actually did all these things, but it made it hard to explain to people and added complexity/slowness to the code. I still prefer that this is done by the user according to their preferences.

(Filtering results isn't hard, especially if streaming/chunking the input -- only save what rows you want.)

**Comment by bluej100** [comment]
That makes sense. Thanks for your time.
