### ISSUE TITLE
Nested structures

### ISSUE THREAD

**Issue by evliu** [mholt/PapaParse#134]
I was wondering if there would any support for parsing/unparsing nested structures, for instance:

``` json
[{
     a: {
          b: 'one',
          c: 'two',
          d: {
               e: 'three'
          }
     },
     f: 'four'
},
...
]
```

into field columns like
`a.b, a.c, a.d.e, f`
or something like that.

Thanks!

**Comment by PAEz** [comment]
Here's how I converted the output to an object....
http://plnkr.co/edit/8XqkQL?p=preview
...its real simple code but worked for me ;)
Its not that hard to make something for your individual needs.
