### ISSUE TITLE
Travis CI integration

### ISSUE THREAD

**Issue by bluej100** [mholt/PapaParse#141]
It's great that this project has a solid unit test suite. It would be nice to show that off with a Travis CI badge in the readme and to have automatic verification of pull requests.

http://docs.travis-ci.com/user/getting-started/

I'm happy to do this.

**Comment by mholt** [comment]
Let's keep this issue in the loop with #155 which is about using a real test framework.

**Comment by Turbo87** [comment]
this should be resolved by #233 now

**Comment by mholt** [comment]
Yep
