### ISSUE TITLE
Get rid of copyAndValidateConfig - feedback

### ISSUE THREAD

**Issue by mholt** [mholt/PapaParse#145]
For reference, here's the function in question:

```javascript
// Replaces bad config values with good, default ones
function copyAndValidateConfig(origConfig)
{
	if (typeof origConfig !== 'object')
		origConfig = {};

	var config = copy(origConfig);

	if (typeof config.delimiter !== 'string'
		|| config.delimiter.length != 1
		|| Papa.BAD_DELIMITERS.indexOf(config.delimiter) > -1)
		config.delimiter = DEFAULTS.delimiter;

	if (config.newline != '\n'
		&& config.newline != '\r'
		&& config.newline != '\r\n')
		config.newline = DEFAULTS.newline;

	if (typeof config.header !== 'boolean')
		config.header = DEFAULTS.header;

	if (typeof config.dynamicTyping !== 'boolean')
		config.dynamicTyping = DEFAULTS.dynamicTyping;

	if (typeof config.preview !== 'number')
		config.preview = DEFAULTS.preview;

	if (typeof config.step !== 'function')
		config.step = DEFAULTS.step;

	if (typeof config.complete !== 'function')
		config.complete = DEFAULTS.complete;

	if (typeof config.error !== 'function')
		config.error = DEFAULTS.error;

	if (typeof config.encoding !== 'string')
		config.encoding = DEFAULTS.encoding;

	if (typeof config.worker !== 'boolean')
		config.worker = DEFAULTS.worker;

	if (typeof config.download !== 'boolean')
		config.download = DEFAULTS.download;

	if (typeof config.skipEmptyLines !== 'boolean')
		config.skipEmptyLines = DEFAULTS.skipEmptyLines;

	if (typeof config.fastMode !== 'boolean')
		config.fastMode = DEFAULTS.fastMode;

	return config;
}
```

I don't think we need this function. Javascript is async, not concurrent. So copying the config object seems pointless. This is a watering hole for bugs... like the input validation... is it really saving anyone from crashing and burning? Obviously, passing in a delimiter like `\n` is problematic and would yield some very strange results without validation to correct it back to the default value. But that's a silent fix: the developer never has any idea there's a bug in his/her code. I see this as more unhelpful than helpful.

If we did validation, we should throw an exception. But I'm even wondering if that's practical... the valid range for some of those options is so wide. JavaScript's dynamic types makes it even harder since `"yes"` and `"false"` and and `true` and `1` are all truthy. Bah.

I'd love to hear any feedback about this. I'll probably rip this out for a 4.1 update or something -- unless there's strong arguments to the contrary. Let me know what you think!

**Comment by bluej100** [comment]
I agree that silently ignoring invalid settings is not helpful. You could just iterate over the keys in config and throw an exception if they're not of the same type as the corresponding defaults entry, but I'm not sure it's necessary.

**Comment by mholt** [comment]
That's consensus enough for me -- might be slightly breaking for some folks but this'll go out on the 4.1 release coming soon (just to be safe).
