### ISSUE TITLE
unparse - add option to ignore field names to create headerless CSV

### ISSUE THREAD

**Issue by jasonxeno** [mholt/PapaParse#146]
Hi!

This is an amazing package!

I have data in this format:
```
var csv = Papa.unparse([
	{
		"Column 1": "foo",
		"Column 2": "bar"
	},
	{
		"Column 1": "abc",
		"Column 2": "def"
	}
]);
```
and I don't want a header in the csv so my desired output would be:
```
foo,bar
abc,def
```
the solution that currently works for me is to make a function and call it every time I want to unparse:
```
this.csv_no_header = function(csv) {
  csv = csv.replace(/(.*\r\n)/, "");
  return csv;
};
```

but it would be nice to have something in the PapaParse config for unparse like header: false to ignore field name data:
```
{
	quotes: false,
	delimiter: ",",
	newline: "\r\n"
        header: false
}
```

Thank you!

**Comment by mholt** [comment]
Pinging @jasonxeno - did my post make sense? Let me know if I need to clarify further. I'll probably close this issue in a while otherwise.
