### ISSUE TITLE
Bower

### ISSUE THREAD

**Issue by jozzhart** [mholt/PapaParse#152]
Heya, 

Love the library.  Great work.  I see you've got a bower file, but can't find your library on the Bower package repository.  Has it been published to Bower?  If it has, maybe add the details to your lovely web page.

Thanks

**Comment by mholt** [comment]
Thanks for your encouragement! The bower file came from PR #17. (Obviously I had no idea what it was.)

Currently working on a release for the near-future, and I will probably publish to bower and add npm and bower instructions to the readme/website. (Even though Papa Parse is still made specifically for the browser.)

**Comment by jozzhart** [comment]
Cool, good luck and keep up the good work

**Comment by mholt** [comment]
@jozzhart Do you see Papa in this search? http://bower.io/search/?q=papaparse

I think the other guy actually submitted it to Bower for me. If something about the manifest needs to change, though, feel free to submit a PR!

**Comment by jozzhart** [comment]
Hey @mholt 

Must have only registered it recently, I wasn't finding anything when searching the bower registry just the other day.

I'd suggest a different registration name for the package, papa-parse, but that's just being pedantic.  If you do want to change it here are the instructions.

http://bower.io/docs/creating-packages/#unregister

**Comment by mholt** [comment]
Thanks, I'll do that.

I actually don't remember ever publishing to Bower, let alone choosing the name, but I agree that the hyphen could go. I'll re-register it as "papaparse" shortly.

**Comment by dinoboff** [comment]
I am seeing 3 packages (I didn't registered any):
```
$ bower search papaparse
Search results:

    papaparse.js git://github.com/mholt/PapaParse.git
    papaparse git://github.com/mholt/PapaParse.git
$ bower search papa-parse
Search results:

    papa-parse git://github.com/mholt/jquery.parse.git
```

You could try that https://github.com/bower/bower/issues/120 . The owner or collaborator of the repository can unregister them.
