### ISSUE TITLE
delimiter auto-detect error

### ISSUE THREAD

**Issue by imadhajjchahine** [mholt/PapaParse#153]
Hi,

I have the following data and trying to auto-detect the delimiter (replaced tab with ; for visibility):

101300;010114;00;2132500450881;A.N. au 010114;;;733480,00;-733480,00
106110;010114;00;2132500450881;A.N. au 010114;;;73348,16;-73348,16
106320;010114;00;2132500450881;A.N. au 010114;;;539346,47;-539346,47

since the numbers are in french notation, the decimal separator used is a comma not a point.

The problem is that papaparse detect the comma as a seperator for the CSV not the tab or semi-column in this example.

I checked the source code for the guessDelimiter function and i think the bestDelimiter should also be determined by the highest avgFieldCount not only the bestDelta.

Waiting for your feedback on the issue.

Thank you.

**Comment by mholt** [comment]
Ah, yep, that's a confusing situation for the parser to figure out by itself. I recommend setting the delimiter manually in those cases.

Thanks for taking a look at the source code! Using highest avgFieldCount may help in your case, but it assumes that the faux-delimiter (the comma in your case) is less frequent than the actual delimiter. Other CSV files may have just two or three actual fields but multiple commas in each field.
