### ISSUE TITLE
Use a real test framework

### ISSUE THREAD

**Issue by mholt** [mholt/PapaParse#155]
The current tests run on an ad-hoc test runner I threw together in a couple hours, and it's been hacked to work for a variety of cases that I never anticipated from when the project was just still a small experiment.

I'd say it's time to move to something legit. Something that TravisCI can use to verify builds/PRs... something that still lets us see the output as clearly as we can now (including special characters like `\r\n` and stuff so that the diff is easy to see).

As of right now, I'm open to suggestions as to what which framework we use; I haven't made a decision yet.

**Comment by caverna** [comment]
What about QUnit?
As a .Net programmer, I'm very comfortable using QUnit to do TDD, as easy as I do TDD with NUnit to develop C# code...

**Comment by bluej100** [comment]
Sounds reasonable to me.
