### ISSUE TITLE
Guess header

### ISSUE THREAD

**Issue by mef** [mholt/PapaParse#157]
Are you interested in adding the feature of guessing whether the first row is a header?

I'm implementing it for my own needs anyway, will send a PR if you want it :)

**Comment by mholt** [comment]
Not really, mainly because it is believed to be impossible to detect accurately enough - see issue #104 for my philosophy on auto-detecting the header row. Even if we do detect it accurately, say, 75-80% of the time, the output format changes abruptly and the developer has to account for either situation in their code, which makes the library harder to use.

**Comment by mef** [comment]
ok

**Comment by mholt** [comment]
If you have a sure-fire algorithm for doing header row detection, feel free to show it off. If it can withstand some rigorous testing, maybe we can offer it as part of a pre- or post-process, like an add-on to Papa Parse or something.

Thanks for the feedback!

**Comment by mef** [comment]
I have implemented header detection in [this branch](https://github.com/Mango-information-systems/PapaParse/commit/36bb0220065032a295746304348a2ab8b8761dba). I understand it does not fit in the main code, as it's a very naive approach which is used.

Fits my use case as the user previews the result and can change the setting. 

P.S.: I've just deployed an offline-first CSV to JSON converter based on papaparse, you can see it [here](http://mango-is.com/tool/csv-to-json.html).

**Comment by mholt** [comment]
Hey @mef, thanks for showing me. If I understand correctly, it simply checks to see if the first row has any field that is numeric, and if so, it isn't a header row. That's not generalizable, but I'm glad it fits your use case!

**Comment by mef** [comment]
> Hey @mef, thanks for showing me.

you're welcome.

> If I understand correctly, it simply checks to see if the first row has any field that is numeric, and if so, it isn't a header row.

Indeed, that's exactly the approach. It's really a guess, not a robust detection.

> And that's a neat tool too, I like how it updates as you toggle settings and stuff.

Thanks :)
