### ISSUE TITLE
failure to detect embedded delimiter

### ISSUE THREAD

**Issue by bae43** [mholt/PapaParse#160]
From issue #107, there is still issues parsing embedded commas in quotes when commas are a delimiter.
Using the example given from the previous thread-

toto, "tutu, tata"

produces an array of three elements and does not group by quotes. There is nothing I can find in the documentation about grouping by quotes.

**Comment by mholt** [comment]
Grouping by quotes happens automatically as per the RFC, but a quote has to be the first character of the field. In your example, there is a space before the quotes, making them become part of the data.

**Comment by bluej100** [comment]
Perhaps you could set delimiter to ', ' if that's the convention in your data?

**Comment by mholt** [comment]
I don't think the parser plays well if the delimiter is more than a single character. (But I haven't tried it lately.)

**Comment by bluej100** [comment]
Ah, good thought. Seems to work for the simple case on http://papaparse.com/demo if you remove the length constraint on the delimiter field, at least.

**Comment by mholt** [comment]
Interesting. I know that with the 3.x version of the parser, multiple-char delimiters weren't supported, but with the 4.0 rewrite, it's possible that they are now. I'll do some tinkering and performance testing and if all goes well, I guess there's no reason to restrict delimiters to a single character.

**Comment by mholt** [comment]
It looks like with the 4.0 rewrite I thought of multiple-character delimiters: https://github.com/mholt/PapaParse/blob/bfbfedb8fc6d3d03cf79d4fb24db9fd507ac7e3b/papaparse.js#L958

So I have a commit coming that actually allows them to be used. It is definitely not recommended to use a multi-char delimiter, but as far as I can tell, it doesn't hurt parsing performance at all (maybe insignificantly), and only one line of code has to be removed to allow it, so we might as well. However, this feature will not be documented as I don't want to guarantee that it will remain in future versions.
