### ISSUE TITLE
Error while parsing a valid CSV with a newline at the end

### ISSUE THREAD

**Issue by frol** [mholt/PapaParse#161]
Steps to reproduce:

1. Create a file with content (make sure that there is a newline after "1,2"):

     ```
     a,b
     1,2
     ```
2. Set `header=true`
3. Try to parse the file
...
5. First error: `Object {type: "FieldMismatch", code: "TooFewFields", message: "Too few fields: expected 2 fields but parsed 1", row: 1}`

**Comment by frol** [comment]
BTW, I used the Demo site, unless it is outdated the bug hasn't been fixed.

**Comment by mholt** [comment]
Thanks for the report. But that's not a bug. Try the `skipEmptyLines` config option. Otherwise the line has to be interpreted as data,  and the data doesn't have enough fields to fill out the header row.

**Comment by frol** [comment]
I see. Thank you!

**Comment by alexeyraspopov** [comment]
Why don't you make `skipEmptyLines: true` by default? It's really easy to face with this behavior that can be treated as a bug.

**Comment by mholt** [comment]
Some applications interpret empty lines to indicate missing record. It isn't Papa's job to assume that empty lines are meaningless. But you are welcome to enable that assumption with `skipEmptyLines`.
