### ISSUE TITLE
[Suggestion] Add skipEmptyLines checkbox to the Demo site

### ISSUE THREAD

**Issue by frol** [mholt/PapaParse#162]
As it is not uncommon to have files ending with an empty line, it would be clearer if skipEmptyLines checkbox will be on the Demo site and will be checked by default.

**Comment by mholt** [comment]
That's a great idea! I forgot to add that option earlier. I'll probably replace "Fast Mode" with "Skip Empty Lines" since fast mode is now triggered automatically.
