### ISSUE TITLE
Don't break autodetection when only single column

### ISSUE THREAD

**Issue by ghempton** [mholt/PapaParse#165]
Currently, when parsing a CSV with a single column we get "unable to detect delimiting character...".

**Comment by mholt** [comment]
Then specify it. There has to be a delimiter in order to be able to detect what it is.

**Comment by ghempton** [comment]
Sorry for the delayed response. We have a use case where our customers can upload a csv with *one* or more columns. In the case where there is one column, we just want that single value per row. In the case where there are multiple columns, it would be nice to auto-detect the delimiter.

IMO, what auto-detection on a single column should do is detect that *there is no delimiter* instead of failing. Does that make sense?

**Comment by bluej100** [comment]
Well, it essentially does that. For a single-column file, you get an error, "Unable to auto-detect delimiting character; defaulted to ','", but the data property still contains your data.

One thing you could do is first run a preview parse with auto delimiter and present the detected delimiter to the user before the full parse.

**Comment by mholt** [comment]
In that case, Braden's advice is good.

Also, you don't *have* to show the error to the user at all. Your code might see that error, then look at the field length and if there's only one field, treat the error as a warning (as expected behavior). If there's more than one field, then maybe it's cause for concern.

**Comment by XavierChevalier** [comment]
I did this workaround, it works for me.
```ts
const getParseErrors = (
  errors: ParseError[],
  headers: string[]
): ParseError[] => {
  // If the csv has only one header, papaparse will not detect the delimiter and fail.
  // @see https://github.com/mholt/PapaParse/issues/165
  if (headers.length === 1) {
    return errors.filter((error) => error.code !== 'UndetectableDelimiter')
  }

  return errors
}

export const parseCsv = (
  csvText: string,
  { headers }: { headers: string[] }
) => {
  const { errors, ...rest } = parse<AnyRecord>(csvText.trim(), {
    header: true,
  })

  return { ...rest, errors: getParseErrors(errors, headers) }
}

const {
  data, // [{ name: 'John' }, { name: 'Sophie' }]
  errors // [] instead of [{ code: 'UndetectableDelimiter', message: 'Unable to auto-detect delimiting character; defaulted to ',' }]
} = parseCsv(`name\nJohn\nSophie`, { headers: ['name'] })
```
