### ISSUE TITLE
Always getting results undefined 

### ISSUE THREAD

**Issue by almogdesign** [mholt/PapaParse#168]
I'm trying to parse a CSV to JSON but I'm always getting results undefined 

This is what I have 
```html
 <input type="file" id="csv-file" name="files"/>
```

```javascript
$('input').change(function(e) {
        $('input[type=file]').parse({
            config: {
                // base config to use for each file
            },
            before: function(file, inputElem)
            {
                console.log(file);
                // executed before parsing each file begins;
                // what you return here controls the flow
            },
            error: function(err, file, inputElem, reason)
            {
                console.log(err);
                // executed if an error occurs while loading the file,
                // or if before callback aborted for some reason
            },
            complete: function(results, file) {
                console.log("Parsing complete:", results, file);
            }
        });
    });
```

**Comment by mholt** [comment]
Actually, that's not a bug (that's what I get for doing issues at 6 in the morning).

The complete callback you're expecting results in is the complete callback that's fired when all files are finished parsing. You want to specify that complete function in the `config` object, which is executed on a per-file basis. The overall complete callback used by the jQuery plugin, which you're currently expecting results in, doesn't get passed any parameters. It's simply there so you can do stuff when all the files are finished.

**Comment by almogdesign** [comment]
Yea I got working not to long ago thanks, just forgot to update the ticket sorry about that. I am having an issue when parsing a CSV file with spanish accents will open a ticket for that
