### ISSUE TITLE
Progress bar

### ISSUE THREAD

**Issue by userew** [mholt/PapaParse#171]
Hey, so I am trying to implement a progress bar with a "Stream" option and I was referring to the discussion at https://github.com/mholt/PapaParse/pull/125 

But I can't get it to work, is this implemented to v4.1.0 yet or documented anywhere that I can refer to? If not, would you mind to provide a sample how to implement a progress bar while parsing out big files? 

Thank you.

**Comment by bluej100** [comment]
Here's what I ended up doing. I create a web worker with roughly this code. Whenever the worker posts a message back, I use the percent to set the CSS width of my progress bar.

```
  var size = file.size;
  var percent = 0;
  Papa.parse(file, {
    step: function(row) {
      var progress = row.indexes[0];
      var newPercent = Math.round(progress / size * 100);
      if (newPercent === percent) return;
      percent = newPercent;
      postMessage({
        percent: percent,
      });
  });
```

I may switch it to a chunk callback with small chunkSize instead of a step callback.

**Comment by userew** [comment]
Thank you. I'll give this a try. I guess I couldn't tie the row.index to the actual progress bar. I'll try again by setting the CSS width of the progress bar to the percent by using your snippet.

**Comment by userew** [comment]
I have never worked with web workers before and I keep getting "Uncaught SyntaxError: Failed to execute 'postMessage' on 'Window': Invalid target origin '' in a call to 'postMessage'. 

Would you mind to elaborate on your answer? Below is what I have, taken from the player.js example

My worker class
```
onmessage = function (e) {
    console.log('Message received from main script');
    var workerResult = 'Result: ' + (e.data[0]);
    console.log('Posting message back to main script');
    postMessage(workerResult);
}
```
Then
```
var myWorker = new Worker("Scripts/worker.js");

    myWorker.onmessage = function (e) {
        console.log(e.data);
        console.log('Message received from worker');
    }

var dtrows = [];
function stepFn(results, parserHandle) {
    stepped++;
    rows += results.data.length;
    parser = parserHandle;

    if (pauseChecked) {
        console.log(results, results.data[0]);
        parserHandle.pause();
        return;
    }

    if (printStepChecked)
        console.log(results, results.data[0]);

    dtrows.push(results.data[0]);

    var progress = results.data[0].indexes;
    var newPercent = Math.round(progress / size * 100);
    if (newPercent === percent) return;
    percent = newPercent;
    postMessage({
        percent: percent,
    });
}

```

Also, since it is using stepFn() , can I just pass row to it, if so how? It seems like results.data[0].indexes is not accessible? Sorry I am a little new to all this

**Comment by userew** [comment]
Actually I figured out the answer to everything above, but I have another question. In your snippet you have 
```
var size = file.size;
...
var newPercent = Math.round(progress / size * 100);
```

, so size is the file.size where progress is the number of rows we grab in each stepFn. Which is not really showing the parsing progress of rows by totalRows or am I missing something?

**Comment by mholt** [comment]
The progress variable, which comes from row.indexes, is actually the number of bytes into the file parsing is (assuming an ASCII encoding). So it should be overall file progress.

**Comment by mholt** [comment]
@bluej100 What do you think about adding a little progress bar tutorial (no more than a couple paragraphs, maybe) to the FAQ page of the site? Either of us could do it maybe. (I wouldn't get around to it for a long time.)

**Comment by userew** [comment]
I could not get indexes to work within stepFn(results, parserHandle), but in my example above rows += results.data.length; and then progress= rows; gives me , like you said, the actual progress, which is how many rows are being parsed each time we step into the stepFn. However, when we divide that by file.size, that is not accurate. It should be total number of rows. No?

Say we have file.size =50 MB. So progress (number of rows being parsed) / file.size is not what we want. How do we know the total number of rows to be parsed? Or how can I use that row.indexes? Both row and indexes are undefined when I try.

**Comment by userew** [comment]
Oh..actually after doing dtrows.push(results.data[0]);  , if I calculate size of dtrows then divide it by file.size then that might work? I'll give this a try today

**Comment by mholt** [comment]
No, `file` is a File object given by the File API, and `file.size` is the size of the file in bytes, not rows. And that's what the indexes array tells you: the starting character (if ASCII, character == byte) position of each field. And the indexes array will be correct across multiple chunks, which is important if your file is larger than the chunk size. So use the indexes array.

**Comment by bluej100** [comment]
(Sure, I'd love to add it to the FAQ.)

**Comment by userew** [comment]
I'd very much appreciate that..because I can't seem to get this working by using your snippet with indexes. I always get row.index undefined..

**Comment by bluej100** [comment]
I think instead of results.data[0].indexes, you should have results.indexes[0].

**Comment by bluej100** [comment]
Writing your own worker isn't essential to any of this, by the way. In my case, it noticeably improved responsiveness because I was able to do summarizing in the worker and send minimal information to the main thread, but it's not vital.

**Comment by userew** [comment]
I realized that and eliminated the worker for now to get the progress working but I get Uncaught TypeError: Cannot read property '0' of undefined even when I try results.indexes[0] and undefined with results.indexes.

**Comment by mholt** [comment]
Uh oh, I think I forgot that before that change was merged in we changed it from "indexes" to just `meta.cursor` -- does that sound familiar, @bluej100? I can't find "indexes" in the source. I think what you want, @userew, is meta.cursor.

**Comment by userew** [comment]
My config is
```
function buildConfig() {
            return {
                header: true,
                dynamicTyping: true,
                preview: 5,
                step: stepFn,
                worker: true,
                complete: completeFn,
                skipEmptyLines: true,
            };
        }
```
and my StepFn
```
function stepFn(results, parserHandle) {
            stepped++;
            rows += results.data.length;
            parser = parserHandle;

            console.log(results.indexes[0]);
}
```

None my my tries were successful, and I don't see index field in any of the objects that I log to console

**Comment by mholt** [comment]
@userew Try meta.cursor instead...

**Comment by userew** [comment]
ah..that might explain it all :) Let me try

**Comment by userew** [comment]
Ok seems like I got this working.
```
step: function(row) {
                    var progress = row.meta.cursor;
                    var newPercent = Math.round(progress / size * 100);
                    if (newPercent === percent) return;
                    percent = newPercent;
                    console.log('percent = newpercent', percent);
                },
```
with the console output as 
```
percent = newpercent 21
percent = newpercent 42
percent = newpercent 63
percent = newpercent 84
percent = newpercent 100
Finished input (async). Time: 21047.862000006717 [undefined, File, input#files]
Rows: 0 Stepped: 0 Chunks: 0
Done with all files.
```
and it would be results.meta within stepFn() , does it look right?

**Comment by bluej100** [comment]
Looks right to me. Sorry for the confusion.

**Comment by userew** [comment]
Thank you both of your help.

**Comment by pulkitsinghal** [comment]
@bluej100 - which branch or PR can I peek in for the progressBar worker's tutorial/sample/faq?

**Comment by bluej100** [comment]
@pulkitsinghal , https://github.com/mholt/PapaParse/issues/171#issuecomment-74704173 is the best public example.

**Comment by sonaye** [comment]
```javascript
const csv = e.target.files[0]; // <input type="file" />

const data = [];

Papa.parse(csv, {
  // dynamicTyping: true,
  // header: true,
  complete: () => console.log(data),
  error: error => console.error(error.message),
  step: row => {
    data.push(row.data[0]);
    console.log(row.meta.cursor / csv.size * 100);
  }
});
```

**Comment by KrishnaPG** [comment]
Came here looking for a way to identify the end-of-stream. Would this work with preview also?

If we set `preview` to be, say, 10 records, how to identify that we are at the end of the records (the last record in the preview) ?

**Comment by pokoli** [comment]
@KrishnaPG you should probably open a new issue as it seems unrelated to the asked question.

**Comment by CptDayDreamer** [comment]
What happend to row.meta.cursor? It's not available anymore. How can I count the rows now or get my current progress?

**Comment by pokoli** [comment]
@CptDayDreamer Please open a new issue with an example to reproduce your case.

**Comment by lortschi** [comment]
@CptDayDreamer put e.q. "chunkSize: 500" to the parse options and it will start to work.
