### ISSUE TITLE
A way to generate and download CSV files client-side

### ISSUE THREAD

**Issue by mholt** [mholt/PapaParse#175]
There seems to be a lot of confusion about how to properly generate a file client-side and have it downloaded in modern browsers. I know how to do it (it's not hard, but it uses a modern web API) and it could potentially be a valuable addition to the library.

Something like:

``` js
Papa.download(Papa.parse(csv), "data.json");   // download JSON file
Papa.download(Papa.unparse(data), "data.csv"); // download CSV file
```

Might take no more than about 20-30 lines of code. Should I do it?

**Comment by bluej100** [comment]
My impression is that it's currently not possible in Safari: see https://github.com/eligrey/FileSaver.js/issues/12 . I think it's an awesome feature, though, and would support including it with that caveat noted.

**Comment by mholt** [comment]
This seems to work in all modern browsers:

```js
var blob = new Blob([csvString]);
if (window.navigator.msSaveOrOpenBlob)	// IE hack; see http://msdn.microsoft.com/en-us/library/ie/hh779016.aspx
	window.navigator.msSaveBlob(blob, "filename.csv");
else
{
	var a = window.document.createElement("a");
	a.href = window.URL.createObjectURL(blob, {type: 'text/plain'});
	a.download = "filename.csv";
	document.body.appendChild(a);
	a.click();	// IE: "Access is denied"; see: https://connect.microsoft.com/IE/feedback/details/797361/ie-10-treats-blob-url-as-cross-origin-and-denies-access
	document.body.removeChild(a);
}
```

**Comment by bluej100** [comment]
Very cool.

**Comment by Gribbs** [comment]
Yes please! Awesome library. But yeah, really hard to find any clear documentation on how to get the Papa.unparse(data) into a csv file

**Comment by JedWatson** [comment]
Looks like this didn't go anywhere, but it would be awesome if it did land in a new version. I'll use your snippet in the meantime, @mholt - thanks!

**Comment by mholt** [comment]
I haven't abandoned this -- still on my list for the next version, along with a million other little fixes. Just been busy with another project the last few months. Gotta encrypt the Web!!

**Comment by JedWatson** [comment]
Awesome, thanks for the update and totally understand!

**Comment by jhawthor** [comment]
Here is what I changed to based on the Google Article here: https://developers.google.com/web/updates/2012/06/Don-t-Build-Blobs-Construct-Them?hl=en
Note that I do not need to append and remove the link from the body.

```javascript
var csvData = new Blob([str], {type: 'text/csv;charset=utf-8;'});
var csvURL = window.URL.createObjectURL(csvData);
var tempLink = document.createElement('a');
tempLink.href = csvURL;
tempLink.setAttribute('download', 'ActiveEvent_data.csv');
tempLink.click();
```

**Comment by mholt** [comment]
Oooo, that's nice. Thanks! Will need to check browser compatibility, but I like that better.

**Comment by jhawthor** [comment]
Update:  Fix for IE11
```
var csvData = new Blob([str], {type: 'text/csv;charset=utf-8;'});
var csvURL =  null;
if (navigator.msSaveBlob) {
	csvURL = navigator.msSaveBlob(csvData, 'download.cv');
} else {
	csvURL = window.URL.createObjectURL(csvData);
}
var tempLink = document.createElement('a');
tempLink.href = csvURL;
tempLink.setAttribute('download', 'download.cv');
tempLink.click();
```

**Comment by AkshayHarshe** [comment]
This is a great discussion!! This helped me a lot.. Thanks everyone who contributed to this thread.

**Comment by lneffa** [comment]
:+1:

**Comment by hamidzokaee** [comment]
Thank you for your efforts. Please publish version 4.2 as soon as possible.

**Comment by mholt** [comment]
I want to, but right now this project is being squeezed out by another project that has funding. (Gotta pay the bills, you know.) If somebody is willing to fund the development of this project then I will be able to afford to put time into it sooner!

**Comment by hamidzokaee** [comment]
hi
I am living in Iran. I can not help you. I love your work. Thank

**Comment by mholt** [comment]
That's alright, thank you! I'll try to seek funding for this before too long...

**Comment by OliveSaikiran** [comment]
I am facing the problem related to Safari, whenever am trying to download the csv file in safari, it is not getting in tabular foemat.

**Comment by jessewmc** [comment]
None of these solutions work in Safari 9.0.3 for the same reasons @bluej100 posted above. I just tested them all, and they all still open raw text in a new browser tab and do not download.

**Comment by SergMuller** [comment]
jesse, it may work if you change "text/csv" to "attachment/csv", but the file name would be just some default one.

**Comment by Ginolan** [comment]
If you use dispatchEvent of a new MouseEvent click, instead .click(), it will work also on Internet Explorer and Edge. The only browser i have problem to get working is Safati. I don't have any idea about the way to make it work there.

**Comment by Am1rr3zA** [comment]
I am having the  same issue with type = 'application/vnd.ms-excel'; I am on safari 9.0.3 and your solution doesn't work.

**Comment by keemor** [comment]
For modern browsers solution goes like this, tested: IE11, FF & Chrome
`var csvData = new Blob([arg.data], {type: 'text/csv;charset=utf-8;'});
//IE11 & Edge
if (navigator.msSaveBlob) {
	navigator.msSaveBlob(csvData, exportFilename);
} else {
	//In FF link must be added to DOM to be clicked
	var link = document.createElement('a');
	link.href = window.URL.createObjectURL(csvData);
	link.setAttribute('download', exportFilename);
	document.body.appendChild(link);	
	link.click();
	document.body.removeChild(link);	
}`

**Comment by keemor** [comment]
For modern browsers solution goes like this, tested: IE11, FF & Chrome
```javascript
var csvData = new Blob([arg.data], {type: 'text/csv;charset=utf-8;'});
//IE11 & Edge
if (navigator.msSaveBlob) {
	navigator.msSaveBlob(csvData, exportFilename);
} else {
	//In FF link must be added to DOM to be clicked
	var link = document.createElement('a');
	link.href = window.URL.createObjectURL(csvData);
	link.setAttribute('download', exportFilename);
	document.body.appendChild(link);	
	link.click();
	document.body.removeChild(link);	
}
```

**Comment by orenmagen100** [comment]
any news about safari? not found a valid solution for safari...

**Comment by export-mike** [comment]
@keemor so does this need to be appended to the document.body for support reasons?

**Comment by dannynoeloconnor** [comment]
Has anybody found a way to handle this in Safari?

**Comment by SergMuller** [comment]
I ended up using a sub-form that will drop that content to a tiny PHP script, that will just stick a proper header and return right back:

**Comment by orenmagen100** [comment]
@dannynoeloconnor 
managed to get it work in Safari 9 for a month (I'm using angular but it can work without) with:

this.$window.open('URL_TO_SERVER_ENDPOINT_?$FILENAME_PARAM', '_self');

but I think the last safari update ruined it. Doesn't work again.

**Comment by raza2022** [comment]
@mholt Any update on that ?

**Comment by mholt** [comment]
Nope, sorry :-/ I haven't worked on this project in a while, been very busy with other things.

**Comment by raza2022** [comment]
@mholt can i submit PR, code check with E11, FF Chrome & Safari 9

**Comment by mholt** [comment]
Sure, I have time for a quick look at a PR.

**Comment by whoisglover** [comment]
@raza2022 any luck with pull request? Banging my head against same issue with Safari 9

**Comment by Philip-Nunoo** [comment]
_downloadCSV: function(csv) {
		var blob = new Blob([csv]);
		var a = window.document.createElement("a");
	    a.href = window.URL.createObjectURL(blob, {type: "text/plain"});
	    a.download = "contacts.csv";
	    document.body.appendChild(a);
	    a.click();
	    document.body.removeChild(a);
	}

**Comment by datafunk** [comment]
In case it's any help, check this out: http://stackoverflow.com/questions/16376161/javascript-set-file-in-download which evolved into https://github.com/rndme/download/

Doesn't seem to work in Safari (Safari's fault I think), but I used it in my project with the proviso of limited browser support (it's a utility for a small group with specific needs).

**Comment by suhailtaj** [comment]
Create a Node Proxy and set headers as:

```Javascript
router.get("/downloadList/:Id/:fileName", function(req, res) {
    // Set hedders to CSV and giving file name
    res.setHeader('Content-disposition', 'attachment; filename=' + req.params.fileName + '.csv');
    res.set('Content-Type', 'text/csv');
    var url = 'https://' + host_name + '/agtech/v1/downloadCsv/' + req.params.Id;
    client.get(url, function(data) {
        dateReceived(data);
    });

    function dateReceived(data) {
        var outerData = data;
        res.send(outerData);
    }
});
```

+++++++++++++++++++++++++++++++++++++++++++++++
From client side, request pointing to node JS route:

```javascript
function downloadCSV(Id) {
            // Create file name and pass it to nodeJS
            var fileName = "FileName";
            var e = document.createElement('a');
            e.href = window.location.origin + "/api/v1/home/downloadList/" + Id + "/" + fileName;
            e.target = '_blank';
            document.body.appendChild(e);
            e.click();
            document.body.removeChild(e);
        }
```

**Comment by elfenheart** [comment]
With the multiple solutions posted here, have anybody tried with a large file? There is an existing bug in V8 where Blob size is limited to 500mb.

ref: https://bugs.chromium.org/p/chromium/issues/detail?id=375297

**Comment by amruta1885** [comment]
Hi All,

For me data is getting downloaded in CSV file, but my requirement is to add a border to the table. Only to the contents in the CSV file. 

Can someone help me out here?

Thanks,
Amruta.

**Comment by pokoli** [comment]
@amruta1885 The CSV file does not contain any styles (only data), so you should generate an spreadsheet in order to add styles to the table. And this is out of the scope of PapaParse.

**Comment by pokoli** [comment]
Indeed there are other libraries providing this functionality, so we should not reinvent the wheel. See https://github.com/mholt/PapaParse/issues/421#issuecomment-332179793 as and example.

**Comment by ashokrathore** [comment]
in ts file we can do like this as well:-  
function download(blob: Blob, fileName: string) {
        if (window.navigator.msSaveOrOpenBlob)
            window.navigator.msSaveOrOpenBlob(blob, fileName);
        else {
            const temp = document.createElement('a');
            const url = window.URL.createObjectURL(blob);
            temp.download = fileName;
            temp.href = url;
            temp.target = '_blank';
            temp.click();
            temp.remove();
        }
    }

**Comment by DenVdmj** [comment]
function openSaveFileDialog (data, filename, mimetype) {

      if (!data) return;

      var blob = data.constructor !== Blob
        ? new Blob([data], {type: mimetype || 'application/octet-stream'})
        : data ;

      if (navigator.msSaveBlob) {
        navigator.msSaveBlob(blob, filename);
        return;
      }

      var lnk = document.createElement('a'),
          url = window.URL,
          objectURL;

      if (mimetype) {
        lnk.type = mimetype;
      }

      lnk.download = filename || 'untitled';
      lnk.href = objectURL = url.createObjectURL(blob);
      lnk.dispatchEvent(new MouseEvent('click'));
      setTimeout(url.revokeObjectURL.bind(url, objectURL));

    };

**Comment by sindyxin** [comment]
@orenmagen100  your code fixed my problem for firefox browser.  Thank you so much.

**Comment by AnandAs005** [comment]
How can we download CSV or XLSX files in a customized way from DB.?
means, field headings are in bold, contents are in italics. can anyone help.

**Comment by bndynet** [comment]
> ```js
> function openSaveFileDialog (data, filename, mimetype) {
> 
>   if (!data) return;
> 
>   var blob = data.constructor !== Blob
>     ? new Blob([data], {type: mimetype || 'application/octet-stream'})
>     : data ;
> 
>   if (navigator.msSaveBlob) {
>     navigator.msSaveBlob(blob, filename);
>     return;
>   }
> 
>   var lnk = document.createElement('a'),
>       url = window.URL,
>       objectURL;
> 
>   if (mimetype) {
>     lnk.type = mimetype;
>   }
> 
>   lnk.download = filename || 'untitled';
>   lnk.href = objectURL = url.createObjectURL(blob);
>   lnk.dispatchEvent(new MouseEvent('click'));
>   setTimeout(url.revokeObjectURL.bind(url, objectURL));
> 
> }
> ```

Save my day. and works in Firefox

**Comment by cannnAbsoft** [comment]
Thank You!
