### ISSUE TITLE
Cannot remove reference form global scope.

### ISSUE THREAD

**Issue by Chyzwar** [mholt/PapaParse#176]
One of possible pieces of code causing a problem. 
```javascript
	function FileStreamer(config)
	{
		config = config || {};
		if (!config.chunkSize)
			config.chunkSize = Papa.LocalChunkSize;
		ChunkStreamer.call(this, config);
```

I am using a Papa in Angular application. I am wrapping a 3rd parties libraries in factory and remove reference in global scope. Papa is using a references to global scope inside. it is not possible to remove Papa from global scope without breaking a library itself. 

I think it is not very clear module pattern implementation. Overall I am happy with Papa.

**Comment by mholt** [comment]
Well I've never used Angular so you're welcome to submit a pull request to make an improvement. Sorry for the trouble you're having.

**Comment by Chyzwar** [comment]
```javascript 
(function(global)
{
global.Papa = {}

})(this);

``` 

It cannot be doe in simple way. because Papa is tied to global object. To make isolated from global scope this will need to become:

```javascript 
(function(global)
{
 var Papa = {}
.
.
.
return Papa; 
});

``` 

This would use clojure to isolate it from golobal. jQuery use this approach as well. I dont know maybe there are some consideration on workers.

**Comment by mholt** [comment]
The problem with doing that is that it breaks everyone who expects Papa to be a variable in the global scope. And outside the browser I'm not entirely sure what the consequences would be. What is wrong exactly with having a single variable (`Papa`) in the global scope when you include Papa Parse into the page?

**Comment by Chyzwar** [comment]
```javascript
(function(global)
{
 var Papa = {}
.
.
.
return Papa; 
});
```
This will be also one variable in global scope. But contexts will be different.  

http://eloquentjavascript.net/10_modules.html
http://addyosmani.com/resources/essentialjsdesignpatterns/book/#modulepatternjavascript

**Comment by bluej100** [comment]
@Chyzwar , we currently have a pull request to expose Papa as a module. Will https://github.com/mholt/PapaParse/issues/167 satisfy your needs when merged?

**Comment by bluej100** [comment]
Sorry, https://github.com/mholt/PapaParse/pull/172 , rather.

**Comment by Chyzwar** [comment]
This might help. I will check after it is merged.

Thanks



2015-03-02 16:31 GMT+00:00 Braden Anderson <notifications@github.com>:

**Comment by mholt** [comment]
@Chyzwar I was able to merge that PR today so you can take a look when you get a chance.

**Comment by robd** [comment]
@Chyzwar I think this PR (#172) may well provide some of what you're looking for. I attempted to ensure that Papa isn't written into the global scope if it is loaded as a module. I'm not familiar with AngularJS, so not quite sure if further tweaks are needed, but would be interested if this now works or you still have difficulties.

**Comment by Chyzwar** [comment]
Its works for now. I can remove Papa from global scope and inject it as Factory. Thanks.

Now Papa is cleaner imo.

**Comment by robd** [comment]
What happens if you supply an error callback?

```javascript
error: function(err, file, inputElem, reason)
{
  // executed if an error occurs while loading the file,
  // or if before callback aborted for some reason
},
```
Looking at the docs, I think the signature you're using is incorrect:  

```javascript
complete: function (results, $files, err) {...}
```
should be 
```javascript
complete: function(results, file) {...}
```
I don't think PapaParse will ever pass anything to the *err* parameter.

**Comment by mholt** [comment]
The signature shouldn't matter; but Rob is right that the err parameter is not needed in the complete callback. Use the error callback instead. And do you have more information about header:true not working any more?

**Comment by Chyzwar** [comment]
Thanks,

```javascript
Papa.parse($files[0], {
                        config: {
                            header: true
                        },
                        complete: function (results) {
                            console.log(results);
                        },
                        error: function (err, file, inputElem, reason) {
                            console.log(err);
                        }

                    });
```

This works, but according to docs:

*The complete callback shown here is executed after all files are finished and does not receive any data. Use the complete callback in config for per-file results.*

but this in my case console.log(results) is showing me results.

**Comment by mholt** [comment]
No, the whole second argument *is* the config object. Just put header in the same object as complete and error.

**Comment by Chyzwar** [comment]
```javascript

                    Papa.parse($files[0], {
                        header: true,
                        delimiter: ',',
                        worker: true,
                        complete: function (results) {
                            resetState();
                            parseResults(results.data);
                        },
                        error: function (err) {
                            console.log(err);
                        }
                    });
```

When I use worker I receive:

*Uncaught ReferenceError: window is not defined*

**Comment by robd** [comment]
I guess like this:

``` javascript
Papa.parse($files[0], {
    header: true,
    complete: function (results) {
        console.log(results);
    },
    error: function (err, file, inputElem, reason) {
        console.log(err);
    }
});

**Comment by mholt** [comment]
Bingo! That should do the trick for ya. Thanks for opening this discussion; I think we made some good progress.
