### ISSUE TITLE
Get current line number

### ISSUE THREAD

**Issue by GingerGeek** [mholt/PapaParse#177]
In the step function what can you call to get your current line number?

**Comment by mholt** [comment]
Just to be sure: line or row? (A line is un-parsed like what you would see in a text editor, a row is parsed.)

**Comment by GingerGeek** [comment]
Line preferably

**Comment by mholt** [comment]
The line number isn't something that Papa Parse keeps track of, because all it needs to know is row numbers. It might be worth just keeping a line counter from your step function. Just increment the line number by 1 for each field that contains a newline `\n` character and for each row of data.

**Comment by GingerGeek** [comment]
How would I get the row number?

**Comment by frol** [comment]
@GingerGeek Set your own counter and increment it on every step function execution. Here is how it is done in the demo: https://github.com/mholt/PapaParse/blob/master/player/player.js#L125

**Comment by mholt** [comment]
That would be the way to do it! Just increment your row counter by `results.data.length` (assuming your argument is called `results`, of course).

**Comment by GingerGeek** [comment]
Cheers :D
