### ISSUE TITLE
Exceed valid string length when loading big CSV

### ISSUE THREAD

**Issue by simonbergstrom** [mholt/PapaParse#184]
Hey,
When I try to load a bigger CSV file (~350MB) the parser throws the error: Uncaught RangeError: Invalid string length (papaparse.js:371) . I use the step function to stream my parsing and create own chunks which load to server. When I print the length of the string this._partialLine before line 371 in papaparse I see the length increases over time when parsing until it exceeds limit , throws the error and the string gets cleared. 

I guess something is funky here..

**Comment by mholt** [comment]
Thanks for the report -- we'd love your help to fix it; the discussion can be found in #179. Feel free to take a look at the PR and see if it helps you, offer your feedback if you want, etc.

**Comment by bluej100** [comment]
I believe #183 fixed this issue, @simonbergstrom . Would you mind re-testing against the latest code?

**Comment by mholt** [comment]
@simonbergstrom I did a patch release today - could you confirm it fixes the problem?

**Comment by mholt** [comment]
I imagine we're good to go -- closing bug report.

**Comment by CKanishka** [comment]
I am still facing this issue when I try parsing a file > 500mb, this is my Parser Config-
 `{ 
    skipEmptyLines: 'greedy',
    header: false,
    preview: 20,
    step: (rowResults) => this.onParseRow(rowResults),
    complete: () => this.onParseComplete(),
  }`. 
 
 Let me know if I am doing something wrong or missing something, any help will be appreciated.

**Comment by datermine** [comment]
I'm getting this error as well. 

I have an array of ~3M rows

<img width="864" alt="Screenshot 2024-11-04 at 1 45 10 PM" src="https://github.com/user-attachments/assets/9801bb64-bae9-4ce7-b586-b3a248165542">
