### ISSUE TITLE
Determining when multiple CSV are complete

### ISSUE THREAD

**Issue by jondo89** [mholt/PapaParse#185]
Hi , This may not be an issue , more a query , what is the best way to determine when a batch of CSV files are complete ? ie. when loading x 0ff individual files and looping into the parser , how do you determine that the x off files are complete.Thanks

**Comment by mholt** [comment]
If you're using the jQuery integration, there's a complete callback that executes when *all* the files are done. There is no way to parse multiple files with one call to `parse` without the jQuery plugin. So if you are parsing multiple files without jQuery, you just have to keep a counter that gets updated every time a file is finished.

**Comment by mholt** [comment]
Did this answer your question? I will close this now to keep things tidy, but you may re-open it if there is anything else that I missed.
