### ISSUE TITLE
Skip lines at the beginning of a file? (Feature Suggestion)

### ISSUE THREAD

**Issue by zemzelett** [mholt/PapaParse#186]
Hi there,

just deleted two big paragraphes of rambling why i want that feature, instead i'll give the same in short:

I wondered if you ever thought of a parse config object option called _startAtLine: number_ which then tells papaparse at which line the actual csv data starts if there are lines in a file (at the beginning), that are not csv data (e.g. general information about the data).

Is this a feature you might add in the future or could you think of doing so?

**Comment by mholt** [comment]
This could be useful for ARFF files (popular in some areas of machine learning especially the academic realm). I will take a closer look at your PR when I have time, and that might answer my question, but: Why not just truncate the beginning of the input string before you parse? Is it really Papa's job to skip lines, or should the input be prepared for the parser before being submitted to it? Or maybe the extra lines at the beginning could be commented out? Papa can skip lines starting with a certain string.

**Comment by bluej100** [comment]
> Is it really Papa's job to skip lines, or should the input be prepared for the parser before being submitted to it?

Currently, if users want to manipulate the input, then they can't take advantage of Papa's file / URL chunk handling, which is super useful. As I suggested in the linked thread, it might be nice to expose a callback for users to prepare chunks.

**Comment by mholt** [comment]
Ah, good point. As you can tell I was a little :sleeping: when I wrote that.

So a callback to prepare chunks - that's interesting. What would that look like? Receives the string to be parsed and returns the *actual* string to parse, maybe? That could be pretty simple. I'd like to see what that looks like.

**Comment by bluej100** [comment]
Yeah, precisely. I'm not sure whether it should happen before or after the trailing line from the previous chunk is prepended. Maybe it should only be called for the first chunk, even.

**Comment by mholt** [comment]
Since chunks are somewhat arbitrarily sized, I'm not sure that there would be much value in having a preprocess callback for each chunk - with workers, especially, it'll just involve lots of string copying. So you have a good point, we may only need this callback to execute once, at the beginning.

**Comment by bluej100** [comment]
Yeah, that seems reasonable. It fails if you have more than a chunk of preface, but that would be kind of ridiculous.

**Comment by mholt** [comment]
And since the chunk size is customizable, it would be the user's responsibility to be aware of that. Sounds good to me so far!

**Comment by zemzelett** [comment]
I never heard of the term ARFF before but  i assume your where talking about this all the time? (Considering ARFF files hold meta information about the data being presented)

@mholt To answer your question: If i use the download option of Papa, i am not able to manipulate the data before parsing, that's why this suggestion came to my mind. Apart from that, i think you are right, the user should be hold responsible to prepare data before parsing it, but it's not always that easy. And that's why i think @bluej100's thought is brilliant, having a preprocessor function which simply gives you the actual input to manipulate it at the beginning, __once__. That would have totally solved my problem.

I think the preprocessor callback is the way to go here.

**Comment by bluej100** [comment]
I believe #192 provides what we've discussed, @zemzelett . Would you review it, please?

**Comment by zemzelett** [comment]
I am going to review it tomorrow!

By the way: The name of the callback confused me at first, it doesn't sound clear to me. _processFirstChunk_ or _manipulateFirstChunk_ sounds a little bit clearer to me. But i'm not a native english speaker, so...

Anyways expect a review tomorrow!

**Comment by mholt** [comment]
Your English is good for a non-native speaker.

In this case, though, I will have to agree with keeping the name `beforeFirstChunk`, since the function only gets _executed_ before the first chunk, it doesn't necessarily process or manipulate it. And it will be consistent with the `before` callback of the jQuery plugin.

Thanks for taking a look!

**Comment by zemzelett** [comment]
Ok, after your explanation of the naming choice i can totally agree with it too.

**Comment by bluej100** [comment]
Well, the function must return the chunk if it doesn't manipulate it, for what it's worth.

**Comment by zemzelett** [comment]
Ok, i tested the callback functionality. I think it serves my purpose just perfectly and it's more flexible than my requested feature. And it's using less code.
Being able to work with the data before being parsed is a big plus for Papa, i think.

@bluej100 Referring to your last comment: If nothing is returned by the callback, Papa could use the original chunk, maybe? -> (`chunk = this._config.beforeFirstChunk(chunk) || chunk;`)


Sidenote:
I ran against an error testing the callback. But i think it's not related to the callback functionality. It's related to changing the chunk size or the chunk size in general and the row parameter on errors. I might open an issue if i can pin the error down more precisely.

**Comment by bluej100** [comment]
Oh, yeah, `|| chunk` is a good idea. Thanks for your testing.

**Comment by bluej100** [comment]
I might specifically check for `undefined`, so it doesn't ignore the empty string.

**Comment by zemzelett** [comment]
Right, checking for undefined (or if the return value is a string at all?) is needed, as an empty string could be valid data. True.
