### ISSUE TITLE
Using PapaParse inside a worker

### ISSUE THREAD

**Issue by marcelgwerder** [mholt/PapaParse#188]
I have the problem that the parser always wants to post the results using postMessage because I'm using PapaParse inside a worker.  I guess it's because it thinks it is one of the workers the parser spawned. 

Is there any kind of global where I can deactivate all the worker behaviour?

**Comment by bluej100** [comment]
I'm actually using PapaParse inside a worker myself. I just ignore the messages that don't match my accepted format. But yes, I can look into differentiating running as a worker from running in a worker.

**Comment by marcelgwerder** [comment]
Yes that's the workaround I decided to use too for now. But I guess it's not that efficient sending huge objects to the main thread without using it. Having a simple way to deactivate that behaviour would be nice.

**Comment by bluej100** [comment]
Yeah, you're totally right. I'll see what I can do.

**Comment by benekastah** [comment]
I think it would also be nice to provide the option to use `FileReaderSync` for people using PapaParse inside a worker.

**Comment by mholt** [comment]
@benekastah  FileReaderSync has issues. See [this comment and its link](https://github.com/mholt/PapaParse/blob/1c64d5c098570f243911e920bf7cbe170f69a9eb/papaparse.js#L590)
