### ISSUE TITLE
Header enabled makes data objects too large

### ISSUE THREAD

**Issue by ataft** [mholt/PapaParse#191]
When the header row is enabled, data is stored as an array of objects.  When it's disabled, data is stored as an array of arrays.  Since the meta object exists, I don't see the need for storing the header names in the data objects, which makes them much larger than they need to be.  Perhaps a "datatype" configuration option: JSON or Array?

**Comment by bluej100** [comment]
It sounds to me like you could just store your first row returned as a header row. The header option is intended for people who want objects returned.

Is your concern memory usage, or what? I would think the difference wouldn't be so large once the JIT compiler recognizes the object class.

**Comment by ataft** [comment]
Good point, thanks for the tip. Yes, memory usage was the concern, but as long as this method doesn't affect the dynamicTyping, then it should work perfectly. Thanks!
