### ISSUE TITLE
Release minor version bump with UMD?

### ISSUE THREAD

**Issue by cesarandreu** [mholt/PapaParse#193]
Since I'm using Webpack with PapaParse, I had to hard-code my `package.json` to use the following commit hash: [b3c84bf1f1a0781e5d30fe91e44c9e23699c362b](https://github.com/mholt/PapaParse/commit/b3c84bf1f1a0781e5d30fe91e44c9e23699c362b). 

Would you consider releasing a minor version bump, or do you have any planned release timeline in mind? 

If adding UMD causes breaking changes and merits a full version bump, would you consider releasing something like `v5.0.0-alpha.0` (`beta` or `pre` would also be fine)?

Thank you!

**Comment by mholt** [comment]
I'm swamped with school until April, but I will definitely be doing a release at that point. Sorry about the trouble! I'm anxious to do one too.

**Comment by cesarandreu** [comment]
Sure thing, thanks!

**Comment by snario** [comment]
+1

**Comment by mholt** [comment]
Better deployment is in the works. For now still a mostly manual process. Just released [4.1.1](https://github.com/mholt/PapaParse/releases/tag/4.1.1).

**Comment by cesarandreu** [comment]
Awesome, thank you @mholt! :D
