### ISSUE TITLE
Bundling with other libraries?

### ISSUE THREAD

**Issue by davidmegginson** [mholt/PapaParse#195]
The MIT license is very liberal (thank you), but I also wanted to check your own preferences as developer/maintainer:

* Are you comfortable with PapaParse being bundled as a separate file in the distro of another JavaScript library?
* Are you comfortable with PapaParse being combined with another JavaScript library in an all-in-one min-ified file (assuming full credit and a pointer to the original and its license info in the docs)?

Thanks. My particular use case is a Public Domain library for processing humanitarian-crisis data at the UN (and elsewhere), but this question is probably of broader interest.

**Comment by mholt** [comment]
- Yep, that's totally fine. Just take the license along with it (meaning, include the license file in there somewhere).
- Yeah that's good too. Just be aware that if you do this, you can't use the worker thread feature unless the other libs in the same file are hardened for worker environments, which is unlikely.

Thanks for asking! And always happy to see Papa being used for something so good.

**Comment by davidmegginson** [comment]
Thank you -- that works for us. I'll ping you when there are some public sites using Papa for humanitarian data.
