### ISSUE TITLE
Papa.unparse(Papa.parse(foo))

### ISSUE THREAD

**Issue by pykiss** [mholt/PapaParse#198]
It would be nice can to can parse a file, modify the parse result and unparse back easily.

For instance, 

    var csv = Papa.parse(foo, {header:true});
    detele csv.meta.fields[0];
    return Papa.unparse(csv);

**Comment by pykiss** [comment]
Ok, I just see that it is really easy.

   var csv = Papa.parse(foo, {header:true});
   csv.fields = csv.meta.fields;
   detele csv.meta.fields[0];
   return Papa.unparse(csv);

**Comment by mholt** [comment]
Making the parse output and unparse input symmetric would be really useful, actually. I'd you don't mind I will reopen this so I can remember to take a closer look to see if that's feasible.
