### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by domharrington** [mholt/PapaParse#200]
The version on NPM is 4.1.0 which was released in january https://github.com/mholt/PapaParse/commit/0e0ee8dcfa5e11f251c12b377ebf572d49c8800c

Any chance you can release a new version with the changes since then?

**Comment by mholt** [comment]
Yep, I promise that's high on my priority list. I just finished my last final exam for the semester this morning, so I'll have to collect my sanity and then I'll get right on it.

**Comment by domharrington** [comment]
@mholt great stuff. It's not a big deal, i can just put this in my package.json for now.

`"papaparse": "git://github.com/mholt/PapaParse#3bd5c47ddc1390415eab8aee0cd1bde9dff2f74c"`

Thanks for the great module!

**Comment by mholt** [comment]
Patch [4.1.1](https://github.com/mholt/PapaParse/releases/tag/4.1.1) just released. It should have only backward-compatible improvements and bug fixes.
