### ISSUE TITLE
getFileSize results in null error when using Content-Range

### ISSUE THREAD

**Issue by slafragola** [mholt/PapaParse#202]
Hello,

Using Windows 7, Firefox 37.02 / 37.01, papaparse.js v4.1.1, and the following code:

```js
function doStuff(results) {
		console.log(results.data);
}
	function parseData(url, callBack) {
		Papa.parse(url, {
			header: true,
			download: true,
			dynamicTyping: true,
			complete: function(results) {
				callBack(results);
			}
		});	
	}
	parseData("http://ipnumbers/logs/somefolder/somelog.CSV", doStuff);
```

Results in the following error:
TypeError: contentRange is null papaparse.js:574:3

If using the papaparse.min.js, the error becomes: t is null.

The line it's refering to is:
```
function getFileSize(xhr)
		{
			var contentRange = xhr.getResponseHeader("Content-Range");
			return parseInt(contentRange.substr(contentRange.lastIndexOf("/") + 1));
		}
```

Looking at the headers from my file, Content-Range or contentRange is not one of the values.  There is a "Range" value with bytes=0-5242879 under request headers and "Content-Length:	36680" under response headers.

Replacing Content-Range with Content-Length in papaparse.js fixes the issue.

Thanks

**Comment by cuiatec** [comment]
I can confirm this issue. Testing with local development environment on linux.

The webserver I'm using doesn't support partial content - it returns status code 200 with the full content. In this case only the Content-Length header could be used to get the file size.

Found [this post](http://www.cyberciti.biz/cloud-computing/http-status-code-206-commad-line-test/) that explains how to test for partial content. Maybe it can help.

**Comment by mholt** [comment]
Thanks for reporting this so clearly and accurately. It's actually a known issue - see #62 which was an attempt to solve this, but there is another, much more subtle issue with reverting to Content-Length.

This is unfortunate, as servers really should support Content-Range to be compliant with the HTTP/1.1 spec which has existed now for ~17 years.

**Comment by andekande** [comment]
I made a suggestion here, where one would autodetect if the Server supports Ranges:
https://github.com/mholt/PapaParse/commit/44cb0b04b508dd3e04f0fa5d3565c341a8ddfbf5#commitcomment-11461582

**Comment by mholt** [comment]
In retrospect, this issue may be fixed with 44cb0b04b508dd3e04f0fa5d3565c341a8ddfbf5, recently pushed to master. (It may be different than 62, now that I think about it. Ohhhh these bugz are so subtle!) Would you try again @slafragola, and see if the problem still occurs?

@andekande Thanks for your suggestion btw -- really appreciate it.

**Comment by JoeIsCool** [comment]
I believe you have fixed the issue.  Do you know when the fixed version hits Bower?

**Comment by mholt** [comment]
@JoeIsCool Soon - when I push the next patch release.
