### ISSUE TITLE
'before' callback for parse()?

### ISSUE THREAD

**Issue by cdasx** [mholt/PapaParse#208]
Similar to the `step` and `complete` callbacks, I've felt the need for a `begin` callback to execute tasks just before parsing is about to begin, setting a flag, for example. I'm currently doing this inside the `step` callback like so:
```
    ....
    step: function(results, parser) {
        if (!flag)
            flag = true;
    }
    ....
```
However, it'd be great if there were a way that avoided making unnecessary calls to `step()`

**Comment by mholt** [comment]
Why not just set the flag before calling the parse function?

**Comment by mholt** [comment]
Closing - if this is still an issue, feel free to comment.
