### ISSUE TITLE
requirejs error when minifying (4.1.0 onwards)

### ISSUE THREAD

**Issue by MartijnR** [mholt/PapaParse#209]
Sorry for the vague issue report.

When minifying my app including papaparse.js v4.1.0 using grunt-contrib-requirejs, the minified script throws an error:

```
Uncaught Error: Mismatched anonymous define() module: function (){return k}
```

The stack shows it occurs at `global.define(function() { return Papa; });` (around [here](https://github.com/mholt/PapaParse/blob/master/papaparse.js#L45))

V4.0.7 and lower do not have this issue.

**Comment by mholt** [comment]
@robd Would you know anything about this? I'm stumped. (I don't use RequireJS) - any reason why minifying the script would cause this error?

@MartijnR So this only happens using papaparse.min.js?

**Comment by robd** [comment]
I have no idea I'm afraid. 

@MartijnR, could you come up with a minimal project that exhibits this behaviour, and the commands we have to run to make the error occur?

As I understand it, you can successfully minify your app, which includes the un minimised papaparse.js using grunt-contrib-requirejs, but when you actually come to run your minified code you get the error. Is that right?

**Comment by MartijnR** [comment]
> As I understand it, you can successfully minify your app, which includes the un minimised papaparse.js using grunt-contrib-requirejs, but when you actually come to run your minified code you get the error. Is that right?

Yes, that's it. I'll try to create a minimal project to reproduce this (but some time after 1st of June probably)

**Comment by MartijnR** [comment]
After reading [this](http://requirejs.org/docs/errors.html#mismatch), I figured it had something to do with the global.define call. 

Changing the line to the following fixes it:
```
define( function() {	return Papa; } );
```

Would that break other use cases?

**Comment by mholt** [comment]
I'm flagging this as "help wanted" because, frankly, I know nothing about RequireJS so I probably shouldn't be the one to decide on this. :smile:

**Comment by robd** [comment]
Yeah, I don't know enough about this either I'm afraid. All I can say is that the latest PapaParse setup works for me. I use webpack 1.9.10 and load Papaparse like this:

```javascript
handleNewFile: function(event) {
  require('papaparse').parse(event.target.files[0], {
    complete: function(results) {
      // Use results
    }.bind(this)
  });
},
```

When I get a chance, I will try to see if this still works when `global.define(function() { return Papa; });` is replaces with just `.define(function() { return Papa; });`

**Comment by lee-reinhardt** [comment]
I just want to chime in here and say I was recently bitten by this issue. The change @MartijnR put forth fixed it for me.

I looked over many of the AMD-compatible modules we have in our app, and all of them do a plain global `define()` call. I wish I could articulate a clear reason for why this matters, but I cannot at the moment.

**Comment by mholt** [comment]
Thanks @lee-reinhardt, for your comment. Will get on this soon - sorry for the trouble.

**Comment by yiyezhiqiu** [comment]
Wow, I got the same error.
Thanks for the solution.
There is a lot of guys using requirejs optimization. :+1: 
Thanks!

**Comment by MartijnR** [comment]
Does this fix (and others) perhaps deserve a minor version bump to 4.1.2?

Thanks in advance!
