### ISSUE TITLE
Empty lines are not skipped if they are at the beginning of the file

### ISSUE THREAD

**Issue by LucasSeveryn** [mholt/PapaParse#214]
I am using papa parse to read a csv file hosted remotely. The issue is that header row is not in the first line of the file, instead, the file begins with a few empty lines, then we have the header row, and then all data. I am struggling to get papa parse to ignore the empty lines at the beginning of the file.

**Comment by mholt** [comment]
You could use `skipEmptyLines` config option, but the more correct thing to do would probably be to trim the whitespace from your input before sending it to be parsed. See [String.trim()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/Trim)

**Comment by LucasSeveryn** [comment]
Thank you for quick reply, skipEmptyLines does not work - papa parse will ignore the header row and assume it's a data row. If I understand correctly string.trim would require loading of the whole file first, losing the streaming option

**Comment by mholt** [comment]
That's what the `beforeFirstChunk` callback is for. You can use that to pre-process the beginning of the file, like trimming out whitespace. (Great idea, @bluej100!)

**Comment by LucasSeveryn** [comment]
beforeFirstChunk looks promising, but wouldn't that disable row by row streaming?

**Comment by bluej100** [comment]
No, beforeFirstChunk is compatible with the row callback. (It's not compatible with workers yet, though.)

**Comment by mholt** [comment]
That's because row streaming uses chunks under the hood, except that with row streaming, the data is only delivered to your code 1 row at a time, rather than the whole chunk at once.

**Comment by LucasSeveryn** [comment]
Ah, perfect. I will test that. BTW maybe the documentation for beforeFirstchunk needs an update in this case: "A function to execute before parsing the first chunk. This only applies if using a chunk callback. "

**Comment by bluej100** [comment]
Yeah, it should even work with "non-streaming" (null chunkSize) mode as well.

**Comment by mholt** [comment]
You're right - that's a mistake. Will leave this open until corrected.

**Comment by LucasSeveryn** [comment]
Is there a reason why this does not work? I was not able to find any documentation on the use of beforeFirstChunk with rows

Papa.parse('data/gen/pipelines/'.concat(filename), {
    download: true,
    header: true,
    dynamicTyping: true,
    skipEmptyLines: true,
    preview: 30,
    beforeFirstChunk: function(chunk) {
        console.log("beforeFirstChunk");
        console.log(chunk)
        console.log("afterFirstChunk");
        return chunk;
    },
    step: function(row) {
        console.log("Row:", row.data);
    },
    complete: function() {
        console.log("All done!");
    }
});
