### ISSUE TITLE
Question: does PapaParse support streaming from the bottom up?

### ISSUE THREAD

**Issue by LucasSeveryn** [mholt/PapaParse#215]
Many csv files have new data appended at the bottom - assuming a new 1MB CSV file is published every 10 minutes, what would be the best approach of loading new lines added since the last published file without iterating over the whole file?

**Comment by mholt** [comment]
I've looked into this before -- it's really hard to do, and nearly impossible to get it right across browsers. See #49. (I'll close this issue since it's technically a duplicate, but feel free to continue the discussion if you'd like.)
