### ISSUE TITLE
error when line ends with double (or more) quotes

### ISSUE THREAD

**Issue by andekande** [mholt/PapaParse#217]
see pull request #216
The cause is in Line #L1099 where on position is skipped when looking for the closing quote.
We need to change the condition. Not sure by now on how to do it best.

**Comment by andekande** [comment]
Hm I just read in RFC-4180, paragraph "If double-quotes are used to enclose fields, then a double-quote appearing inside a field must be escaped by preceding it with another double quote."
And indeed, escaping the quotes makes the same test pass fine

**Comment by mholt** [comment]
Closing according to conversation in PR #216.
