### ISSUE TITLE
Cannot set LocalChunkSize for workers

### ISSUE THREAD

**Issue by pulkitsinghal** [mholt/PapaParse#221]
As an experiment, I tried:

```
        Papa.LocalChunkSize = 1;
        Papa.parse(this.myFile, {
          header: true,
          chunk: function(rows) {
            console.log('Chunked Rows:', rows);
          },
          complete: function(results) {
            console.log('All done!');
          }
        });
```
And I saw lots of individual log statements for `Chunked Rows:` but when I set `worker: true`, it turned into just one log statement ... probably because the worker didn't get the change in `LocalChunkSize` ... I'm not sure if this is a bug or just a misconfiguration on my part.

**Comment by bluej100** [comment]
Yeah, that's currently not passed into workers. There is an undocumented chunkSize property on the config object that should work, though.

**Comment by pulkitsinghal** [comment]
Thanks!
