### ISSUE TITLE
Quotes with commas fails when in last column

### ISSUE THREAD

**Issue by jmeineke** [mholt/PapaParse#222]
When parsing, if you have a comma within quotes in the last column, a 'too many fields' error is returned.

This works:
header1, header2, header3, header4
item1,item2,"item 3,hi there",item4

This fails:
header1, header2, header3, header4
item1,item2,item3,"item4, hi there"

Config options are as follows:

            pConf = {
                delimiter: ",",
                header: true,
                complete: papaDone,
                skipEmptyLines: true,
            }

My callback is as follows:

        function papaDone(results, file) {
            
            /// <summary>
            /// called when papaparse is done parsing.
            /// </summary>
            /// <param name="results">The results.</param>
            /// <param name="file">The file.</param>
            /// <returns></returns>
            var maxErrors = 5;
            if (results.errors.length != 0) {

                for (err in results.errors) {
                    if (err > maxErrors-1) {
                        dealvhandler.addBatchImportError((results.errors.length - maxErrors) + ' ERRORS NOT SHOWN')
                        dealvhandler.showErrors();
                        return;
                    }
                    var row = results.errors[err].row == undefined ? '' : '<br />(row #' + (results.errors[err].row + 2) + ')';
                    dealvhandler.addBatchImportError(results.errors[err].message + row)
                }
                dealvhandler.showErrors();
                return;
            }

            //success
            toastr.info('todo - create pending deals')
        }

Am I missing a setting or is this a bug?

Thanks

**Comment by jmeineke** [comment]
pConf = {
                delimiter: ",",
                header: true,
                complete: papaDone,
                skipEmptyLines: true,
            }

**Comment by mholt** [comment]
I don't see any error with that input and those config options. Try it on the [demo page](http://papaparse.com/demo) and let me know if an error is reported in the console.

**Comment by jmeineke** [comment]
It is failing for me in the console as well using the following from a local file.  Data row 3 is good, 6 reports too many columns.

header1, header2, header3, header4
item1,item2, item 3, item4
item1,item2, item 3, item4
item1,"item2, dd", item 3, item4
item1,item2, item 3, item4
item1,item2, item 3, item4
item1,item2, item 3, "item4, fsdf"

**Comment by mholt** [comment]
That's because there's a space before the opening quote character in row 6. The quotes must be the first character after the delimiter to be considered an opening quote. Whitespace *is* significant.

**Comment by vergel-mercado** [comment]
Hi,
Regarding this commas, I have this issue that even inside the quote, the delimiter comma is still cutting/splitting the string. Let say i have this:

Column 1,Column 2,Column 3,Column 4
1-1,1-2,1-3,1-4
2-1,2-2,2-3,2-4
3-1,3-2,3-3,3-4
40,41,42,43
"Quoted,field",No quotes,"Foo","bar",extra
"Field quoted with
line break"

The "Quoted,field" will result as ["Quoted", "field",] .. i want to ignore that comma when it's inside the quotes. so the output i want would be ["Quoted,field", "No Quotes"] ..

**Comment by mholt** [comment]
@vergel-mercado I can't reproduce that in the demo on the website.

**Comment by vergel-mercado** [comment]
@mholt thanks for the quick answer. so, we don't have solution for this? :(

**Comment by mholt** [comment]
We don't have a problem :wink:

**Comment by vergel-mercado** [comment]
aww hahahaha! that's my problem, my client doesn't want to do that converting stuff lol

**Comment by mholt** [comment]
Sorry to hear that. If you find a bug in Papa Parse please feel free to open a new issue to report it so that it can be reproduced!
