### ISSUE TITLE
tab delimited file with field starting with double quote causes MissingQuotes error

### ISSUE THREAD

**Issue by twojustin** [mholt/PapaParse#226]
i have a tab delimited input string where one field starts with some double quoted string, but the quote finishes without it. 
```
edward\t"the rainmaker" norton\ted@norton.com
```

the parser raises the following error: 
```
code: "MissingQuotes"
message: "Quoted field unterminated"
```

i'm using 4.1.1

**Comment by mholt** [comment]
That's correct behavior. The second field has an opening quote but no closing quote at the end of the field. If you have quotes in the data, they need to be escaped as per [RFC 4180](https://tools.ietf.org/html/rfc4180#section-2).
