### ISSUE TITLE
beforeFirstChunk not working with minified source?

### ISSUE THREAD

**Issue by rwampler** [mholt/PapaParse#227]
Hi,

I can't seem to get 'beforeFirstChunk' callback to work with the latest 4.1.1 minified version of the parser, but the normal (fat) works fine.

Am I doing something wrong? Are there any work-arounds for this?

Thanks!

**Comment by mholt** [comment]
I'd need to see your code and the error message.

**Comment by rwampler** [comment]
I'll see if a can reproduce with a simple example, though everything works fine if we reference normal non-minified js library.

I'm not a minify expert, but shouldn't I still expect to see the literal "beforeFirstChunk" somewhere in the source, as that's the config option I'm setting in my code? I didn't see any references to it when searching through https://github.com/mholt/PapaParse/blob/master/papaparse.min.js

**Comment by mholt** [comment]
Without your error message, I'm only blindly guessing, but if you're using the minified file here in the repository, it is only built when Papa is released. 4.1.1 doesn't have the beforeFirstChunk callback. That will be rolled out in the next release.
