### ISSUE TITLE
Papa.unparse() failing to detect Array of objects

### ISSUE THREAD

**Issue by bourquep** [mholt/PapaParse#235]
I'm using `BabyParse.unparse()` to convert an array of objects to CSV. My code runs server-side in a [Parse cloud function](https://parse.com/docs/js/guide#cloud-code-cloud-functions).

My code is along those lines:

``` javascript
query.find().then(function(results) {
    var data = [];
    results.forEach(function(r) {
        data.push({
            col1: r.get('field1'),
            col2: r.get('field2'),
        });
    });

    var csv = babyparse.unparse(data);
    // csv is empty!
});
```

I've traced the source of the problem to this part of `BabyParse.JsonToCsv()`:

``` javascript
if (_input instanceof Array) // THIS RETURNS FALSE
{
    if (!_input.length || _input[0] instanceof Array)
        return serialize(null, _input);
    else if (typeof _input[0] === 'object')
        return serialize(objectKeys(_input[0]), _input);
}
else if (typeof _input === 'object')
{
        // It thinks my source array is an object!
}
```

I am no Javascript expert, so I can't comment on the nuances of `typeof` vs `instanceof` vs other methods of checking a type, but [this SO answer](http://stackoverflow.com/a/4775737/114623) seems to say that the preferred way to check if a variable is an array is:

``` javascript
Object.prototype.toString.call( someVar ) === '[object Array]'
```

I patched my copy of `babyparse.js` to use this check instead of `instanceof Array`, and sure enough it works and I get the csv I want.

Anyone who understands these JS intricacies better than I do care to comment?

**Comment by mholt** [comment]
Ugh, that's weird. That change feels so hacky... but I guess it is JavaScript. Will leave this open for a bit to see if anyone else has any thoughts before we go forward.

**Comment by bluej100** [comment]
If we'd rather require IE9 than include the prototype.toString, we could use [Array.isArray](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/isArray).

This comment from that SO question is probably roughly why it's failing: "v instanceof Array will return false if v was created in another frame (v is instance of thatFrame.contentWindow.Array class)."

**Comment by mholt** [comment]
Interesting. After looking into it some more, it seems that toString may be the best way to go about it and most standard among all the engines. I'm fine with that.

**Comment by bean5** [comment]
@bourquep could you open a PR with the change? Are there other places in the code that could adopt the accepted SO advice?

**Comment by bourquep** [comment]
@bean5 I haven't been using PapaParse/BabyParse for a long while... It should be fairly trivial for anyone to issue a PR.
