### ISSUE TITLE
Count rows of file before processing

### ISSUE THREAD

**Issue by DarkRanger** [mholt/PapaParse#236]
Is there any way that I can count the rows that the csv file has before starting the steps?

I want to say something like processing row 0 of 1000.

**Comment by mholt** [comment]
You want the preview feature? Set `preview: 1000` in your config.

**Comment by bluej100** [comment]
Since newlines can be in quotes, determining the number of rows in the file is equivalent to parsing the file. I would suggest that instead you use the file size and the cursor position from https://github.com/mholt/PapaParse/pull/125 to provide a progress indication.

**Comment by DarkRanger** [comment]
@mholt No I don't want the preview feature. I want to parse the whole file.

@bluej100 Thanks, will try that :)

**Comment by mholt** [comment]
I see now. I misread your last sentence. Yes, you'll have to parse the whole file. You can indicate progress by file size but that's about the best we can do.
