### ISSUE TITLE
Can't update DOM from step

### ISSUE THREAD

**Issue by Bird87ZA** [mholt/PapaParse#237]
I don't know if I'm doing anything wrong, but I can't update the DOM from a step.

This is my code:

```
$.getScript(config.basedir + '/app/lib/papaparse/papaparse.min.js',function() {
    Papa.SCRIPT_PATH = config.basedir + '/app/lib/papaparse/papaparse.min.js';
    pt.html('Libraries loaded, reading file. <span id=pp">0</span> rows processed.');
    var parser = $('#csv_file').parse( {
        delimiter: $('#delimeter').val(),
        worker: true,
        skipEmptyLines: true,
        config: {
            step: function(results,parser) {
                row++;
                $('#pp').html(row);
            }
        },
        before: function(file,inputElement) {
            return { action: "continue" };
        },
        error: function(err, file, inputElement, reason) {
        },
        complete: function() {
            console.log('done');
        }
    });
});
```

Is it not possible updating the DOM from inside a step or am I being an idiot.

**Comment by DarkRanger** [comment]
Forgot to mention, if I do a `console.log` from there it outputs on the fly.

**Comment by mholt** [comment]
First thing I notice is that the config property should contain the delimiter, worker, and skipEmptyLines properties. (See [docs for the jQuery plugin](http://papaparse.com/docs#jquery).)

You should be able to update the DOM from the step callback. It's hard to tell what's going on without seeing the rest of your code and page.

**Comment by pokoli** [comment]
I'm closing this issue as a valid answer have been given without more feedback in two years.
