### ISSUE TITLE
Incorrect result when last record ends with an empty quoted value

### ISSUE THREAD

**Issue by vsa** [mholt/PapaParse#238]
Consider this example:
```csv
a,1,""
b,2,""
c,3,""
```
Parsing this structure results in the following data:
```json
[
    [
        "a",
        "1",
        ""
    ],
    [
        "b",
        "2",
        ""
    ],
    [
        "c",
        "3",
        "\""
    ]
]
```
Notice that the last string value contains an extra double quote, which is incorrect IMHO. I'd at least expect every record to be treated equally.

**Comment by bluej100** [comment]
Confirmed with a test:

https://github.com/bluej100/PapaParse/tree/eof

On it.

**Comment by bluej100** [comment]
Tiny fix. I think I introduced this; sorry about that.

I'll merge it myself if @mholt doesn't get to it today.

**Comment by mholt** [comment]
Thanks for the fix! (Sorry, been busy with lots of things and another project lately.)

**Comment by bluej100** [comment]
I forgive you for your eight-minute delay. :smile:

**Comment by vsa** [comment]
That was quick … apologies not accepted :-)

**Comment by mholt** [comment]
Ha. I was referring more to all of the open issues/PRs I haven't gotten around to in months. But this one was easy.
