### ISSUE TITLE
Update documentation to show chunkSize

### ISSUE THREAD

**Issue by ssadams11** [mholt/PapaParse#242]
I ran across this config parameter roaming the forums for help.
It made a huge difference in my application.
But it missing from the docs.

I <3 Papa!

**Comment by mholt** [comment]
You mean the LocalChunkSize and RemoteChunkSize at the bottom of this page? http://papaparse.com/docs

**Comment by ssadams11** [comment]
Missed that, but it seems chunkSize works as well.
have another issue with large files but I'll post separate.

Thanks for the amazing response time!

**Comment by mholt** [comment]
chunkSize overrides the chunk size that applies to the type of file being parsed, so those are the defaults. Cheers!
