### ISSUE TITLE
Large file overwhelming Chrome (Oh, SNAP), even when using chunks

### ISSUE THREAD

**Issue by ssadams11** [mholt/PapaParse#243]
I have a 100MB file with about 400K csv records.  I have chunkSize set to 10000.  My chunk handler calls a Meteor method that posts http to a graph database in 5 record chunks due to limitations of REST API.  Papa blazes through the file, apparently creating a huge stack of server calls.  My server doesn't croak, but eventually the browser snaps, likely due to memory issues.  Is there a way to give Papa a coffee break so this doesn't happen?

My test runs make it through 300K records

**Comment by mholt** [comment]
Could I see your code?

**Comment by bluej100** [comment]
Perhaps you could create a worker which does the parse and ajax requests synchronously? That would be a fairly straightforward way to ensure only one request is in flight at a time.

**Comment by ssadams11** [comment]
Client Side:
Template.Home.rendered = ->
  $('.parse-button').click ->
    window.REPORTS={}
    Session.set 'totalRecords',0
    $('#files').parse
      config:
        header: true
        #preview: 360000
        skipEmptyLines:true
        chunkSize: 10000
        chunk: ((chunk, handle)->
          file = handle.fileBeingParsed
          if not window.REPORTS
            window.REPORTS = {}
          if not window.REPORTS[file.name]
            window.REPORTS[file.name]=0
          window.REPORTS[file.name]=window.REPORTS[file.name]+chunk.data.length
          console.log window.REPORTS
          props = []
          for results in chunk.data
            #console.log 'Row data: ', results
            propsForVert = results
            propsForVert['__ingestedFromFile']=file.name
            propsForVert['__originalTableName']=file.name.slice 0,(file.name.length-4)
            propsForVert['__ingestedAtTime']= (new Date()).toString()
            propsForVert['__type'] = 'ingestedCSVRecord'
            props.push propsForVert
          Session.set 'totalRecords',(Session.get 'totalRecords')+props.length
          total = 'Added '+props.length+' to '+(Session.get 'totalRecords')+' total records added'
          if props.length > 0
            Meteor.call 'addVertices', props, total, (err,resp)->
              if err
                console.log 'ERROR=',err
                window.RetryQueue.push
              if resp
                console.log 'RESPONSE=',resp
        )
      before: ((file, inputElem)->
        #window.REPORTS[file.name]=0

        console.log 'Parsing file:', file.name
        Session.set 'fileBeingParsed', file.name
        Session.set 'recordsParsed',0)
      complete: ((file)->
        if file
          console.log 'Completed',file.name
        Session.set 'fileBeingParsed',''
        Session.set 'reports',JSON.stringify(new Date())   #to force an update

      )

**Comment by ssadams11** [comment]
If you are wondering about the little  " file = handle.fileBeingParsed", I hacked your code to pass the file up through the handler so I could have the name inside the chunk handler

**Comment by mholt** [comment]
Hmm, would handle.pause() work for you? You could pause while you wait for the network to catch up and then resume when you're ready for the next chunk.

**Comment by bluej100** [comment]
Oh, handle.pause is a perfect idea.

**Comment by ssadams11** [comment]
Never tried it.  Given all the async stuff going on everywhere, I'm not sure I know how to tell when the logjam is over.  Any ideas?

**Comment by bluej100** [comment]
You should be able to handle.resume in the complete callback from your ajax request.

**Comment by ssadams11** [comment]
That seems to be doing the trick....
Thanks for the support!
