### ISSUE TITLE
PapaParse unparser is not flattening  the input object

### ISSUE THREAD

**Issue by tejasatara** [mholt/PapaParse#245]
Hi,

I am using Papa unparser in my project. All my input is highly dynamic and unpredictable (nested objects and arrays).
When I provide a input which has nested objects the unparser just writes [object Object] instead of flattening the object. 

Example : 
```javascript
{
    "_index": "documents",
    "_type": "message",
    "_id": "4868ecf0-01ba-3f1a-b6f5-e7eb0c9c630f",
    "_score": null,
    "_source": {
        "fileName": "dynamically-loading-controllers-and-views-with-angularjs-and-requirejs",
        "header": {
            "artifactModifiedBy": "ops",
            "source": "internal",
            "artifactCreatedDate": 1438247629068,
            "uuid": "250efb1c-57e7-44f7-a02a-eee1bef9dc48",
            "type": "message",
            "date": 1438247629232,
            "relationships": {
                "parent": "a6d84953-8f0a-41f4-8fb5-756b5f65ea1b"
            },
            "artifactModifiedDate": 1438247629232,
            "artifactUUID": "4868ecf0-01ba-3f1a-b6f5-e7eb0c9c630f"
        },
        "mimeType": "text/html; charset=utf-8",
        "size": 88707
    },
    "sort": [
        1438247629232
    ]
}
```
The _source field just written as [object Object].

**Comment by mholt** [comment]
Printing any object as a string results in [object Object] - you need to traverse the data structure to print what you're looking for, or use console.log().

**Comment by tejasatara** [comment]
Thanks for the update.  I have written a flatten script which does the traversing,  it would've been great if it was a part of parser itself.

**Comment by leblancmeneses** [comment]
following worked for me
https://www.npmjs.com/package/flat

const csv = Papa.unparse(this.itemSource.map(flatten));
