### ISSUE TITLE
Ignores empty headers

### ISSUE THREAD

**Issue by DarkRanger** [mholt/PapaParse#247]
Hi,

When I import a CSV file with headers, the importer ignores columns with empty headers. Since this importer is mostly used for customer data, I have no control over what's in the header field. What it seems to be is that, because the header is empty, it keeps writing that row's data to the same (empty) key, so it keeps overwriting it.

Can I suggest an improvement where if it picks up an empty header it names it unknown_1, unknown_2 etc?

**Comment by DarkRanger** [comment]
Okay, I've made a change to my local files. The method `fillHeaderFields()` on line 763.

ORIGINAL:

    function fillHeaderFields()
    {
        if (!_results)
            return;
        for (var i = 0; needsHeaderRow() && i < _results.data.length; i++)
            for (var j = 0; j < _results.data[i].length; j++)
                _fields.push(_results.data[i][j]);
        _results.data.splice(0, 1);
    }

MODIFIED:

    function fillHeaderFields()
    {
        var unknown = 0;
        if (!_results)
            return;
        for (var i = 0; needsHeaderRow() && i < _results.data.length; i++)
            for (var j = 0; j < _results.data[i].length; j++) {
                if(_results.data[i][j] == "") {
                    _results.data[i][j] = "No Header " + unknown;
                    unknown++;
                }
                _fields.push(_results.data[i][j]);
            }
        _results.data.splice(0, 1);
    }

**Comment by mholt** [comment]
I'm glad you found a solution that works for you. I'm not sure that it's the right thing to do for everyone, but thank you for posting it here so others looking for a similar thing can adopt your answer. :+1:

**Comment by DarkRanger** [comment]
Sorry for continuing this here, but, out of interest, why do you not thig it's the right thing to do for everyone? I'm just curious, as I believe that most of the uses of papaparse will be for a user to upload lots of data. This means you work on the assumption that all csv files will always have all the headers. And I can assure you, the majority of people in South Africa think that CSV is some form of handout. :stuck_out_tongue_closed_eyes:

**Comment by mholt** [comment]
It's simple, really. Papa Parse is a CSV parser. Changing the parsed data to something that wasn't there is not aligned with the goals of the project. I don't operate on the assumption that all CSV files have header rows. If your CSV files don't have headers, turn off the headers setting.

**Comment by AndreasHassing** [comment]
In case someone reaches this and is not interested in modifying PapaParse internals, you could do something like:

```javascript
// deconstruct Papa.parse `data`-property and give it the `rows` alias
var { data: rows } = Papa.parse(yourCsvInput, {
    // don't set `headers` to true, else you will lose data from unnamed columns
    dynamicTyping: true
});

// rename unnamed headers to `_unnamedColumn{columnIndex+1}`
// +1 since non-devs usually don't think of columns as 0-indexed
var headers = rows[0].map((h, idx) => h || ('_unnamedColumn' + (idx + 1)));

// helper function to make the map-reduce below look prettier
var reduce = fun => lst => lst.reduce(fun, {});

var rowObjects =
    rows
    // skip first row which are headers
    .slice(1)
    // map: for each row... reduce: each column in the row to an object that contains
    // each column's value as a property
    .map(reduce((acc, val, idx) => ({ ...acc, [headers[idx]]: val })));

console.table(rowObjects);
```

Sample input:
```csv
Column 1,Column 2,,Column 4,Column 5,,
1-1,1-2,,1-3,1-4,5,
2-1,2-2,wups,2-3,2-4,,3
3-1,3-2,,3-3,3-4,,
4,5,,6,7,,hi
```

Sample output:
|(index)|Column 1|Column 2|_unnamedColumn3|Column 4|Column 5|_unnamedColumn6|_unnamedColumn7|
|--|--|--|--|--|--|--|--|
|0|"1-1"|"1-2"|null|"1-3"|"1-4"|5|null|
|1|"2-1"|"2-2"|"wups"|"2-3"|"2-4"|null|3|
|2|"3-1"|"3-2"|null|"3-3"|"3-4"|null|null|
|3|4|5|null|6|7|null|"hi"|

**Comment by nickgrato** [comment]
> It's simple, really. Papa Parse is a CSV parser. Changing the parsed data to something that wasn't there is not aligned with the goals of the project. I don't operate on the assumption that all CSV files have header rows. If your CSV files don't have headers, turn off the headers setting.

but isn't adding _1 _2 worse than say a static value we could pinpoint and remove?"_1" and "_2" is not in the original file so there is manipulation. I think there could just be a better way to about it. Ideally I could map through my fields and remove a static value than chasing an indexed value.
