### ISSUE TITLE
Custom header label

### ISSUE THREAD

**Issue by nhduc296** [mholt/PapaParse#249]
I need this feature, please help to to implement it.
var field = ['col1', 'col2'];
var fieldName = ['First  Column', 'Second Collumn']
var data = {
col1: 'abc',
col2: 'xyz'
}

Papa.unparse(data, {field: field, fieldName: fieldName})

**Comment by bluej100** [comment]
Here's a way to do that with Underscore:

```
var rawData = _.map(data, function(x) {return _.values(x);})
Papa.unparse({fields: field, data: rawData});
```

**Comment by nhduc296** [comment]
hi @bluej100, I can explicit transform data, but I think many people need this feature

**Comment by mholt** [comment]
Hopefully Braden's comment was helpful. Papa Parse isn't in the business of arbitrarily transforming data; it's just good at parsing CSV. There are many popular libraries which already perform these mappings, so we'll leave it to the experts for that. :wink:

**Comment by nhduc296** [comment]
@mholt thank you for your comment
