### ISSUE TITLE
Aurelia

### ISSUE THREAD

**Issue by johntom** [mholt/PapaParse#250]
Hi,
I've been doing a lot of work lately with Aurelia and I'm now testing the papa unparse feature. Aurelia.io uses the latest ES6 and ES7 and Everything looks good in Chrome debugger  but file does not get saved. I will create a gist when complete. 
Thanks,
![aureialscreenshot](https://cloud.githubusercontent.com/assets/1877376/9293452/d0969368-43f9-11e5-8322-20b6bb8fa189.png)

```
buiding-list.js
import {  PapaParse} from '../resources/papaparse';
modalCode(building) {
    console.log('  building.BuildingId ', building.BuildingId, building)
    this.headingModal = building.BuildingId + '/' + building.Address;
     this.url = 'http://some_restful_endpoint';
    this.isLoading = false;
    return this.http.get(this.url).then(response => {
      this.lists = response.content.data;
      console.log('  this.lists ', this.lists) // returns array of json objects
      let pconfig = {quotes: true,delimiter: ",",newline: "\r\n"}
      var csv = Papa.unparse(response.content.data,pconfig);
      return {
       title: "c:\files\Daily",
        content: csv
      }
      $('#modal1').openModal(); // open materializecss modal
    });
  }
```

**Comment by johntom** [comment]
Hi,
i created a plnkr http://plnkr.co/edit/Fq9F2L that tries to use papaparse. The plnkr says that Papa is not defined while my code does not have this problem and I can debug and see all the Papa properties the file does not get wriitten to disk.
```
  let pconfig = {
        quotes: true,
        delimiter: ",",
        newline: "\r\n"
      }
      // var
      var csv = Papa.unparse(this.piedata, pconfig);
       return {
         title: "c:\files\testpapaparse",
         content: csv
       }
```

**Comment by mholt** [comment]
Well, I don't know anything about Aurelia (or plinkr) so you might have to ask them for support. But let me know if there's anything I can help you with about Papa Parse!

**Comment by johntom** [comment]
Hey Matt, I'm just trying to get papaparse to work with Aurelia (http://aurelia.io/) as it does with with angular 1.x.  I'm sure the same type of issue will exist for Angular 2 whenever it arrives. Plnkr is just a site where developers put up samples.

**Comment by mholt** [comment]
Gotcha. You're welcome to post the solution here so it can help other people. (I just closed it since there's nothing else for me to do with it, as far as I can tell.) Good luck!
