### ISSUE TITLE
Cue CSV files with Papaparse.

### ISSUE THREAD

**Issue by jondo89** [mholt/PapaParse#251]
Hi Matt ,

Thanks again for the great CSV parser , I am having some difficulty with processing so pretty bulk data , it is SCADA data from a stock pile reclaimer , and we are trying to use papa-parse to summarize the data into a JSON summary table.

each csv is a readout from 1 day at 1 Hz with 22 columns , as such the 3 months worth of data cannot be conducted In a bulk operation as any more than 1 csv being parsed at a time clogs up the memory . As such I need to put together a cue function , however the config setting option does not provide much flexibility to parse the file name as a local variable through it.

Using an array of file names to run a function effectively triggers then entire batch of ajax calls at the same time . What i would like to do is place a function callback in the complete area of the papa-parse config area , however the AJAX query clears the file name local variable as it passes though the papa -parse function.

What is the best way to pass a variable through the papa-parse function ? (or maybe some has done a cue function for papa-parse already.)

Thanks Jon

**Comment by mholt** [comment]
So instead of effectively calling Papa.parse in a loop, why not call it after a file is finished parsing instead? (In the complete callback.) I don't see why you have to overwrite the file name variable for every AJAX request (a request you're making, I imagine?).

**Comment by jondo89** [comment]
Thanks for the response , I think I have cracked it , The problem was not calling config file correctly and in the correct sequence.

**Comment by jondo89** [comment]
Great  ,16 min for 110 000 000 data points (504000 rows) , taking max , min , average , count , greater than , less than  , between and not between , and writing to disk!

**Comment by mholt** [comment]
Cool, glad it's working for you now!
