### ISSUE TITLE
Reading special characters

### ISSUE THREAD

**Issue by joshbenhamou** [mholt/PapaParse#253]
Hi, thanks for the fantastic work on the plugin.

Everything is working extremely well, however, whenever a special character is in the CSV file that I import, the parse is unable to read it and return this: �

Is there support for special characters?

Thanks

**Comment by mholt** [comment]
You need to specify the encoding in the config.

**Comment by mbaquerizo** [comment]
@mholt What would be valid values for the encoding option?
