### ISSUE TITLE
add header row 

### ISSUE THREAD

**Issue by ballesdbc** [mholt/PapaParse#254]
Is there any way to add the fields of the header?

I've tried using 
fields: ["Column 2", "Column 2"]
 header: true
 
but it doesn't work, any idea?

**Comment by mholt** [comment]
When parsing CSV data, the header row has to already exist and you have to set header: true for Papa to interpret the first row as a header row.

**Comment by ballesdbc** [comment]
In the case that my first line isnt a header, is it possible to set the fields?

**Comment by mholt** [comment]
Hmm, no, you'll have to use numeric indexing (is faster anyway).

**Comment by ballesdbc** [comment]
thanks!
