### ISSUE TITLE
requirejs build

### ISSUE THREAD

**Issue by ataft** [mholt/PapaParse#255]
The papaparse library can't be integrated with a build because it includes a bad AMD define signature that can’t be discovered by the optimizer, which causes it to define itself as the main module and breaks the application.

**Comment by mholt** [comment]
Huh? (Remember you're speaking to a non-requirejs guy, here!) Calling anyone else who knows what this means to help out here. @ataft Do you have any steps you'd recommend to fix whatever is wrong?
