### ISSUE TITLE
Option to perform data conversion (dynamicTyping) only if data is not enclosed between double quotes

### ISSUE THREAD

**Issue by luiscdsc** [mholt/PapaParse#260]
The dynamicTyping options works great but sometimes something that looks like a number but is not is converted into a number when using it.

I've seen other issues related to this and I think an easy fix it would be to add a setting to disable data conversion if the value is enclosed in double quotes. For example, in the line below the first column would be converted to a number but not the second one, the third column would be converted to a boolean but not the fourth one

123,"456",true,"false"

**Comment by mholt** [comment]
Thanks for the suggestion.

> sometimes something that looks like a number but is not is converted into a number when using it.

Can you explain more what you mean here? Maybe give an example or two.

**Comment by luiscdsc** [comment]
Thanks for your reply. For an example of what I mean, in the system I am using your library in a pilot project we have a field called "order number" which look like this:

23422827
00283762-3
00202938

As you can see, although some look just like numbers, this field is not a number. Leading zeros, if present, need to be preserved and an order number can have a dash in it. Loading this data using dynamicTyping enabled would result in:

23422827 -> number
00283762-3 -> string
202938 -> number

... while all 3 values should ideally be treated as strings.

**Comment by mholt** [comment]
Hmm, I would recommend simply disabling dynamic typing, then, since by default all data is treated as strings.

**Comment by ataft** [comment]
I made a pull request to allow for a "leadingZeroAsString" config option when using dynamicTyping:
https://github.com/mholt/PapaParse/pull/332

Would this work?

**Comment by pokoli** [comment]
I'm closing this in favour of #377
