### ISSUE TITLE
Support for ndjson

### ISSUE THREAD

**Issue by jeroenooms** [mholt/PapaParse#262]
>  [NDJSON](http://ndjson.org/) (Newline delimited JSON) is a convenient format for storing or streaming structured data that may be processed one record at a time. It works well with unix-style text processing tools and shell pipelines. It's a great format for log files.

Example form the [spec](http://dataprotocols.org/ndjson/) page

``` json
{"some":"thing"}
{"foo":17,"bar":false,"quux":true}
{"may":{"include":"nested","objects":["and","arrays"]}}
```

**Comment by pokoli** [comment]
I'm wondering how we should support ndjson. As fas as there is a javascript library that can convert between json and javascript objects we don't have nothing to do. Parsing files on a diferent format than CSV/TSV is out of the scope of this project. 

I close the issue. Re-open it if you don't agree.
