### ISSUE TITLE
BabyParse - reading large files is a stronger usecase in Node

### ISSUE THREAD

**Issue by ghostsquad** [mholt/PapaParse#263]
I'd file this in the BabyParse repo, but because it's seen as a "fork", it doesn't support issues.

Reading an entire file into memory to be parsed by BabyParse can be a problem. Given that Node applications are more likely to have direct access to the filesystem, it seems like it would be a stronger usecase to support filestream parsing.

**Comment by bluej100** [comment]
Relevant: https://github.com/mholt/PapaParse/pull/201

**Comment by alokrajiv** [comment]
very much agree with @ghostsquad . Facing the same issue solvable only by input from stream . @bluej100  is the development of the node version still ongoing?

**Comment by pokoli** [comment]
I'm closing this in favour of #370
