### ISSUE TITLE
Random object created at end of output

### ISSUE THREAD

**Issue by indiesquidge** [mholt/PapaParse#264]
First off, thanks for the awesome library! Really enjoy using it. However, I'm noticing something strange. Given my file, `merchants.csv`
```txt
id,name,created_at,updated_at
1,Schroeder-Jerde,2012-03-27 14:53:59 UTC,2012-03-27 14:53:59 UTC
2,"Klein, Rempel and Jones",2012-03-27 14:53:59 UTC,2012-03-27 14:53:59 UTC
3,Willms and Sons,2012-03-27 14:53:59 UTC,2012-03-27 14:53:59 UTC
```
and my current method of parsing this
```javascript
Parser.prototype.parse = function (file) {
  var csvContents = fs.readFileSync(file, 'utf8');
  var parsed = Baby.parse(csvContents, { header: true });
  var rows = parsed.data;
  console.log(rows);
};
```
My output seems to be all correct, only there is an extra object that is always present at the end of the file, with a key of whatever my first header is (in this case, `id`) and an empty string value.
```sh
[ { id: '1',
    name: 'Schroeder-Jerde',
    created_at: '2012-03-27 14:53:59 UTC',
    updated_at: '2012-03-27 14:53:59 UTC' },
  { id: '2',
    name: 'Klein, Rempel and Jones',
    created_at: '2012-03-27 14:53:59 UTC',
    updated_at: '2012-03-27 14:53:59 UTC' },
  { id: '3',
    name: 'Willms and Sons',
    created_at: '2012-03-27 14:53:59 UTC',
    updated_at: '2012-03-27 14:53:59 UTC' },
  { id: '' } ]
```
Any ideas where this is coming from? Am I missing some sort of option in `config` that needs to be set? I apologize in advance if this is already an issue. I tried searching for it before making this new issue.

**Comment by mholt** [comment]
Does your file end with a new line?

**Comment by indiesquidge** [comment]
Ugh, yes. My editor does that by default on save but it doesn't show it in the file. I just realized that right as I posted this issue. Thanks for the (insanely) speedy response though :)

**Comment by mholt** [comment]
Easy question, easy answer ;)
