### ISSUE TITLE
Multiple Delimiters

### ISSUE THREAD

**Issue by michaelvaneck** [mholt/PapaParse#267]
Hello! Awesome library but I can't seem to find a way to add multiple delimiters to my parse.

My CSV file consists of comma's, vertical bars, and empty spaces.

**Comment by mholt** [comment]
That's awful. Why isn't there just one delimiter?

**Comment by michaelvaneck** [comment]
I have no clue! But I tried to parse the result object from the parse to "re-parse" it for a second time but that won't work.

Any idea's how to fix this?

**Comment by mholt** [comment]
Honestly, ask the person who made the CSV file to do it correctly -- CSV files have one consistent delimiter.

Or do a search-replace before parsing... if you dare. :wink: It might work for you depending on your data.

**Comment by michaelvaneck** [comment]
Yes i already thought about a mass replace but this would be very inefficient. I actually dont know why they use multiple symbols in their CSV but I cant ask them to change it it's integrated in their entire software structure.

**Comment by mholt** [comment]
I would replace them, yes it'll be inefficient and hard depending on what the data is like, but that's a pretty bad situation. Their software should not be writing CSV files like that. Good luck!
