### ISSUE TITLE
Guess delimiter error

### ISSUE THREAD

**Issue by T00rk** [mholt/PapaParse#270]
In some csv files I use, the is a delimiter (for example ";") and in every line, columns are filled with spaces to always have the same width. That's strange and useless but it exists.
The problem in this case is papaparse is unable to guess the correct delimiter and nothing happens.

I've modified the guessDelimiter function like this.

	function guessDelimiter(input, newLine)
	{
		var delimChoices = [",", "\t", "|", ";", Papa.RECORD_SEP, Papa.UNIT_SEP];
		var bestDelim, bestDelta;
		var delimData = [];

		for (var i = 0; i < delimChoices.length; i++)
		{
			var delim = delimChoices[i];
			var delta = 0, avgFieldCount = 0, firstLineCount = 0;

			var preview = new Parser
                        ({
				delimiter: delim,
				newline: newLine,
				preview: 10
			}).parse(input);

			for(var j = 0; j < preview.data.length; j++)
			{
				var fieldCount = preview.data[j].length;

				if(j === 0)
				{
					avgFieldCount = fieldCount * 10;
					firstLineCount = fieldCount;
				}
				else
				{
					if(fieldCount > 1)
					{
						avgFieldCount += fieldCount;
					}
				}
			}

			avgFieldCount /= (preview.data.length + 9);
			delimData[i] = { avg : avgFieldCount, fl : firstLineCount, delta : Math.abs(avgFieldCount - firstLineCount) };
		}

		for(var i = 0; i < delimData.length; i++)
		{
			if(delimData[i].avg > 1)
			{
				if(typeof(bestDelta) === 'undefined')
				{
					bestDelta = delimData[i].delta;
					bestDelim = i;
				}
				else
				{
					if(delimData[i].delta <= bestDelta)
					{
						bestDelta = delimData[i].delta;
						bestDelim = i;
					}
				}
			}
		}

		_config.delimiter = delimChoices[bestDelim];

		return {
			successful: !!_config.delimiter,
			bestDelimiter: _config.delimiter
		}
	}

and the parse function like this

    this.parse = function(input, baseIndex, ignoreLastRow)
	{
		if (!_config.newline)
			_config.newline = guessLineEndings(input);

		_delimiterError = false;
		if (!_config.delimiter)
		{
			var delimGuess = guessDelimiter(input, _config.newline);
			if (delimGuess.successful)
				_config.delimiter = delimGuess.bestDelimiter;
			else
			{
				_delimiterError = true;	// add error after parsing (otherwise it would be overwritten)
				_config.delimiter = Papa.DefaultDelimiter;
			}
			_results.meta.delimiter = _config.delimiter;
		}

		var parserConfig = copy(_config);
		if (_config.preview && _config.header)
			parserConfig.preview++;	// to compensate for header row

		_input = input;
		_parser = new Parser(parserConfig);
		_results = _parser.parse(_input, baseIndex, ignoreLastRow);
		processResults();
		return _paused ? { meta: { paused: true } } : (_results || { meta: { paused: false } });
	};

**Comment by mholt** [comment]
Huh, that is a very strange use case indeed. Thanks for sharing! Maybe it will be able to help other people who come looking for the same answer.
