### ISSUE TITLE
Support true streaming

### ISSUE THREAD

**Issue by at88mph** [mholt/PapaParse#271]
Hi there,

I have a need to support streaming from a URL.  There is a feature for this now, but the entire file is read before the streaming happens.  The XMLHttpRequest supports a progress event that could facilitate actual streaming from the response.

I have a large SlickGrid that could have data streamed into it as it comes in, rather than waiting for the entire file and then have the grid loaded.

I saw a couple of issues that could potentially be duplicates of this.  I'm sorry if it is a duplicate.

Many thanks.
Dustin

**Comment by mholt** [comment]
Specify a chunk callback and the file will be downloaded in small chunks, it doesn't load the entire file.

**Comment by bluej100** [comment]
Specifically, NetworkStreamer loads in 5 MB HTTP range chunks. It would be cool for it to use the progress event, but it would add complexity, especially if we can't depend on it in all browsers.

**Comment by bluej100** [comment]
Looks like IE9 doesn't have progress callbacks, judging by http://caniuse.com/#feat=xhr2 .

**Comment by at88mph** [comment]
Thank you for the quick replies.  Does this look right, then:
```javascript
    ....
    download: true,
    chunk: function(results, parser) {
                // Array of rows.
                var rowArray = results.data;

                for (var i = 0, rl = rowArray.length; i < rl; i++)
                {
                  rowCount++;
                  processNextRow(rowArray["0"][i]);
                }
    }
```

It seems like my 50MB file is still downloading entirely, but I'll test more.  I'm using 4.1.2.

**Comment by at88mph** [comment]
By the way, does it rely on the Content-Range header being present?

**Comment by mholt** [comment]
@at88mph I'm not sure what `processNextRow` does, but that's the basic idea. `results` will contain the results of parsing all the rows of just that chunk.

It does rely on the server supporting Content-Range. Python's simpleHTTPserver, for example, does not.

**Comment by at88mph** [comment]
Sorry, the processNextRow is my own function.

**Comment by bluej100** [comment]
FYI, if you just want to process one row at a time, you can also stream with a step callback. See https://github.com/mholt/PapaParse/blob/master/papaparse.js#L485 .

**Comment by at88mph** [comment]
The step and chunk functions work well, but the file is still being downloaded underneath.  

My Java servlet that streams out the CSV data does not include the Content-Range header.  It only includes the Content-Type.  I'll need to read up on the Content-Range header and what it means I think.

Thanks.  I like this library's simplicity!

**Comment by mholt** [comment]
Yeah, the server isn't fully compliant with the HTTP spec. Glad we figured that out. :smile: Good luck, and thanks for using Papa Parse!
