### ISSUE TITLE
Parsing some files

### ISSUE THREAD

**Issue by Sergiodiaz53** [mholt/PapaParse#274]
Hi,

Is possible for papaparse to deal with some files automatically?

I'm loading 3 or 4 files through FileReader, so I have a function called 'handleFiles' that receives and array of files. After that I'm calling Papaparse to parse the files with a for. 

The problem is that I'm using the CSV to paint in a Canvas and for each file there is one 'complete' method executed which calls the 'redraw' function. So the first time I paint file 0, the second time I paint file 0 and 1, third 0,1 and 2.. and so.

I know how to change in my code to avoid this, but my question is: Is there an option to give Papaparse an array of files and execute like a finalcomplete or similar? The problem is that I can't put it after the for because I'm using workers, so the methods executes before worker finish.

**Comment by mholt** [comment]
You can [use jQuery](http://papaparse.com/docs#jquery) to select the files you have for parsing.

**Comment by Sergiodiaz53** [comment]
I already have my files into an array (files) through the FileReader, but now can I pass the full array to papaparse?

I mean, I'm doing this:


for( index = 0; index < files.length; index++) {

        Papa.parse(csv, {
            worker:true,
            complete: function (results) {
                lines[index] = results.data;
                redraw();
            },
            error: function(err,reason){
                alert(err);
                alert(reason);
            }
        });
}

So if I put three files it executes the method 'redraw()' three times. But I want that it will be executed just once at the end of reading the three files.

Where 'files' is an array of files and not just one. If I set workers to false, like this: 

for( index = 0; index < files.length; index++) {

        Papa.parse(csv, {
            worker:false,
            complete: function (results) {
                lines[index] = results.data;
            },
            error: function(err,reason){
                alert(err);
                alert(reason);
            }
        });
}
redraw();

It works like I want, but workers are not working. I hope I had explained better.
Thanks in advance.

**Comment by bluej100** [comment]
I would suggest that you set parseCount = files.length and then parseCount-- in your complete function. Then when parseCount == 0, you can redraw.

**Comment by Sergiodiaz53** [comment]
Thanks bluej100, I don't know how I didn't see it. I was thinking about events, callbacks.. when sometimes simple answers works!!.  Fixed and working. Thanks again.
