### ISSUE TITLE
Question - Can i use papaparser for implement a Leaflet plugin?

### ISSUE THREAD

**Issue by p4535992** [mholt/PapaParse#275]
Hello I just finished implementing a new function for a plugin Leaflet for the use of csv file, and to do that I had used PapaParser, now i wanted to implement my solution in the plugin to make it available to others, but first I wanted to know if for you, It was fine.
The File of the project where i is used papaParse is http://adf.ly/1Rlv8d .
Best regards.

**Comment by mholt** [comment]
That's fine, just credit Papa Parse when you distribute your plugin. Thanks for using it!
