### ISSUE TITLE
Two consecutive double quotes get merged to one

### ISSUE THREAD

**Issue by trych** [mholt/PapaParse#276]
Hello there,
now, I am very new to all this JavaScript, CSV and JSON business, so I hope this is nothing that I am doing obviously wrong, but I observed something strange happening, if I try to parse a csv file that contains a field with a JSON syntax, which in itself contains a part with two consecutive double quotes.

Consider this simple CSV:

```
id;json
1;"{"_content": ""}"
```

If I PapaParse this and try to access `data[1][1]`, then instead of  `{"_content": ""}` it returns `{"_content": "}`, which subsequently I cannot parse anymore of course.

However, if the original file is
```
id;json
1;"{"_content": " "}"
```

(with a space between doublequotes), then it works just as intended.
According to jslint and jsonlint, `{"_content": ""}` is a perfectly valid JSON, so I think it should work.

Oh, and it also keeps the two double quotes, if I set `fastMode: true`, but then, I cannot parse the file at all, as it contains numerous double quotes.

Not sure, if all this was known already, either way, thanks for looking into it.

**Comment by mholt** [comment]
```
id;json
1;"{"_content": ""}"
```

This CSV data is malformed. Quotes need to be escaped with another quotes preceding them, like so:

```
id;json
1;"{""_content"": """"}"
```

Fast Mode only works if the file doesn't contain quoted fields. It will automatically use this for you if it can.

**Comment by trych** [comment]
Thank you mholt, escaping the quotes with quotes solves the issue indeed.
The fact that it worked whenever there was no `""` present made me believe that double quotes would not need to be escaped.
