### ISSUE TITLE
[Q] Papa streaming to monitor file updates (eg. log)?

### ISSUE THREAD

**Issue by breznak** [mholt/PapaParse#278]
Hi, a newbie question here :) 

I've happily figured how to use `streaming` with PapaParse (can't use Worker), this gets me rid of freezing the browser and I'm able to parse a really big file. 

Now the parsing is actually faster than my updates to the "streaming source" file and I want PaPa to wait "monitoring" when it reaches the end of the file, and when a new line appears in the file, I want it hooked to `step`. A good example would be parsing a system log on a long running system. Would that be possible? 

One naive implementation would be wait given time, and then reread the whole file. 

Thanks for any insight,

**Comment by mholt** [comment]
You're not the first to ask about this; turns out, it's really hard and next to impossible to do correctly, so it's not implemented. See #49 and #215.

If there's a clean, reliable way of doing this, I'm all ears, but for now, the answer is no, sorry.
