### ISSUE TITLE
Trailing blank line breaks delimiter auto-detection for tab-delimited strings

### ISSUE THREAD

**Issue by timwis** [mholt/PapaParse#279]
If you attempt to parse the following tab-delimited contents (yourself or in the [demo](http://papaparse.com/demo)) it works and identifies the columns properly. But if you add a trailing blank line at the end (which many text editors do by default), it can no longer parse it properly. It thinks the delimiter is a comma and that there's only one field, `name office`.
```tsv
name	office
Abraham Lincoln	President
Joe Biden	Vice-President
```
Any idea what the issue is?

**Comment by mholt** [comment]
Probably just because the input is so short, it can't reliably determine the delimiter. In the case of a blank line at the end, only 2/3 of the rows have two fields, and 1/3 have one -- it may not be enough confidence to assume a tab delimiter. In the case of very short inputs you should set the delimiter manually.

**Comment by timwis** [comment]
Interesting. I assumed it would test for common delimiters at least -- in the example above, the `meta` property suggests that the delimiter is a comma `,` even though there's no comma in the string.

In [my use case](https://github.com/prose/prose/pull/911), I won't be able to set the delimiter manually because I don't know what it will be, which is why I wanted to use the auto detection.

I ended up just doing a trim before passing it to PapaParse, but I just wanted to explain how I ran into this in case you feel like this is unexpected behavior.

**Comment by mholt** [comment]
It tests for comma, tab, pipe, and ASCII 30 and 31. True, it's odd that comma is the result when no comma is present in the data but we cannot assume that is true for all inputs and, also, comma is the delimiter specified by RFC 4180.

A PR would be welcome if it can be proven to increase the detection accuracy!
