### ISSUE TITLE
Dynamic typing doesn't recognize numbers with leading + and NaNs

### ISSUE THREAD

**Issue by DmitrySK** [mholt/PapaParse#282]
Hello.

I was trying out the dynamic typing option and it turned out that items in CSV files like "+2.0" and "NaN" are not recognized as numbers. Same goes for "+Infinity" and "-Infinity", though it's not as obvious, whether they should be or not (though, parseFloat("Infinity") == Infinity).
Leading pluses, as rare as they are, are valid parts of numbers, and NaNs are often used to represent a missing numeric value, so, I think, it'd be nice if numbers with leading pluses and "NaN" strings were parsed as numbers, when dynamic typing is on.

Thanks.

**Comment by mholt** [comment]
That seems like a special case - I'd suggest just trimming the first character of the field and doing the conversion yourself (dynamicTyping *is* just a convenience, after all, for the common case).

We have to draw the line somewhere, sorry... like "two" and "three" aren't going to be converted to numbers, either.
