### ISSUE TITLE
Parser chokes on extra EOF linebreak

### ISSUE THREAD

**Issue by jeroenooms** [mholt/PapaParse#285]
I have a somewhat strangely formatted CSV file like [this](http://web.ohmage.org/~snolen/sample_classes/01sample_class.csv). The file uses `\r\n` linebreaks and has an additional linebreak at the end of the file. When parsing with `{header : true, skipEmptyLines : true}`

```
[row 11] Too few fields: expected 20 fields but parsed 1
[row 12] Too few fields: expected 20 fields but parsed 1
``` 

The problem goes away if I remove the EOF linebreaks, but unfortunately the csv input is beyond my control. Shoulnt `skipEmptyLines` be skipping redundant linebreaks?

**Comment by mholt** [comment]
What happens if you set `newline: "\r\n"`in the config?

**Comment by jeroenooms** [comment]
It fails with an error from the trailing empty line

**Comment by mholt** [comment]
More info, please -- what's the error? And the file has several trailing empty lines, which one?

**Comment by jeroenooms** [comment]
If I parse with:

```js
Papa.parse(file,{
	header : true,
	skipEmptyLines : true,
	newline: '\r\n',
```

I get:

     [row 11] Too few fields: expected 20 fields but parsed 1

**Comment by mholt** [comment]
Does the error only appear once? i.e. do you get an error on row 12?

**Comment by jeroenooms** [comment]
Yes only once. You can easily reproduce it with the [csv file](http://web.ohmage.org/~snolen/sample_classes/01sample_class.csv)

**Comment by mholt** [comment]
(Closing for reasons explained in #286)
