### ISSUE TITLE
Trim header column names

### ISSUE THREAD

**Issue by slgal** [mholt/PapaParse#287]
Idea is a trim spaces at the begin/end of columns name.

Example:
Product Name,SKU,Product Code, Price ,Member Price, Cost,Stock Quantity

So price header will be 'Price' insted of ' Price ' and cost will be 'Cost' insted of ' Cost'

**Comment by mholt** [comment]
I'd rather Papa just parse the data as-is and let the user clean it up.

**Comment by larryboymi** [comment]
Sometimes with non-printable characters this becomes pretty unintuitive.

**Comment by pokoli** [comment]
@larryboymi see #589

**Comment by larryboymi** [comment]
Oh thanks! I didn't see that in the documentation, but now I do. Much appreciated.

**Comment by mtmacdonald** [comment]
In case it helps anyone else, 4x version does have `trimHeaders` option (undocumented). And 5x version has `transformHeader`.
