### ISSUE TITLE
Papa fails to recognize correct delimiter

### ISSUE THREAD

**Issue by egeriis** [mholt/PapaParse#290]
In this CSV document, Papa recognizes comma `,` as the delimiter, while the correct one is semicolon `;`.

```
08/01/2016;A;-21.419,06
12/01/2016;A;-21.375,00
13/01/2016;A;-15.000,00
14/01/2016;A;-1.071,31
15/01/2016;A;37.996,97
19/01/2016;A;-53,9
26/01/2016;A;-10.301,58
28/01/2016;A;23.750,00
28/01/2016;A;-1.341,99
29/01/2016;A;-7.612,50
29/01/2016;A;2.031,00
04/01/2016;A;-317,94
26/01/2016;A;-308,33
27/01/2016;A;-4.000,00
27/01/2016;A;-4.000,00
27/01/2016;A;-3.138,32
29/01/2016;A;-4.000,00
15/01/2016;A;-116
20/01/2016;A;-2.405,17
04/01/2016;A;-249
04/01/2016;A;1.509,88
07/01/2016;A;-275
18/01/2016;A;-3.172,95
```

I had a brief look at `guessDelimiter`, and `delta` seems to be the issue, due to some rows having only 1 column with comma `,` as delimiter.

Could it possibly be a factor to take into account, how many columns are detected with the different delimiters, the more the better?

**Comment by mholt** [comment]
> Could it possibly be a factor to take into account, how many columns are detected with the different delimiters, the more the better?

Not necessarily, since the data may just contain a lot of delimiters in it.

Frankly I'd recommend not auto-guessing the delimiter if your data has delimiter characters in it; just specify it manually.
