### ISSUE TITLE
ignore empty columns

### ISSUE THREAD

**Issue by jmls** [mholt/PapaParse#291]
Is there a way to tell the parser not to store empty columns ? I am trying to parse some data where (and I can't control this) there may be some extra spaces ..

so I would normally expect

F1_F2_F3_F4

but sometimes get
F1__F2___F3_F4

(where _ is a space)

so obviously when I parse this, I don't get the expected column (in the second example, col[0] is F1 but col[1] is "_" etc

I know that I can workaround this by splicing the empty cols, but was hoping that there is some magic feature not being invoked ;)

thanks

**Comment by bluej100** [comment]
Are you sure your file isn't actually fixed-width?

You can just use .filter(function(x) {return x != "";}) to remove empty string values.

**Comment by pokoli** [comment]
PapaParse is a CSV parser but not a transformer. So you must filter your data after it have been parsed. 

I'm closing the issue as a solution have been already provided.
