### ISSUE TITLE
Linux: EOF character not recognized

### ISSUE THREAD

**Issue by ericlenio** [mholt/PapaParse#293]
It seems that EOF is not detected/handled running in Linux. At least when I use papaparse in non-browser mode. A simple fix for me was this:

```
if (csvString.search(/\x0a$/)) csvString=csvString.slice(0,-1);
```

I don't believe this issue affects Windows users, but I could be wrong.

**Comment by pokoli** [comment]
Hi @ericlenio, 

Could you please provide a unitest in order to reproduce it. Or at least a sample file and the current output and the expected output. 

Thanks in advance!

**Comment by ericlenio** [comment]
Sample attached. Just realized I am using babyparse 0.4.6, not papaparse, so perhaps I should have filed this issue elsewhere...back in March when I opened the ticket I may have been using papaparse, sorry for any confusion. Anyway the issue still definitely exists in babyparse 0.4.6. Here's a hex dump of the attached file where you can visually see the \x0a at the very end:
```
0000000: 2266 6972 7374 5f6e 616d 6522 2c22 6c61  "first_name","la
0000010: 7374 5f6e 616d 6522 2c22 636f 6d70 616e  st_name","compan
0000020: 795f 6e61 6d65 222c 2261 6464 7265 7373  y_name","address
0000030: 222c 2263 6974 7922 2c22 636f 756e 7479  ","city","county
0000040: 222c 2273 7461 7465 222c 227a 6970 222c  ","state","zip",
0000050: 2270 686f 6e65 3122 2c22 7068 6f6e 6532  "phone1","phone2
0000060: 222c 2265 6d61 696c 222c 2277 6562 220d  ","email","web".
0000070: 0a22 4a61 6d65 7322 2c22 4275 7474 222c  ."James","Butt",
0000080: 2242 656e 746f 6e2c 204a 6f68 6e20 4220  "Benton, John B 
0000090: 4a72 222c 2236 3634 3920 4e20 426c 7565  Jr","6649 N Blue
00000a0: 2047 756d 2053 7422 2c22 4e65 7720 4f72   Gum St","New Or
00000b0: 6c65 616e 7322 2c22 4f72 6c65 616e 7322  leans","Orleans"
00000c0: 2c22 4c41 222c 3730 3131 362c 2235 3034  ,"LA",70116,"504
00000d0: 2d36 3231 2d38 3932 3722 2c22 3530 342d  -621-8927","504-
00000e0: 3834 352d 3134 3237 222c 226a 6275 7474  845-1427","jbutt
00000f0: 4067 6d61 696c 2e63 6f6d 222c 2268 7474  @gmail.com","htt
0000100: 703a 2f2f 7777 772e 6265 6e74 6f6e 6a6f  p://www.bentonjo
0000110: 686e 626a 722e 636f 6d22 0d0a            hnbjr.com"..
```

[us-500.csv.txt](https://github.com/mholt/PapaParse/files/716489/us-500.csv.txt)

**Comment by pokoli** [comment]
I have tested the attached file on the [papaparse demo](http://papaparse.com/demo) and it works correctly.

I also tested using paparse on node (installed with npm). The following code parsed the file correctly:

pp = require('paparse');
fs = require('fs');
fs.readFile('us-500.csv.txt', 'utf8', function(err, data){
   console.log(pp.parse(data))
});

Could you please provide some code in order to reproduce the issue?

**Comment by ericlenio** [comment]
Looks like I found the issue: in my code I was using shelljs's "cat" method to read the file into memory. I tried using fs.readFileSync instead and it worked without my patch. Sigh. I didn't bother to examine what "cat" is doing behind the scenes, using shelljs in my project has been problematic in other areas for me too, I need to stop using it.

**Comment by ericlenio** [comment]
I have to correct myself again, the issue is not fixed for me. However, as I noted a few days ago I am using babyparse so I will re-close this and follow up with the babysource maintainer.
