### ISSUE TITLE
Windows: EOL. Can't recognize windows end of line character ^M

### ISSUE THREAD

**Issue by felippenardi** [mholt/PapaParse#294]
When a user uploads a file where each line ends with the windows character `^M`, it will fail to parse.

Is there a way to setup Papaparse to accept `^M` as end of line?

Here is an sample file with that line ending character: [windows_eol_example.csv.zip](https://github.com/mholt/PapaParse/files/174403/windows_eol_example.csv.zip)

<img width="282" alt="screen shot 2016-03-15 at 2 06 09 pm" src="https://cloud.githubusercontent.com/assets/1354492/13786586/1cb4fcc6-eab7-11e5-915e-a8e9ee1fd58a.png">

The error that I get when importing it is "Too few fields: expected 2 fields but parsed 1".

**Comment by pokoli** [comment]
You can use the newline caracther to especify ^M as end of line. See:

http://papaparse.com/docs#config
