### ISSUE TITLE
New-line parsing problem, wrong number of rows in results

### ISSUE THREAD

**Issue by ghost** [mholt/PapaParse#296]
I am trying to set up copy and paste between our site and Google Docs.  I am using this spreadsheet to test, and this project seems to have a closer handle on the problem than my current solution.  However, using the Demo, when I paste in and use tab as a delimiter, it seems to get confused at semi-colon on line 11:

https://docs.google.com/spreadsheets/d/1GRxuO51iiZmL92rMAx7B8EPM4PFRXgiM5-c6MSaqNRI/edit?usp=sharing

**Comment by bjcullinan** [comment]
Nvm, looks like http://stackoverflow.com/questions/1293147/javascript-code-to-parse-csv-data worked fine!

**Comment by pokoli** [comment]
I'm closing this issue as I understand it have been already solved. Reopen it if you don't agree.
