### ISSUE TITLE
AMD define environment detection is incorrect

### ISSUE THREAD

**Issue by ArturDorochowicz** [mholt/PapaParse#297]
The detection logic of AMD define environment is incorrect. 

I'm referring to the following code [1]:
```
	else if (isFunction(global.define) && global.define.amd)
	{
		// Wireup with RequireJS
		define(function() { return Papa; });
	}
```

Changes for issue #209 changed the `define` call from `global.define`. This is a good change, but the detection logic in the `if` statement should also be changed in the same manner:

```
else if (isFunction(define) && define.amd)
```

You may want to check the UMD pattern for more information [2].

This became an issue for me in System.js/jspm bundling. At installation time it detects papaparse as an AMD module which is good. But after bundling it works in such a way that there is no window.define function, so `if` in the code above evaluates to `false` and the module does not register.

[1] https://github.com/mholt/PapaParse/blob/a61e4a3153de22852a95727484fcab91ca349391/papaparse.js#L44
[2] https://github.com/umdjs/umd/blob/f208d385768ed30cd0025d5415997075345cd1c0/templates/returnExports.js

**Comment by IceOnFire** [comment]
Hi @ArturDorochowicz,

I created a bugfix tag [here](https://github.com/IngloriousCoderz/PapaParse/blob/4.1.3/papaparse.js), you can use it for emergency while my pull request is processed.

Antony

**Comment by mholt** [comment]
Thanks @IceOnFire for the fix.
