### ISSUE TITLE
Escape + enclosure character configurable, allow backslash escape

### ISSUE THREAD

**Issue by si4dev** [mholt/PapaParse#299]
The CSV to be imported uses the backslash character as the quote escape character. 

"1","TV 50\"","1234"

Papa Parser escapes the two quotes ("") instead of backslash quote (\") and will corrupt the further data.

For PHP the backslash is the default escape character and can be configured like the delimiter and enclosure, see php str_getcsv. Is it possible for Papa Parser to configure the enclosure and escape or will it be on the roadmap in the near future?

**Comment by pokoli** [comment]
This have been solved on latest paparse relase as the quoteChar is now configurable. 

I'm closing the issue.
