### ISSUE TITLE
"File" parameter not passed to complete(res,file)

### ISSUE THREAD

**Issue by AstroAndyN** [mholt/PapaParse#300]
Hi
I've noticed that when using Papa.parse(file, config), the behaviour of "complete" is not as specified in the documentation. Specifically,:

```
complete = function(results, file) { 
    console.log(results); //Returns the result as expected
    console.log(file); //Returns 'undefined'...
}
```

This _seems_ to be because the relevant call in ChunkStreamer does not include the reference to the file. I.e. line 455 reads:

			    this._config.complete(this._completeResults);

and should probably read:

			    this._config.complete(this._completeResults, this._input);

Apologies if I'm not on the right track here - I'm new to both PapaParse and JS (and indeed, GitHub - lots to learn!)

**Comment by mholt** [comment]
Thanks for the report. Did that change work for you? Feel free to submit a pull request :+1:

**Comment by AstroAndyN** [comment]
It did seem to work, but I'm not confident that it will not break other aspects (e.g. other Streamed input that is not File based), so I'll not sure a pull request is appropriate. I can try a few more tests, but if anyone with a bit more experience of the structure of the code could try it that might be safest.

**Comment by AstroAndyN** [comment]
It worked for me, although I haven't tested it extensively (e.g. with non-File input). Pull request submitted.

**Comment by mholt** [comment]
Thanks! We'll see if anyone reports any problems with it.
