### ISSUE TITLE
skipEmptyLines not working

### ISSUE THREAD

**Issue by drmanitoba** [mholt/PapaParse#302]
Unless I'm misunderstanding what PP looks for in evaluating an empty line, it seems like it's not working. My config is:

```js 
Papa.parse(file, {
        header: true,
        skipEmptyLines: true,
        complete: function(results) {
          console.log(results);
        }
      });
```

but I'm still seeing empty lines in the result set:

![screen shot 2016-04-07 at 12 25 26 pm](https://cloud.githubusercontent.com/assets/253703/14358635/dd9d5684-fcbb-11e5-8759-d96606fd6652.png)

**Comment by mholt** [comment]
What's your entire input file? (Use a gist or file hosting service, since GitHub comments don't preserve all whitespace properly.)

**Comment by drmanitoba** [comment]
https://gist.github.com/drmanitoba/f65b0b56c381b601d069a65752e97fc6

**Comment by mholt** [comment]
Thanks. You don't have any empty lines in that file. From the docs:

> If true, lines that are completely empty will be skipped. An empty line is defined to be one which evaluates to empty string.

**Comment by drmanitoba** [comment]
Ah I figured I misunderstood. I thought this was per-field. Thank you for clarifying.
