### ISSUE TITLE
Suggestion: adding config flag to ignore protoype

### ISSUE THREAD

**Issue by shank8** [mholt/PapaParse#303]
I am using PapaParse alongside AngularJS and due to the prototypal inheritance that an Angular $resource adds to the JSON, PapaParse is doing a JSON to CSV conversion and adding those prototype properties/methods to the CSV. I added 2 lines of code into the `ObjectKeys` function in order to fix this.  I would be willing to add an implementation of the config object to add this functionality when needed. Let me know if you think this is a valid request and I will fork and add this.

```
function objectKeys(obj)
{
        if (typeof obj !== 'object')
            return [];
        var keys = [];
        for (var key in obj)
            if(obj.hasOwnProperty(key)) {
                keys.push(key);
            }
        return keys;
}
```

**Comment by pokoli** [comment]
@shank8 could you please add some example code on how you are using Paparse with angular. 
Also if you have some code suggestion feel free to open a PR so others can review them.

**Comment by pokoli** [comment]
As disscues on #810 I do not think we should add this configuration option.
