### ISSUE TITLE
Chunk size config fails with workers.

### ISSUE THREAD

**Issue by ardouglass** [mholt/PapaParse#304]
If I set a chunk size using Papa.LocalChunkSize, the code works fine unless it's using workers. Code outside the worker believes the chunk size is set to the new value, but the worker doesn't.

**Comment by mholt** [comment]
Can you please post your input file and your code so we/others can reproduce the issue? Thanks.

**Comment by pokoli** [comment]
I'm closing this issue as no reproducible scenario have been provided. Re-open it if you have one.
