### ISSUE TITLE
Undetectable Delimiter error for local files ending with a empty line, even if skipEmptyLines is true

### ISSUE THREAD

**Issue by supergundel** [mholt/PapaParse#309]
By default excel adds a empty line at the end of exported csv files. If you try to parse these with the local file function and auto detect delimiter you'll end up with an "Undetectable Delimiter" error. Even if you enable skipEmptyLines you'll get the error. 

It can be reproduced with the demo on your website and the attached file.
[Mappe1.zip](https://github.com/mholt/PapaParse/files/236626/Mappe1.zip)

**Comment by slolo2000** [comment]
I can confirm too this behavior with the following example:

EAN13;QTE
1122334455666;1
9988776655444;2

Try it on the demo mode and you will see.

But if you specify the Delimiter to ";" it works well but my goal is to leave Papa Parse plugin detect itself the delimiter.
Is it a confirmed bug?

Thanks in advance and have a nice day.

**Comment by mholt** [comment]
@slolo2000 That worked in the online demo for me, no errors.

Anyway, for really short inputs, your best bet is to specify the delimiter manually.

If somebody would like to improve the delimiter detection algorithm, that's fine, but it has to be shown that it is in fact better than the one we have right now.

**Comment by slolo2000** [comment]
Hello mholt,

Thanks for your answer.

You are right and me too in fact.
I have searched the reason which make it works for you and not for me.

In fact, if you try again with my example and add a blank line to the end, You will see that it will not work (even if "Skip empty lines" option is checked)

Perhaps there is a way to improve it.
Thanks in advance and have a nice day.

**Comment by mholt** [comment]
In that case, it's because the input is too short. It needs to be larger; right now, an empty line accounts for 1/3 of the input which is enough to break confidence in its guess for a delimiter.

**Comment by rhunwicks** [comment]
Python's `csv.writer` also automatically adds a final newline character with no easy way to prevent, which breaks detection on short files.

**Comment by caesarsol** [comment]
@mholt I had the same error and investigated a little, it is a bug.

An easy solution would be to propagate `skipEmptyLines` to the `guessDelimiter` function, and take that option into account.

The problem is due to the fact that `avgFieldCount` is wrong if there are empty lines, so the `preview.data.length` would need to have the empty lines count subtracted in the formula `avgFieldCount /= preview.data.length`.

Would you accept a PR?

**Comment by pokoli** [comment]
Hi @caesarsol, 

Thanks for joining the discussion. 

Yes, we will accept a PR and it will be great to have a test case for it. 

Once you submit, I will be happy to review it, so go for it.

**Comment by caesarsol** [comment]
@pokoli Here it is! Thanks for the fast feedback 👍
