### ISSUE TITLE
RequireJS && worker: true => Uncaught TypeError

### ISSUE THREAD

**Issue by griii2** [mholt/PapaParse#314]
When papaparse.js is loaded via RequireJS (in my case it is also minified and concatenated to one file with other libs but that should not make a difference I suppose) and at the same time worker is set to true, when I try to parse a string PapaParse throws an error:
Uncaught TypeError: Cannot read property 'createElement' of undefined

Version: Papa Parse v4.1.2
My config:
    var config : PapaParse.ParseConfig = {
        delimiter: "",  // auto-detect
        newline: "",    // auto-detect
        header: false,
        dynamicTyping: false,
        preview: 0,
        encoding: "",
        worker: true,
        comments: true,
        step: undefined,
        complete: parseCSVComplete,
        error: parseCSVError,
        download: false,
        skipEmptyLines: true,
        chunk: undefined,
        fastMode: undefined,
        beforeFirstChunk: undefined,
    };

Also, thanks for an awesome library.

**Comment by pokoli** [comment]
As it's already explained on the [faq](http://papaparse.com/faq) adding other libs on worker process may cause the process fail. I copy the full explanation:

> **Can I put other libraries in the same file as Papa Parse?**
> 
> Yes, but then don't use the Web Worker feature unless your other dependencies are battle-hardened for worker threads. A worker thread loads an entire file, not just a function, so all those dependencies would be executed in an environment without a DOM and other window features. If any of those dependencies crash (Cannot read property "defaultView" of undefined is common), the whole worker thread will crash and parsing will not succeed.
> Which browsers is it com

I believe this is the source of your error, so I'm closing the issue. Reopen it if you don't agree.
