### ISSUE TITLE
Is there way to skip lines where all columns are empty?

### ISSUE THREAD

**Issue by gmrash** [mholt/PapaParse#319]
I need to skip lines with separators only.
But I have found only options for skipping empty lines, bot not for lines with all emty columns.

**Comment by pokoli** [comment]
@gmrash what's the use case? 

I think this is easy doable after reading the file, when processing it. Would this solve the issue for you?

**Comment by pokoli** [comment]
I'm closing the issue as a solution have been provided. Re-open if you don't agree.
