### ISSUE TITLE
Parsing in Cordova iOS

### ISSUE THREAD

**Issue by darylldawn** [mholt/PapaParse#320]
I'm currently trying to parse a csv file in a codova app.
It successfully parses for the Android platform, however for iOS it returns nothing.
Has anyone else encountered this and Is there a workaround?

**Comment by gontard** [comment]
Same problem here.

I found [this issue](https://github.com/nolanlawson/pouchdb-load/issues/11) in pouchdb on ios. 
It seems that 

> for some reason, iOS is returning 0 as the status for the xhr request even when there is data loaded from file

So  i change in the papaparse `_chunkLoaded` function, this line 
`if (xhr.status < 200 || xhr.status >= 400)`
by this one:
` if (!((xhr.status >= 200 && xhr.status < 300) || (xhr.status==0 && xhr.responseText.length>0)))`

And now it works.

**Comment by darylldawn** [comment]
@gontard's solution worked! Thanks again!

**Comment by mirko77** [comment]
This is still an issue using Papaparse 5.0 on android 9
