### ISSUE TITLE
Dynamic Typing and decimal points

### ISSUE THREAD

**Issue by jhwheuer** [mholt/PapaParse#327]
Hi Matt, awesome parser, love it!

The issue with decimal point/comma is a bit weird. Why not support a simple flag that would tell the component to treat a number accordingly.

Something like "decimalpoint:true" would suffice totally. From that, the script could change a detected number string before it is parsed and swap if necessary.

I would not go for auto-detection, as I can think of several scenarios where there might just be a point present, but both interpretations (as decimal point or thousand separator) are valid. One could go all out Attila and say that thousand separators can only occur every four characters inside the integer part (either the end of the string or the point token), and decimal points can only occur once. But that could be rather nasty, potentially, for performance? I would go with the simple flag and make it the responsibility of the user to set the formats accordingly.

What do you think?

**Comment by pokoli** [comment]
@jhwheuer could you please provide and example describing the issue and the new behaviour with your proposal?

**Comment by jhwheuer** [comment]
Hi, and thanks for the interest...

Right now, we have to ask whoever is providing numeric data whether the floating point is provided with a decimal point "." or a decimal comma ",". The comma is the usual form in most German speaking countries... 
It would be great if upon instantiation the dev could indicate how floating point numbers are being formatted: either with "." or with ",". Then throughout the run, all numbers would be treated accordingly. It would also mean that numbers need to be in quotes, to not interfere with the "," used as a seperator...

Does that suffice?

**Comment by pokoli** [comment]
@jhwheuer Thanks for the explanation, now it makes sense. 

The goal of PaPaparse is to parse the data but not to transform/process it. We give some helpers when it's easy and we can help, but I think it will be too much to support all the cases. Disabling dynamic typing (so all the values will be returned as string) and manually converting the required fields to numbers using the correct format will solve the problem and will lead to the developer the possibility to implement much complicated issues. 

I think we have nothing to do with this issue. Feel free to re-open it if you don't agree, thanks for you suggestion.
