### ISSUE TITLE
Ignore white space around field separators?

### ISSUE THREAD

**Issue by jcford73** [mholt/PapaParse#330]
Is there a way to ignore white space around field separators?

Such that this:
`"Luke Skywalker", "Jedi"`
gets parsed as:
`["Luke Skywalker", "Jedi"]`
instead of as:
`["Luke Skywalker", " \"Jedi\""]`

**Comment by kfroemming** [comment]
Hey Matt, I also second this. Its an issue I am running into when importing an csv.

**Comment by semikolon** [comment]
I just had this problem, but this fixes it:
```
        const row = results.data[0].map(field =>
          (typeof field === 'string') ? field.trim() : field
        )
```

**Comment by pokoli** [comment]
I'm closing this issue as the objective of Paparse is to read the file "AS IS". If you wan't to manipulate the output you can use a custom code after reading as  @semikolon suggested.

**Comment by SelaO** [comment]
To handle those space you can trim the whole input string out of spaces: `.replace(/ /g, '')`
