### ISSUE TITLE
Seeking new lead maintainer

### ISSUE THREAD

**Issue by mholt** [mholt/PapaParse#331]
As you can probably tell, I've been out of the loop with this project lately. Life is busy, and it's taking me to other fields of research and development.

Papa Parse has been an incredible journey and I've learned a lot while I was developing it. It has served tens of thousands of developers and even more end users. Wikipedia, the United Nations, various national and state governments around the world, academic institutions, research teams, and other non-profits all use (or have used) Papa Parse to some extent for data processing, not to mention countless commercial entities. They use Papa Parse because it's the fastest correct CSV parser for the browser and the easiest to use, with the most advanced performance features for big files. I'm really happy with that.

I'm about to begin graduate school and will spend about two years on my masters degree. That, along with [Caddy](https://github.com/mholt/caddy), will keep me occupied during my work day in the foreseeable future.

While I'm not relinquishing ownership of the project, who would like to take over in leading its development? Respond to issues and pull requests, deploy new releases, implement bug fixes -- keep it maintained.

Preferably somebody who has some experience with managing open source projects... this one is a little big for a brand new entrant, I feel... bonus points if you have a passion about high-performance CSV parsing. :smile:

The new lead maintainer will of course be granted Collaborator status here and permission to publish to npm.

If there is more than one person interested in adopting this project, I'm sure the new lead maintainer would love to have some help. We can have multiple maintainers, but there does need to be leadership. So, no need to take it personally if you are not chosen! You can still be a collaborator and contribute in significant ways.

Comment here if you are interested in becoming the lead maintainer of Papa Parse. It would help if you explain why and what plans you have for it or what you'd like to accomplish, what your priorities are, etc. Doesn't have to be fancy; just has to earn my trust*. :wink:

*_Trust comes in two flavors: competency and character. One is hard to evaluate from the Internet._

**Comment by pickhardt** [comment]
Want me to add your project at https://github.com/pickhardt/maintainers-wanted?

**Comment by mholt** [comment]
@pickhardt Oh, cool -- sure! PR submitted.

**Comment by mholt** [comment]
I've handed the reins to @pokoli for now, who will be triaging some of the issues and going through PRs. I'll leave this issue open since I'm sure he could use some help. :)

**Comment by pokoli** [comment]
@mholt I'm closing this as ad137bd3bc336ddba181a95462ceb2ba275de362 have been pushed. Thanks
