### ISSUE TITLE
Fetch the header without parsing the file

### ISSUE THREAD

**Issue by vipulvkp** [mholt/PapaParse#336]
Hello,

I have a csv like below where the first line is the header
H1,H2,H3,H4
1,2,3,4
5,6,7,8

I just want PapaParser to fetch the header without parsing the full file. In my case, the file is huge and I dont want it to get parsed. Just read the first line(i.e. header) and return.

Please help.

**Comment by pokoli** [comment]
@vipulvkp you can use header = false and preview = 1, so only the first row will be read. You can test it on the demo website: http://papaparse.com/demo
