### ISSUE TITLE
Error when no 'Content-Range' header in response

### ISSUE THREAD

**Issue by kravets-levko** [mholt/PapaParse#339]
Hello. I'm using PapaParse to load part of CSV file (first 1000 lines) via URL specified by user. 
And sometimes I get error `Uncaught TypeError: Cannot read property 'substr' of null` in [getFileSize](https://github.com/mholt/PapaParse/blob/master/papaparse.js#L597) function. 

Some servers does not return `Content-Range` header even if `Range` is specified. In this case, response will contain entire file, not a part.

Here is my config:

``` js
{
  download: true,
  preview: 1000,
  skipEmptyLines: true,
  encoding: encoding,
  chunk: function(results) { ... },
  complete: function(results) { ... }
}
```

**Comment by kravets-levko** [comment]
I found PR https://github.com/mholt/PapaParse/pull/335 that solves my problem in a different way, but also looks good for my case.

**Comment by pokoli** [comment]
I'm closing this issue as I understand it have been solved already. Please, re-open if you don't agree.
