### ISSUE TITLE
Worker does not work (Riotjs & Webpack)

### ISSUE THREAD

**Issue by pgoergler** [mholt/PapaParse#343]
Hello,

i'm trying to use PapaParse.
I did:
`npm install -S papaparse`

in my script i do:

``` javascript
import Papa from 'papaparse'
[...]
inputFile.onchange = function() {
                 Papa.parse(inputFile.files[0], {
                    worker: true,
                    step: function(row) {
                        console.log("Row:", row);
                    }
                });
}
```

But i in my browser console i can see:
`Uncaught ReferenceError: document is not defined`

If i disable, `worker: false`, the error disapear.

PS: I use Chrome : Version 52.0.2743.116 (64-bit)

**Comment by elfenheart** [comment]
@pgoergler did you load PapaParse in the same file as RiotJS? If so, that would be the reason why you are getting that error.

Here's an excerpt from the FAQ:

```
Can I put other libraries in the same file as Papa Parse?
Yes, but then don't use the Web Worker feature unless your other dependencies are battle-hardened for worker threads. A worker thread loads an entire file, not just a function, so all those dependencies would be executed in an environment without a DOM and other window features. If any of those dependencies crash (Cannot read property "defaultView" of undefined is common), the whole worker thread will crash and parsing will not succeed.

```

**Comment by pokoli** [comment]
I'm closing this issue as I understand that the reply from @elfenheart explained the error and provided a fix for it. Re-open it if you don't agree.
