### ISSUE TITLE
newline in quoted field

### ISSUE THREAD

**Issue by tamasmahr** [mholt/PapaParse#344]
Hi,

I have a csv file, which contains (quoted) fields with newline characters. Moreover the file itself has \n line termination, but the newline characters inside the quoted fields are \r\n. Here is how you can create such a file:

`echo -ne '"column 1","column 2"\n"multi line\r\ntext","so sad"\n"single line text","so happy"' > test.csv`

Papaparse fail to parse this file properly. Do you have an idea why?

Thanks!
Tamas

**Comment by mholt** [comment]
Papa handles newlines in quoted fields correctly; are you sure your input is what you think it is?

**Comment by tamasmahr** [comment]
I created a file using the above command, went to the papa parser demo page, uploaded the file and had papa parse it. The result is a single array with the following content:
0:"column 1"
1:"column 2"↵"multi line↵text"
2:"so sad"↵"single line text"
3:"so happy"

I think that the result should be three arrays, each with two strings.
"column 1","column 2"
"multi line↵text","so sad"
"single line text","so happy"

**Comment by mholt** [comment]
It works as expected, although your mixed line endings are confusing the newline detector. If you set the newline configuration parameter to `\n` it works as you want it to.

Thanks for the question!

**Comment by tamasmahr** [comment]
I would like to keep the newline parameter on auto, I don't know what files my users will upload. Is it possible to fix the detector somehow?

I might be wrong here, but why is it necessary to detect the newline character upfront? Can't you just go through the string and accept any combination of \r and \n as a newline?

Thanks!

Tamas

**Comment by mholt** [comment]
No, because `\r` could be part of the data of an unquoted field (in theory).
