### ISSUE TITLE
Not breaking lines in files with both \r and \n

### ISSUE THREAD

**Issue by burchill** [mholt/PapaParse#345]
I don't know if there's an easy way to solve this problem, but when parsing files that vary in their use of what newline character they use (i.e. switching between "\r" and "\n") PapaParse doesn't recognize all these line breaks.  When working with both Windows and Unix based systems, this mish-mash of newline characters can sometimes happen (as it did with me).

I uploaded a small file that demonstrates this for replicability:

https://github.com/burchill/burchill.github.io/blob/master/faulty.csv

**Comment by pokoli** [comment]
@burchill the csv is no longer available, so I can not test it. Could you provide a [demo](http://papaparse.com/demo) input in order to reproduce it or a test scenario?

**Comment by evanplaice** [comment]
The 'easy' solution is to ignore /r linebreaks altogether. But, for some inane reason the CSV output from MS Excel for Mac still uses /r by default; despite the fact that OSX is and has always been *nix based.

I'd recommend preprocessing the CSV and match/replace line endings to be consistent (ie either /n or /r/n).

**Comment by pokoli** [comment]
@evanplaice and how to determine which is the good line delimiter to make the file consistent?

**Comment by wshostak** [comment]
I haven't submitted yet because it does break the test and I have not had time to fix the test.
Right before the comment;
```
// We don't need to compute some of these every time parse() is called,
```
Paste in;
```
// Replace possible EOL to all match
input = input.replace(/[\r\n]+/g, newline);
```
This allows for mixed line breaks.

**Comment by pokoli** [comment]
@wshostak could you create a pull request so we can see what tests are failing?

**Comment by pckhoi** [comment]
Other CSV parsers such as CSV decoder from Go's standard library can handle such files with grace. I don't think this is something that should be ignored by PapaParse.

**Comment by pckhoi** [comment]
@pokoli check out this PR https://github.com/mholt/PapaParse/pull/845 no tests failing.

**Comment by pokoli** [comment]
As commented on the PR I think the input should be modified before parsing to paparse. 
If you now the right delimiter you should replace it before passing it to papaparse.
