### ISSUE TITLE
Ignore last empty line

### ISSUE THREAD

**Issue by slolo2000** [mholt/PapaParse#347]
It could be nice to have an option to skip the last empty lines in a csv file.
The aim is to simply ignore them and not add them to the array of errors.

Like that, blank lines "in the middle" of the document can be considered like "in error" and last blank lines can be skip and do not interfer with real lines.

**Comment by pengsea** [comment]
use this config-- skipEmptyLines: true

**Comment by slolo2000** [comment]
Hello pengsea,

You are right but in this case I speak about ignoring only blank lines at the end of the file.
It often happen that blank lines are present at the end of the file.
So I would like to catch error for blank lines in the middle of the file but not on the end.

**Comment by pengsea** [comment]
like this?
```
if (_config.skipEmptyLines) {
    for (var i = 0; i < _results.data.length; i++)
        if (_results.data[i].length == 1 && _results.data[i][0] == "") {
            if (i < _results.data.length - 1) {
                addError("EmptyLine", "EmptyLineError", "empty line happen in the middle file", i);
            } else
                _results.data.splice(i--, 1);
        }
}
```

**Comment by slolo2000** [comment]
Yes, it is exactly what I would like :+1:

**Comment by pokoli** [comment]
I'm closing the issue as I see it has been solved. Reopen it if you don't agree.
