### ISSUE TITLE
Stream issue in your page

### ISSUE THREAD

**Issue by rahulTheDev** [mholt/PapaParse#355]
In your demo page http://papaparse.com/demo. I downloaded a normal file and tried the option "Stream" located at the left side of the page. and uploaded the normal file in "Local files" tab. But the result set in console was showing 0 arrays. The row count was accurate. When i unselected the "Stream" option, it displayed the result set. Any help? I really need the stream option to work.
![screenshot from 2016-11-10 20 07 53](https://cloud.githubusercontent.com/assets/23382608/20180693/88473b3e-a781-11e6-848b-6c6a04586f22.png)
![screenshot from 2016-11-10 20 08 43](https://cloud.githubusercontent.com/assets/23382608/20180694/885e29b6-a781-11e6-9489-25658d3ce18c.png)

**Comment by mholt** [comment]
Streaming works -- the results are not saved after parsing because, well, that defeats the point of streaming. ;)

**Comment by rahulTheDev** [comment]
Thanks... ;) you guys rock... ;)
