### ISSUE TITLE
active module?

### ISSUE THREAD

**Issue by ckiss** [mholt/PapaParse#356]
@mholt is this module still maintained? the latest merged PR's contain fixes that are useful.

If so, can you please publish a new version on NPM? Cheers!

**Comment by mholt** [comment]
Nope -- I'm currently [unable to maintain this repository](https://github.com/mholt/PapaParse/issues/331). Sorry.

**Comment by ckiss** [comment]
sorry to hear that @mholt. good luck with your studies, and hopefully somebody will take over this project cause it's really cool!
