### ISSUE TITLE
Don't use eval to determine global scope

### ISSUE THREAD

**Issue by sandstrom** [mholt/PapaParse#363]
This commit https://github.com/mholt/PapaParse/commit/fbf22867bfc6280192c5267cab84eadf50307170 use eval to determine the global scope. This will break many things (Content Security Policy is one).

Instead you can use something like this:
https://github.com/paulmillr/es6-shim/commit/2367e0953edd01ae9a5628e1f47cf14b0377a7d6

Would you be willing to make this change?

**Comment by pokoli** [comment]
Hi @sandstrom, 

Thanks for reporting the issue. Yes, we willing to remove the eval part. Could you please submit a pull request?

**Comment by sandstrom** [comment]
@pokoli Great!

PR here: https://github.com/mholt/PapaParse/pull/365

**Comment by pokoli** [comment]
I'm wondering if it's worth to make a minor release for fixing this. Opinions?

**Comment by pokoli** [comment]
Still wondering about if we need a new release for it.

**Comment by bkniffler** [comment]
Yes, please, I've been bitten by this lately due to my CSP.

**Comment by pokoli** [comment]
I have released version 4.1.4 containing only this CHANGE. Thanks for your feedback.
