### ISSUE TITLE
How do you handle multiple header import?

### ISSUE THREAD

**Issue by Muphet** [mholt/PapaParse#366]
How do i parse multiple header names into one object? I mean, let's say document A has ID header and document B has IDENT alias. how do i parse both version and output id: value?

**Comment by pokoli** [comment]
Hi @Muphet, 

It's not clear wat do you want to achieve but you can skip the header row with `{'header': false}` as config. Have a look at the[ example on the docs page](http://papaparse.com/docs#results):

Let me know if that solved the issue for you.

**Comment by Muphet** [comment]
i have figured that out and as always forgot to update ticket :<
what i was doing is i was iterating through all headers imported and checking for names like:
if(item.name) name = item.name
if(item.othername) name = item.othername
so in the end, json header was always "name" no matter what "alias" user used in his spreadsheet file

**Comment by pokoli** [comment]
@Muphet Thanks for updating the issue. I'm closing it.
