### ISSUE TITLE
encoding windows 1250 not available

### ISSUE THREAD

**Issue by Kamill90** [mholt/PapaParse#367]
Hi. I need to load and parse csv file into json format object. And this is file. Problem is that my source file contain polish text and after I parse it with babyparse (work in node) text is not encoded right. 
Below there is my code for it and sample attached. 
var baby = require("babyparse");
parsed = baby.parseFiles("data/test1.csv",{
    delimiter: ";",
    header: false,
    encoding: "utf8"
    })
var data = parsed.data;

Thanks in advance. 
[test.txt](https://github.com/mholt/PapaParse/files/752550/test.txt)

**Comment by pokoli** [comment]
@Kamill90 I see in your code block that you use 'utf8' as enconding. Does specifing the valid encoding solve the issue?

**Comment by pokoli** [comment]
I'm closing the issue as I understand it have been fixed with my previous comment. Reopen if you don't agree
