### ISSUE TITLE
PapaParse

### ISSUE THREAD

**Issue by ArditKurti** [mholt/PapaParse#368]
Hi i get this error
 Uncaught TypeError: Cannot read property 'data' of undefined
    at getData (upload.js:41)
    at completeFn (upload.js:62)
    at Object.e.instanceConfig.complete (papaparse.min.js:6)
    at s.parseChunk (papaparse.min.js:6)
    at s._chunkLoaded (papaparse.min.js:6)
    at FileReader.<anonymous> (papaparse.min.js:6)

this is my code

$(document).ready(function() {

    $("#csv-file").click(function () {
        $("#csv-file").change(handleFileSelect);
    })

});

function handleFileSelect() {
    var files = $('#csv-file')[0].files;
    var config = buildConfig();

    $('#csv-file').parse({
        config: config,
        before: function (files , inputElem) {
            console.log("Parsing file:", files);
        },
        complete: function()
        {
            console.log("Done with all files.");
        }
    });
}

function buildConfig() {
    return {
        header: true,
        dynamicTyping: false,
        complete: completeFn
    }
}

function completeFn()
{

    var container = document.getElementById('csv-table');

    var getData = function () {
        var csvData = arguments[0].data;

        return function () {
            var page = parseInt(window.location.hash.replace('#', ''), 10) || 1,
                limit = 10,
                row = (page - 1) * limit,
                count = page * limit,
                part = [];

            for (; row < count; row++) {
                part.push(csvData[row]);
            }

            return part;
        }
    };

    var hot = new Handsontable(container, {
        data: getData(),
        colHeaders: arguments[0].meta.fields,
        fixedRowsTop: 0,
        columnSorting: true,
        sortIndicator: true,
        contextMenu: true
    });

    console.log(arguments);

    Handsontable.Dom.addEvent( window, 'hashchange', function (event) {
        hot.loadData(getData());
    });

}

the idea is that i get the files from papaparse and create an handsontable with that.
But when i try to make a pagination thats the error that happens

**Comment by pokoli** [comment]
Hi, 

First of all thanks for reporting the issue, but I'm sorry to say that it seems unrelated to the paparse code. From the error traceback the problem is that arguments[0] is undefined on the getData function. So it can not access the data property of an undefined object. I think you should manage the case when you receive no parameters on the function (or ensure that they are always passed correctly). 

Something similar to this should do the trick:

```
var getData = function () {
    if (arguments[0]===undefined) {
       return; 
    }
    var csvData = arguments[0].data;
    //your current code here
}
```

Hope it helps.

**Comment by ArditKurti** [comment]
HI the thing is that when i use a function comes up this error.
When i use it to data: arguments[0].data the table is shown
@pokoli

**Comment by pokoli** [comment]
@ArditKurti this is not related to paparse, but how Hansdomtable expects the data. Indeed you are calling with empty argument here:

```
var hot = new Handsontable(container, {
    data: getData(),
    colHeaders: arguments[0].meta.fields,
    fixedRowsTop: 0,
    columnSorting: true,
    sortIndicator: true,
    contextMenu: true
});
```

So it's normal that arguments is undefined. Have you tryied changing it to something like: 

```
var hot = new Handsontable(container, {
    data: getData, // Note that () is removed from here.
    colHeaders: arguments[0].meta.fields,
    fixedRowsTop: 0,
    columnSorting: true,
    sortIndicator: true,
    contextMenu: true
});
```
Sorry but I can not provide a better guidance as this is related to Handsontable. You should contact the handontable library support if you need further assistance.

**Comment by ArditKurti** [comment]
Thanks anyway man i really appreciate your help.
And this is an amazing plugin.
Keep up the good work
