### ISSUE TITLE
Store datatype information in meta object

### ISSUE THREAD

**Issue by agk23** [mholt/PapaParse#371]
It'd be great if there was an option for PapaParse to track what kind of datatypes it found in a column.  Basically I'd propose the meta object look something like this:
```
meta = {
    ...
    fields: ["name", "notes", "age", "isStudent"]
    fieldTypes: {
        1: {
            types: ["string"],
            maxLength: 20
        },
        2: {
            dataTypes: ["string","numeric"],
            maxLength: 45,
            maxPrecision: 5,
            maxScale: 8
        },
        3: {
            dataTypes: ["numeric"],
            maxPrecision: 2,
            maxScale: 0
        },
        4: {
            dataTypes: ["boolean"]
        }
    ],
    ...
}
```

This way I'd know that all the Names were strings, the notes were a mix of strings and pure numbers, age was all numbers and isStudent was all booleans.

I have two use cases:

1. Take arbitrary CSV data and dynamically creating a filter menu from it.  Using the above JSON, I'd know that for the "Name" column to only show string filters like ==, !=, contains, like, etc, and that age is always a number so use numeric filters like <, >, =. <=, >=.

2. Upload the CSV data into a dynamically created SQL table, so if its possible to track the max scale/precision on numerics, and max length of strings that'd be awesome.

**Comment by pokoli** [comment]
Hi @agk23, 

Thanks for your suggestion. I'm wondering how it will be possible to determine the data types in the column? I don't see how all this information will be detected by papaparse.

**Comment by agk23** [comment]
I was envisioning that when that "Dynamic Typing" datatype detection happens, it would track this additional meta data.  Something like this (note: contrary to my first post, meta.fieldTypes.x.types is probably better off being an object than an array):

**From:**
```
function parseDynamic(field, value)
{
	if ((_config.dynamicTyping[field] || _config.dynamicTyping) === true)
	{
		if (value === 'true' || value === 'TRUE')
			return true;
		else if (value === 'false' || value === 'FALSE')
			return false;
		else
			return tryParseFloat(value);
	}
	return value;
}

function tryParseFloat(val)
{
	var isNumber = FLOAT.test(val);
	return isNumber ? parseFloat(val) : val;
}
```

**To:**
```
function parseDynamic(field, value, j)
{
	if ((_config.dynamicTyping[field] || _config.dynamicTyping) === true)
	{
		if (value === 'true' || value === 'TRUE'){
			_results.meta.fieldTypes[j].types.boolean = true
			return true;
		}else if (value === 'false' || value === 'FALSE'){
			_results.meta.fieldTypes[j].types.boolean = true
			return false;
		}else{
			if(FLOAT.test(val)){
				_results.meta.fieldTypes[j].types.numeric = true;
				var number = myVal.split(".")
				_results.meta.fieldTypes.x.maxPrecision = meta.fieldTypes.x.maxPrecision< number[0].length ? number[0].length : meta.fieldTypes.x.maxPrecision
				_results.meta.fieldTypes.x.maxScale = meta.fieldTypes.x.maxScale< number[1].length ? number[1].length : meta.fieldTypes.x.maxScale
				return parseFloat(val);
			} else {
				_results.meta.fieldTypes[j].types.string = true
				return val;
			}
		}
	}
	return value;
}
```

I haven't spent more than a few minutes in the source though and I haven't tested this, so I may be way off.

**Comment by pokoli** [comment]
Hmmm... interesting. I have some doubts about what will be the result when the column contains mixed types. Which will be the result? 

I'm wondering if it won't be better to determine the types of the columns at the end of the parsing. This will allow to know the different types of the columns (in case they exist) and this can be done in your custom script without adding complexity on the PapaParse code.

**Comment by agk23** [comment]
I currently do test it outside of PapaParse, but I figure that if I'm already going through every value and it's already resolving the data types, I may as well just record what it found.

My idea is that meta.fieldTypes.x.fieldTypes starts off as an empty object.  And lets say we process a single column CSV and in the first row and find the value "One."  The fieldTypes Object would look like this:

```
fieldTypes: {
        1: {
            types: {
                  string: true
            }.
            maxLength: 3 //"one".length
        }
```

Then we go to the second row and find "10.555"
```
fieldTypes: {
        1: {
            types: {
                  string: true,
                  number: true
            }.
            maxLength: 3, //Not a string so don't change
            maxPrecision: 2, //"10.5".split(".")[0]
            maxScale: 3 //"10.555".split(".")[1]
        }
```

Then lets say we find "100.2"
```
fieldTypes: {
        1: {
            types: {
                  string: true,
                  number: true
            }.
            maxLength: 3, //Not a string so don't change
            maxPrecision: 3, //"100.2".split(".")[0] is > the previous max
            maxScale: 3 //"100.2".split(".")[1] is < the previous max, so don't change it
        }
```

I think the metadata will help anyone that's processing unknown datasets.  If the user can upload anything, I think in most cases the application will need to know what kind of data is in there in order to handle it properly.

Fantastic product either way though - good job and thanks.

**Comment by pokoli** [comment]
I just want to record that the PapaParse objective is to read CSV files and read them fast. Although the meta data information may be useful for some people, I don't think it fits the problem PapaParse want to solve. Keeping that in mind, and taking in account that the metadata can be generated after a first parse of the file I think we must not introduce this code to PapaParse. 

Although this is an interesting feature, I think it's better to have it outside of the project as it allows everyone to build it's own metadata format. If we introduce on the module, I'm afraid of getting a lot of new code to be able to customize how the metadata information is build transforming a simple feature (which is how it's now with your proposal) to a more complex one that it's out of the scope of the project. 

Having said that, I'm closing the issue and I encourage you to generate the metadata outside of PapaParse. Thanks for the proposal!
