### ISSUE TITLE
Unicode BOM messes up first property name

### ISSUE THREAD

**Issue by LeaVerou** [mholt/PapaParse#372]
First off, thanks for the great library! Its API is a work of art. 👍 

I ran into an issue when parsing CSV files fetched from the Github API with `headers: true`. The first column didn't have the property name I expected due to an invisible character which turned out to be the UTF-8 BOM (`U+FEFF`). I fixed it in my code via:

```js
response = response.replace(/^\ufeff/, "");
```

However, I thought you guys might want to fix it in the library at some point (and include other BOMs too, like the UTF-16 BOM etc). It's debatable whether this should be fixed in the library, and I could argue it both ways, but thought I should bring it to your attention and let you decide. :)

**Comment by pokoli** [comment]
Hi @LeaVerou,

Thanks for opening the issue. 

Which is the current behaviour? Is Papa crashing? Could you provide some example csv (or some test scenario better) in order to reproduce the issue.

**Comment by LeaVerou** [comment]
No crashes, no errors, just the BOM becomes part of the first property name.

**Comment by pokoli** [comment]
I think we can not do anything more. If the input contains this data we should show this data and the only solution is to fix the data before (or after) parsing.

**Comment by cweezy** [comment]
@LeaVerou I was running into this problem too, and I fixed the problem a different way. I am using javascript's [`FileReader`](https://developer.mozilla.org/en-US/docs/Web/API/FileReader) API and was using `readAsBinaryString` on a CSV file. Switching to `readAsText` for CSV files got rid of these BOMs.

Not sure if this would fix your issue, but figured it was worth sharing.

**Comment by havenl** [comment]
@cweezy `readAsText` apparently does not remove the BOM in Internet Explorer (I was testing in IE10, not sure about other versions), so you'll still want to manually remove it _just in case_ your user uses IE.

@pokoli I would argue the library should remove the BOM as other CSV parsers do not make prepend BOM, an invisible character, to the first property key.

**Comment by pokoli** [comment]
@havenl I'm open for discussion about remove the BOM but if the problem is that Internet Explorer 10 is not properly handling the text stream I don't think we should do anything. Internet Explorer 10 is not supported by Microsoft since December 13, 2016, so you users should upgrade it's browser.

**Comment by kaligrafy** [comment]
It happens if we use Papa with nodejs also if the csv files contain BOM.
It is not that trivial to remove BOM when using a readstream. Would it be possible to remove the DOM when parsing the header automatically?

**Comment by PaulMest** [comment]
For anybody else who is running into this issue, you can create a pretty simple function to strip the BOM.
NPM Package: `strip-bom`

Or if you just want to create the function yourself, it is very straight-forward: https://github.com/sindresorhus/strip-bom/blob/master/index.js

**Comment by kpatrick** [comment]
For me it causes problems on streaming where the first header cell is quoted then the BOM presence causes the first field to contain quotes.

**Comment by gap777** [comment]
Shockingly, this is still something to be reckoned with in node env.

**Comment by wdporter** [comment]
I think it's up to whoever is processing a file to handle the BOM correctly. In this case it's papa-parse who should take responsibility. The current behaviour is utterly unexpected, when a file has a BOM (which is hardly an exceptional use-case), it becomes part of the first property name. A trivial fix indeed, if (my.charCodeAt(0) === 0xFEFF) mystring = mystring.slice(1)
At the very least, put it in your documentation "Sorry we can't properly parse a file with a BOM, the BOM will become part of the first property name -- you will need to make sure your file has no BOM"

**Comment by maon-fp** [comment]
Using Node.js v14.2.0 `.trim()` is doing the trick as well (not sure about browsers).

```
const headers = ["﻿<0xfeff>time_stamp_from", "time_stamp_until"];

console.log(headers.map((header) => /^[\x00-\x7F]*$/.test(header)));
console.log(headers.map((header) => /^[\x00-\x7F]*$/.test(header.trim())));
```

> [ false, true ]
> [ true, true ]

**Comment by my-lalex** [comment]
I got the same issue, it's true that papaparse should handle this use-case as Excel export adds the BOM...

Waiting for this, I'm using the `transformHeader`config from 5.0+ and `trim`in nodejs:
```typescript
// only for first header
// could also be in all headers as usually property names
// don't have leading or trailing spaces
transformHeader: (h, i) => (i ? h : h.trim())
```
