### ISSUE TITLE
Suggestion: option to format json as dict with specified row as key when header:true

### ISSUE THREAD

**Issue by bmperrea** [mholt/PapaParse#373]
I am often importing csv's with headers. The output is an array of well-labeled, flat javascript objects:

```
 [ 
    {colname1: val11, colname2: val21, ...},
    {colname1: val12, colname2: val22, ...},
    ...
]
```

I am usually converting this array of flat row objects to a keyed object, of row objects, resembling a dictionary from other languages (python):

```
{
    keyval1: {colname1: val11, colname2: val21, ...},
    keyval2: {colname1: val12, colname2: val22, ...},
}
```
where `keyval` is the value of a column that I have chosen as the key. It would be nice if I could specify this type of output directly in the options for PapaParse, such as with `key: 'id'` which would us the 'id' column as keys. This could default to `key: null` which would indicate that the current array format should be returned. 

If someone knows of a better way to do this without looping (or using map, I guess I mean a built-in way) that would be interesting. Ideally I wouldn't loop through the data an extra time. 

Here is what I currently do:
```
var array = Baby.parse(body, {header: true, skipEmptyLines: true}).data;

dict = {};
for (var j=0; j<array.length; j++) {
    dict[array[j][options.key]] = array[j];
}
```

**Comment by pokoli** [comment]
Hi @bmperrea, 

Thanks for the suggestion. I  doubt about which has to be the behaviour when the key has repeated values, as this will cause to some data to be lost. Do you think we should raise and error, or it's up to the developer to return a a proper key? 

I'm wondering if it won't be better to don't implement this as core PapaParse, and let the developers who wants this behaviour to re-parse the data using it's key and deciding if they want to raise an error or now with duplicate keys. 

What do you think?

**Comment by bmperrea** [comment]
Thanks @pokoli .

Good point about repeated keys. I think devs will sometimes want to continue despite duplicate keys, but including an error would be great. 

No problem if this doesn't seem worth it. I think this kind of thinking would be more common on the server/database side where unique keys are the best way to distinguish data points (arrays aren't even allowed in firebase, for instance) so as to avoid competition between multiple asynchronous write commands.

I suggest we see whether other people notice this post and get interested.

**Comment by pokoli** [comment]
Ok, so for now I'm closing the issue in order to notice that we do not plan to implement anything for suporting it, and if other people gets interested we may reopen it when the work to do is clear. 

Anyway, thanks for your suggestion.
