### ISSUE TITLE
Allow Papaparse to be used by everyone

### ISSUE THREAD

**Issue by RedShift1** [mholt/PapaParse#376]
Right now PapaParse is only for big boys and girls according to the main website. This is discriminatory to people who do not identify as boy or girl, or are not big either. Furthermore, it is also contradictory to the license under which PapaParse ships, which states "Permission is hereby granted, free of charge, _to any person_ obtaining a copy of this software...".

I recommend the statement to be changed to "The powerful, in-browser CSV parser for any size Boy, Girl, Agender, Androgyne, Androgynous, Bigender, Cis, Cisgender, Cis Female, Cis Male, Cis Man, Cis Woman, Cisgender Female, Cisgender Male, Cisgender Man, Cisgender Woman, Female to Male, FTM, Gender Fluid, Gender Nonconforming, Gender Questioning, Gender Variant, Genderqueer, Intersex, Male to Female, MTF, Neither, Neutrois, Non-binary, Other, Pangender, Trans, Trans*, Trans Female, Trans* Female, Trans Male, Trans* Male, Trans Man, Trans* Man, Trans Person, Trans* Person, Trans Woman, Trans* Woman, Transfeminine, Transgender, Transgender Female, Transgender Male, Transgender Man, Transgender Person, Transgender Woman, Transmasculine, Transsexual, Transsexual Female, Transsexual Male, Transsexual Man, Transsexual Person, Transsexual Woman or Two-Spirit".

List of genders retrieved from [this news article](http://abcnews.go.com/blogs/headlines/2014/02/heres-a-list-of-58-gender-options-for-facebook-users/), but there may be more genders that I'm not aware of.

**Comment by mholt** [comment]
Thanks for this. Consider the license text to be the official take on this. ;)
