### ISSUE TITLE
docs need to specify worker only applies to `parse` not `unparse`

### ISSUE THREAD

**Issue by efx** [mholt/PapaParse#378]
The http://papaparse.com/faq#workers gives the impression that `worker` option applies to all `Papa` interfaces. However, it only applies to the `parse` method: https://github.com/mholt/PapaParse/blob/master/papaparse.js#L198
I think the FAQ and documentation should reflect this.

**Comment by pokoli** [comment]
Hi @efx, 

Thanks for reporting. 

The documentation is on the gh-pages branch. Feel free to propose a PR in order to improve the docs using this branchs.

**Comment by efx** [comment]
thanks @pokoli for grabbing that!
