### ISSUE TITLE
Set header labels in `config.header`

### ISSUE THREAD

**Issue by jwernicke** [mholt/PapaParse#379]
If I have a CSV file without a header, I'd like to define a header in `config.header`. Something like this:

``` javascript
Papa.parse(fs.createReadStream(myCsvFile, {header: ['foo','bar','baz']}), {
  complete: function(results){
    // results is [{foo: '', bar: '', baz: ''},...]
  }
})
```

**Comment by pokoli** [comment]
@jwernicke could you explain your use case? If you now the header in advance, it's exactly the same to use the column number or the names. Indeed, you can use you own converter for names and column numbers. Something like:

`
function getColumnName(i) { return ['foo', 'bar', 'baz'][i] }
`

Hope it helps.

**Comment by jwernicke** [comment]
@pokoli Because there's no header in the file, I use the `parse` function to read the file into an array of arrays, then use separate logic to convert it to an array of objects. I'd like this logic to be integrated into the `parse` function. If there were a header in the file, the `header: true` option would provide the desired object, but because there's no header in the file, I would need to supply a header somewhere, and I think the `header` parameter would be an appropriate place to do that.

**Comment by pokoli** [comment]
@jwernicke but which are the benefits of providing the header array on the parse function? It's not enough to do it once the file is parsed?

**Comment by wernicke81** [comment]
@pokoli I think the main benefit is to abstract out the array-to-object conversion from the end user by leveraging the existing `header: true` logic.

**Comment by pokoli** [comment]
@wernicke81 Paparse is a parsing library, but not a converter one. So convering the parsed data it's out of the scope of the library and that's why I'm closing this issue.

**Comment by sgehrman** [comment]
I came looking for this feature too... seems like a perfectly good idea to me.

**Comment by ataft** [comment]
This feature would ensure the result data is consistently an array of objects. You should be able to supply a header array if it's not defined in the spreadsheet.
