### ISSUE TITLE
Question: How to view row data from errors[].row

### ISSUE THREAD

**Issue by rosscoco** [mholt/PapaParse#381]
If a row cannot be parsed an entry is added to the errors array like so:

```
{
  "type": "FieldMismatch",
  "code": "TooFewFields",
  "message": "Too few fields: expected 3 fields but parsed 2",
  "row": 2
}
```

I cannot see a way to access the raw row string using the row number. I wish to provide feedback on any unparsed rows and displaying the incorrect line in full would be useful rather than just the row number.

Is this possible?

Thank you.

**Comment by pokoli** [comment]
You can access it from the result array using the index. For example:

`
csv = Papa.Parse();
errors = csv.errors[0];
invalid_row = csv.data[errors.row];
`

Hope it helps.
