### ISSUE TITLE
No errors and successful parsing of an image file in demo

### ISSUE THREAD

**Issue by SergiuNegara** [mholt/PapaParse#382]
Hi Matt, I just found this library while browsing and have decided to give the demo a try. I've used a couple of valid CSV files along with an image. Surprisingly the image has been successfully parsed (no errors).

http://papaparse.com/demo > local file
https://www.dropbox.com/s/vp6tpihh2vhev0e/hiking.jpg?dl=0

I also tried another image and it failed with the "UndetectableDelimiter" error.

Otherwise thanks for sharing great stuff!

**Comment by mholt** [comment]
Thanks.

To a CSV parser, there's little difference between image bytes and CSV bytes. It just does its thing.
