### ISSUE TITLE
Feature Request: Convert Rows to Objects

### ISSUE THREAD

**Issue by oleersoy** [mholt/PapaParse#383]
I wrote it up on [SO here](http://stackoverflow.com/questions/43691714/convert-papaparse-rows-to-objects).  Thoughts?

**Comment by pokoli** [comment]
Which benefits does it add? Why we should implement this? 

Which performance implications will have this feature?

Can you please elaborate a little bit more on it?

**Comment by oleersoy** [comment]
For example [super-csv has a CSV bean reader](https://super-csv.github.io/super-csv/examples_reading.html) that automatically maps csv rows to Java beans.  In my case I'm looking to map orders read in in CSV format into Typescript Order instances that can then be validated using the [class-validator](https://github.com/pleerock/class-validator).

So for example one could do something like:

```
var orders:Order[] = parse('csv-orders', {objects: true})
orders.forEach((order)=>order.validate() ... );
```
Perhaps it's better to have a utility function library that can perform array to object mapping...But I figured I would check to see whether you all thought it might be useful.

**Comment by pokoli** [comment]
I think the easiest solution is to build the orders after parsing the CSV file. I doubt we can implement a generic way of converting rows to objects without adding too much complexity. 

Keeping in mind that the objective of PapaParse is to parse CSV in a performant way, I think we must reject this feature. This allows other people to implement it in a separate library that depend on PapaParse.
