### ISSUE TITLE
Grunt integration

### ISSUE THREAD

**Issue by CFenner** [mholt/PapaParse#384]
Is it possible to wrap PapaParse in a Grunt task? Has anyone done this?

I would need to verify CSV files in a Grunt build.

**Comment by pokoli** [comment]
Hi @CFenner,

Yes, it's possible to use PapaParse on a grunt task. You just have to define it as a dependency of your project (or install with npm install papaparse --save) and then on your grunt file add the following line:

` var Papa = require('papaparse'); `

Then you can use the Papa.parse method to parse files. 

Hope it helps.

**Comment by CFenner** [comment]
Good explanation how to do this: http://stackoverflow.com/questions/43853490/validate-csv-files-in-grunt-build
