### ISSUE TITLE
Problems with keeping input data format: all gets into strings

### ISSUE THREAD

**Issue by lilloraffa** [mholt/PapaParse#388]
Hi,

In cases like this:
`a,b,c,d
1,2,3,"c"`

the parter returns:
`{"a": "1", "b": "2", "c": "3", "d":"c"}`

instead of:
`{"a": 1, "b": 2, "c": 3, "d":"c"}`

This create problems if you need to keep the info on the format type of each field. Am I missing something?
Thansk a lot!

**Comment by lilloraffa** [comment]
I should have read the doc more carefully :)
In case anyone got stuck as I did, just need to set the following option:
`dynamicTyping: true`

Thanks for the very nice product!

**Comment by pokoli** [comment]
@lilloraffa Thanks for solving the issue by yourself ;-) Glad that you are enjoying PapaParse.
