### ISSUE TITLE
Computes wrong rows length

### ISSUE THREAD

**Issue by dhruvdutt** [mholt/PapaParse#394]
Let's say my file has 16 rows including the first row for header and next 15 rows for data.

The results shows length as 16 and the 16th object is blank which stacks up into errors array with message "Too few fields".

The simplest solution is to do
`results.data.splice(-1, 1);`

**Comment by mholt** [comment]
This is expected. If you have a newline at the end of the file, that starts a new row. And if it does not have the right number of fields, then that is an error.

**Comment by dhruvdutt** [comment]
I've already checked that. There are no new lines/rows at the end of the file.

**Comment by mholt** [comment]
Oh, I misread that. Is this a bug report? If so, you'll need to provide the input and output and what you expected instead.
