### ISSUE TITLE
Add description to website (http://papaparse.com/)

### ISSUE THREAD

**Issue by epicleptico** [mholt/PapaParse#396]
That's what's shown when page link is shared across some platforms. (This one is Hipchat)

![image](https://user-images.githubusercontent.com/261778/27423838-497d3a86-5733-11e7-8363-c20e8731d899.png)

**Comment by pokoli** [comment]
Thanks for reporting. It seems that this website is only showing the <p> tags, which we are missing on our description.  I've added them, now it should render another text which explains what PapaParse is about it.
