### ISSUE TITLE
Parsing 1GB file on node server

### ISSUE THREAD

**Issue by rimita** [mholt/PapaParse#397]
Hi,

I have been using papa parse to parse huge cvs files (around 1GB) via streaming and it performed really well. Now I am required to do the same thing on the NodeJS server. I tried with babyparse and also by importing the papaparse.js as a module in my code. 
But in both the scenarios I faced the same problem. To get the file object I am using the fs.readFileSync method. But this loads the entire file content into the memory and I am getting a buffer exception ( as I am exceeding the string buffer limits). 

Is there any other way through which I can pass the file object without the contents to papa.parse method? Or if anyone can suggest some work around, even that will be great.
I have tried with around 250MB data file and it is working fine. 

I am really stuck right now and any help will be greatly appreciated.

**Comment by pokoli** [comment]
In #370 we implemented support for Node Read Strems, so I think you can use a [FileSystemReadStream](https://nodejs.org/api/fs.html#fs_class_fs_readstream) instead of fs.ReadFileSync to prevent loading the entire content of the file into memory. 

Hope it helps

**Comment by rimita** [comment]
Thank yo so much........ Saved my day!
