### ISSUE TITLE
Is there any way to handle multiple values?

### ISSUE THREAD

**Issue by rajagopalx** [mholt/PapaParse#398]
I have a csv like this:

```
name, email
raja, "raja@gmail.com, xyz@gmail.com"
```

Note that email has two values.

I want my json to be like:

```
{
   "name": "raja"
    "email": ["raja@gmail.com","xyz@gmail.com"]
}
```

Is there any way to do it in papa parser ?

**Comment by pokoli** [comment]
You have to manually convert the data after parsing. We are correctly parsing the right value, thanks the quoteChar option, which defaults to "
