### ISSUE TITLE
Get data as array of columns

### ISSUE THREAD

**Issue by andreydung** [mholt/PapaParse#399]
Hi,

I'm wondering how to get data as array of columns, as opposed to array of rows? Is there any available configuration in the package?

Thanks,

**Comment by pokoli** [comment]
Hi @andreydung,

This option is not currently available, but I'm wondering which is the use case of having an array of columns. 

Having said that, once the csv is parsed you can process the data and transform to whatever structure you want. The objective of Paparparse is to parse CSV (but not transform the data), so I think this will be out of the scope of the library.

**Comment by andreydung** [comment]
Hi @pokoli, thanks for the reply! 

I was using Plotly.js and PapaParse to visualize time-series data. Plotly.js requires array of columns (each separate data is visualized individually). I did the transpose after loading the csv and everything works fine now.

**Comment by Braintelligence** [comment]
I have the exact same problem. @andreydung Can you elaborate a bit more on what workflow you settled with? Do you load predefined CSV now and transpose them afterwards?
