### ISSUE TITLE
rewrite header when unparse

### ISSUE THREAD

**Issue by RifeWang** [mholt/PapaParse#400]
Sometimes we get the data like a array of objects , and i want to show the header row, but not these keys data in databse ,so we need to rewrite the keys as headers,  i think it is a better way to add a future in config .

**Comment by pokoli** [comment]
Sorry but don't understand what do you mean. Can you clarify which is this issue about? What are you trying to implement?

**Comment by pokoli** [comment]
I'm closing this issue as no further feedback have been provided.
