### ISSUE TITLE
Module not found: Error: Can't resolve 'fs'

### ISSUE THREAD

**Issue by sudheerDev** [mholt/PapaParse#401]
ERROR in ./~/babyparse/babyparse.js
    Module not found: Error: Can't resolve 'fs' in /node_modules/babyparse'
    @ ./~/babyparse/babyparse.js 41:16-29

I have this error when i use npm to install babay parse

For now i was able to add a workaround https://github.com/webpack/webpack/issues/2142

   	"main": "babyparse.js",
	"browser": {
		"fs": false
	}

Is there any onther way of solving this?

**Comment by pokoli** [comment]
Indeed you can use directly PapaParse on Node. Have you tried that?

**Comment by sudheerDev** [comment]
@pokoli i am trying to use it for converting csv on the browser. I thought it's better to use babyParse. but would PapaParse solve this on using it for browser?. I had the same issue here as well. https://github.com/Keyang/node-csvtojson/issues/183

**Comment by pokoli** [comment]
@sudheerDev If you want to use it on browser there is no need to install it just include the paparse.js file (Can user bower if you want) in your html page and use it as javascript funciton. 

You can have a look at the[ demo page source code](https://github.com/mholt/PapaParse/blob/gh-pages/demo.html) if you have doubts:

I'm closing this issue.

**Comment by sudheerDev** [comment]
@pokoli I am using webpack and npm for dependency management. 
I will try with papaparse.js instead but if papaparse depends on `fs` or child_process it would still throw that error with out mentioning those browser flags in package.json. I would really prefer not to change package.json myself. do you have any more suggestions?

**Comment by pokoli** [comment]
Just try and report back here if you have some errors :)
