### ISSUE TITLE
UnknownError with large (150MB) file

### ISSUE THREAD

**Issue by webenji** [mholt/PapaParse#402]
I've been using PapaParse successfully for a while now and came across an error while attempting to parse a large CSV file (33,955 rows, 3 columns, with a total file size of about 150MB). When parsing this file, I get an "UnknownError" from the "err" (first) parameter of the error callback function: {constructor: DOMError {...}, name: "UnknownError"}. I've looked online and in the GitHub issues to try and find what could be the source of error, but did not find anything...

Suspecting it had something to do with the file size, I have divided the file into 4 files of up to 10,000 rows (accounting for every row) and each of these files are parsed correctly. Here is the code I am using (note that the beforeFirstChunk function does not get executed and that changing the preview parameter to 1 gives the same error):

```
Papa.parse(file, {delimiter: ",", newline: "", preview: 50, skipEmptyLines: true, header: true,
    beforeFirstChunk: function(chunk) {
        $rootScope.log("beforeFirstChunk");

        var index = chunk.match( /\r\n|\r|\n/ ).index;
        headings = chunk.substr(0, index).split( ',' );
        headers = angular.copy(headings);
					    
        var length = headings.length;
        for(var i=0; i<length; i++)
            headings[i] = "Column_" + i;

        return headings.join() + chunk.substr(index);
    },
    complete : function(results) {
        records = results.data;
        delimiter = results.meta.delimiter;
        parseDataTypes();
        deferred.resolve();
    },
    error : function(err, file, inputElem, reason) {
        $rootScope.log("error");
	$rootScope.log(err);
	$rootScope.log(file);
	$rootScope.log(inputElem);
	$rootScope.log(reason);
	deferred.reject(err);
    }
});
```

Any help with this error/problem would be greatly appreciated.

**Comment by pokoli** [comment]
On which environment are you parsing it? Server (NodeJS) or on the browser? 

Have you seen #397 ?

**Comment by webenji** [comment]
I am parsing it on the browser. I did see #397 but assumed it did not apply to my case.
Do you think it's a problem of memory/buffering/size (I'm assuming it's not since I am using the preview parameter with a very low number)?

**Comment by pokoli** [comment]
@webenji could you raise the error and put the full stack trace that will be printed on the browser console?

**Comment by webenji** [comment]
Sorry for not replying sooner. I've worked on "fixing" the error and was able to circumvent it by using the streaming feature. I'm not sure what was the actual problem, although I suspect it has something to do with the file size (although with the preview set to 1 or 50, it should not have been an issue, right?). Anyway, here is the code snapshot that works, in case people come across the same problem:

```
Papa.parse(file, {delimiter: ",", newline: "", preview: 50, skipEmptyLines: true, worker: true,
    step: function(results, parser) {
        if(records==null) { // First row
            delimiter = results.meta.delimiter;
            var length = results.data[0].length;
            records = new Array(50);
            headings = new Array(length);
	    headers = new Array(length);
            rowNum = 0;

	    for(var i=0; i<length; i++) {
	        headers[i] = results.data[0][i];
	        headings[i] = "Column_" + i;
	    }
	}
        else {
	    var length = results.data[0].length;
	    var row = {};
	    for(var i=0; i<length; i++) {
	        var data = results.data[0][i];
	        row["Column_" + i] = data;
	    }
	    records[rowNum] = row;
	    iterativeDataTypeParsing(rowNum++);
	}
    },
    complete : function() {
        deferred.resolve();
    },
    error : function(err) {
        deferred.reject(err);
    }
});
```
