### ISSUE TITLE
[React] Passing props to complete callback

### ISSUE THREAD

**Issue by musaghauri** [mholt/PapaParse#403]
I am using papaparse in react! I tried a lot but couldn't find any way to pass props in complete callback! I need to call this.function from within complete callback! Thanks!

**Comment by pokoli** [comment]
Hi @musaghauri,

I'm not sure to understand what are your problems. Can you post your code, and which callback you exxpect that don't have available?

Thanks.

**Comment by pokoli** [comment]
I'm closing the issue as no new information have been provided. Reopen with some code example. THanks
