### ISSUE TITLE
Parsed data has keys in quotations?

### ISSUE THREAD

**Issue by kevin-coelho** [mholt/PapaParse#407]
Hi, sort of new to parsing csv / not super experienced in JS, BUT having the following data output from one of parsed rows from my csv and I'm printing:

Papa.parse(content, {<blockquote>
                header: true,
                step: results => { 
                     <blockquote>
                    // process row
                        var obj = results.data[0];
                        console.log(obj);
                        ......
      </blockquote>
      </blockquote>

Prints out below:
---------------------------
{ '﻿UID': '424125',
  Email: 'somemail',
  FName: 'bla',
  LName: 'bla',
 ... etc etc}

I'm having issues because that first key there seems to be in quotations and isn't recognized when I do

obj.hasOwnProperty('UID') => returns false

It's really weird because all the other keys seem to be getting parsed just fine. Any ideas about why this is happening? I thought it was an encoding thing but I made sure that Excel was saving using UTF-8 and I've specified to parse using that encoding.

**Comment by pokoli** [comment]
Are you sure you are typing the right column name? Note: that it's case sensitive.

I give a test on the demo page and hasOwnProperty returns true if the column is present, so I don't think there is any error in PapaParse. 

I'm closing the issue, reopen if you don't agree but please provide aditional information in order to show how to reproduce the issue.

**Comment by kevin-coelho** [comment]
If you see my code above, I am clearly typing the column name properly. The issue is that PapaParse is outputting data where one of the keys has quotes around it and so JS isn't recognizing it, I would have to do obj.hasOwnProperty("'UID'") to make it work. What would make this happen? You can see from my output that the other keys are properly encoded.

**Comment by pokoli** [comment]
I can not see if you are typing the column name property as you don't provide any file and the header option is used. 

I imagine your input file has the quotes also on the header, so that's why they are used on column name.

**Comment by kevin-coelho** [comment]
I suspect that might be true - how would I remove them though? When I open the csv in excel, it doesn't show any quotes.

**Comment by pokoli** [comment]
@kevin-coelho try opening the CSV with a text editor. Notepad++ is a good one.

**Comment by kevin-coelho** [comment]
Tried with google sheets and fixed the issue - thanks very much for the help. Excel is a screwy program -_____-

**Comment by sal10peppr** [comment]
I faced the same issue when running in nodejs. First key was in quotes, every other key unquoted. Somehow pasting the contents in a new csv file (in sublime) worked !

**Comment by riddla** [comment]
Excel was probably saving your CSVs with a https://de.wikipedia.org/wiki/Byte_Order_Mark. This happened to me, too.
My first header field was supposed to be `type` but ended up being `  ﻿type` (which starts with the UTF8 encoded BOM, see https://github.com/nodejs/node-v0.x-archive/issues/1918 for details).

By removing the encoded BOM (e.g. via https://www.npmjs.com/package/strip-bom) from the CSV string and then handing over to 'Papa' it did the trick and the quotations finally disappeared.

**Comment by thebetternewt** [comment]
@riddla I know this is an older post, but it trips me up from time to time and I always seem to find my way back here to remember what I did. Thanks for the help!  😁

**Comment by benb1983** [comment]
Same ☝️

**Comment by samvanemelen** [comment]
quick solution for removing BOM when you are using VSCode:

In the bottom right corner you can see if the file uses BOM
![image](https://user-images.githubusercontent.com/36103001/205927914-67cfeb7c-8afe-4a67-9b1a-b4225af0ca79.png)

When you click on it you get the option to save it using another encoding:
![image](https://user-images.githubusercontent.com/36103001/205928109-bf9320cd-7cfd-42a0-9dd3-b7d30306f12a.png)

And then you get the option to save using any encoding you like
![image](https://user-images.githubusercontent.com/36103001/205928228-de149b1b-7e39-4546-ae2f-f7987b5f7978.png)

This is how I fixed the issue without downloading I didn't already have
