### ISSUE TITLE
Drops fields that don't exist in the first record if using implicit header row

### ISSUE THREAD

**Issue by antony** [mholt/PapaParse#408]
If you create a dataset like this:

```
[ { a: 'foo', b: 'bar' }, { b: 'bar', c: 'baz' }, { a: 'foo', b: 'baz', d: 'qux' } ]
```
and run it through `unparse` to turn it into a CSV

You will get the following:

```
a     | b
-------------
foo   | bar
      | bar
foo   | baz
```

whilst this is somewhat predictable behaviour according to the docs - my actual prediction would be that objects with _more_ fields were simply missing headers, not that their values would be dropped, it means I have to have a function like this:

```
const sorted = data.sort((a, b) => {
  const aLength = Object.keys(a).length
  const bLength = Object.keys(b).length
  return bLength - aLength
})
```

which is a bit suboptimal.

Also it's totally unpredictable for a new user - shouldn't the dropping of fields (which is kinda a big thing) be very explicit in the documentation.

**Comment by pokoli** [comment]
I don't think we should change the library behaviour, as it will be too costly to read all the file to compute all the available columns, so for me it's ok to use the first one as data structure. 

If you are constructing the read object and you now all the possible keys, you can include them with None values on the first row, which will make the code work. 

You can submit a pr to the gh-pages branch of this repository to improve the docs if desired.
