### ISSUE TITLE
Can quoteChar be implemented as a custom setting in config?

### ISSUE THREAD

**Issue by terryureche** [mholt/PapaParse#415]
Hi guys,

I tried to set a custom quoteChar ('`'), I wasn't able to do that through the config in parseFiles.
Can you implement this feature as it is in papaparse.

Best Regards,

**Comment by pokoli** [comment]
You can set by using the [quoteChar setting](http://papaparse.com/docs#config).

**Comment by terryureche** [comment]
Hi pokoli,

I posted in the wrong thread.
I wanted to post for babyparse.
Sorry for the inconvenient.

Thank you!
Have a nice day.

**Comment by pokoli** [comment]
hi @terryureche I will recomend using latest version of Paparse instead of BabyParse as PapaParse also works with node.

**Comment by terryureche** [comment]
Wow, that's a great news. 
Thank you very much.
