### ISSUE TITLE
Always skip empty lines while detecting delimiter ?

### ISSUE THREAD

**Issue by jhpommier** [mholt/PapaParse#416]
I set `skipEmptyLines` to false in order to keep line number.
The negative counterpart is that `guessDelimiter` doesn't work if there's an empty line in the first 10 lines.

I resolved this problem by setting custom function into `delimiter` config.

But looking at https://github.com/mholt/PapaParse/pull/404
i wonder if we shouldn't skip empty lines while detecting delimiter
(even if `config.skipEmptyLines` is set to `false`) ?

**Comment by pokoli** [comment]
For me, if you skip empty lines, the same behaviour should be applied when detecting delimiter. 

Indeed I will accept a pull request that allows to customize the function used to guess delimiter, so you can implement whatever you want. This function have to accept the input and the config used. 

Feel free to create a pull request for it.
