### ISSUE TITLE
Papa.unparse encoding

### ISSUE THREAD

**Issue by vnikolay** [mholt/PapaParse#421]
Hello.
In Papa.parse we can set encoding, but Papa.unparse don't have encoding parameter and saves only in UTF-8. How can I set in the result csv (after Papa.unparse) the same encoding as in Papa.parse?

**Comment by pokoli** [comment]
Indeed it's a missing feature. So a PR implementing it will be very welcome.

**Comment by vnikolay** [comment]
Maybe there is some simple workaround code while it will be implemented? Or only google can help?

**Comment by pokoli** [comment]
@vnikolay BTW could you please post the code you are using to save the file? Just only the relevant Paparse part.

**Comment by vnikolay** [comment]
Now, while I'm in developing process, I just took code from this topic: https://github.com/mholt/PapaParse/issues/175 . But I think the best way is to use html5 fileapi for that, if there is no need to support old browsers. Like in this: https://stackoverflow.com/questions/13752984/html5-file-api-downloading-file-from-server-and-saving-it-in-sandbox

**Comment by pokoli** [comment]
Then you should probably especify the blob content type as explained on:

https://stackoverflow.com/questions/18925210/download-blob-content-using-specified-charset

I'm closing this issue as we have nothing to do with it. But if you want to create a PR for #175 I will be happy to review it. We can start with a basic code and then adding support for most complex scenarios (i.e: older browsers) in newer versions.

**Comment by vnikolay** [comment]
What about this solution for saving files: https://github.com/eligrey/FileSaver.js/
?

**Comment by pokoli** [comment]
@vnikolay thanks for sharing. 

Feel free to use it on your projects, but it should not be part of Paparse. 

Indeed if other libraries exist for doing this, we should not reinvent the wheel. So I will close #175 with a reference to your message. Thanks another time.
