### ISSUE TITLE
QuoteChar option in `unparse` blows up the parser if it's a regex special char

### ISSUE THREAD

**Issue by pkrumins** [mholt/PapaParse#424]
If you specify a regex special char as a quoteChar then the library blows up:

```
Papa.unparse('[{"a": "1", "b": "2", "c": "3"}]', { quoteChar: '(' })
```

> papaparse.min.js:6 Uncaught SyntaxError: Invalid regular expression: /(/: Unterminated group
>    at new RegExp (<anonymous>)
>    at Object.b [as unparse] (papaparse.min.js:6)
>    at <anonymous>:1:6

**Comment by pokoli** [comment]
I don't think we can do a lot here. If you are using bad parameters for the options, it's normall that the library raises an error. 

Any suggestion on how to improve it?

**Comment by chriszs** [comment]
Can reproduce:
```js
JSON.stringify(papaparse.parse("|2018|,|1010320180036112826|,|Y0000025957L|,|WELCH, WESLEY MR|,|N00003280|",{quoteChar:'|'}).data)
```
Expected output:
```
[["2018","1010320180036112826","Y0000025957L","WELCH, WESLEY MR","N00003280"]]
```
Output:
```
[["|2|0|1|8|","|1|0|1|0|3|2|0|1|8|0|0|3|6|1|1|2|8|2|6|","|Y|0|0|0|0|0|2|5|9|5|7|L|","|W|E|L|C|H|,| |W|E|S|L|E|Y| |M|R|","|N|0|0|0|0|3|2|8|0|"]]
```

Trying to escape it, like one would a regular expression special character, doesn't work because elsewhere the quote character is used as a string. A possible fix would be to properly escape it before creating a regular expression from it.
