### ISSUE TITLE
cannot auto detect '}' as a delimiter

### ISSUE THREAD

**Issue by logicminds** [mholt/PapaParse#425]
When my data contains `}` as a delimiter Papaparse cannot properly auto detect the delimiter and fails to parse correctly unless I supply the delimiter. 

Sample data

```
CODE}AREA
600}S. Peo Is-SB
601}N. Pike Is-SB
602}Sallay Is-SB
```

result

```
{ 'CODE}AREA': '600}S. Peo Is-SB' },
  { 'CODE}AREA': '602}Peo Is-SB' },
  { 'CODE}AREA': '603}Sallay Is-SB' },
```

Papa.parse(file, {
  dynamicTyping: false,
  header: true,
  skipEmptyLines: true,
  error: function(err) {
    console.log(err);
  },
  complete: function(results) {
    console.log("Finished:", results.data);
  }
});

**Comment by pokoli** [comment]
Hi @logicminds, 

The paparse auto detect function only searches for most common delimiters and { is not on the list. I think we should keep like this for the sake of simplicity, as the list of separator values is huge. 

If you know your data uses { as delimiter, it's better to pass it explicitly.

**Comment by logicminds** [comment]
Yea I am already manually passing in the value.  However, the docs say "autodetect" so I figured it was magical and would scan the first few lines to find the delimiter instead of working off a static list.  Maybe update the docs to reflect this since I thought this was a bug.

**Comment by pokoli** [comment]
Thanks for the suggestion. I clarified the docs in https://github.com/mholt/PapaParse/commit/9fb92261db69da2a0722e8054509aba98338c66a
