### ISSUE TITLE
Allow blob urls for PAPA.SCRIPT_PATH

### ISSUE THREAD

**Issue by andre-f-paggi** [mholt/PapaParse#426]
Hi,

I have a weird problem with my application server in which it doesn't allow to get URLs of javascript files with search string in it, because of URL Rewrite configuration.

I'm saying that because this library always puts "?papaworker" when working with web workers.

Example of failure: 
mycompany.com/assets/papaparser.min.js?papaworker

So, what I suggest is to allow blob URLs, since they do not mess with the server.

Today, I can set the PAPA.SCRIPT_PATH variable, but the always appended "?papaworker" messes the blob URL and doens't allow the browser to point to that blob.

**Comment by andre-f-paggi** [comment]
Setting the PAPA.SCRIPT_PATH variable:
![screenshot_1](https://user-images.githubusercontent.com/8538938/31457668-cbfa43d4-ae93-11e7-99f1-edea99e34c1d.png)

Error in the browser:
GET blob:http://mycompany.com/0c6fb13f-4fba-4383-9326-6e063849bf0f?papaworker 404 (Not Found)

**Comment by pokoli** [comment]
Is there any alternative to remove the ?papaworker argument? I will be happy to accept a PR that adds an aditional way of calling workers.

**Comment by pokoli** [comment]
Fixed by #599
