### ISSUE TITLE
Are quotes still the issue?

### ISSUE THREAD

**Issue by hellofantastic** [mholt/PapaParse#427]
Hello
I'm using 4.3.6 
https://cdnjs.cloudflare.com/ajax/libs/PapaParse/4.3.6/papaparse.min.js

in a project and csv data row value fields  can sometimes be double quoted and contain commas which is also the delimiter

Company Name  Inc.,Yes,Senior-level manager,"Director, Software Engineering"

And papa makes "Director   a value and Software Engineering" a value shifting row data over 
![screen shot 2017-10-15 at 3 53 53 pm](https://user-images.githubusercontent.com/6655746/31590197-1d55b116-b1c1-11e7-8721-73189ba09f1a.png)

I've tried all the permutations on the config settings because nothing has worked .. just to see if anythin work affect the outcome 

quotes: false
quoteChar: "'"

quotes: true
quoteChar: "'"

quotes: false
quoteChar: '"'

quotes: true
quoteChar: "'"

tried those with fastmode forced on and off

Any insight? try a different version? I was on 4.1.1 before 4.3.6 and that also did same results

**Comment by pokoli** [comment]
hi @hellofantastic,

I'm not sure to understand what's the problem. 

We have several tests cases for using delimiters inside quotes and that works as expected. 

Could you describe what's the current output and which is the expected output? 

Is this a regresion?

**Comment by hellofantastic** [comment]
The problem was data value if in quotes and contained delimiter was getting split
you see in the screenshot header column Title should be   Director, Software Engineering  not "Director

I did get it to resolve by not having any config values set.
