### ISSUE TITLE
Issues parsing a CSV with " and ' as part of the data adjacent to the delimiter ,

### ISSUE THREAD

**Issue by lunatixcoder** [mholt/PapaParse#430]
When using PapaParse if there is a " after a , delimiter, the remaining file gets loaded into the one value. I thought I fixed it by specifying quoteChar: "'", in the config, but there are fields with values that start with ' right after the delimiter as well.

Examples of lines of data from CSV...

060003T,RACEAIR DESIGNS INC ,'LIL BITTS ,4,7 ,1,2,01,001,CLASS 1,0000,

05618AR,MILLER ,"A" ,4,1 ,1,1,01,001,CLASS 1,0085,

05618AT,TRAVEL AIR ,"R" ,4,1 ,1,1,01,001,CLASS 1,0085,

I do not control the data, so I am forced to use the file AS IS.

If I use quoteChar: '"', I can get around the "A" row and the "R" row, but not the 'LIL BITTS row. How do I fix this?

Thanks!

**Comment by pokoli** [comment]
@lunatixcoder have you tested using a quoteChar diferent than " or '. Probably using | will do the trick.

**Comment by lunatixcoder** [comment]
Ok, that works.  However, that will only work until I get data (which I dont control) that has a | as part of a data field in the first character.  Now the likelihood of that is probably none. BUT...  If I set...

quoteChar: '', // setting quoteChar to empty 

The positive assertion should be not to look for any quote characters in the data. (IMHO)

The issue that occurs is papaparse.js automatically defaults to quoteChar: '"' at line 1155 of the latest commit at least.

1155    var quoteChar = config.quoteChar || '"';

If I change that line to...

1155    var quoteChar = config.quoteChar || '';

papaparse does what I would expect it to.  Is there a reason if you don't specify quoteChar or set it to nothing that it assumes a " as quoteChar?  I know the RFC is very grey on this, but when its ambiguous you should always assume positive assertion by the programmer.

I was able to debug this just now, and I do accept that a change like that may not be the correct way to fix it, but it does seem pretty glaring that if I specify NO quote char it should ignore quote searching within a field and assume everything between the delimiters is just a literal.  

I would think that best practices would say that you should have the ability to set a config of ignoreQuotes: true(false)   or  be able to set a positive assertion of quoteChar of null and in either case it should ignore quotes between delimiters.

**Comment by pokoli** [comment]
I will be happy to accept a PR the allows false as quoteChar and in this case no quote character is used. 

Probably that will fix your use case.

**Comment by lunatixcoder** [comment]
PR?  Sorry, Im not understanding.

**Comment by pokoli** [comment]
@lunatixcoder Pull Request. See: 

https://help.github.com/articles/about-pull-requests/
https://help.github.com/articles/creating-a-pull-request/

**Comment by lunatixcoder** [comment]
Oh ok.  Cool.  I'll try and submit something later today.  Thanks!!!!

**Comment by mirko77** [comment]
Same issue here, +1

**Comment by smitshah91** [comment]
+1 for this issue. Has it been fixed?

**Comment by lunatixcoder** [comment]
Yes... the code change committed n 430 fixed the issue.

**Comment by KuryKat** [comment]
I used quoteChar: '🙌'
XD
