### ISSUE TITLE
Add ability to skip empty columns

### ISSUE THREAD

**Issue by StephenOTT** [mholt/PapaParse#434]
Cam across some files that have double semi-colons which caused the parse to think there was multiple empty fields (header and value).

**Comment by pokoli** [comment]
I don't think we should implement something to manage empty columns. If there are empty columns the parser should return and empty value so the process that reads the parsed data should decided what to do: i.e: Raising and error or skip the empty value.

**Comment by StephenOTT** [comment]
@pokoli skipping empty columns seemed like the same logic/reasoning as having the ability to skip empty rows.

**Comment by StephenOTT** [comment]
@pokoli How do you see the difference between a extra row vs a extra column?

**Comment by pokoli** [comment]
Extra row contains no data, so it can be directly skipped.
Extra column is and empty value for a field, which may be intereseting for some people.

**Comment by StephenOTT** [comment]
>which may be intereseting for some people. 
😄 yes, the Extra Row may be interesting to some, hence the optional "Skip Extra Rows".  Same logic applied for Extra Columns.

**Comment by dvopalecky** [comment]
I would also appreciate this option "Skip Empty Columns" in the config.

**Comment by pokoli** [comment]
@dvopalecky you can filter the empty values after parsing the file. So I do not think this option is necessary

**Comment by tutoring** [comment]
I think there's a misunderstanding here where "empty values" and "empty columns" are being treated as the same idea. Keeping an **empty value** makes sense, but keeping an **empty column** usually doesn't (e.g. if the whole column had no values and potentially a blank header as well). I would definitely see the value in skipping empty columns.

**Comment by rmathur101** [comment]
+1. an optional argument would go a long way. i assume this is a common issue.

**Comment by Gledros** [comment]
> I think there's a misunderstanding here where "empty values" and "empty columns" are being treated as the same idea. Keeping an **empty value** makes sense, but keeping an **empty column** usually doesn't (i.e. if the whole column had no values and potentially a blank header as well). I would definitely see the value in skipping empty columns.

So, still not added right?

Just a tip for anyone trying a fix: I just had to use the step callback to process line by line avoiding the undefined columns, like this:

`step: (results, parser) => {
    results.data = _.pick(results.data , ['column1', 'column2', 'columnN']);
    return results;
},`

Hope it helps someone
