### ISSUE TITLE
Remove recommendation to use BabyParse with NodeJS from FAQ

### ISSUE THREAD

**Issue by stephanbogner** [mholt/PapaParse#435]
The [FAQ of the website](http://papaparse.com/faq) still says you should use BabyParse if you want to parse a CSV using NodeJS.

Since that is not necessary anymore, it would be cool to state on the website that PapaParse now supports NodeJS :)

**Comment by pokoli** [comment]
Thanks for the report. I've uploaded the website to remove the babyparse reference.
