### ISSUE TITLE
unparse,  header is  always  included.  even if  header : false, 

### ISSUE THREAD

**Issue by alpastar** [mholt/PapaParse#436]
unparse, header is  always  included.
is this  bug ? 

the  diifference  between demo  and my code is  that 
data is  array of object  rather than array of array ( which  is demo)

in mycase  setting fields is mandatory , 
but  specifing fields and/or  not specifing fields has no difference.
header is always included 

var csv = Papa.unparse({
	fields: ["foo", "bar"],
	data: [
		{"foo":"foo",  "bar": "aaa"},
		{"foo":'ggg", "bar: "bbb" }
	],
       config:{
          delimiter: ",",
           header : false,            //  but, always  header included   
           newline: "\n",
           skipEmptyLines:true
    }
});

**Comment by pokoli** [comment]
Probably is a missing feature. I will be happy to accept a Pull Request that implements it.

**Comment by Devil-Boy** [comment]
According to the docs, the config object should be a second argument to the unparse() function. It looks like you have it as a value inside of the data object. Are any of the other config options working for you?

**Comment by pokoli** [comment]
I'm closing this issue as I see there is test that verifies it:

https://github.com/mholt/PapaParse/blob/30f8a397017473005d136e17e7fd65152dc7a1fe/tests/test-cases.js#L1401

So the problem is that you are not passing correctly the config. Re-open if you don't agree.

**Comment by pbaldridge** [comment]
I could be mistaken, but it seems this was closed based on reviewing documentation instead of actually attempting to duplicate the issue. I have the exact same issue and am passing the config as the second option. not a value inside the data object. Perhaps this should be re-opened. Did anyone actually verify this works as designed?

**Comment by pokoli** [comment]
@pbaldridge could you share a simple example to reproduce it?
