### ISSUE TITLE
complete handler doesn't return results

### ISSUE THREAD

**Issue by etanxing** [mholt/PapaParse#437]
const complete = function(results) {
      console.log(arguments)
    }

    const step = function (results, parser) {
      if (self.state.cancelled) {
        console.log('parser.abort')
        parser.abort()
        removeFile()
      }
    }

    const options = Object.assign({}, {
        complete,
        worker: true,
        step
      }, config)

    if (file) Papa.parse(file, options)

Once I specify `step` or `chunk` in options the results in `complete` is undefined. It's React/Redux web app. 

Anyone knows how that happens?

Thanks

**Comment by Tzinov15** [comment]
I ran into this same issue and after some investigation, I believe this functionality is not even supported. 

Reading the [docs](http://papaparse.com/faq#streaming) I came across this:

> How do I get all the results together after streaming?
> 
> You don't. Unless you assemble it manually. And really, don't do that... it defeats the purpose of using a stream. Just take the parts you need as they come through. 


and after going through the [test cases](https://github.com/mholt/PapaParse/blob/master/tests/test-cases.js), I didn't see anything indicating you can call `step` and then collect the results in one spot.

`step` seems to lock you into "stream mode" where the results no longer  get stored in memory

**Comment by jurajpiar** [comment]
This issue should be closed as answered in the documentation. @mholt 

> The callback to execute when parsing is complete. It receives the parse results. If parsing a local file, the File is passed in, too:
```javascript
complete: function(results, file) { 	
   console.log("Parsing complete:", results, file); 
}
```
> **When streaming, parse results are not available in this callback.**
