### ISSUE TITLE
Easy Programmatic Access to Headers

### ISSUE THREAD

**Issue by AABoyles** [mholt/PapaParse#438]
It would be nice if there were a way to get the headers of a parsed file without having to parse the entire file (or more than the fist line for that matter).

**Comment by pokoli** [comment]
@AABoyles any idea on how to implement this?

**Comment by AABoyles** [comment]
I'm not familiar with Papa's internals, but there's a point at which the parser must know the headers in order to set the keys of the output objects when `header` is `true`. Perhaps there could be a function on Papa that replicates the behavior of `Papa.parse` up to this point in the process, and then stops (i.e. pauses any ReadableStreams) and returns the headers as an array of strings.

**Comment by pokoli** [comment]
I think's it's enough to use the preview option with the header option to get all the headers and a limited output of the file. See http://papaparse.com/docs#config for further reference. 

@AABoyles  Is this enough for your use case?

**Comment by pokoli** [comment]
I'm closing this as I understant that my previous response solved the problem. Re-open if you don't agree.

**Comment by AABoyles** [comment]
Thanks, @pokoli, I'll use preview instead.
