### ISSUE TITLE
Parse remote CSV from Node?

### ISSUE THREAD

**Issue by necevil** [mholt/PapaParse#440]
Hey guys,
Love the project and have used it in the browser in the past.
I am currently working on parsing a remote csv product feed from a Node app and would like to use Papa Parse to do that.

That said my initial attempts and web searching haven't turned up exactly how this would be done.

The readme says that Papa Parse is now compatible with Node and as such Baby Parse (which used to serve that functionality) has been depreciated.  Here's a link to the Node section of the docs for anyone stumbling on this issue in the future: https://github.com/mholt/PapaParse#papa-parse-for-node

From that doc paragraph it looks like Papa Parse in Node can parse a readable stream instead of a File.  My question is, is there any way to utilize this functionality to download / parse a remote CSV some what similar to how Papa in the browser uses XMLHttpRequest to accomplish that same goal?

**For Future Visibility**
For those searching on the topic (and to avoid repeating a similar question) attempting to utilize the remote file parsing functionality described here: http://papaparse.com/docs#remote-files will result in the following error:
"Unhandled rejection ReferenceError: XMLHttpRequest is not defined"

**Comment by pokoli** [comment]
Hi @necevil, 

I've never tried it but as far as I understand it should be possible to stream a file donwload directly to PapaParse. As we use node readable stream, you should download the file to a stream and then use this stream as papaparse input. 

Something like this question:

https://stackoverflow.com/questions/11944932/how-to-download-a-file-with-node-js-without-using-third-party-libraries

But instead of using a writable stream to save it to a file, stream it to Paparse. 

Hope it helps.

**Comment by pokoli** [comment]
BTW: It will be great if you share your code here. And feel free to propose any documentation enachment if you think it's required.

**Comment by necevil** [comment]
100% Will do @pokoli.

**Comment by necevil** [comment]
@pokoli I haven't been able to get the pipe working quite yet but I was able to setup a fall back as described in the StackOverflow mirror to this question over here: https://stackoverflow.com/questions/47823288/parse-remote-csv-file-using-nodejs-papa-parse

The code to download the file (using HTTP and fs) is below: 
`// Papa Parse for parsing CSV Files
var Papa = require('papaparse');
// HTTP and FS to enable Papa parse to download remote CSVs via node streams.
var http = require('http');
var fs = require('fs');

var destinationFile = "yourdestination.csv";

var download = function(url, dest, cb) {
  var file = fs.createWriteStream(dest);
  var request = http.get(url, function(response) {
    response.pipe(file);
    file.on('finish', function() {
      file.close(cb);  // close() is async, call cb after close completes.
    });
  }).on('error', function(err) { // Handle errors
    fs.unlink(dest); // Delete the file async. (But we don't check the result)
    if (cb) cb(err.message);
  });
};

download(feedURL, destinationFile, parseMe);

var parseMe = Papa.parse(destinationFile, {
  header: true,
  dynamicTyping: true,
  step: function(row) {
    console.log("Row:", row.data);
  },
  complete: function() {
    console.log("All done!");
  }
});`

I am continuing to work on the piping but I wanted to be sure that my code downloading the file was correct.  In this instance I am piping out to fs to write the contents of the remote csv which DOES work (I end up with a local copy and can see that it is intact).

Now I need to figure out why Papa Parse has trouble when I pipe to papa instead of to fs to write that file.

**Comment by pokoli** [comment]
Download code seems ok to me, just make sure to parse the CSV file once it hase been fully downloaded if you use a file.

**Comment by pokoli** [comment]
I'm closing this issue as I understand that the proposed solution worked for you. Re-open if you don't agree

**Comment by Evertvdw** [comment]
> But instead of using a writable stream to save it to a file, stream it to Paparse.

Really missing an example of this, everywhere it is mentioned that this is possible I only don't know how.

**Comment by liaocanada** [comment]
After lots of tinkering I finally got a working example of this: 

```
const papa = require("papaparse");
const request = require("request");

const options = {/* options */};

const parseStream = papa.parse(papa.NODE_STREAM_INPUT, options);

request
    .get("https://example.com/myfile.csv")
    .pipe(parseStream);

parseStream.on("data", data => {
    console.log(data);
});
```

For some reason all the data is given on "data", it never calls on "end". Hope this helps someone!

**Comment by Oreilles** [comment]
Is it possible to listen to error events with this solution?

**Comment by rohanrajpal** [comment]
> After lots of tinkering I finally got a working example of this:
> 
> ```
> const papa = require("papaparse");
> const request = require("request");
> 
> const options = {/* options */};
> 
> const parseStream = papa.parse(papa.NODE_STREAM_INPUT, options);
> 
> request
>     .get("https://example.com/myfile.csv")
>     .pipe(parseStream);
> 
> parseStream.on("data", data => {
>     console.log(data);
> });
> ```
> 
> For some reason all the data is given on "data", it never calls on "end" (is this a bug?). Hope this helps someone!
> 
> EDIT: the callback for "data" runs once for each row in the CSV. And the "end" event never happens for the parseStream. I found a workaround for this to tell when the stream is done processing: to use the "finish" event for the original stream:
> 
> ```
> const papa = require("papaparse");
> const request = require("request");
> 
> const options = {/* options */};
> 
> const parseStream = papa.parse(papa.NODE_STREAM_INPUT, options);
> 
> const dataStream = request
>     .get("https://example.com/myfile.csv")
>     .pipe(parseStream);
> 
> let data = [];
> parseStream.on("data", chunk => {
>     data.push(chunk);
> });
> 
> dataStream.on("finish", () => {
>     console.log(data);
>     console.log(data.length);
> });
> ```

In case anyone here is using Axios/Nestjs, here is the way to make it work:

```ts
const url = 'url-of-csv';

const parseStream = parse(NODE_STREAM_INPUT);

const { data: res } = await firstValueFrom(
    this.httpService.get(url, { responseType: 'stream' }),
);

const dataStream = res.pipe(parseStream);

const data = [];

parseStream.on('data', (chunk) => {
    data.push(chunk);
});

dataStream.on('finish', () => {
    console.log(data);
    console.log(data.length);
});
```

Since axios doesn't implement the stream interface to use the pipe method, we do it manually.

Huge thanks to -> https://github.com/axios/axios/issues/3971#issuecomment-1159556428

**Comment by RaiMX** [comment]
```
public async import(): Promise<any> {
    const filepath = '/app/dist/imports/ar/s_geonims.txt';

    const dataStream = fs.createReadStream(filepath);

    // Create parser stream
    const parseStream = Papa.parse(Papa.NODE_STREAM_INPUT, {
        delimiter: '|',
        dynamicTyping: true,
        header: true,
        encoding: 'utf8',
    });

    dataStream.pipe(parseStream);

    return new Promise((resolve, reject) => {
        parseStream.on('data', (row) => {
            console.log(row);
        });

        parseStream.on('finish', () => {
            resolve(true);
        });
    });
}
```
