### ISSUE TITLE
download converted csv file to "download"-directory

### ISSUE THREAD

**Issue by Gargamel13** [mholt/PapaParse#442]
Is there an option where the app (Android) put the file to a specific directory/place?

I implemented PapaParse to an app (Cordova-Ionic) and on the browser the csv-File will be downloaded to the "Downloads"-dir. On android, there is no error message, but cannot find the data anywhere.

My Code is:

`
```
downloadCSV() {
		let csv = papa.unparse({ fields: this.headerRow, data: this.csvData }, { delimiter: ";" });
		var blob = new Blob([csv]);
		var a = window.document.createElement("a");
		a.href = window.URL.createObjectURL(blob);
		a.download = moment().format('LLL') + ".csv";
		document.body.appendChild(a);
		a.click();
		document.body.removeChild(a);
		this.showToast("Die CSV-Datei wurde erfolgreich im Dateisystem abgelegt");
	}
```
`

**Comment by pokoli** [comment]
Maybe you should use the FileTransfer plugin:

https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-file-transfer/

**Comment by Gargamel13** [comment]
first of all thanks for your tip. This is what I got:

`let csv = papa.unparse({
			fields: this.headerRow,
			data: this.csvData
		}, { delimiter: ";" });

		this.platform.ready().then(() => {
	
		  const fileTransfer: TransferObject = this.transfer.create();
			  
		  if(this.platform.is('android')) {
			  
			console.log(cordova.file.dataDirectory);
			  
			  var blob = new Blob([csv]);
	
			const csvLocation = `${cordova.file.dataDirectory}${blob}`;
			
			fileTransfer.download(csvLocation, this.storageDirectory + "dallmannCSV").then((entry) => {
	
				const alertSuccess = this.alertCtrl.create({
				  title: `Download OK!`,
				  subTitle: `data saved: ${entry.toURL()}`,
				  buttons: ['Ok']
				});
		
				alertSuccess.present();
		
			  }, (error) => {
		
				const alertFailure = this.alertCtrl.create({
				  title: `Download failed!`,
				  subTitle: `Download failed. Fehlercode: ${error.code}`,
				  buttons: ['Ok']
				});
		
				alertFailure.present();
		
			  });
		  } else {
			console.log("browser");

			var blob = new Blob([csv]);
			var a = window.document.createElement("a");
			a.href = window.URL.createObjectURL(blob);
			a.download = moment().format('LLL') + ".csv";
			document.body.appendChild(a);
			a.click();
			document.body.removeChild(a);
			this.showToast("saved successfully");
		  }`

fileTransfer needs to know where the CSV is located so it can be found.

**Comment by pokoli** [comment]
I'm closing this issue as I understand that it's working correctly.
