### ISSUE TITLE
IE 11 Unable to get property 'readable' of undefined or null reference

### ISSUE THREAD

**Issue by kidasov** [mholt/PapaParse#443]
I have a code:

       `const csvToJson = file => new Promise((complete, error) =>
            Papa.parse(file, { skipEmptyLines: true, complete, error }));

        csvToJson(file).then(({ data }) => {
           // some code to use data
        }).catch(error => {
            // some code to show error
        });`
I debugged Papa.parse call. Inside the function there is a field input, that is undefined when the parser tries to execute this line.

`
        else if (_input.readable === true && isFunction(_input.read) && isFunction(_input.on))
`
 
This error happens only in IE-11. Any help will be highly appreciated.

**Comment by pokoli** [comment]
The input you are posting is the file to be parsed. So the problem is that you are trying to parse an undefined file. 

You should fix your code to pass a proper readable element.

**Comment by HenriqueDerosa** [comment]
Does not happen only on IE 11. It's just a wrong implementation, as @pokoli said. 
Thanks, by the way! 🎉
