### ISSUE TITLE
Retain a copy of the documentation in the github wiki so docs are accesible when the papaparse site is down

### ISSUE THREAD

**Issue by chriszrc** [mholt/PapaParse#450]
http://papaparse.com/ 
Is down right now, and I'm in the dark for getting documentation for the library. Would be nice to have a backup copy of the docs in the github wiki-

**Comment by pokoli** [comment]
Hi @chriszrc 
The website is hosted on gh-pages, so if github goes down, probably gh-pages also. 
I see the website it's up now. 

If you want to have a local copy, you can clone the gh-pages branch of this repository. 

Hope it helps.

**Comment by chriszrc** [comment]
Hi, 
Thank you, it's still down here (NY, USA), but that's great, thank you, I didn't realize the site was using gh-pages, maybe a note about that somewhere in the readme.md could be helpful-

**Comment by pokoli** [comment]
I added a note on readme on https://github.com/mholt/PapaParse/commit/1faa87409acafd207d847e19e33410238390deb1. Thanks for the sugestion.

**Comment by mholt** [comment]
It's working here for me. Should be redirecting to `http://www.papaparse.com`. (There is an experimental transition to HTTPS happening.)

**Comment by drekuru** [comment]
papaparse down right now, any way to find out when it will be up or how long it's been down?

**Comment by pokoli** [comment]
@drekuru the website is running now.
If you have issues you can read the documentation from [the docs folder on the source repository. ](https://github.com/mholt/PapaParse/tree/master/docs)
