### ISSUE TITLE
where is the documents?

### ISSUE THREAD

**Issue by zjsxwc** [mholt/PapaParse#451]
because of the Chinese GFW, i cannot reach the site `http://papaparse.com/docs`.
is there other ways to get the documents? 
could you put the documents as the `doc` fold in the repository?

**Comment by pokoli** [comment]
As explained on the [Readme](https://github.com/mholt/PapaParse/blob/master/README.md#homepage--demo), the docs are on the gh-pages branch of this repository. 

You can clone it to have it available locally.

**Comment by mholt** [comment]
@pokoli There were some DNS hiccups this weekend with the domain name, should be resolved now.

**Comment by pokoli** [comment]
@mholt Thanks for the explanation. As a side-effect we improved the project by explaining where the webiste is hosted.
