### ISSUE TITLE
" right after , and space just before the new line does not parse the csv very well..

### ISSUE THREAD

**Issue by smitshah91** [mholt/PapaParse#452]
My application accepts a csv string from the user. Recently I found out that if there is a quote right after delimiter and space at the end of the line, papaparser does not parse it very well.

**Input**

_ABC, 12345, XML,"true"_ 
DEF, 1235, XML,"false"
_QWE, 4567, JSON,"true"_ 
YUI, 890, XML,"false"
DFG, 123245, XML,"true"

_Italics line have the space at the end_

**Output**

![image](https://user-images.githubusercontent.com/7065145/35657117-a2c7682e-06af-11e8-8180-8b0918c2ae1f.png)

I have seen an issue already reported where " right after , does not parse well but works for me if I do not have space at the end.

**Comment by pokoli** [comment]
Hi @smitshah91, 

I can confirm that the issue exists. For me the problem is on https://github.com/mholt/PapaParse/blob/master/papaparse.js#L1299 which only searches de newline right after the last quote. 

I think we can use your example as test case, and provide a fix for it on a PR.

**Comment by smitshah91** [comment]
I have submitted a PR #453 . Solves the issue mentioned above. not sure about rest of the tests. I will appreciate an update on this.

**Comment by smitshah91** [comment]
PR #454
