### ISSUE TITLE
Setting Chunk Size

### ISSUE THREAD

**Issue by idibidiart** [mholt/PapaParse#456]
Hi,

Chunk size seems to be set to 50 rows. How do I configure that?

**Comment by pokoli** [comment]
We have several configurable properties related to chunk size: 

https://www.papaparse.com/docs#extras

**Comment by ddgflorida** [comment]
Did not see anything to limit # of rows passed as results.data. Would like to be able to set maxChunkRows = 50 so results.data.length would always <= 50

**Comment by KrishnaPG** [comment]
Looking for similar option to limit the number of rows in a chunk. Wondering if there is any solution for it?
