### ISSUE TITLE
Unable to parse files with \n and \r\n

### ISSUE THREAD

**Issue by akiross** [mholt/PapaParse#457]
I am having a little issue with PapaParse when parsing a file that contains newlines in fields. In particular, the file has `\r\n` as line separator, but inside fields there are `\n` as new lines.

When I load such files, PapaParse recognizes `\n` as newline delimiter instead of `\r\n`, so the entire file is read in the first row.

An example file follows, base64-encoded (there is BOM at the beginning).

```
77u/Zmlyc3Qtcm93LCJMaW5lICIid2l0aCBxdW90ZWQiIiB0ZXh0CgpGb28gYmFyIGJheiINCnNl
Y29uZC1yb3csInNvbWUgb3RoZXIgIiJxdW90ZWQiIiB0ZXh0IAoKTGluZSBhZnRlciBlbXB0eSIN
Cmxhc3QtZW1wdHktbGluZSw=
```

In particular, when I try parsing the file I get

```
// ff is the file string above
Papa.parse(atob(ff)).data.length // 1
JSON.stringify(Papa.parse(atob(ff)))
"{\"data\":[[\"ï»¿first-row\",\"Line \\\"\\\"with quoted\\\"\\\" text\\n\\nFoo bar baz\\\"\\r\\nsecond-row,\\\"some other \\\"\\\"quoted\\\"\\\" text \\n\\nLine after empty\\\"\\r\\nlast-empty-line,\"]],\"errors\":[{\"type\":\"Quotes\",\"code\":\"MissingQuotes\",\"message\":\"Quoted field unterminated\",\"row\":0,\"index\":14}],\"meta\":{\"delimiter\":\",\",\"linebreak\":\"\\n\",\"aborted\":false,\"truncated\":false,\"cursor\":131}}"
```

I don't know what delimiters are used inside fields and between records, so I am unable to specify the `newline` option when parsing. As a reference, LibreOffice is parsing the above file correctly.

Am I missing some option or is this a bug?
Thanks!

**Comment by pokoli** [comment]
have you tryied using \r\n as separator on config file?

**Comment by pokoli** [comment]
I'm closing the issue as I understand it has been already solved. Reopen if you don't agree

**Comment by akiross** [comment]
Sorry for this late answer. No, I don't think issue is solved: as I said, I am unable to determine the newlines used inside the text, so I am not sure if only `\n` are used or `\r\n` appears both in text and as file line separator.

Since fields with newlines are quoted, I expect PapaParse to have higher precedence for them than for newlines to determine when a line is ended. In other words:

    "foo","bar","baz
    qux"
    "one","two","three"

should be parsed correctly independently on the line terminator used. This is not the case as far as I can tell.

**Comment by pokoli** [comment]
Ok, could you please post the config you are using and a sample file wich contains the line break inside the quotes?

**Comment by akiross** [comment]
I already did provide an example in my original post, is another one required?

Although I did not specify any version: I am using 4.3.0.

**Comment by jasonfutch** [comment]
same issue
