### ISSUE TITLE
Unexpected url with React-Native

### ISSUE THREAD

**Issue by Johnscorps** [mholt/PapaParse#458]
Hi! I am trying to parse a local csv file using Papaparse on React-Native but I keep getting the same error everytime, no matter the path...
`
       let csvUrl = '../assets/gtfs/stops.csv';

        Papa.parse(csvUrl, {
            download: true,
            header: true,
            complete: function (results) {
                console.log(results);
            }

        });
`

![image](https://user-images.githubusercontent.com/18403414/36902279-3960e1d4-1e2a-11e8-91ca-180ac7999b3f.png)

How can I get the data from this file?

**Comment by pokoli** [comment]
For me it seems an issue with server side and not related to papaparse.
