### ISSUE TITLE
Manage escaped quotes 

### ISSUE THREAD

**Issue by marius-wieschollek** [mholt/PapaParse#459]
I am using PapaParse 4.3.7 and i want to import a csv file where the quotes inside a column are escaped with a backslash (`\"`) instead of a double quote (`""`).

The file looks like this:
```csv
"Column 1","Column 2","Column 3","Column 4"
"Text 1","Text in \"Quotes\"","Text 3","Text 4"
```

When i try to import it, the error `"Trailing quote on quoted field is malformed"` is in the result, and the line is converted incorrectly. 

Is there an option to set the escape character for quotes?

**Comment by pokoli** [comment]
For me this should is a missing feature that we probably want to implement. It will be great if you can submit a pull request implementing it.

Probably it's not needed to configure the scape character and always use the blackslash. I don't think anyone is going to use a different charater and if it does we can add support for configuration on the future.

**Comment by marius-wieschollek** [comment]
I added the option `escapeChar` to specify a custom escape character.

**Comment by marius-wieschollek** [comment]
I added the test and made a pull request for the documentation.

Usually the escaped quote character is detected by searching for the next occurrence of the quoteChar and then checking if the next character is the quoteChar and if so skipping both.
When a custom escapeChar is used and the quoteChar is found, i check if the previous character is the escapeChar, not the next one, and if so only the current character is skipped. This should by design already prevent all other occurrences of the escapeChar from being altered.
