### ISSUE TITLE
Changed column position when parsing

### ISSUE THREAD

**Issue by urosgruber** [mholt/PapaParse#46]
While testing some of the test csv files I noticed some strange results. Here is test csv to replicate this.

```
"a1","b2","c1","d1","41","0"
"a2","b2","c2","d2","42","1"
```

In case header is set to false. Normal in this case result is expected and order is preserved.

```
[ [
      "a1",
      "b2",
      "c1",
      "d1",
      "41",
      "0"
], [
      "a2",
      "b2",
      "c2",
      "d2",
      "42",
      "1"
]]
```

If header: true the columns with number values are moved to the begining. 

Actual result:

```
"rows": [ {
        "0": "1",
        "41": "42",
        "a1": "a2",
        "b2": "b2",
        "c1": "c2",
        "d1": "d2"
}]
```

Expected result:

```
"rows": [ {
        "a1": "a2",
        "b2": "b2",
        "c1": "c2",
        "d1": "d2"
        "41": "42",
        "0": "1"
}]
```

Is this related to JavaScript or this is something papa parse is changing. Parameter dynamicTyping does not help in any case.

**Comment by fruske** [comment]
Hi, @mholt  know this is pretty old but i stumbled upon the same issue. So please allow me one comment.

> Specifying a header row with Papa is merely a convenience to access values by field name rather than positional index. In your case, it sounds like the ordering is important, so I would actually disable the header row with Papa, even if you still let your users specify that they have a header row. In the case of a header row, you can still treat the parse output so that the first row is treated as the header, and they will be in order.
> 
> Does that make sense?

The problem with the workaround is that if you set header: false and create your own header based on UI settings then you will not receive any errors anymore like 
"{type: 'FieldMismatch', code: 'TooManyFields', message: 'Too many fields: expected 12 fields but parsed 16', row: 1}"

Or is there any other way to receive that with disabled header functionality?

Thank you for your great work!

**Comment by JackEcuyer** [comment]
Stumbled upon this issue, my fix was to parse with **header:true**, then store **results.meta.fields** as the original column order. When I render the objects, I loop through the stored column order and access row[columnName] of the object.
