### ISSUE TITLE
backslash escape character '\' is not correctly used

### ISSUE THREAD

**Issue by andrevio** [mholt/PapaParse#470]
Suppose your escapeChar is a backslash. Then I'd expect that the following string would be parsed as:

`"cat,in,the\,hat,is,here" --> ["cat", "in", "the\hat", "is", "here"]
`

Note that I am using a single backslash for clarity, while in JavaScript you'd want to use to backslashes. 

`Papa.parse("cat,in,the\\,hat,is,here", {delimiter: ',', escapeChar: '\\'});
`
outputs this
`data: ["cat", "in", "the\", "hat", "is", "here"]`

I tested this right on the papaparse.com website, on the demo page.

![image](https://user-images.githubusercontent.com/15352086/38331738-e2fd4c08-3808-11e8-8cd9-63e1c5243f32.png)

**Comment by mholt** [comment]
Thanks for opening an issue. But the current behavior is correct. The only thing backslashes (should) escape in quoted fields is quotes themselves; nothing else need be escaped.

**Comment by andrevio** [comment]
Thanks for looking into it. So if that's the correct behavior, how do you escape the delimiter character? In my example the delimiter is comma character ','. How would you allow for the comma character to be inside of a single column?

**Comment by mholt** [comment]
Like I said:

> To use a delimiter in your data, you must quote the field.

:)
