### ISSUE TITLE
error callback is only passed error.message instead of full Error object on stream error

### ISSUE THREAD

**Issue by gabegorelick** [mholt/PapaParse#472]
On stream errors, PapaParse only returns `error.message` instead of the full Error object:

https://github.com/mholt/PapaParse/blob/be7e72cfd4baf3c25d8631b5823e1b4ae88364be/papaparse.js#L798-L802

This makes it harder to debug errors since things like stack trace, error code, etc are not present.

**Comment by pokoli** [comment]
A Pull Request to change it from message to error will be very welcome.

**Comment by gabegorelick** [comment]
> A Pull Request to change it from message to error will be very welcome.

Happy to provide one, but that would break the current API. Is that OK?

**Comment by pokoli** [comment]
@gabegorelick no problem to break the current api as we will include it only on the next release. 

It will be great if you can update the docs also. They are on the gh-pages branch of this same repository. Not sure if this is correctly documented but for sure is a good time to review it.
