### ISSUE TITLE
dynamicTyping should use JSON.parse and config should allow custom processing

### ISSUE THREAD

**Issue by efossas** [mholt/PapaParse#487]
I think dynamicTyping should use JSON.parse to convert data to javascript types. It makes the most sense as its based on a standard (rfc7159) and javascript types are what are usable here anyways.

Since some users might need special conversion (such as converting "True"/"False" to boolean or empty strings to null), the config should have the option to accept a function that applies custom processing to the data.

I have already coded these changes and features (view my fork), as well as made doc changes to the gh-pages branch. Please let me know what you think and if you'll accept a PR with these edits. Thanks.

**Comment by efossas** [comment]
I generated csv strings with 100,000 lines and 8 columns, filled with random strings, booleans, arrays, etc.

These are the results I saw in seconds:

Original PapaParse w/ dynamicTypic on: ~0.70
My updates w/ transform function identical to original dynamicTyping: ~0.75
My updates w/ dynamicTyping using JSON.parse: ~10.6
Replacing JSON.parse w/ json_parse in my updates: ~4.1

The json_parse function can be found at:
https://github.com/douglascrockford/JSON-js/blob/master/json_parse.js

Btw, I noticed a bug in my update where objects are converted to [Object]. This isn't the json parsing functions, it happens somewhere else in PapaParse. I'll look into it later.

At a minimum, I think the ability to add a custom transform function should be added. It does nothing to performance when set to false and gives users more control.

As for using json_parse, what do you think? After some thought, I'm leaning toward removing dynamicTyping all together and just adding examples to the docs on different ways to add dynamicTyping functionality using a custom transform function.

**Comment by pokoli** [comment]
I'm closing this issue as it has been fixed by #505
