### ISSUE TITLE
unparse won't accept file path as data object?

### ISSUE THREAD

**Issue by I-keep-trying** [mholt/PapaParse#488]
This seems too straightforward, am I missing something obvious? 

I keep getting "unexpected token . at position 0" because the file path begins with "."

I assumed since using file path in place of literal data is like, a normal thing, I expected this to work: 

```
const Papa = require('papaparse')
const fs = require('fs')
var results = Papa.unparse('./data.json')
fs.writeFile('papa.csv', results, err =>
  console.log('File successfully written!')
)
```

What am I doing wrong?

**Comment by pokoli** [comment]
As explained on our [README](https://github.com/mholt/PapaParse#papa-parse-for-node) the parser expects a Readable Stream on Node. If you pass a string it will try to parse the contents of this string.
