### ISSUE TITLE
continue to parse a growing (such as csv) file?

### ISSUE THREAD

**Issue by mr23** [mholt/PapaParse#49]
Does PapaParse/HTML5 have the capability to continue to stream/step a file that grows over time?
Enhancement request?

**Comment by breznak** [comment]
Thanks @mholt for this link and sorry for the duplicite. I'll try to go this direction to resolve this 

> Parsing local files: Chrome conveniently updates the file size in the File object without having to re-select it in the DOM. This could make parsing a growing file possible by continually reading that metadata and maybe polling every so often to see if it has grown. However, Firefox does not do this. In Firefox, you have to actually choose the file again in the file selector.

**Comment by breznak** [comment]
Actually figuring the solution/workaround is possible, but not easy to implement, would you consider re-opening the issue and creating a correct, unifying and close-to-ideal implementation in your library? 
I have some ideas howto approach here https://github.com/nupic-community/nupic.visualizations/issues/17#issuecomment-163172061

**Comment by mholt** [comment]
No, it's not something I'm interested in implementing myself at this time.
