### ISSUE TITLE
Real time results parsing

### ISSUE THREAD

**Issue by mohssine54** [mholt/PapaParse#492]
Hi, I'm having trouble to use PapaParse to get real time results in a csv file.
the file I'm parsing is getting  updated every 1s, but I'm getting the first downloaded file from the cache.
is there any option to deactivate caching files to the browser.
Thank you.
here is a simple code that I'm using in my AngularJS app : (it's working but using the cached file only)
Papa.parse("path/csv.csv", {
          download: true,
          header: true,
          skipEmptyLines: true,
          complete: function (results) {
            $scope.var = results.data;
          }

**Comment by pokoli** [comment]
I think we should not introduce any behaviour on the library to manage this kind of results. This should be done with care by removing the cache of the file on server side (as already pointed) and calling Papa to reparse the file on an infinite loop.
