### ISSUE TITLE
npm tests are failing

### ISSUE THREAD

**Issue by navinjethani** [mholt/PapaParse#493]
Custom Tests
    - Complete is called with all results if neither step nor chunk is defined
    ✓ Step is called for each row
    ✓ Step is called with the contents of the row
    ✓ Step is called with the last cursor position
    - Step exposes cursor for downloads
    - Step exposes cursor for chunked downloads
    - Step exposes cursor for workers
    - Chunk is called for each chunk
    - Chunk is called with cursor position
    ✓ Chunk functions can pause parsing
    ✓ Chunk functions can resume parsing (506ms)
    ✓ Chunk functions can abort parsing
    - Step exposes indexes for files
    - Step exposes indexes for chunked files
    - Quoted line breaks near chunk boundaries are handled
    ✓ Step functions can abort parsing
    ✓ Complete is called after aborting
    ✓ Step functions can pause parsing
    ✓ Step functions can resume parsing (505ms)
    - Step functions can abort workers
    - beforeFirstChunk manipulates only first chunk
    - First chunk not modified if beforeFirstChunk returns nothing
    - Should not assume we own the worker unless papaworker is in the search string

  162 passing (2s)
  17 pending

> papaparse@4.4.0 test-phantomjs /Users/navinjethani/Downloads/PapaParse-4.4.0
> node tests/test.js --phantomjs

phantomjs terminated with signal SIGSEGV

Also, demo mode files are not loaded

**Comment by pokoli** [comment]
Thanks for reporting, this was failing silently on Travis so we didn't notice.

**Comment by pokoli** [comment]
Probably is something on your side as it's running correctly on my laptop and also on travis. See:
https://travis-ci.org/mholt/PapaParse/jobs/370449086#L798

**Comment by navinjethani** [comment]
I tried on another mac machine & got the same problem.
I got the latest code from github.

If you want me to try out anything else, please let me know.

I want to have local csv files & parse the fields.

In fact, the demo mode files are also NOT working on both the mac machines.

Regards
Navin

**Comment by pokoli** [comment]
I use linux (and travis do so) and everything works as expected. It's should also work on mac. Can anyone else confirm taht it is not working on mac?
