### ISSUE TITLE
Step function arguments

### ISSUE THREAD

**Issue by omeid** [mholt/PapaParse#495]
Hello Matt,

First thanks for the excellent library.

Looking at the docs it is not clear for me that whatever the step function is expected to always receive one or possibly multiple rows as part of the result.

Could you please clarify on that?

Cheers

**Comment by pokoli** [comment]
Hi @omeid,

The step function is called with a object containing the following values:

- data: Array which contains the parsed row
- errors: The produced errors
- metadata: Additional information of the source file with the following properties like delimiter, linebreak and others.

Everything is in this line of code:

https://github.com/mholt/PapaParse/blob/master/papaparse.js#L1485

P.S: We host the documentation on the gh-pages branch of this repository under the doc folder. If you think that something can be improved, feel free to create a PR for it and I will be happy to merge it.

**Comment by pokoli** [comment]
> That  is actually not true, which is what tripped me, result.data seems to be an array of at least one row instead of a single row! (at least with 4.3.7).

Please read carefully. I said: **An array** containing the parsed row

> Cool, but what is results.data supposed to be? or an array of at least one row? or exactly one row?

For me simpler is better so it should be *exactly one row*. If we agree on this and it is implemented I don't mind creating a new major releases to include this API change. 

But you asked about the documentation and that's why I explained the behaviour and I pointed on how to improve the documentation. If the problem is the API then we should probably reopen the issue and create a pull request that implements it.

**Comment by omeid** [comment]
The problem is documentation.

_An array containing the parsed row_ is ambiguous. It could mean that it is **an array** that _contains_ the **parsed row array**; it could also mean that it is the **parsed row array** itself.

Anyways, whichever way it is intended to be, it is better documented along with the `step` function. I have no comments about the design choice, only seeking clarity.

**Comment by pokoli** [comment]
Then feel free to create a pull request improving the documentation. 

The documentation is on the doc folder on the gh-pages branch of this repository.

**Comment by omeid** [comment]
@pokoli What part of _I don't understand what is the intended behavior_ do you want me to create a pull request for?

**Comment by pokoli** [comment]
I will prefer a PR that touches the code and returns the correct value (a single row object, not array), but I don't mind having only a pull request that clarifies the current behaviour on documentation. 

So it's up to you ;)

**Comment by pokoli** [comment]
FYI I created a PR that returns a single row on step function.

**Comment by omeid** [comment]
Excellent! thought I would have been happy with just the docs, a clear API is always better. :)
