### ISSUE TITLE
Is there a way for papaparse to block xls files?

### ISSUE THREAD

**Issue by bautistp** [mholt/PapaParse#501]
Hello,

I'm dealing with an issue while trying to parse and validate files uploaded by user. First our input file element will allow only to select csv and txt files, the issue is that for windows I need to accept 'application/vnd.ms-excel' to allow the user to select csv files, also, some web browsers will pass my filter and user can select any other type of file.

So, my second filter comes when I validate the MIME Type, which in windows, for csv and xsl is the same: 'application/vnd.ms-excel', so I'm forced to accept xsl files. 

I don't want to continue with parsing only for xsl files, the data is a huge byte content and papaparse is returning results from that type of files. Is there a way for papaparse to block those files with stuff that I don't want?

Thanks

**Comment by pokoli** [comment]
Which kind of results is paparse returning from this files? 
Is not returning any type of error which allows to indentify that it's a malformed file?

**Comment by schinckel** [comment]
No, it appears to just parse it and displays garbage characters.

**Comment by bautistp** [comment]
Hi Sergi, sorry for my late response. All right, so the results I'm getting from papaparse are mostly related with Field Mismatch. It says for example, that processed less or more fields than expected in certain rows. 

What I noticed is that for certain fields, it will take them as binary data. I did my tests using .xls and .xlsx files. None of then containing formulas but many different books.

**Comment by pokoli** [comment]
It makes sense to raise a fileld Mismatch as the format of the files is not correct. 

I don't think we can do something more. Probably checking if the file is xls can be done with javascript before passing the file to PapaParse.

**Comment by schinckel** [comment]
My approach was to use `beforeFirstChunk` and sniff the first four bytes of the file.

**Comment by pokoli** [comment]
@schinckel sharing your code snippet will probably help @bautistp  and others which have the same issue.

**Comment by pokoli** [comment]
I'm closing this issue as I think we should not include none of this code as PapaParse. 

Reopen if you don't agree

**Comment by bautistp** [comment]
As mentioned, 'beforeFirstChunk' is my best option, I've been using it to validate some other rules, so I think it's enough for now. Thank you!
