### ISSUE TITLE
CSV gets parsed sometimes, sometimes it doesn't 

### ISSUE THREAD

**Issue by mamtakathar** [mholt/PapaParse#508]
Hello, 

I am trying to parse a CSV to JSON to draw 7-8 charts  on a page using pivotttable.js
While I do that, I can see the all the charts won't load always and realized that the papa.Parse gives an error. 
errors: Array(1)
0:{type: "Delimiter", code: "UndetectableDelimiter", message: "Unable to auto-detect delimiting character; defaulted to ','", row: undefined}

Now, I did research about this error online and updated the Papa parse library to the most recent release and set delimiter:""  . But the error still persists.
The problem is that say, for example, a chart would load once and a second later after I refresh, it wouldn't( and that is when it throws the above-mentioned error)and then again a second later after I refresh, it would load. This is quite inconsistent as it doesn't happen with the same charts every time.  Sometimes all of them load perfectly, sometimes most of them, sometimes just 1/2.

I will be very grateful if I could get help on this.

Thank You, 

Mamta

**Comment by pokoli** [comment]
Sorry but can not help without any steps to reproduce, code sample and anything else.

From my point of view it seems that the error is not releated to paparese, but the csv file not being ready for reading so paparse reads an empty string and thus returns the error. 

I don't think there is nothing to fix on our side so I'm closing the issue. Feel free to re-open it if you don't agree but make sure to include a proper steps to reproduce the issue (a test case will be the best).
