### ISSUE TITLE
At row 119 FieldMismatch TooFewFields Too few fields: expected 5 fields but parsed 1

### ISSUE THREAD

**Issue by GusBeare** [mholt/PapaParse#510]
Hi
I am getting the above in errors but there doesn't seem to be anything wrong with the data.
It seems to be returning this error when it hits the end of the file by default.

The data imported looks fine and it's all there. The headers are handled very well and numbers are correctly parsed. If you see the image below you can see that the last row is correctly imported. I am getting this error when the end of the file is reached.

Am I doing something wrong? 

![a](https://user-images.githubusercontent.com/5166509/40475563-d764a8c0-5f39-11e8-8151-9837d29d6178.jpg)

**Comment by GusBeare** [comment]
hmm.. I just went into the file and cleared empty space at the end up to the last character, re-loaded and the issue went away.  How can I ensure this when the file loads?  I am not using Papaparse to read the file.
Perhaps I should be doing that?

**Comment by GusBeare** [comment]
passing "contents.trim()" into Paparse fixed it for me.

**Comment by pokoli** [comment]
If the last line of the file is all empty you should probably set skipEmptyLines to true on your config to ignore the line and the error should disapear. 

Let me know if that fixes the issue for you.

**Comment by GusBeare** [comment]
Yep, great thanks skipEmptyLines fixed it!

Many thanks for a very nice little tool. Saved me a lot of work.

**Comment by pokoli** [comment]
You are welcome! Happy to save others work.

**Comment by maurobilotti** [comment]
I'm with the same error, but `skipEmptyLines` didn't solve it. The funny thing is that happens after three steps or three chunks using both functions:
![image](https://user-images.githubusercontent.com/4137980/224058223-8cab27eb-5b96-4f52-ba69-87bc59bf3644.png)

The file completely well, the problem isn't there. Any idea on how you solved it?
