### ISSUE TITLE
header: true and force return of arrays instead of an object

### ISSUE THREAD

**Issue by nitrocode** [mholt/PapaParse#512]
I'm working with customer CSV files and I'd like to use their header names so I flip `header: true` but Papaparse will now default each row to return an object instead of an array so I have to guess the column names or convert the object back into an array which doesn't seem efficient.

I can solve if these solutions exist:

* Is there a way to set `header: true` and return arrays instead of objects?
    * This way I can grab the headers at the end.
* Is there a way to skip the first line? e.g. can the `step()` use an index?
    * This way I can skip the first line, make my transformations, and then after it's finished I can grab the header from the first row... I think.
    * I didn't see this in the `row.meta` object

Workaround:

* Parse the entire csv with `header: false`, then parse the first row as the header, then iterate through the rest for transformations.

**Comment by pokoli** [comment]
The column names are returned on `result.meta.fields` which is an array that returns the header name for each parsed column. This should allow you to do anything with the parsed that without any workaround. 

I'm closing this issue as I understand it is already resolved. Feel free to re-open if you don't agree.

**Comment by nitrocode** [comment]
@pokoli the issue is that I want to parse the headers so it's set in `result.meta.fields` but I don't want each row to return an object. I want to force it to still return an array because only 1 field name out of 20 are set in stone and need transformations, and the other 19 need to have their order kept. 

How papaparse is setup, I'd need to set header to true and then convert every row object back into an array which may not preserve the original order of the columns.

**Comment by pokoli** [comment]
As the order of the headers is preserved in `result.meta.fields` you should be able to reconstruct the original row by doing a lop in the fields array and reading the object with the keys.

**Comment by nitrocode** [comment]
@pokoli that still sounds inefficient. Papaparse reads the header, reads the rows and creates an object for every row. Then I take that row within the step function, convert that back into a string using `result.meta.fields`?

It would be easier if this was a configuration param `rowAsString: true` instead of converting the object back into a string.

If no one is willing to make the change, I can put a PR together.

**Comment by pokoli** [comment]
I don't think we need to add a new configuration parameter for each specific use case. The API is pretty clear: 

* An array is returned for each row if no headers is set
* An object is returned for each row if headers is set

If you want an array don't use the headers option an pick the first row as headers.

Everything is on your hands.

**Comment by nitrocode** [comment]
Perfect. Thank you!
