### ISSUE TITLE
Set a maximum number of rows and number of columns

### ISSUE THREAD

**Issue by nitrocode** [mholt/PapaParse#513]
I'd like to set a maximum number of rows and columns so if I set max rows to 1,000,000 and max cols to 10, a csv file uploaded with 10,000,000 rows and 22 columns, would have that files excess ignored or return an error. 

Is this possible right now?

**Comment by pokoli** [comment]
There is no option for the number of columns and I do no think it makes sense. 

For the number of rows you cn use the preview attribute which will only return up to the number of rows specified. 

Could you explain why you need such limits?

**Comment by pokoli** [comment]
I'm closing this issue as we do not have to include new functionalities to support if. 

If you don't agree please provide an explanation why you need such feature.

**Comment by nitrocode** [comment]
@pokoli why would you remove my comments on this?

**Comment by hsul-git** [comment]
I need the same feature because we process large datasets, which can take rly long to process. Would like to see this feature for the react version.
