### ISSUE TITLE
When line ends with quoted field and first field of next line empty, parsing fails

### ISSUE THREAD

**Issue by baerrach** [mholt/PapaParse#514]
When line ends with quoted field and first field of next line empty, parsing fails because the quoting algorithm gobbles up the newline moving to the next delimiter.

I've got a test case and a solution I'll include in a PR shortly.

input: 'a,b,c\n,e,f\n,"h","i"\n,"k","l"'
expected.data: [['a', 'b', 'c'], ['', 'e', 'f'], ['', 'h', 'i'], ['', 'k', 'l']]
actual data: [['a', 'b', 'c'], ['', 'e', 'f'], ['', 'h', 'i', 'k', 'l']]

**Comment by scholtzm** [comment]
Could we get a patch release with this fix?

**Comment by pokoli** [comment]
@scholtzm I've just published 4.5.1 which contains this fix.
