### ISSUE TITLE
Transformations in step function

### ISSUE THREAD

**Issue by nitrocode** [mholt/PapaParse#520]
I'm looking for a way to transform rows on the fly for large files without having to push to an array. I'm doing this now for a million row file and it's very slow.

Any tips on how to make the `step` function smoother? I tried modifying the row's data and returning it and that didn't seem to work.

    var csv = $("input[type=file]").parse({
      config: {
        delimiter: '',
        preview: maxRows,
        step: function(row) {
          newRow = row.data[0].slice(0, maxCols);
          // row.data[0] = row.data[0].slice(0, maxCols);
          // return row.data[0];
          this.contents.push(newRow);
          // return newRow;
        },
        complete: function(results, file) {
          // upload file
        }
      }
    });

Seems like if I step through each row, the complete function doesn't have knowledge of the results unless I push the transformed results to contents.

**Comment by pokoli** [comment]
On latest version you can use the `transform` option to specify a function that will be called for each column of your csv file. See #516
