### ISSUE TITLE
Incorrect trimHeaders option in documentation

### ISSUE THREAD

**Issue by CookPete** [mholt/PapaParse#522]
Just a heads up. The `trimHeader` option at https://www.papaparse.com/docs#config should actually be `trimHeaders` according to the codebase:

https://github.com/mholt/PapaParse/blob/0b3f29c3535e28519d58d04e8b8092e499abdd23/papaparse.js#L1113-L1115

**Comment by pokoli** [comment]
I have fixed it. Thanks for reporting!
