### ISSUE TITLE
Failed to execute 'postMessage' on 'Worker'

### ISSUE THREAD

**Issue by dornstein** [mholt/PapaParse#525]
I've been using papa parse successfully for quite a while.  If have found cases where it's necessary to parse really big (70MB) CSV file and while that's running the browser UI locks up.  So I thought I'd try 'worker: true'.  I added a complete: call back.  But when it runs I get the error: ***Failed to execute 'postMessage' on 'Worker'*** 

I'm running on Chrome 67.0.3396.87.

What am I missing?  The docs suggested all I needed was to say "worker: true"...

**Comment by suavelizard** [comment]
This is happening in electron.

`
Error Parsing File
{
    "stack": "Error: Failed to execute 'postMessage' on 'Worker': function () {\n if (this.autoClose) {\n this.destroy();\n }\n } could not be cloned.\n at Object.CsvToJson [as parse] ([REMOVED]\\node_modules\\papaparse\\papaparse.js:225:6)\n at eval (webpack-internal:///./src/renderer/translators/shared.js:41:64)\n at new Promise ()\n at new F (webpack-internal:///./node_modules/core-js/library/modules/_export.js:36:28)\n at _callee$ (webpack-internal:///./src/renderer/translators/shared.js:40:20)\n at tryCatch (webpack-internal:///./node_modules/regenerator-runtime/runtime.js:62:40)\n at Generator.invoke [as _invoke] (webpack-internal:///./node_modules/regenerator-runtime/runtime.js:296:22)\n at Generator.prototype.(anonymous function) [as next] (webpack-internal:///./node_modules/regenerator-runtime/runtime.js:114:21)\n at step (webpack-internal:///./node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)\n at eval (webpack-internal:///./node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14)"
}`

**Comment by pokoli** [comment]
Fixed by #599
