### ISSUE TITLE
Align number of columns

### ISSUE THREAD

**Issue by pikotrek** [mholt/PapaParse#527]
Hi.

Firstly. I love PapaParse :)
Secondly. I tried to use Papa parser in Google Scripts in order to import csv data into the Google Sheets. It works perfectly, however Google Sheets have problems with importing rows of various lengths. I think that adding the possibility of generating rows with the same size would be very useful.

**Comment by pokoli** [comment]
Could you elaborate which problems does Google have? 

If I understand correctly what you need to generate is a file is fixed column size which for me is out of the scope of PapaParse

**Comment by pokoli** [comment]
I'm closing this issue as no further explanation have been provided.

Reopen with some explanation if you do not agree
