### ISSUE TITLE
InvalidQuotes error only when parsing file directly

### ISSUE THREAD

**Issue by kspearrin** [mholt/PapaParse#535]
Please see the attached example CSV file. Using this local file on https://www.papaparse.com/demo produces a "InvalidQuotes" error. However, if I open the file in a text editor and simply copy/paste the same exact data directly to the demo it works without error.

[upm.zip](https://github.com/mholt/PapaParse/files/2182902/upm.zip)

File data

```
Google,googleuser,0UI9eH4$,google.com,"This is a note

Line1
line2"
Yahoo,,k7F3EKZ>,,
GitHub,githubuser,~UAWk2DO,http://github.com,
```

**Comment by dboskovic** [comment]
I think this is the same issue as https://github.com/mholt/PapaParse/issues/252
