### ISSUE TITLE
quoted fields not parsed when they contain escaped quotes

### ISSUE THREAD

**Issue by conceptualspace** [mholt/PapaParse#537]
Triple quotes on a field seem to be a valid case but they throw an error. For example, take the following input:

Column 1, "To be or not to be, that is the question"
Column 2, "To thine own self, be true"

We want to keep the quotes in the second field, so they need to be escaped. But we also want to enclose the second field in quotes as well, since it contains commas.

The result is:

Column 1, """To be or not to be, that is the question"""
Column 2, """To thine own self, be true"""

But then Papa throws an error:
```
code: "InvalidQuotes"
message: "Trailing quote on quoted field is malformed"

code: "MissingQuotes"
message: "Quoted field unterminated"
```

PapaParse v4.5.0

**Comment by dboskovic** [comment]
@monkeydzeke this is another one we should look at. XLS escapes quotes by doubling them.

**Comment by MonkeyDZeke** [comment]
Using the Papaparse demo doesn't replicate this error with this input:

```Column 1,Column 2
"""To be or not to be, that is the question""","""To thine own self, be true"""```

It outputs with the escaped quotes as expected. Could you clarify what exactly you are using that is creating this error?

**Comment by conceptualspace** [comment]
hmm i was using the demo but i can confirm it now works as expected. perhaps i pasted some errant trailing character; not sure what else would explain the discrepancy. thanks, closing.

**Comment by MonkeyDZeke** [comment]
From some further investigations, I think that you might have been including a space before the quoted fields, and according to the test specs, `"The quotes must be immediately adjacent to the delimiter to indicate a quoted field"`. Trailing spaces are fine, but not otherwise.

No worries!

**Comment by tturnerswdev33** [comment]
> 

Where are the "test specs" that specify that "quotes must be immediately adjacent to the delimiter"??  I am having an issue with pp parsing a header that has each column in double quotes... giving InvalidQuotes error and I'm having trouble figuring out why...
