### ISSUE TITLE
Add checkEncoding function

### ISSUE THREAD

**Issue by 11341684** [mholt/PapaParse#538]
I am very sorry to bother you, I hope you can add a custom detection code function.
For example, add the following script to the first paragraph of the _chunkLoaded function.

`if(this._config.checkEncoding&&!this._config.checkEncoding.call(this._config,event.target.result,bindFunction(this._readChunk, this))){
			   return false
			}`

When you call, you can customize the function to judge the encoding.
> 
     encoding:'GBK',
            header:true,
            skipEmptyLines:true,
            checkEncoding(txt,next){
                parseNumber++;
                if(parseNumber>1){
                    //parseError('文件编码不是GBK,也不是UTF-8,或者是此文件被加密了,这会让解析出现乱码,从而无法正常运行,请更改文件编码，或者使用普通导入！');
                    return false;
                }
                if(!/[序订]/.test(txt.slice(0,50))){
                    this.encoding='UTF-8';
                    return next()&&0
                }
                return true
            }
 
Looking forward to the author's more perfect implementation

**Comment by pokoli** [comment]
Why not using the preview functionality to pick the first X rows with and encoding and check if it is correct? 

I'm not sure if we should bloat the library with encoding detection functions.

**Comment by dboskovic** [comment]
Agree - if the preview works for this problem it makes the most sense.

**Comment by pokoli** [comment]
I'm closing this in favor of the preview functionality. Re-open if you don't agree
