### ISSUE TITLE
how to unparse complex array of objects ?

### ISSUE THREAD

**Issue by acharotariya** [mholt/PapaParse#539]
i have productdata array of object that look like below,

 var productdata = [
                {
                  car: { make: 'Audi', model: 'A3' },
                  price: 40000,
                  color: 'blue'
                },
                {
                  car: { make: 'BMW', model: 'F20' },
                  price: 35000,
                  color: 'black'
                },
                {
                  car: { make: 'Porsche', model: '9PA AF1' },
                  price: 60000,
                  color: 'green'
                }
              ]

when i'm unparse using 

var csv = Papa.unparse(productdata);
output:
--------
car,price,color
[object Object],40000,blue
[object Object],35000,black
[object Object],60000,green

i want unparse data that is inside object.how to do ??

**Comment by dboskovic** [comment]
Since CSV doesn't allow for any depth, I'd recommend running https://github.com/hughsk/flat on your object first and *then* running `Papa.unparse()`
