### ISSUE TITLE
how to parse row field string to array or object ?

### ISSUE THREAD

**Issue by YouSour** [mholt/PapaParse#541]
hi , i have data structure like below : 
[
{id: "1", name: "jhon", gender: "m", options: "1,3"},
{id: "2", name: "mar", gender: "m", options: "13,8"},
{id: "3", name: "lina", gender: "f", options: "1,6"} ]

what i want the options field convert to array or object : 
[
{id: "1", name: "jhon", gender: "m", options: [1,3]},
{id: "2", name: "mar", gender: "m", options: [13,8]},
{id: "3", name: "lina", gender: "f", options: [1,6]} ]

any idea ?

**Comment by pokoli** [comment]
PapaParse is limited to only parsing the data and it is not designed to transform the data meanwhile. You should parse the data as and use a custom code to transform the data after the parser has endend.
