### ISSUE TITLE
trimHeaders not works

### ISSUE THREAD

**Issue by ricaragao** [mholt/PapaParse#547]
Hi, 

I am using PapaParse 4.5.1 and trimHeaders: true not works. Can you check, please?

Thanks

**Comment by pokoli** [comment]
Could you please explain what is not working and provide an example?

**Comment by ricaragao** [comment]
I'm sorry, I am using v4.1.4.

I had a csv with headers with space on left. And I put trimHeaders: true , and result space was there yet.

**Comment by pokoli** [comment]
I'm closing this as no reply in 4 months, and the trim headers has been deprecated in mater branch. 

If the issue is already present on 4.6.2, please reopen with a test case that we can include on a new bug fix version.
