### ISSUE TITLE
Either skipEmptyLines is broken--or is not used for unparse()

### ISSUE THREAD

**Issue by bean5** [mholt/PapaParse#553]
**Expected**
Calling unparse with skipEmptyLines: 'greedy' results in no basically empty rows.

**Actual**
Calling unparse with skipEmptyLines: 'greedy' (or true) will still have rows with no data (except commas). 

**Sample Code**
```
let csv = Papa.unparse(
      {
        fields: ['a', 'b'],
        data: [[null, ' '], [], ['1', '2']]
      },
      {
        skipEmptyLines: 'greedy',
        worker: true
      }
 );
console.log(csv);
```

**Discussion**
Am I misunderstanding something or not setting the config correctly? Is `skipEmptyLines` only for parse, perhaps? In the mean time, I suppose I can do some edge checking so I don't pass "empty" rows to unparse.... :(

Keep up the good work! I love the project. Glad I found it. Fast, clean, modern, reliable.

**Comment by dboskovic** [comment]
@MonkeyDZeke ^

**Comment by MonkeyDZeke** [comment]
Currently skipEmptyLines is only used on parse, not unparse. We should either update the documentation to be more clear about that or add support for unparse. I prefer the latter, since this is a totally valid use-case. I'll start on a PR to create support for that, unless someone belays that. :slightly_smiling_face:

**Comment by dboskovic** [comment]
Yeah. Let’s use it on unparse. There’s no reason why not since the config is passed separately to unparse. So I don’t see any incompatibilities.

**Comment by MonkeyDZeke** [comment]
Definitely makes sense, yeah. Will do!

**Comment by bean5** [comment]
I re-ran the sample code provided above. It still outputted rows that had nothing by whitespace. Am I passing the config the wrong way?

**Comment by MonkeyDZeke** [comment]
Hmmm :thinking: I ran this test-case:

```
{
		description: "Returns without rows with no content when skipEmptyLines is 'greedy' and using a header",
		input: [{a: null, b: ' '}, {a: '1', b: '2'}],
		config: {skipEmptyLines: 'greedy', header: true},
		expected: 'a,b\r\n1,2'
	}
```
And it failed with: `expected 'a,b\r\n," "\r\n1,2' to equal 'a,b\r\n1,2'`

So it looks like it is still struggling with handling it when there's a header. I'll see what I can do. Thanks for letting us know!

**Comment by bean5** [comment]
Glad you have test cases. Plan to reopen this case or open another?

**Comment by pokoli** [comment]
I think it makes sense to open a new issue and upload a new PR that fixes it.
