### ISSUE TITLE
Release 4.6.0 zip contains wrong file

### ISSUE THREAD

**Issue by bean5** [mholt/PapaParse#556]
At https://github.com/mholt/PapaParse/releases/tag/4.6.0 , js/papaparse.js appears to have the wrong contents while js/papaparse.min.js seems to have the expected changes.

Not a big deal (in this case), but may indicate that the release process is slightly buggy.

**Comment by pokoli** [comment]
This is probably my fault as the release process is currently manually.

Probably it's worth to include a script into the repository

**Comment by pokoli** [comment]
Should be fixed on 4.6.1
