### ISSUE TITLE
Could I change default column name?

### ISSUE THREAD

**Issue by thearabbit** [mholt/PapaParse#557]
```
Col1, Col2, Col3
1,1,1
2,2,2
```
Would like to change column name
```
{ColA: 1, ColB: 1, ColC: 1}
```

**Comment by dboskovic** [comment]
This PR would provide a solution for this issue. https://github.com/mholt/PapaParse/pull/543

**Comment by pokoli** [comment]
I'm closing this as the PR has ben merged to master
