### ISSUE TITLE
Published documentation is not for latest release (4.5)

### ISSUE THREAD

**Issue by Serik0** [mholt/PapaParse#561]
Hello!

Now I see that published documentation ( https://www.papaparse.com/docs ) - is not for 4.5, but seems to be for master code.
For example, config field `skipEmptyLines` doesn't support value `"greedy"` in 4.5, but it is mentioned in published docs.

I think either published documentation should match published main download or 2 versions of documentation should be available - for latest release and for "master" branch.

**Comment by dboskovic** [comment]
Latest release is actually 4.6 - the version number on the home page is wrong. https://www.npmjs.com/package/papaparse

**Comment by pokoli** [comment]
Thanks for reporting. I've updated the docs version number.

**Comment by Serik0** [comment]
Thanks! Now version and download link point to 4.6.
