### ISSUE TITLE
Performance issues with @^4.4

### ISSUE THREAD

**Issue by MonkeyDZeke** [mholt/PapaParse#562]
Parsing times on some files jumped from 6.19 ms to 44538.19 ms. I still haven't narrowed down exactly what is causing it or what triggers the performance drop.

**Comment by pokoli** [comment]
Is the performance issue also present on latest version?

**Comment by MonkeyDZeke** [comment]
Yes, it was originally noticed on 4.6, but it goes back to 4.4.

**Comment by pokoli** [comment]
could you provide a test case to reproduce it? If so it will be easly to determine which changeset introduced the issue by running a git bisect

**Comment by MonkeyDZeke** [comment]
Turns out that the `string-trim` polyfill that babel-polyfill was using in our build for some reason wasn't playing nicely with something in the upgrade to 4.4 in Papaparse. When tested without babel it ran lickety-split as expected. We're adjusting our babel build in our project now. I'm still curious about why the two wouldn't play nicely together, though. I hope it's not a big enough problem that anyone other than us would run into it.

**Comment by MonkeyDZeke** [comment]
This issue should be able to be closed.

**Comment by FloPrey** [comment]
@MonkeyDZeke Have you found a solution for this?

We have the same issue as described in https://github.com/mholt/PapaParse/issues/624 and the only possible fix is downgrading to version 4.3.7 otherwise some of our CSV take a huge amount of time to parse.

**Comment by MonkeyDZeke** [comment]
I'd have to dig back into our codebase again to remind myself exactly how we did it. But the basic gist of it is that the `string-trim` polyfill in babel-polyfill is terrible, and so you basically need to set up your babel configuration in a way that excludes that specific polyfill. How you do that is unique to your own project, though.
