### ISSUE TITLE
Worker failed with webpack 3

### ISSUE THREAD

**Issue by tamnvt** [mholt/PapaParse#566]
i got this error when using `{worker: true}` for configuration
![screen shot 2018-09-08 at 12 04 43 pm](https://user-images.githubusercontent.com/10257173/45250559-b3867a80-b35f-11e8-99ff-5630a6f3d8f8.png)

Can refer to source code in file node_modules/webpack/lib/JsonpMainTemplatePlugin.js, line 129
i am using 
webpack 3.8.1
papaparse: 4.6.0
typescript: 2.9.1

**Comment by pokoli** [comment]
Could you please post the full stack trace? Which line is causing the error?

From your screenshoot is seems that the erros is that window is not defined, but this is already [managed by PapaParse](https://github.com/mholt/PapaParse/blob/master/papaparse.js#L31)

**Comment by tamnvt** [comment]
Hi sorry for late response. Actually i got the answer after posted this. 

First, as u can see in my attached image. worker execution failed because this is not worker environment, this is browser environment. When i import papaparse in my component, all papaparsejs code will be wrapped by webpack module. so the worker url is http://localhost:3006/static/js/bundle.js?papaworker
-> This is totally wrong with import statement

So to fix this:
- Use webpack to serve papaparsejs as static file, so do not wrap it with webpack module.
- Then change papa SCRIPT_PATH: 
Papa.SCRIPT_PATH = "http://localhost:3006/static/js/papaparse.js"
Papa will look up this path to get service worker as I read in Papaparse source code 
But if u are using TypeScript, need to manually edit node_modules/@types/papaparse/index.d.ts line 53: 
export const SCRIPT_PATH: string;
to export let SCRIPT_PATH: string;

And the error is gone.

**Comment by pokoli** [comment]
@tamnvt Here you can find the [Papaparse TypeScript definitions](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/papaparse)

It will be great if you can create a Pull Request on this github repository to change the SCRIPT_PATH definition from a constant to a variable.

P.S: I'm closing this isseu as I understand there is nothing to do from our part. Thanks for posting the solution!
