### ISSUE TITLE
mocha-phantomjs is deprecated

### ISSUE THREAD

**Issue by MonkeyDZeke** [mholt/PapaParse#571]
[Mocha-phantomjs is deprecated](https://github.com/nathanboktae/mocha-phantomjs) and it is recommended to upgrade to something like [mocha-chrome](https://github.com/shellscape/mocha-chrome).

I noticed this when I did an npm audit and found out that it's insecure. This is already documented [on the mocha-phantomjs repo](https://github.com/nathanboktae/mocha-phantomjs/issues/262).

**Comment by pokoli** [comment]
Fixed by #581
