### ISSUE TITLE
Request: parsing should allow transforming and validating rows

### ISSUE THREAD

**Issue by MarZab** [mholt/PapaParse#572]
I would like to transform/check the value based on other data in the row and return an error.

I imagine sometihng like this:

```js
Papa.parse(data, {
  header: true,
  transform(value, field, { addError, row, rowCounter }) {
    if (field === 'name' and value === 'Fred' and row['position'] ==='calldesk') {
      addError("FancyError", "NameNotFancy", "Expected the name to have a certain something", rowCounter);
    }
    return value;
  }
});
```

<img width="407" alt="screen shot 2018-09-22 at 14 48 40" src="https://user-images.githubusercontent.com/1311249/45917403-9df07500-be76-11e8-9ff8-4694b7947205.png">

**Comment by pokoli** [comment]
@MarZab The goal of PapaParse is to parse CSV files but not validate it's data. So you should parse the results using PapaParse and then add your custom validations on the parsed data.
