### ISSUE TITLE
How to get data from csv remote files using papaparse

### ISSUE THREAD

**Issue by hengsoheak** [mholt/PapaParse#573]
I separated server to store my assets and everything based on my API now I'm going to create the import feature to import csv from another server to my back end server due to this process I searching and testing a lot of NPM. The last one I tried with `papaparse` to get all row of my remote csv files then insert to my database.

**My Environment:** 
node -v: v8.9.2
npm -v: 5.5.1
tsc -v: Version 1.0.3.0
"papaparse": "^4.6.0",

**Code:**

`@Description("`Import")
                 @POST("/v1/import")
                @Authorization
                 @CheckPermission(Action.Read)
                  async import(
                  @ContextRequest request: express.Request,
                 @Param() filePath: string
        ): Promise<any> {
            const urls = filePath;
            const csv = papaparse.parse(urls, {
                delimiter: ",", 
                newline: "\r\n", 
                quoteChar: '""',
                header: false,
                dynamicTyping: false,
                preview: 0,
                encoding: "",
                worker: false,
                comments: false,
                step: undefined,
                complete: function (data) {
                    console.log(data);
                },
                error: (error) => {
                    console.log(error);
                },
                download: false,
                skipEmptyLines: false,
                chunk: (chunk) => {
                    console.log(chunk);
                },
                fastMode: undefined,
                beforeFirstChunk: undefined,
                withCredentials: undefined
            });
              return csv;
           }`

**Console Result**
`{ data: [ [ 'https://akhura.com/test.csv' ] ],
[Node]   errors: [],
[Node]   meta:
[Node]    { delimiter: ',',
[Node]      linebreak: '\r\n',
[Node]      aborted: false,
[Node]      truncated: false,
[Node]      cursor: 27 } }`

**Comment by pokoli** [comment]
You should add the downaload: 'true', setting on the config file in order to download the file from an url. See the [parse remote file section of our documentation](https://www.papaparse.com/docs)

**Comment by hengsoheak** [comment]
if I enable it, it will show me below error. and is it possible if we don't download file 
`{
    "statusCode": 500,
    "error": "INTERNAL_SERVER_ERROR",
    "message": "Uncaught Exception: XMLHttpRequest is not defined"
}`

**Comment by hengsoheak** [comment]
Onemore thing I think it should support with backend process?

**Comment by pokoli** [comment]
Sorry, I missread your post, the download only works when running on browser, if you are running on node please have a look at #440
