### ISSUE TITLE
Larger Documentation Use Case Headings?

### ISSUE THREAD

**Issue by oleersoy** [mholt/PapaParse#574]
I was reading through the documentation and got to the JQuery case, and at that point it was a little confusing.  I did not see the JQuery heading because it's written in small light gray color, and if I had seen that right away, it would have been a lot less confusing ...

It's still seems a little "Indirect" to go directly from `Papa.parse` to $ ... I'm assuming some JQuery plugin or something is needed to complete the setup?

**Comment by pokoli** [comment]
Hi @oleersoy, 

Our docs are in the docs folder in this repository and are written using html. Any patch to improve it's format is welcome!

**Comment by oleersoy** [comment]
I just created a pull request.  I changed this rule as follows:

```
h5, footer h4 {
    font-size: 20px;
    letter-spacing: 2px;
    text-transform: uppercase;
    color: #242627;
    line-height: 1em;
    margin: 50px auto;
}
```

**Comment by oleersoy** [comment]
Also my impression is that most people these days use either Angular / React / Vue / Polymer and ideally there would be an integrations page for framework / utility integration that the JQuery example could live in.  WDYT?

Medium / Gitbook might be another option.  I wrote a blog post on [Typescript integration here](https://medium.com/@ole.ersoy/using-papaparse-with-typescript-b8dea81bf602)

**Comment by pokoli** [comment]
@oleersoy I will be happy to include documentation on how to use papaparse with most know front-end frameworks. 

I have a doubt about the TypeScript integration. Does the process of using paparse with typescript difer for any other javascript library? I will prefer to add a link to the oficial typescript documentation where it explains how to use with a existing framework than copying a custom descrption. Of course, any PR including this is also very welcome
