### ISSUE TITLE
Papaparse does not work with this test data

### ISSUE THREAD

**Issue by sarawut-p** [mholt/PapaParse#578]
[not_work.csv.zip](https://github.com/mholt/PapaParse/files/2437113/not_work.csv.zip)
Papaparse does not work with this test data

**Comment by pokoli** [comment]
Could you explain what does not work?
Which configuration options are you using to parse the file?

**Comment by sarawut-p** [comment]
It does not parse the line break on second line correctly.
Default configuration.
It seems like the root cause is that line break are in inconsistent format across the file though.

**Comment by dboskovic** [comment]
If there's mixed line endings, then Papaparse will definitely have issues. That sounds like a corrupted file and isn't something I think we should add any support for.
