### ISSUE TITLE
better if raw row data supplied in step callback 

### ISSUE THREAD

**Issue by xxjapp** [mholt/PapaParse#579]
When select or filter some rows of a csv file according to some conditions, this feature will be convenient

**Comment by pokoli** [comment]
Could you explain what are you trying to achieve?

Please note that PapaParse goal is to only parse the CSV file, if you need to filter the parsed results you should do it on the result array but not before reading the data.

**Comment by pokoli** [comment]
You should use _Papa.parse_ to read records as array, filter them and then use _Papa.Unpars_e to write the second file. 

If you are on Node you should be able to pipe the results between all calls so you do not fill the memory.
