### ISSUE TITLE
[Feature Request] Symmetric string and File interface?

### ISSUE THREAD

**Issue by oleersoy** [mholt/PapaParse#583]
I'm reading through the documentation again and just wanted to say nice update to the site!  Also curious whether something like this exists or perhaps there's room for it (Pseudo Typescript):
```
var results = Papa.parse(csvString);
var results = Papa.parse(file:File);
```
Seems like it would be good to have a symmetric approach to parsing regardless of whether it is a file or a string?

IIUC if it's a file we have to pass in a callback function, but if it's a string we get the results returned synchronously?

**Comment by pokoli** [comment]
[Parsing files is already supported ](https://github.com/mholt/PapaParse/blob/master/papaparse.js#L244)

**Comment by davidgilbertson** [comment]
@pokoli when you say "Parsing files is already supported" do you mean
a) It is possible to parse files? OR
b) `Papa.parse(file: File)` will synchronously return the results?

If b), how does it work?

If I pass a string, `Papa.parse()` returns the results, if I pass a file, `Papa.parse()` returns `undefined`. (But if I define `complete` in the config object, then I can get the results there.)

And on the demo site, if I use the string, I see `Synchronous results:` in the console. But if I use a file, I don't. This is the results from running parsing a string, then a file:

![image](https://user-images.githubusercontent.com/4443482/111551394-32cc5300-87d4-11eb-88e6-436ec9ab1d72.png)
