### ISSUE TITLE
setting 'header' config param to 'true' fails to read file data correctly

### ISSUE THREAD

**Issue by shayts** [mholt/PapaParse#584]
Setting 'header' config param to 'true' causes the read data to be incorrect and therefore unusable.
It happens with languages other than English.
Tested with CSV file created with google sheets and files created with Excel.
Attached is a test file.

I tried using a sample code and also tested with PapaParse demo:
https://www.papaparse.com/demo

[utf8_test_file - Sheet1.zip](https://github.com/mholt/PapaParse/files/2481908/utf8_test_file.-.Sheet1.zip)

**Comment by pokoli** [comment]
I think the problem is that your file contains an empty line before the headers.

Have you tried skipping empty lines?

**Comment by shayts** [comment]
@pokoli  yes, I have.

**Comment by dboskovic** [comment]
I'm not sure that skipEmptyLines would apply before the header is pulled. But @shayts can you confirm if you tried `skipEmptyLines:'greedy'`

**Comment by shayts** [comment]
@dboskovic I can't set `skipEmptyLines` as 'greedy' since I'm using this library in angular and it's set as boolean.
The problem was with the empty line. Somehow google-sheets and Excel added an empty line at the beginning of the file. I managed to remove it using Notepad and now it works.
Thank you for your help.
