### ISSUE TITLE
Not Parsing Embedded Delimiters

### ISSUE THREAD

**Issue by asevans48** [mholt/PapaParse#586]
10/23/2018 @ 6:50 pm MST
I noticed that Papa Parse fails to account for delimiters embedded between escape characters.

Browser:
 Firefox 62.0

Papa Parser Version: 4.6

Operating System:  Ubuntu

Expected:
1970,  73, "Hi, Mom!" would detect 3 columns with data:
>  0: Object { Year: "1970", "\"Score\"": "  73", "\"Title\"": " \"Hi, Mom!\"", … }

Result:

The line is parsed but the data is truncated at the embedded delimiter:
> 0: Object { Year: "1970", "\"Score\"": "  73", "\"Title\"": " \"Hi", … }

Description:

It appears that the line is split on an embedded delimiter and that escape characters are potentially parsing incorrectly.

**Comment by dboskovic** [comment]
CSV does not allow for whitespace after commas. It's considered valid content. Quotes only escape content when immediately following a comma. This usually only happens if you manually edit a CSV. No compiler should pad CSV with spaces.

**Comment by bladerunner2020** [comment]
@dboskovic thank you for clarification - I run into the same issue today. Will update manually crafted CSVs now.

**Comment by pokoli** [comment]
I'm closing this issue as I understand that the question has been already resolved. Please re-open if you don't agreee.
