### ISSUE TITLE
Delimiter is incorrect for example data

### ISSUE THREAD

**Issue by Erik-HH** [mholt/PapaParse#592]
KR-SV1|3,4|AC
KR-SV1|3,4|AC
KR-SV1|3,4|AC

Using this example data the delimiter is always set to a comma instead of the pipe  (which i think it should be). 
This is because in the guessDelimiter()-function the if-statement in the screenshot is true only once (when the comma is tested as delimiter) and the variable bestDelim never gets overriden.
![papaparsebugtrack](https://user-images.githubusercontent.com/30230530/47847032-4d036300-ddca-11e8-8ded-b7b30fbafdcf.PNG)

**Comment by Erik-HH** [comment]
To get it working i made the following changes in the guessDelimiter function:
![papaparsebugtrack_fix](https://user-images.githubusercontent.com/30230530/47848524-e0d72e00-ddce-11e8-8864-428532cd5ab9.PNG)
![papaparsebugtrack_fix2](https://user-images.githubusercontent.com/30230530/47848523-e03e9780-ddce-11e8-8af2-1b4bf7378d68.PNG)

**Comment by pokoli** [comment]
@Erik-HH Could you please create a pull request with your changes and a unit test with your example data? 

We will be happy to include it on PapaParse
