### ISSUE TITLE
If-None-Match header

### ISSUE THREAD

**Issue by lanthias** [mholt/PapaParse#595]
Hi there!

I'm trying to stream a file from GCS, and they are having problems supporting the `If-None-Match` request header for CORS. This isn't a problem with Papaparse per-se, but I was digging into the code and it seems to refer to to this webkit bug: https://bugs.webkit.org/show_bug.cgi?id=82672 which I believe is fixed.

Is there something that should/could be removed? 

Thanks!

**Comment by pokoli** [comment]
Hi @lanthias, 

For me the Header can be removed as it's already fixed. A PR removing the line is wellcome.

**Comment by lanthias** [comment]
Done! Thanks!
