### ISSUE TITLE
drop Array.isArray() polyfill

### ISSUE THREAD

**Issue by leeoniya** [mholt/PapaParse#598]
`Array.isArray()` is supported everywhere now:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/isArray#Browser_compatibility

**Comment by pokoli** [comment]
@MonkeyDZeke which browsers did you plan to support when introduced? 

Can we safely remove it?

**Comment by MonkeyDZeke** [comment]
I wasn't thinking of a specific set of browsers which needed to be supported by it, I was just playing it safe since the polyfill is so lightweight. It should be safe to remove it depending on how backwards compatible we want to be with browsers.

**Comment by pokoli** [comment]
Ok then I think we can safetly remove it. A PR removing it is very welcome

For browser support I think we should only support the browsers that are supported for the vendors, which IIRC is latests version on firefox and chrome
