### ISSUE TITLE
transform: get column number instead of header name

### ISSUE THREAD

**Issue by ksilz** [mholt/PapaParse#601]
According [to the documentation](https://www.papaparse.com/docs#config), the transform() function of the config object gets the "_column number as its second argument_". For me, it actually gets the column header name when using a header:

 const dataAsJson = Papa.parse(originalData, {
      delimiter: ';',
      header: true,
      skipEmptyLines: true,
      dynamicTyping: false,
      transform: function(value: string, columnNumber: string) {
         // here, "columnNumber" is indeed a string
         return value;
      }
    });

Is there a way to get the column number instead? The header name may change, and it's actually dependent on the locale of the user (my application supports two different languages).

**Comment by pokoli** [comment]
I guess that's because you are using _header:true_ so that's why you are getting the header name instead  of the row number. 

If do you want to get the column number set _header: false_

Probably the documentation can be improved to explain that the behavior depends on the header flag.

**Comment by asuraphel** [comment]
@ksilz The workaround i found is using transform header to rename the column by its index. And use the name you gave to that column.
