### ISSUE TITLE
# in object values breaks Papa.unparse

### ISSUE THREAD

**Issue by btm1** [mholt/PapaParse#603]
Maybe this is obvious but it's not to me from reading the documentation but, how can I ensure that # can be present in object values (headers or otherwise) and still be able to do Pap.unparse?  These # are not comments but actual values that need to be present.

Thanks in advance for your help.

**Comment by pokoli** [comment]
Could you explain what is not working for you? Which config values are you using? Which is the current result? Which is the expected result

The following test cases is working for me:

       {
               description: "Using # in unprase",
               input: [['a', '#'], ['#', 'a']],
               config: {},
               expected: 'a,#\r\n#,a'
        }

**Comment by btm1** [comment]
my understanding from my team is that having a "#" anywhere in the object that is then unparsed into a CSV will result in everything after the # being blank.

**Comment by btm1** [comment]
Seems as though it's interpreting the # as a comment?

**Comment by pokoli** [comment]
Could you please share a simple code snippet to reproduce the issue?

**Comment by Reddian** [comment]
I'm also having this issue. 

Code:
```
$scope.downloadCSV = function( data, file_name ){
      var a = document.createElement("a");

      var data = [{"Id":158,"MemberId":41076,"Membership":"Senior Dues Relief","MembershipExpiration":"","FirstName":"John","LastName":"Smith","Email":"example@email.com","Address":"123 Test Street #121","City":"Amazeville","State":"AW","PostalCode":"12345","Country":"United States","BadAddress":"N","HomePhone":"555-555-55555","MobilePhone":""}];

      var csv = Papa.unparse(data,{
        	quotes: true,
        	quoteChar: '"',
        	escapeChar: '"',
        	delimiter: ",",
        	header: true,
        	newline: "\r\n"
        });

      if (window.navigator.msSaveOrOpenBlob) {
        var blob = new Blob([decodeURIComponent(encodeURI(csv))], {
          type: "text/csv;charset=utf-8;"
        });
        navigator.msSaveBlob(blob, file_name);
      } else {

        a.href = 'data:attachment/csv;charset=utf-8,' + encodeURI(csv);
        a.target = '_blank';
        a.download = file_name;
        document.body.appendChild(a);
        a.click();
      }
  };
```

The address field is making anything after it blank including any new data afterwards.

**Comment by dboskovic** [comment]
https://codesandbox.io/s/61lv118q6z

@btm1 and @Reddian - can you have your developers try to mess with the above sandbox and provide a version that replicates the issue you're experiencing. @Reddian this sandbox is a copy paste of the logic you shared and it's working as expected. 🤔

**Comment by Reddian** [comment]
@dboskovic After testing, I realize this solution does work in Chrome. However, it does not work for me in Firefox for mac.

**Comment by btm1** [comment]
I ended up just wrapping every single object value on quotes before
converting to JASON and downloading and that solved the problem for me.
It's because # is a comment so I believe it was reading it as such.

**Comment by michaeljonsampson** [comment]
I also just ran into this. One of my column headers had a '#' in it and everything after it was blank. I'm still on 4.3.6. I tested the above sandbox with 4.3.6 and couldn't recreate the problem there. I'll try upgrading my app's version and report back.

**Comment by michaeljonsampson** [comment]
This isn't a PapaParse bug. I had similar code to @Reddian. I think there was a recent change in Chrome that causes this issue with the `#` and `href` tags. Safari doesn't have the problem. I've had this code in production for 4+ years and just starting having complaints about it last week. 

Use `encodeURIComponent()` instead of `encodeURI()` or downloadjs (https://github.com/rndme/download) to solve this problem.

**Comment by pokoli** [comment]
@michaeljonsampson thanks for giving a proper solution! I'm closing this issue if there is nothing to do in PapaParse.

**Comment by pokoli** [comment]
@michaeljonsampson thanks for giving a proper solution! I'm closing this issue if there is nothing to do in PapaParse.
