### ISSUE TITLE
parse a local csv file with semicolon as delimiter

### ISSUE THREAD

**Issue by SebbarSara** [mholt/PapaParse#606]
Hello,
Thank you for this interesting library !
I noticed that Papa Parse that not support the delimiter  ";" when trying to parse a local csv file.

csv file : 

> nom;prenom;age;celibataire
> ABC;Fudge;123.665;true
> CWE;ICECREAM;532;false 

Expected : 

> 0: {nom: "ABC", prenom: "Fudge", age: "123.665", celibataire: "true"}
> 1: {nom: "CWE", prenom: "ICECREAM", age: "532", celibataire: "false"}

Results : 
> 0: {nom;prenom;age;celibataire;: "ABC;Fudge;123.665;true;"}
> 1: {nom;prenom;age;celibataire;: "CWE;ICECREAM;532;false"}

I have tried to specify the delimiter ";" in the configuration but i still having the same results

Thank you

**Comment by pokoli** [comment]
Hi, 

Thanks for reporting, could you share which configuration values are you using for parsing the file and which library version are you using?

**Comment by SebbarSara** [comment]
Hi, 
I am using : Papa Parse v4.4.0 in an Angular Project and this is the configuration : 

>  let options = {
>       =
>       delimiter: ";",
>       header: true,
>       dynamicTyping: true,
>       preview: 10,
>       skipEmptyLines: true,
>       complete: (results) => {
>         list = this.getFieldsAndTypes(results);
>       },
>     };

I have done the same test in PapaParse demo website : https://www.papaparse.com/demo and i have get the same results above

**Comment by MonkeyDZeke** [comment]
Hey there! I just tried it on the PapaParse site demo using the settings and data you provided and it is providing results as expected, not the buggy behavior. Were you able to isolate your issue and solve it yet?

**Comment by GendelfLugansk** [comment]
Hello there! I am able to reproduce this error. Here is an example of data:

```
;prenom;age;celibataire
ABC;"Fudge";123.665;true
CWE;ICECREAM;532;false
```

There are two important conditions in data that lead to buggy behavior:

1. First column of the first line is empty
2. Some of fields are quoted

**Comment by pokoli** [comment]
@GendelfLugansk there was an issue when first column of first line is empty which has been resolved by #696 

Could you restest using the [development version of papaparse. ](https://raw.githubusercontent.com/mholt/PapaParse/master/papaparse.js)

**Comment by GendelfLugansk** [comment]
@pokoli Works fine with master branch

**Comment by pokoli** [comment]
@GendelfLugansk Thanks for the feedback. 

I'm closing this issue as duplicate re-open with proper example if you don't agree.
