### ISSUE TITLE
question : Errors Documentation

### ISSUE THREAD

**Issue by ahmed-ben-s** [mholt/PapaParse#607]
Hello,

Is there any documentation about the possible errors?
When I read in the doc: "Just because errors are generated does not necessarily mean that parsing failed. The worst error you can get is probably MissingQuotes." its quiet confusing because we don't know if the parsing failed or not. And actually we don't know if we need or not to fire an error message to the user.

Can you please tell us which errors we can consider as blocking errors?

Thanks.
Ahmed.

**Comment by pokoli** [comment]
[Our documentation contains a section about errors](https://www.papaparse.com/docs#errors)

**Comment by mohammad-suliman** [comment]
Thanks for the valuable work on this parser! To be sure: if the aborted property of the meta is false, then it's safe to assume the parsing was successful?
