### ISSUE TITLE
Incorrect Parsing of Lines 

### ISSUE THREAD

**Issue by fuchsberger** [mholt/PapaParse#611]
I cannot seem to get numbers parsed correctly:
Here is my csv file format. 4 columns, first two are int, last two are float:
```
1,0,7.4333696,-2.119892
2,0,7.457081,-5.6058187
3,0,0.75248903,-4.0468054
4,0,2.9416115,-2.710186
7,0,1.3348191,0.4555091
```
I am using:
```
      <CSVReader
        onFileLoaded={ markers => {
          console.log(markers)
        }}
        parserOptions={{
          dynamicTyping: true,
          fastMode: true,
          skipEmptyLines: true
        }}
      />
```
This is the parsed output:
https://pasteboard.co/HTQc1H4.png

Any help would be appriciated. I tried changing the delimiter, manually set delimiter and new line character option, disable dynamic Typing, but for whatever reason, column 3 and 4 seem to get merged even though there is a delimiter in between.

**Comment by dboskovic** [comment]
Are you're using this library? https://www.npmjs.com/package/react-csv-reader

**Comment by fuchsberger** [comment]
yes, but I think react-csv is reading the file correctly so i would assume the problem arises when parse is called.

**Comment by dboskovic** [comment]
Can you replicate this issue here? https://codesandbox.io/s/o540qq65pq

**Comment by dboskovic** [comment]
And if you can, share the version of `react-csv-reader` you're using.

**Comment by fuchsberger** [comment]
i could not replicate the issue. I learned that a sorting operation _after_ parsing caused the messed up console output! thanks very much though! can be closed :)

**Comment by dboskovic** [comment]
Great to hear @fuchsberger!
