### ISSUE TITLE
Download links on homepage link to pre-release versions

### ISSUE THREAD

**Issue by john-cullen** [mholt/PapaParse#615]
The `Lil papa` and `Fat papa` download links in the footer lead to the master branch, which is a bit misleading as the master is currently on version 5.0.0-beta but the website documentation is for version 4.6

**Comment by pokoli** [comment]
I've found: https://help.github.com/articles/linking-to-releases/

Do you think using the latest release will be OK? Note that it currently points to 4.6.0 but latests stable release is 4.6.2

**Comment by dboskovic** [comment]
I think linking to the latest stable release makes sense!

**Comment by dboskovic** [comment]
That said, I think maybe we should be linking to the NPM files via unpkg, rather than the ones on github. What do you think?

**Comment by pokoli** [comment]
Yes, probably using npm for releases is a good option. Indeed I see one benefit as on npm we got the latests minor version as:

https://www.npmjs.com/package/papaparse/v/latest

Points to 4.6.3 (which is the latest one now) 

So for me, this is the best option

**Comment by dboskovic** [comment]
And we can link directly to files with:
https://unpkg.com/papaparse@latest/papaparse.js
https://unpkg.com/papaparse@latest/papaparse.min.js
