### ISSUE TITLE
Encoding does not handle Greek files generated by Excel

### ISSUE THREAD

**Issue by SheetJSDev** [mholt/PapaParse#64]
Example file: https://github.com/SheetJS/test_files/blob/master/biff5/number_format_greek.xls.0.csv

The encoding is windows codepage 1253.  The original XLS file is https://github.com/SheetJS/test_files/blob/master/biff5/number_format_greek.xls.  To reproduce, set the language for non-Unicode characters to "Greek".

What is the correct encoding setting to parse the file?  Using "iso-8859-7" appears to have no effect on the result.

**Comment by mharn** [comment]
FWIW I've had success with using Encoding.js (https://github.com/polygonplanet/encoding.js) to detect some encodings including Japanese text (e.g. SJIS) and then run Papaparse based on that result.

Be warned that Encoding.js says that it mainly supports Unicode and Japanese formats, and not other European-centric ones. 

`
<script type="text/javascript" src="./js/encoding.min.js"></script>
  function onFileSelect(event) {
    var file = event.target.files[0];

    var reader = new FileReader();
    reader.onload = function(e) {
      var codes = new Uint8Array(e.target.result);
      var encoding = Encoding.detect(codes);
      console.log(encoding);
      var files = event.target.files;
      Papa.parse(files[0], {
        skipEmptyLines: true,  // need this or papaparse adds a blank entry (despite csv only have 5 lines, it gives a 6th empty string)
  	    header: true, // testing adding a source/target header
        encoding: encoding,
        complete: function(results) {
		      console.log(results.data);
	     }
      });
    };

    reader.readAsArrayBuffer(file);
  }

  document.getElementById('encoding.js').addEventListener('change', onFileSelect, false);
`
