### ISSUE TITLE
Array value in parse ?

### ISSUE THREAD

**Issue by djmisterjon** [mholt/PapaParse#645]
hi guys, it possible to get array value from excel value example with 1,4
to array [1,4] ?
![image](https://user-images.githubusercontent.com/24865815/54471942-6e705480-4797-11e9-96f4-d3c5c99d0d1d.png)

is a specific options or i use bad way ?
this is what i try in excel
![image](https://user-images.githubusercontent.com/24865815/54471963-9e1f5c80-4797-11e9-8a80-9bbbd09a07bc.png)
thanks for help

**Comment by pokoli** [comment]
I do not think this is supported on paparse as the value will be interpreted as string.

Having said taht if you store arrays as [1, 4] you may convert them to Arrays after parsing with [JSON.parse](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/parse)
