### ISSUE TITLE
skipEmptyLines config doesn't work

### ISSUE THREAD

**Issue by starcraft0429** [mholt/PapaParse#659]
here is my code
```
Papa.parse(fileUrl, {
                    download: true,
                    header: true,
                    skipEmptyLines: true,
                    delimiter: ",",
                    quoteChar: '"',
                    complete: function(results) {
                        if(results.errors.length > 0){
                            console.log(results.errors);
                            alert("CSV file parse error!\nPlease check console for error!");
                            return;
                        }
                        console.log(results)
                    }
                });
```

however the empty result is at the end of array
![Screenshot from 2019-04-29 13-50-25](https://user-images.githubusercontent.com/22740206/56891630-cc29d900-6a85-11e9-856e-d0ba50e5bd0d.png)

Pls help

**Comment by Serrulien** [comment]
As said in the [doc ](https://www.papaparse.com/docs#config) about `skipEmptyLines`: 
> If true, lines that are completely empty (those which evaluate to an empty string) will be skipped. If set to 'greedy', lines that don't have any content (those which have only whitespace after parsing) will also be skipped.

Take a look at these :
https://github.com/mholt/PapaParse/blob/ae25f7cefd255b3c014d66f0841c2a27c989d996/tests/test-cases.js#L1124-L1130
https://github.com/mholt/PapaParse/blob/ae25f7cefd255b3c014d66f0841c2a27c989d996/tests/test-cases.js#L1403-L1410
