### ISSUE TITLE
Multiple tabs csv file

### ISSUE THREAD

**Issue by dbaronov** [mholt/PapaParse#660]
I am working on some functionality to render supplied *.csv data using PapaParse and Charts.js while having great results with both.

Today we have decided to introduce new functionality to be able to render retrospective data too. For this to happen we will need to provide monthly data. As far as I understand it is achievable if individual files are provided for each month. This is an OK solution, but not the most efficient one as every time user selects the month, the file will have to be fetched from the server to update the Chart.

So, to resolve this I have tried to use a *.csv file with multiple tabs in it representing individual months.

Looking into the result of parsing it seems like PapaParse is only capable of parsing the first tab of the document while ignoring the rest.

Am I overlooking / missing anything?

**Comment by pokoli** [comment]
Could you publish a same file and the configuration you are using to parse it?

**Comment by dbaronov** [comment]
I have done my research and it turns out a *.csv indicates one set of data only.

Based on the above I have chosen to drop the *.csv approach all together and work with *.xlsx files instead while creating custom function to process the data.

@pokoli, you might want to keep this issue for others to refer to in the future.

**Comment by pokoli** [comment]
Could you clarify what do you mean by multiple tabls CSV files?

**Comment by dbaronov** [comment]
So imagine I create an workbook with multiple tabs in Excel (3 by default) and decide to save the file in *.csv formal instead of *.xls or .*xlsx. The result I will get  is only first sheet of Excel work book will be saved in that *.csv file.

**Comment by pokoli** [comment]
This is nothing that PapaParse has to do with but something with your spreedsheet software when exporting to CSV format. 
PapaParse is designed to parparse CSV files and not spreadsheets. So I'm closing this issue.
