### ISSUE TITLE
Number format should be is Number without quote

### ISSUE THREAD

**Issue by minhchienwikipedia** [mholt/PapaParse#662]
Hi, I have an issue about the format data. When I get data from the CSV URL, my data always is the string looks like the image.
How can I format number is number type without quote?

<img width="224" alt="Screen Shot 2019-05-18 at 1 13 19 AM" src="https://user-images.githubusercontent.com/20647079/57947872-4d98bc80-790a-11e9-9ad5-fe02a333c6bf.png">

**Comment by pokoli** [comment]
You should use the dynamictiping setting to convert numbers to their type. This is [explained on our documentation](https://www.papaparse.com/docs#config).
