### ISSUE TITLE
can PapaParse help with this reading CSV file problem?

### ISSUE THREAD

**Issue by TahorSuiJuris** [mholt/PapaParse#666]
Posted on stackoverflow, but no responses.

Why does this only return the first character of the string?
    const searchkeywords = fs.readFileSync('kwords.csv','utf-8');
        for (let kword of searchkeywords) {
    console.log(`Search Keyword: ${kword}`);

Text for the first 10 rows is:

"1-800-FLOWERS.COM, INC.",
"1ST SOURCE",
"1ST SOURCE CORP",
"3D SYSTEMS",
"8X8, INC.",
"A.H. BELO",
"AAON",
"AARON RENTS",
"ABERCROMBIE & FITCH",
"ABIOMED",

**Comment by pokoli** [comment]
Whitouh the file we can not provide so much support.

**Comment by TahorSuiJuris** [comment]
We already resolved the issue, but would like to discover how PapaParse can benefit beyond advanced javascript code.

Tahor SuiJuris Ben Beriyth
Ahayah yasha yadah
h1961 h3467 h3034
Proverbs 15:32
A MANDATORY verbal "confession" in sequence Colossians 3:17 / John 14:6 / John 6:44
[http://literateaspects.com](http://www.literateaspects.com/) (under construction)
Acts 17:26, 27 / Judges 2:3, 22
• a  TIME  limit  for  all  to  SEEK •
Deuteronomy 4:28, 29 / Isaiah 55:6, 7
[shub-min.png]

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by pokoli** [comment]
Could you share the solution so others can benefit from your experience?

**Comment by dboskovic** [comment]
Reading the source in this example, it appears Papaparse was not part of the issue. Instead the code example was just iterating through characters in a raw string. Closing this.
