### ISSUE TITLE
Option for set custom columns when parse

### ISSUE THREAD

**Issue by alejandrosc** [mholt/PapaParse#667]
Why not add an option to configure custom columns when using parse function

By example:

```javascript
Papa.parse(file, {
	columns: ["column1", "column2"]
})
```

This can be useful when you don't have control by the name of the columns in a file

**Comment by pokoli** [comment]
Because you can parse as is which returns column numbers and then add the mapping as you want. 

We try to keep focus on just parsing the file, so users are allowed to update it latter.
