### ISSUE TITLE
Add support for transposing returned data.

### ISSUE THREAD

**Issue by bhagyas** [mholt/PapaParse#68]
For an example, if the CSV contains a list of categories and sub categories, the sub categories must be able to be grouped under each category (which might also be defined as a header).

Papa returns this at the moment.

```
[
  [{"catA" : "subcatAA", "catB" : "subcatBA"}],
  [{"catA" : "subcatAB", "catB" : "subcatBB"}],
  [{"catA" : "subcatAC", "catB" : "subcatBC"}]
]
```

instead of the required.

```
[
  "catA" : ["subcatAA","subcatAB","subcatAC"],
  "catB" : ["subcatBA","subcatBB","subcatBC"]
]
```

Currently this can be achieved using underscore.js and following code ;

```
_.transpose = function(array) {
    var keys = _.union.apply(_, _.map(array, _.keys)),
        result = {};
    for (var i=0, l=keys.length; i<l; i++) {
        var key = keys[i];
        result[key] = _.pluck(array, key);
    }
    return result;
};

//results being the argument in complete callback function
var categories = _.transpose(results.data); 
```

Suggesting an optional boolean configuration parameter named `transpose` and results would be a transposed array mapped using the function above.

_References_
http://stackoverflow.com/questions/13353674/how-to-transpose-object-in-underscorejs

**Comment by mysticaltech** [comment]
@mholt Thanks for considering this, it would have helped me a lot actually. I would propose enabling the transpose option when header is false.

**Comment by mysticaltech** [comment]
But no worries, just found out that using the **zip** method from any functional library (licia, underscore etc.) it is easily doable.

```
 const rows = data.map((row) => row.data)
 const columns = zip(...rows)
```
