### ISSUE TITLE
Communicate on potential breaking changes

### ISSUE THREAD

**Issue by oliviermattei** [mholt/PapaParse#680]
Hello you should communicate about breaking changes on major version.

I'd like to update, but i don't see this information.

**Comment by pokoli** [comment]
All changes are explained on [the release notice](https://github.com/mholt/PapaParse/releases/tag/5.0.0) 

Also the pull requests that introducen and api change are labeled with the [Api Change](https://github.com/mholt/PapaParse/issues?q=label%3A%22api+change%22+is%3Aclosed) tag

Hope it helps!
