### ISSUE TITLE
How to reset Papa.parse(...).data

### ISSUE THREAD

**Issue by alaindebecker** [mholt/PapaParse#686]
When reading two csv files in a row 

>     var a = parse('stringA').data ;
>     var b = parse('stringB').data ;

`b` contains the data from the two files cumulatively instead of the data of `b` only.

If this an intended feature, is there a way to empty the data between the two calls ?

**Comment by dboskovic** [comment]
Can you share the following?
- Environment: Browser or Node?
- Config object: (especially if using step function or worker)

**Comment by alaindebecker** [comment]
Problem was mine. Papaparse works perfectly.
Sorry for not having updated.
