### ISSUE TITLE
Parsing issue in latest versions: unrecognized tabs

### ISSUE THREAD

**Issue by gltjk** [mholt/PapaParse#699]
Greetings. I was parsing a csv file with PapaParse and encountered some problems. After some digging, I managed to locate the lines causing such problems, and hence recreated them with the following sample code.

I tested the code in the latest versions of Chrome, Firefox, and Node.js, together with the latest versions of PapaParse (v5.0.0 ~ v5.0.2), and the problem arose. However, when I turned to PapaParse v5.0.0-beta.0 or v4.x, everything worked just well.

The sample code is:
```js
const text = 'h1\th2\th3\na1\ta2"\ta3\nb1\tb2"\tb3'
const result = Papa.parse(text, { header: true }).data
console.log(result)
```
Here's what I expected:
```js
[
  { h1: 'a1', h2: 'a2"', h3: 'a3' },
  { h1: 'b1', h2: 'b2"', h3: 'b3' }
]
```
and this is the actual result I got:
```js
[
  { h1: 'a1', h2: 'a2"', h3: 'a3' },
  { h1: 'b1\tb2"', h2: 'b3' }
]
```
Looking forward to a fix for this bug :smiley:

**Comment by dboskovic** [comment]
Thanks for the detailed example. Linking to a CodeSandbox here that replicates: https://codesandbox.io/s/crazy-thunder-2vjl7
