### ISSUE TITLE
remote url papaparse large csv

### ISSUE THREAD

**Issue by NickCarducci** [mholt/PapaParse#701]
trying to read this csv on a public dropbox link.  It's too large to display in dropbox (200MB), but not too big to download.  I have it downloading automatically & first row header as labels for the object of each row's properties.  I can change ?dl=0 to ?dl=1 in the link to automatically download without papaparse since it's a dropbox link, by the way.
```
Papa.parse("https://www.dropbox.com/s/m5kr9u52eij99mq/worldcitiespop.csv?dl=0", {
  download: true,
  header: true,
  step: function(results) {
    console.log(results.data)
  },
  complete: function() {
    console.log("All done!");
  }
});
```

**Comment by NickCarducci** [comment]
someone made https://cors-anywhere.herokuapp.com/ and I put that directly in from of my link, and set it to download ?dl=1 in dropbox notation.  Only then was I able to log results.data

**Comment by NickCarducci** [comment]
by the way lodash pick works to isolate a property of an object array.
let variable = pick(results.data, ["Property"]

**Comment by NickCarducci** [comment]
I can't figure out how to use **result** outside of Papa.parse
I can't put all components dependent on these objects into step
`Papa.parse(
      "https://cors-anywhere.herokuapp.com/https://www.dropbox.com/s/5vcoo9r60hgczd1/worldcitiespop_northamerica_nolonglat.csv?dl=1", {
    download: true,
    header: true,
    worker: true,
    step: function(results) {
          let **result** = pick(results.data, ["City"]);
    },
    complete: function() {
          console.log("All done!");
    }
});`I heard if I set the whole Papaparse thing to a const, that will create an array of the step objects, but I couldn't get that to work

**Comment by dboskovic** [comment]
Hey @NickCarducci - in a step function like this since it's an event-based read, you'll need to append to an array outside of the step function if you want it all together, and not one row at a time. Normally I'll pool n rows in an array, call `.pause()`, do something with a chunk of the data, clear it, and the continue so you don't load everything into memory.

**Comment by NickCarducci** [comment]
Hey @dboskovic thanks
How do I pool the result into an array? pool.map(result)?
But more importantly & related to Papaparse how do I use that pool or result outside of the Papa.parse thing and in my component.  I don't need them to be pooled since each result is used to render a component.  Here is my full component with Papa.parse inside, I can't get result out "result is not defined." Inside Papa.parse console.log(result) logs the array of objects with City properties well.
```
class CitiesMap extends React.Component {
  render(props) {
    Papa.parse(
      "https://cors-anywhere.herokuapp.com/https://www.dropbox.com/s/5vcoo9r60hgczd1/worldcitiespop_northamerica_nolonglat.csv?dl=1",
      {
        download: true,
        header: true,
        worker: true,
        step: function(results) {
          let result = pick(results.data, ["City"]);
        },
        complete: function() {
          console.log("All done!");
        }
      }
    );

    let filteredCities = result.filter(result => {
      return ( result.City.toUpperCase().indexOf(this.props.search.toUpperCase()) !== -1
      );
    });
    return (
      <div>
        <div className="Cities">
          {filteredCities.map(City => {
            return (
              <div>
                <WeatherCitySkyMap
                  description={this.description}
                  humidity={this.humidity}
                  city={city}
                />
                {JSON.stringify([City])
                  .replace(/[^\w\s]/g, "")
                  .replace(/(city)/g, "")}
              </div>
            );
          })}
        </div>
      </div>
    );
  }
}
```

**Comment by NickCarducci** [comment]
I also hear it is [best practice](https://codeday.me/en/qa/20190306/12163.html) to put a function into step (for urls; complete for files), and (((in react))) set the objects to the state of the component that Papa.parse resides in, instead of trying to get Papa.parse ["to return anything"](https://www.papaparse.com/docs#results), but I still can't even console.log(results.data) inside updateData(results) when calling this.updateData after step:
```
import React from "react";
import WeatherCitySkyMap from "./WeatherCitySkyMap";
import Papa from "papaparse";
import { pick } from "lodash";

import ".././Explore/Cities.css";
let cities = [{ city: "New York" }, { city: "Baltimore" }];

class CitiesMap extends React.Component {
  constructor(props) {
    super(props);
    this.updateData = this.updateData.bind(this);
    this.state = [{ cities }];
  }
  ComponentWillMount() {
    Papa.parse(
      "https://cors-anywhere.herokuapp.com/https://www.dropbox.com/s/5vcoo9r60hgczd1/worldcitiespop_northamerica_nolonglat.csv?dl=1",
      {
        download: true,
        header: true,
        worker: true,
        step: this.updateData,
        function(results) {
          let result = pick(results.data, ["City"]);

          let cities = { ...result };
        },
        complete: function() {
          // console.log("All done!");
        }
      }
    );
  }
  updateData(results) {
    **console.log(results.data);**
    const cities = pick(results.data, ["City"]);
    // Here this is available and we can call this.setState (since it's binded in the constructor)
    this.setState({ cities }); // or shorter ES syntax: this.setState({ data });
  }
  render(props) {
    let filteredCities = cities.filter(cities => {
      return (
        cities.city.toUpperCase().indexOf(this.props.search.toUpperCase()) !==
        -1
      );
    });
    return (
      <div>
        <div className="Cities">
          {filteredCities.map(city => {
            return (
              <div>
                <WeatherCitySkyMap
                  description={this.description}
                  humidity={this.humidity}
                  city={city}
                />
                {JSON.stringify([city])
                  .replace(/[^\w\s]/g, "")
                  .replace(/(city)/g, "")}
              </div>
            );
          })}
        </div>
      </div>
    );
  }
}

export default CitiesMap;
```

**Comment by dboskovic** [comment]
Hey @NickCarducci - these questions would be better posted on StackOverflow, as the issues you're experiencing have to do with javascript / react in general and not PapaParse.

Quick notes while I'm here though:

1. `ComponentWillMount` is the right idea but the incorrect method. Should be `componentWillMount` (small C)
2. I'm not sure what you're doing nearby the step function in the second example as that's more-or-less broken javascript. You should implement something close to the following code:

```js
    let cities = []
    Papa.parse(
      "https://cors-anywhere.herokuapp.com/https://www.dropbox.com/s/5vcoo9r60hgczd1/worldcitiespop_northamerica_nolonglat.csv?dl=1",
      {
        download: true,
        header: true,
        worker: true,
        step: function(results) {
          cities.push(results.data['City'])
        },
        complete: function() {
          // now you have a full array of cities, attach it to the react state
          this.setState({cities})
        }
      }
    );
```

**Comment by pokoli** [comment]
So if there is no issue with paparase I'm closing this issue.

**Comment by NickCarducci** [comment]
Ok so can you at least clear this up for me:
**I know Papa.parse** "Doesn't return anything. Results are provided asynchronously to a callback function."
and so it is best practice **for any framework or language** to **put a function into step or complete** depending on (url or file)?

**Comment by NickCarducci** [comment]
I see that is what you're implying by the code.  This was just a question about the docs

**Comment by NickCarducci** [comment]
I see your also saying to use .push instead of lodash pick

**Comment by NickCarducci** [comment]
the array is still empty
<img width="569" alt="Screen Shot 2019-08-19 at 9 44 19 AM" src="https://user-images.githubusercontent.com/12148373/63270318-f5a18700-c265-11e9-8164-0d261f1ac225.png">

**Comment by NickCarducci** [comment]
<img width="614" alt="Screen Shot 2019-08-19 at 9 49 19 AM" src="https://user-images.githubusercontent.com/12148373/63270736-bcb5e200-c266-11e9-84d7-4b027b611436.png">

**Comment by NickCarducci** [comment]
<img width="736" alt="Screen Shot 2019-08-19 at 9 50 42 AM" src="https://user-images.githubusercontent.com/12148373/63270799-d8b98380-c266-11e9-8fc1-53ec3fd2b028.png">

**Comment by dboskovic** [comment]
@NickCarducci - definitely post this on StackOverflow instead. Because it's asynchronous, line 25 executes before the step function. You also cannot have this in your render function because it will cause a setState() loop that will never stop downloading the file. I'm going ahead and locking this thread, but the community on StackOverflow loves this kind of stuff and will be helpful in talking to you about Javascript.
