### ISSUE TITLE
How to import Papa Parse in js ..No where found in documentation....What is the package name....

### ISSUE THREAD

**Issue by amazedge** [mholt/PapaParse#715]
How to import Papa Parse in js ..No where found in documentation....What is the package name....

**Comment by pokoli** [comment]
The papaparse is avaialbe on npm under [the papaparse package.](https://www.npmjs.com/package/papaparse)

**Comment by yairEO** [comment]
Why was this closed? the README of this project does not state in any way how this package should be imported.

Is there a default export or a named export? should we the developers guess?
