### ISSUE TITLE
Parsing individual fields/cells and validating

### ISSUE THREAD

**Issue by brandondurham** [mholt/PapaParse#716]
I’m sorry if this is already covered or documented — I couldn’t find specific details here. I’m using [Yup](https://github.com/jquense/yup) to validate individual fields/cells in a CSV, and I’m unclear as to where I should be putting this logic, and more importantly, how best to parse individual fields/cells.

My `step` config currently looks like this:

```javascript
return Papa.parse(data, {
	header: true,
	worker: true,
	step: (results, parser) => {
		// parser.pause()
		const fieldsValid = validateFields(results.data)
		// parser.resume()

		// if (!fieldsValid) {
		// parser.abort()
		// }
	},
})
```

The `validateFields` function cycles through all fields in the returned row and validates:

```javascript
async function validateField(type, value) {
	const entries = Object.entries(fields)

	for (const entry of entries) {
		const schema = string()
		const fieldIsValid = await schema.isValid(value)
	}
}
```

### Questions:
1. Am I parsing the fields/cells correctly and most efficiently — with a `for of` loop?
1. Should I be doing this inside of the `step` config, or does Papa Parse have another, more efficient way to do it?

I appreciate any guidance I can get.

**Comment by danielnitsche** [comment]
@brandondurham did you ever work this out?

**Comment by AbakumovAlexandr** [comment]
Any input on this from the PapaParse team? :)

**Comment by pokoli** [comment]
I'm closing this issue as we do not do developer support in issue tracker. 
The issue tracker is for reporting bugs/improvements on the library. 
Feel free to use stackoverflow for suport.
