### ISSUE TITLE
Papa is making our workplace uncomfortable

### ISSUE THREAD

**Issue by ritviknv** [mholt/PapaParse#720]
We use papa parse at work for a variety of tasks. The naming has made our workplace uncomfortable for both men and women alike. A few examples:

Ex 1. one engineer says to another: "Ask Papa to parse it" 
Ex 2. a product manager to her/his team: "We need to infer data types, what can Papa do for us?" 
Ex 3. sales engineer to a customer: "Oh we just let Papa handle all the hairy details"

**Comment by mholt** [comment]
Its name is "Papa Parse"

Not "Papa" (that is weird)

**Comment by treyhakanson** [comment]
I tend to agree with this, the header on the website is even "The powerful, in-browser CSV parser for big boys and girls". Seems a little suspect 🤷‍♀
