### ISSUE TITLE
PapParse Accessibility/Inclusion Concerns

### ISSUE THREAD

**Issue by ianhansborough** [mholt/PapaParse#722]
RE: #720 

OP of #720 has a valid point. Even if we accept a degree of ambiguity regarding the semantics of "Papa", the name still raises an important accessibility issue. Can we really expect engineers of a non-binary/non-conforming gender to feel comfortable using a piece of software whose very name implies such a degree of antiquated patriarchy?

**Comment by staufferl16** [comment]
Typical boys' club move, marking a conversation facilitating discussion around valid concerns as "off topic."

**Comment by leeoniya** [comment]
i'm not trying to be snarky or dismissive, but why is no one clamoring to change other terminology like "motherboard", "mother earth", "mother tongue" gendered nouns/verbs in non-english languages.

if this library was renamed to "Mama Parse", as a guy i would not be offended whatsoever, except for the fact that renaming it was necessary at all. it's one thing is a maintainer or core contributor actively excludes or offends others, but everyone being offended by every word these days is a bunch of nonsense, imo.

also, can't those who are deeply offended by "Papa" simply fork and rename the lib? the license is MIT.
