### ISSUE TITLE
unparse issue with data having \ & \"

### ISSUE THREAD

**Issue by balajic** [mholt/PapaParse#732]
Here is the test case, you can try it out in the https://www.papaparse.com/demo console.

```

let a = a={C1: "Start", C2: "slash at the end of field\\", C3: "slash doublequote in the middle \\\" ..", C4: "double quote at the end \"", C5: "End"};
Papa.unparse([a],{header: false,escapeChar: '\\',delimiter: '^'})
```

And here is the output
```
Start^slash at the end of field\^"slash doublequote in the middle \\" .."^"double quote at the end \""^End
```

I am expecting
```
Start^slash at the end of field\\^"slash doublequote in the middle \\\" .."^"double quote at the end \""^End
```

**Comment by janisdd** [comment]
First, the code is wrong, `a=` must be removed (and formatted):

```js
let a ={
  C1: "Start", 
  C2: "slash at the end of field\\", 
  C3: "slash doublequote in the middle \\\" ..", 
  C4: "double quote at the end \"", 
  C5: "End"
};
Papa.unparse([a],{header: false,escapeChar: '\\',delimiter: '^'})
```
which gives
```
Start^slash at the end of field\\^"slash doublequote in the middle \\\\" .."^"double quote at the end \\""^End
```

better formatted:

```
Start
slash at the end of field\\
"slash doublequote in the middle \\\\" .."
"double quote at the end \\""
End
```

It seems that the `escapeChar` is used to escape the quotes when the field itself is quoted.
It is done by prepending the `escapeChar` before the quotes, e.g. with an `escapeChar: +`  `"a"b"` will be escaped as `"a+"b"`.

`C4: "double quote at the end \""`: the `\"` is just a `"` in a string (string escape sequence). This can be escaped as `\\"` (escapeChar + quotes), thus the result `"double quote at the end \\""`.

` C3: "slash doublequote in the middle \\\" ..", `: the `\\\"` is just `\"` in a string and escaped as `\\"` for the quote and the `\\` is unchanged, resulting in `"slash doublequote in the middle \\\\" .."`.

Everything works as expected (at least in the current version on https://www.papaparse.com/demo).
