### ISSUE TITLE
styling the choose file and parse buttons

### ISSUE THREAD

**Issue by lucyc426** [mholt/PapaParse#733]
I've been following the papaparse documentation (https://npm.runkit.com/react-papaparse) and I've actually been able to make the parsing work so it's not a functionality issue I'm having.

As of now, I have only an "upload" button so when I click that, I can browse for and select a local file, but after I select the file it automatically starts parsing without showing which file I selected. I would like the user to be able to see the file they selected and then press another button to then parse the data.

So essentially one button for "choose file", and one button for "parse" as seen in the papaparse demo.

I have tried creating an input of type "file" to choose a file and then show the name and then onClick={this.handleImportOffer}, but this way it opens the file browser twice.

Or is it possible to create an upload button and once I select the file it just shows up in an input of type "text"?

Essentially, just would like it to look like the papaparse demo but having a hard time getting there.
Papaparse demo for reference: https://www.papaparse.com/demo Thanks for the help.

**Comment by pokoli** [comment]
react-papaparse is not part of the PapaParse project but a dependant project. 

As I see that your issues are with the user interface (which is part of the react-papaparse project), I think you should report this issue to: https://github.com/themodernjavascript/react-papaparse
