### ISSUE TITLE
Chunking broken with pause() and resume()

### ISSUE THREAD

**Issue by duclet** [mholt/PapaParse#736]
Hi, I am trying to use streaming with chunk that inside of it make use of pause and resume. I'm noticing that after the pause and resume, the data of the chunk is incorrect. Essentially, the line where it concatenate the with the reader result, the partial line already contains a portion of the reader result. This can be easily reproduced with the "Local Files(s)" demo on the web site using the Large file. You just need to change the config to be the following:

```javascript
                config: {
					chunk: function(results, parser) {
						parser.pause();
						parser.resume();
					},
				},
```
After pausing and when `resume` is called, when the code makes it to the `parseChunk` method, you'll notice that the contents of `this._partialLine` contains the argument `chunk`.

I've dig a little bit into the code but since it is very large, I'm not sure fully what is going on. However, on pause, the line `_input = _input.substring(_parser.getCharIndex());` doesn't seem like it is necessary. If I set `_input` to just an empty string, issue is resolved.

**Comment by pokoli** [comment]
Could you please add a PR with your fix and a test case that reproduces your problem? 
It will be great to have this as part of papaparse

**Comment by duclet** [comment]
@pokoli - I can definitely create a PR but not with the fix I mentioned above. The reason being is that it was just me temporarily testing it out to see if it fixes the issue I was running into. Considering the line added over 5 years ago, I find it a little hard to believe no one has ran into this issue. That is why the line was there in the first place. Unfortunately, I don't have that knowledge so I can't commit any changes yet. I would like to take more time to figure out the entire flow and problem. That being said, if the original author can chime in for why it exists, that would be very helpful.

**Comment by pokoli** [comment]
@duclet Don't worry, just create the PR with the fix, a test that reproduces the issue. 

With all of this information we can decide if your fix is correct or if there is any side-effect.

**Comment by duclet** [comment]
@pokoli - Created the PR: https://github.com/mholt/PapaParse/pull/745
