### ISSUE TITLE
random newline character

### ISSUE THREAD

**Issue by elChapoSing** [mholt/PapaParse#737]
Why is paparse limiting the newline character to only \r, \n and \r\n ?
To simplify communication between OSes, I have gotten into the habit of delimiting new lines with other characters than the actual new lines characters.

**Comment by elChapoSing** [comment]
I ended up doing a regex replace before going through papaparse but that strikes me as inefficient...

**Comment by pokoli** [comment]
You can use the newLine config option to specify any newline you wan't.

**Comment by elChapoSing** [comment]
```
 let a = Papa.parse("a,b,c#1,2,3",
                {
                    newLine: "#",
                    header: true,
                    dynamicTyping: true
                }
            );
a
"{"data":[],"errors":[],"meta":{"delimiter":",","linebreak":"\n","aborted":false,"truncated":false,"cursor":11,"fields":["a","b","c#1","2","3"]}}"
```
From the [docs ](https://www.papaparse.com/docs#config): 

newline | The newline sequence. Leave blank to auto-detect. Must be one of \r, \n, or \r\n.
-- | --

**Comment by elChapoSing** [comment]
@pokoli what am I missing here ?

**Comment by pokoli** [comment]
Ups, I've missed the line @elChapoSing commented. So I think we should remove the newLine validation to accept any character.
