### ISSUE TITLE
Double characters &#39; resulting in incorrect parsing

### ISSUE THREAD

**Issue by llamamoray** [mholt/PapaParse#739]
I'm trying to parse the following csv (bad.txt):
```
A,B
1,"hello &#39;&#39;there"
```
[bad.txt](https://github.com/mholt/PapaParse/files/3847084/bad.txt)

this results in the following being returned from `Papa.parse`:
```
[{
  "A,B": "1,\"hello &#39",
  "__parsed_extra": [
    "&#39",
    "there\""
  ]
}]
```

If I replace the `&#39;` characters with `'` (in good.txt):
```
A,B
1,"hello ''there"
```
[good.txt](https://github.com/mholt/PapaParse/files/3847087/good.txt)

I get the expected output:
```
[{
  "A": 1,
  "B": "hello ''there"
}]
```

This is the call I'm using: 
```
  import Papa from 'papaparse';

  Papa.parse(files[0], {
    header: true,
    dynamicTyping: true,
    skipEmptyLines: 'greedy',
    complete: (results) => {
     // do something with the results
    },
  });
```
I'm using version 4.6.3

Am I missing an option I need to pass in, or is this a bug?

**Comment by llamamoray** [comment]
I've just upgraded to version 5.1.0 and the issue looks to be fixed. I can't see anything in the release notes though

**Comment by pokoli** [comment]
We only include new features on release notes. Probably this some bug that it had been fixed on a minor release. 

I'm closing this issues as it's already resolved
