### ISSUE TITLE
header not working

### ISSUE THREAD

**Issue by kintony** [mholt/PapaParse#744]
papaparse 5.1.0
An array is specified, but the first line is a header.

```
  let config = {
    header:  ["Full Name","Country","Created At","Id","Email"],
    skipEmptyLines: true
  };
  const stream = fs.createReadStream("test.csv");
  stream.pipe(Papa.parse(Papa.NODE_STREAM_INPUT, config))
  .on('data', (data) => {
     console.log(data);
  });

```

**Comment by pokoli** [comment]
I do not understand. Could you clarify which is the current outpunt and which is the output you spect?

**Comment by miso-belica** [comment]
Hi, my guess is that @kintony expects `header` option to `Papa.parse` can be list of columns. Actually it would be great. If the first line matches the columns it's skipped and if it does not then the fields are generated from given list. What do you think?

Or maybe to push it a little further. Header could be the function which can check the first line if it's the header or not and if not then return `false` or return list of headers defined by some heursistic.

What do you think about the idea?

**Comment by kintony** [comment]
I misunderstood that an array can be used for the header option.
