### ISSUE TITLE
How to convert array of arrays to json?

### ISSUE THREAD

**Issue by loongmxbt** [mholt/PapaParse#747]
Because of some use cases, I need to transpose the 2D array first and then convert to JSON. Now I use parse and unparse several times to do this. Is there a inner API something to convert array of arrays to json?

```js
const arr2dUnitPredictTransposed = transpose(Papa.parse(csvUnitPredict, { skipEmptyLines: true }).data)
const csvUnitPredictTransposed = Papa.unparse(arr2dUnitPredictTransposed)
this.unitPredictData = Papa.parse(csvUnitPredictTransposed).data
```
```json
// Example (header: false)
[
	["Column 1", "Column 2"],
	["foo", "bar"],
	["abc", "def"]
]
// Is there a API direct convert aoa to json?
// Example (header: true)
[
	{
		"Column 1": "foo",
		"Column 2": "bar"
	},
	{
		"Column 1": "abc",
		"Column 2": "def"
	}
]
```

**Comment by pokoli** [comment]
I'm sorry to say that we do not have this api and I don't think is the responsability of PapaParse of expose something like this. PapaParse is designed to only parse CSV files so the developer using it can use any needed transformations before the parse/unparse.

**Comment by 10xchs** [comment]
It's a parser that doesn't parse. Got it!
