### ISSUE TITLE
Architecture Missing in docs

### ISSUE THREAD

**Issue by charanjit-singh** [mholt/PapaParse#757]
I've been studying PapaParse's code from 2 days. It is difficult to understand for a programmer, without proper architecture defined in the docs. I have to read to code and interpret the concept, which could be wrong also!!

**Comment by pokoli** [comment]
I'm not sure to understand what do you mean by "architecture"

Could you please clarify?

**Comment by pokoli** [comment]
I'm closing this as there is no reply for more than one month. 

I've you don't agree please re-open it providing a better explanation of what is missing.
