### ISSUE TITLE
conditional parsing (filtering csv)

### ISSUE THREAD

**Issue by rogerburton** [mholt/PapaParse#759]
I apologize for my poor English.

a suggestion:
patrse the rows of a csv file with conditions.  For example:
header: 
name,     age
data :    
Tom,       28
             Sam,       32
             Eloise,     24

Condition: parse only if age < 30

Thx.
Roger burton

**Comment by pokoli** [comment]
Hi @rogerburton, 

Thanks for your sugestion but this is out of the scope of Paparse. Paparse is only responsible of reading the CSV file and then return it as list on developer. Once this is done the developer can filter the rows as it wants. 

So I'm closing this issue.
