### ISSUE TITLE
Utf8 encoding failing on large input streams

### ISSUE THREAD

**Issue by bencohen2** [mholt/PapaParse#763]
I have a csv of 300,000+ lines, where one of the lines is:

```
1339525|A|1619877|Boż Lś||2348538|||2014|Finalist 
```

The parsing of this line fails (the `Boż Lś` ends at the first unusual character, resulting in `Bo`, and the `ż Lś` part is completely cut off).

However, when I put this line on its own in a csv with just 1 line, the parsing works fine. I'm using the following configuration:

```
fastMode: true,
    delimiter: '|',
    encoding: 'utf-8',
    step: (results, parser) => {}
```
Where I `parser.pause()` right before a database `put`, and `parser.resume()` after the `put`. What could be causing this issue?

**Comment by pokoli** [comment]
did you try without fastmode?

**Comment by bencohen2** [comment]
> did you try without fastmode?

Yes

**Comment by pokoli** [comment]
So we need an easy way to reproduce it otherwise it will be very hard to fix it.

**Comment by pokoli** [comment]
Probably related to #751 ??

**Comment by bencohen2** [comment]
Potentially related to #751, although in my case it doesn't come up as the ?-looking characters, the parse is actually just incorrect, i.e. a csv line with 10 values comes in as 4 or 5 values because of the special characters (in this case, š).

**Comment by bencohen2** [comment]
@pokoli This issue happened for the entry on line 6300. When I put it in a file on its own it worked just fine, so I thought that it might be because of scale. So I tried putting lines 1-7000 in their own file and it worked properly. I think that my zip -> csv unzipping might have been broken, or maybe VSCode corrupted the files somehow, because when I copy-pasted the entire 300,000 line file to a new file with the `.csv` suffix, parsing works perfectly. I think this issue can be closed.
