### ISSUE TITLE
Change in behaviour?

### ISSUE THREAD

**Issue by Aequitas737** [mholt/PapaParse#764]
I've had version `^4.5.0` of PapaParse for a while now, I've also got a unit test that just recently started failing.

My parsed data has a `\n` at the end of the string, which seems to now get stripped out causing the test to fail. Not sure how this has happened without an update.

Anyone know of any reason this could have just started failing now? I was thinking maybe an update to the dependencies of this library?

**Comment by pokoli** [comment]
Probably this was due to some patch version release that fixed some behaviour your test suite was reling on.
