### ISSUE TITLE
Newline return character is not recognized

### ISSUE THREAD

**Issue by defusioner** [mholt/PapaParse#781]
Hello,
I'm trying to parse a file with (I think) different newline characters and autodetection does not wrap second and third lines (I have a hidden return character between them).

File: 
[Train-Iris_-_Train-Iris.txt](https://github.com/mholt/PapaParse/files/4439045/Train-Iris_-_Train-Iris.txt)

Example: upload the file to https://codepen.io/VsevolodTS/pen/mMXJrv

Probably I'm missing some tech basis, could you tell me if it is the file that is broken?

Thanks

**Comment by defusioner** [comment]
Hello, any updates on that?

**Comment by demetris-manikas** [comment]
It does have different newline characters.
I used vi to fix it.

**Comment by pokoli** [comment]
Then I think we do have nothing to fix. 
A file with diferent newline characters is not a valid file for parsing.

**Comment by defusioner** [comment]
@pokoli Hello, just in case, is there a way to check different newline chars before parsing?
