### ISSUE TITLE
getNextUnquotedDelimiter function seems to be useless

### ISSUE THREAD

**Issue by FarSeeing** [mholt/PapaParse#782]
Hello.
Maybe I'm missing something really obvious but it seems that `getNextUnquotedDelimiter` is useless now.

It gets called from 2 places - from the same function on [line 1776](https://github.com/mholt/PapaParse/blob/master/papaparse.js#L1776) and from the outside on [line 1630](https://github.com/mholt/PapaParse/blob/master/papaparse.js#L1630)

Let's check this outside call:
```javascript
// we check, if we have quotes, because delimiter char may be part of field enclosed in quotes
if (quoteSearch > nextDelim) {
    // we have quotes, so we try to find the next delimiter not enclosed in quotes and also next starting quote char
    var nextDelimObj = getNextUnquotedDelimiter(nextDelim, quoteSearch, nextNewline);
```

Now let's check the function definition:
```javascript
/** Gets the delimiter character, which is not inside the quoted field */
function getNextUnquotedDelimiter(nextDelim, quoteSearch, newLine) {
    var result = {
        nextDelim: undefined,
        quoteSearch: undefined
    };
    // get the next closing quote character
    var nextQuoteSearch = input.indexOf(quoteChar, quoteSearch + 1);

    // if next delimiter is part of a field enclosed in quotes
    if (nextDelim > quoteSearch && nextDelim < nextQuoteSearch && (nextQuoteSearch < newLine || newLine === -1)) {
        // some code skipped here
    } else {
        result = {
            nextDelim: nextDelim,
            quoteSearch: quoteSearch
        };
    }

    return result;
}
```
Turns out this `if` condition in function will never happen because `nextDelim` will always be less than `quoteSearch` in this outside function call and function just returns passed arguments.

**Comment by pokoli** [comment]
Did you tested removing it and executing our test suite? It may give a clue of some cases where it's used

**Comment by FarSeeing** [comment]
Yes, I've tried running the tests - function is not tested, all tests run fine w/o it and it's not exposed so yes, it still seems to be useless.

**Comment by pokoli** [comment]
Then it will be good to provide a PR to remove it.
