### ISSUE TITLE
Bug linebreak COVID Data

### ISSUE THREAD

**Issue by strawberry-code** [mholt/PapaParse#785]
Trying to get a JSON from: [https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv](https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv)

By using:

Papa.parse(url, {})

Linebreak fail.

**Comment by pokoli** [comment]
What does "Linebreak fail" mean? 

Papa.parse has a set of options that you may define to specify the read format so the file is correctly read.

**Comment by strawberry-code** [comment]
I don't know what does it mean, I get this error when trying to parse the CSV linked above. 

However, I found a JSON version alternative for the same data so I didn't investigated anymore on this error.
