### ISSUE TITLE
unparse() does not allow selecting a custom delimiter for an array inside a column

### ISSUE THREAD

**Issue by chrisborrelli** [mholt/PapaParse#787]
unparse() seems to use toString() to convert the contents of a column into a string, and toString() only separates array elements by comma. I wonder if join can be used more generically with an added config option, perhaps called subArrayDelimiter or something like that.

If this is acceptable I can try submitting a pull request. I likely need this for a project I am working on so I tried a simple test that seems to work. The code below uses a ';' instead of the default ',' as a delimiter for columns that are arrays. If this acceptable I can try adding a new config option for unparse().

~~~
--- a/papaparse.js
+++ b/papaparse.js
@@ -447,7 +447,8 @@ License: MIT
                        if (str.constructor === Date)
                                return JSON.stringify(str).slice(1, 25);
 
-                       var escapedQuoteStr = str.toString().replace(quoteCharRegex, _escapedQuote);
+                        let tmpStr = (Array.isArray(str)) ? str.join(';') : str.toString() ;
+                       var escapedQuoteStr = tmpStr.replace(quoteCharRegex, _escapedQuote);
 
                        var needsQuotes = (typeof _quotes === 'boolean' && _quotes)
                                                        || (typeof _quotes === 'function' && _quotes(str, col))`
~~~

**Comment by pokoli** [comment]
I think the best option is to convert your array to a string separated by the character you prefer before parsing.

PapaParse is focused on parse/unparse but not on transforming data. It is expected that you provide the data already transformed to the library.

I appricieate your time to create this proposal but I'm sorry to say that we must reject it.

**Comment by chrisborrelli** [comment]
Thanks for the consideration. Just to complete this thought experiment, here is the solution I am going with for now mostly because it is easy and my data sets are not too big. When I create my array I will override the toString property to use join. Not the best solution, but it was the least amount of code and I don't have to make copies of the structure or crawl it when serializing to CSV as you suggested, but it has the same result.

~~~
      item.photoList.toString = function() {
        return this.join(';');
      }
~~~
