### ISSUE TITLE
Calling Papa.parse in worker with _config.worker = false calls postMessage

### ISSUE THREAD

**Issue by shubhanus** [mholt/PapaParse#788]
I am calling `Papa.parse` in my own worker and in `_config.worker` is set false. 
When process completes it calls `postMessage` still that triggers a message to my own worker.
Shouldn't [this](https://github.com/mholt/PapaParse/blob/master/papaparse.js#L529) 
```
if (IS_PAPA_WORKER)
{
	global.postMessage({
		results: results,
		workerId: Papa.WORKER_ID,
		finished: finishedIncludingPreview
	});
}
```
Should also check if `config.worker` is set to `true` then only call `global.postMessage`.
Was this done intentionally?

**Comment by flakey-bit** [comment]
This issue is affecting us too.

**Comment by flakey-bit** [comment]
I've had a go at addressing this, see https://github.com/mholt/PapaParse/pull/937

**Comment by pokoli** [comment]
Hi @flakey-bit,

Everything looks fine now but before merging I'm wondering if it makes sense to re add the [test](https://github.com/mholt/PapaParse/commit/4ecae0b5bbcc76a16abecded59792ed9cea750cb#diff-e0ce8cb4901057c1880bee545909a64f38c7383b4d41982d6f2db9a8ec81eac7L2101) that was removed when causing this issue. Maybe we do not need the same test but somethigns similar. What do you think?

**Comment by flakey-bit** [comment]
Test added.

**Comment by flakey-bit** [comment]
Test added.
