### ISSUE TITLE
Meta data in CSV

### ISSUE THREAD

**Issue by dolanmiu** [mholt/PapaParse#794]
I am tasked to parse a CSV file, but however, there is some meta data above the actual CSV content:

Can PapaParse handle this scenario?

![Screenshot 2020-05-19 at 18 39 37](https://user-images.githubusercontent.com/2917613/82359683-1d459b80-9a00-11ea-9859-dba052f41607.png)

Notice how the CSV actually starts on line 34

**Comment by pokoli** [comment]
Yes, you can use the skiplines option to skip the first 34 lines and start parsing when required.

**Comment by dolanmiu** [comment]
Is there a way to also parse the first 34 lines?

I need those data points too @pokoli

**Comment by dolanmiu** [comment]
skipLines cant be found in the docs:

https://www.papaparse.com/docs
