### ISSUE TITLE
Security vulnerability

### ISSUE THREAD

**Issue by DeeElGee** [mholt/PapaParse#801]
Sorry if this has already been posted, but npm audit is reporting a high vulnerability in this project:

![Screenshot 2020-06-01 at 13 00 29](https://user-images.githubusercontent.com/359846/83407148-ff1c6a00-a407-11ea-825a-197784f20542.png)

**Comment by pokoli** [comment]
This has been reported as https://github.com/mholt/PapaParse/issues/777 
which is already fixed and released.

As indicated on the vulnerability report the fix is already included on latest 5.2.0 version
