### ISSUE TITLE
Bug with unparsing empty objects

### ISSUE THREAD

**Issue by casperbrike** [mholt/PapaParse#802]
### Prerequisites

PapaParse: 5.2.0
Environment: Node 10.14.1

### Description
Empty objects are converted into `[object Object]` string instead of empty string when unparsing data. 

### Steps to reproduce
```javascript
const Papa = require('papaparse')

console.log(
  Papa.unparse(
    [[null, undefined, 1, new String("lorem"), {}]]
  )
)
```

**Expected**
```javascript
,,1,lorem,
```

**Actual**
```javascript
,,1,lorem,[object Object]
```

**Comment by pokoli** [comment]
For me if you pass an object it is correct to add them it with it's string representation on the file. So this is not a bug. 

PapaParse is focused on CSV parsing/unparsing and it does not try to convert the data that it receives, this is the user responsability. So for me you should ensure that the right values are passed to the unparse method.
