### ISSUE TITLE
Date parse

### ISSUE THREAD

**Issue by awariat** [mholt/PapaParse#803]
I use Papaparse to parse CSV . In my file I have column with dates:

DD/MM/YYYY

But Papaparse changes it to format DD-MM-YYYY. How to force Papaparse to stop doing it? If I resave my CSV using Excell it works OK and it is parsing like in source file.

**Comment by pokoli** [comment]
PapaParse only tries to parse dates when using dynamicTyping setting. So you should disable the dynamic typing if you do not want them to evaluate the types of the columns. 

I'm closing this issue as there is nothing to fix from our side.
