### ISSUE TITLE
Guessing wrong delimiter

### ISSUE THREAD

**Issue by Klingseis** [mholt/PapaParse#804]
In #687 there was new guessing of right delimiter added. Right now I'm facing the issue, that it predicts "," (Comma) instead of ";" (semicolon).

The reason for this seems to be the final checking if the previewed delimiter is better or not:
`if ((typeof bestDelta === 'undefined' || delta <= bestDelta)
					&& (typeof maxFieldCount === 'undefined' || avgFieldCount > maxFieldCount) && avgFieldCount > 1.99)`

~The delta for semicolon (0) is smaller than bestDelta (5) but the avgFieldCount equals maxFieldCount. For me this looks like you could assume that this delimiter is better, couldn't you?
Maybe I am wrong, but wouldn't it be better to compare avgFieldCount >= maxFieldCount if the delta is smaller?~

[testGeometries.txt](https://github.com/mholt/PapaParse/files/4805708/testGeometries.txt): File to reproduce similar issue.

One correction from my side: My thought above of comparing avgFieldCount >= maxFieldCount if delta is smaller doesn't work.
In attached file delimiter is semicolon, papaparse guesses comma:

comma delta: 4, comma avgFieldCount: 4.6
semicolon delta: 0, semicolon avgFieldCount: 3

**Comment by Klingseis** [comment]
[testGeometries.txt](https://github.com/mholt/PapaParse/files/4805607/testGeometries.txt): File to reproduce similar issue.

One correction from my side: My first thought of comparing avgFieldCount >= maxFieldCount if delta is smaller doesn't work. 
In attached file delimiter is semicolon, papaparse guesses comma:
- comma delta: 4, comma avgFieldCount: 4.6
- semicolon delta: 0, semicolon avgFieldCount: 3

**Comment by Githamza** [comment]
I have the same issue, any solution ?

**Comment by Klingseis** [comment]
I use PapaParse together with GUI. If a parsing error occurs or the result is only one column, a fieldset will be displayed to the user where he can type in a delimiter by his own and parse the file again.

**Comment by Klingseis** [comment]
Will close this one. Only solution right now is to set the delimiter directly instead of guessing it by PapaParse.
