### ISSUE TITLE
Question: Different errors

### ISSUE THREAD

**Issue by CarlosHdez** [mholt/PapaParse#808]
Hi,
I just noticed that when using `.parse` there are two ways to handle errors, either
```
Papa.parse(file, {
  error: () => {/*handle error */},
  ... 
})
```
or 
```
Papa.parse(file, {
  complete: ({errors, data}) => {
    if (errors.length > 0) //handle error
  }
})
```
And i was wondering if there is a difference between this two options

Thanks

**Comment by CarlosHdez** [comment]
Hi, is there a way I could get an answer for this?
Thanks

**Comment by pokoli** [comment]
Sorry for the late repply. The only diference is that the method is called for each error and the complet is just called once with all errors. 

I'm closing this issues as there is nothing to fix from our side. 

Thanks

**Comment by CarlosHdez** [comment]
Ohh that makes sense, thanks for the response, all the times I tried this I always had only 1 error so I didn't noticed the difference.
Again thanks for the response and sorry if it wasn't the appropriate place for the question.
