### ISSUE TITLE
error while running "npm run build"

### ISSUE THREAD

**Issue by mergingseas** [mholt/PapaParse#812]
When including react papaparse npm module and then doing **npm run build** to create optimized build I get the following error.

Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file: 

 	./node_modules/react-papaparse/dist/react-papaparse.es.js:13:28612 

Read more here: http://bit.ly/2tRViJ9

I tried this with node v13.11 and v8

**Comment by pokoli** [comment]
I see the error is related to react-papaparse.
Where it is it's packages and what it has in common to papaparse?

**Comment by pokoli** [comment]
I'm closing this issue as no further feedback has been provided in 3 months. Please provide and example to reproduce the issue in order to be able to fix it.
