### ISSUE TITLE
Bug: Less Than sign breaks the column import

### ISSUE THREAD

**Issue by shyamal890** [mholt/PapaParse#815]
Using **<** or **>** sign is being consider as a delimiter when its not.

**Comment by pokoli** [comment]
Could you please share and example to reproduce the issue?
Are you ussing guessDelimiter option? If yes disabling it should solve the issue.

**Comment by pokoli** [comment]
I'm closing this issue as no further feedback has been provided in 6 months. Please provide and example to reproduce the issue in order to be able to fix it.
