### ISSUE TITLE
Google Sheets: Different data parsed when on mobile?

### ISSUE THREAD

**Issue by Rinyuu** [mholt/PapaParse#824]
Okay, so I'm a huge noob and not very good at stuff like this at all, so I hope this is not something very stupid:

I use PapaParse to pull some data from one of my Google Spreadsheets, to use on my website. This works perfectly fine... 
At least when accessing the website from a desktop!

When using a phone, or even when using the Chrome Dev Tools in mobile mode, the sheet didn't get parsed at all.
I added a delimiter (","), and this seems to make it parse in mobile mode as well... but the parsed data I can see in the console is completely different from the data I get in desktop mode... Why is there a difference?

Is PapaParse not compatible with mobile? Or does Google give me a different version of the sheets when requesting it from a mobile user agent?

**Comment by pokoli** [comment]
There is no diference on the code run by PapaParse in mobile and on desktop.

Probably this is related to google sheets behaving diferently depending on the device. 

I think there is nothing to fix from our side so I'm closiing this issue. 

If you think there is a something wrong with our library please provide a code sample to reproduce the issue outside google sheets.
