### ISSUE TITLE
Add browser streaming capability

### ISSUE THREAD

**Issue by Josh-Weston** [mholt/PapaParse#826]
Is there any desire for a pull request to add browser streaming functionality? I have implemented it for an isolated use case:

- I needed to stream data to the browser
- The data is streamed from a database
- I do not know the content-length or byte ranges ahead of time
- The target browser supports **fetch()** and  **ReadableStream API**

Going through the source code I could not find what I was looking for, so I implemented the following in my cloned repo:

```
// Pipes browser streaming capability into Papa Parse
// Useful when content-length is unkown (e.g. streaming from a database)
function BrowserStreamer(config) {
	config = config || {};
	if (!config.chunkSize)
		config.chunkSize = Papa.RemoteChunkSize;
	ChunkStreamer.call(this, config);
	const decoder = new TextDecoder('utf-8');
	this.stream = async function(url)
	{
		try {
			const stream = await fetch(url).then((res) => res.body.getReader());
			this._nextChunk = function() {
				stream.read().then(({ done, value }) => {
					if (done) {
						this._finished = true;
						this.parseChunk('');
						return;
					}
					this.parseChunk(decoder.decode(value));
				});
			};
			this._nextChunk();	// Starts streaming
		} catch (err) {
			this._finished = true;
			this.parseChunk(`Error accessing or parsing data: ${err}`);
			return;
		}
	};
}
BrowserStreamer.prototype = Object.create(ChunkStreamer.prototype);
BrowserStreamer.prototype.constructor = BrowserStreamer;
```

```
// Add another config option
if (_config.browser) {
	streamer = new BrowserStreamer(_config);
```

```
// Accessing the new capability 
const url = 'http://someurl.com';
Papa.parse(url, {
    browser: true,
    delimiter: ',',
    newline: '\n',
    complete: () => {
        console.log('All done!')
    },
    step: (results, parser) => {
        console.log('step results');
        console.log(results.data);
    }
});
```

This was a quick implementation that needs more guard rails and syntax regression, but it should provide enough context. If it's something of value, I can add some rigor and submit as a pull request.

**Comment by pokoli** [comment]
Hi @Josh-Weston 

Yes this adds some value please create a pull request with redefined code so we can review. 
We require to have a minimal tests case to test that the new functionalit works correctly. 

BTW: We have an option to download a file from a URL, maybe the setting will be a complement of download to just enable the sreaming. Could you please check it?

**Comment by pckhoi** [comment]
+1

**Comment by MichaelSp** [comment]
isn't this what has been requested in #550 ?

**Comment by pokoli** [comment]
Yes it is. I'm closing this as duplicate.

Thanks @MichaelSp !
