### ISSUE TITLE
Documentation is out of sync with the latest release

### ISSUE THREAD

**Issue by Koziar** [mholt/PapaParse#827]
Hey guys, when are you going to release [this](https://github.com/mholt/PapaParse/pull/796) change?

It seems like your [documentation](https://www.papaparse.com/docs#config) is out of sync with your latest release!
I need to use the `escapeFormulae` option which is listed in your documentation but the [latest release](https://github.com/mholt/PapaParse/releases/tag/5.2.0) was on the 2nd April, so before the change was implemented.

**Comment by vp-miketaylor** [comment]
I also need to use `escapeFormulae`. I am trying to avoid having to create a workaround this week.

**Comment by pokoli** [comment]
I've uploaded PapaParse 5.3.0 which contains this fix!

Sorry for the delay!
