### ISSUE TITLE
Arabic support

### ISSUE THREAD

**Issue by BENLKAMLENourdine** [mholt/PapaParse#828]
Papaparse doesn't parse csv files with columns containing arabic words, it returns some errors with data but it doesn't containe all the columns and the encoding is wrong

**Comment by pokoli** [comment]
Hi @BENLKAMLENourdine, 

Which encoding are you using? 

Could you provide an example to reproduce the issue?

**Comment by BENLKAMLENourdine** [comment]
Hi @pokoli,

you will find the file in the attachments. it contains 10000 row
the encoding is UTF32
here is my code: 

this.config: {
	delimiter: "",	// auto-detect
	newline: "",	// auto-detect
	quoteChar: '"',
	escapeChar: '"',
	header: false,
	transformHeader: undefined,
	dynamicTyping: false,
	preview: 0,
	encoding: "",
	worker: false,
	comments: false,
	step: undefined,
	complete: function(results) {
	console.log("Parsing complete:", results);
},
	error: function(error) {
	console.log("Parsing error:", error);
},
	download: false,
	downloadRequestHeaders: undefined,
	downloadRequestBody: undefined,
	skipEmptyLines: false,
	chunk: undefined,
	chunkSize: undefined,
	fastMode: undefined,
	beforeFirstChunk: undefined,
	withCredentials: undefined,
	transform: undefined,
	delimitersToGuess: [',', '\t', '|', ';', Papa.RECORD_SEP, Papa.UNIT_SEP]
}

Papa.parse(this.file, this.config)

the result in the console:

<img width="776" alt="Screenshot 2020-09-10 at 14 36 51" src="https://user-images.githubusercontent.com/16447200/92737477-12c65d80-f373-11ea-99b7-1427338975c3.png">
<img width="981" alt="Screenshot 2020-09-10 at 14 37 08" src="https://user-images.githubusercontent.com/16447200/92737506-1ce85c00-f373-11ea-8603-ba4de32a674b.png">
<img width="1102" alt="Screenshot 2020-09-10 at 14 37 20" src="https://user-images.githubusercontent.com/16447200/92737528-240f6a00-f373-11ea-8a61-1091ef35953c.png">
[Bulkupload100sar (10).xlsx](https://github.com/mholt/PapaParse/files/5202002/Bulkupload100sar.10.xlsx)

**Comment by pokoli** [comment]
Why you do not use "UTF32" as encoding parameter? 
This should fix the issue.

**Comment by BENLKAMLENourdine** [comment]
i tried it, it doesn't work

**Comment by pokoli** [comment]
The problem is that you are importing an Excel file but PapaParse only imports CSV file.

If you import a CSV file with the right encoding PapaParse will import it correctly
