### ISSUE TITLE
BOM isn't removed in Android (react-native environment)

### ISSUE THREAD

**Issue by giregk** [mholt/PapaParse#833]
I fetched a CSV file without papa, extracted its text content, and fed it to papa.parse.

The file, hence the string, contained a BOM.

This caused the first header name to include the BOM, which then created a bug in my app because I was trying to access the value for a key (the header without the BOM) that didn't exist.

I think papa should check for this and remove the BOM if it exists.

This happens for me only on Android. I'm writing a react-native app, so using the Android javascript environment which might be different from a browser javascript. I haven't checked in an browser. I don't have that issue on iOS where the javascript environment is different.

I fixed this issue in my app by manually removing the BOM before parsing the string (this works in my case, but this assumes the first header starts with a letter.

```
let rawCSV = ...

// remove BOM if it exists
if (!rawCSV.match(/^[a-zA-Z]/)) {
    rawCSV = rawCSV.substring(1);
}

Papa.parse(rawCSV, {...});
```

**Comment by pokoli** [comment]
I think PapaParse should parse the file correctly if it contains the BoM.
Could you please provide some test case to reproduce the issue? This way we can create include it on our test suite, provide a fix and ensure that the behaviour is keep for newer versions.

**Comment by pokoli** [comment]
I'm closing this issue as no further feedback has been provided in 3 months. Please provide and example to reproduce the issue in order to be able to fix it.
