### ISSUE TITLE
Date strings being enquoted 

### ISSUE THREAD

**Issue by Frinkiac-7** [mholt/PapaParse#834]
I have a file with the following structure:

```
Record Year,Record #,Name of Deceased,Date of Birth,Date of Death
1976,1,NAMEOF PERSONHERE,10/32,01/01/1976
```
Everything works for the most part but for some reason the output has the last date field encased in quotes as shown below:

```
1992,3166,NAMEOF PERSON1,07/11/1921,"12/16/1992"
1992,3167,NAMEOF PERSON2,10/26/1920,"12/15/1992"
```
I don't know why the last date field is being enquoted and I would like it not to be.  The fs.write method syntax is as follows:
```
   outputFile.write(results[prop]['Record Year'] + ',' + 
    results[prop]['Record #'] + ',"' + 
    results[prop]['Name of Deceased'] + '",' + 
    results[prop]['Date of Birth'] + ',' + 
    results[prop]['Date of Death'] + '\r\n')
```

My config options are as follows:

```
delimiter: ',', header: true, dynamicTyping: true, skipEmptyLines: true
```

Can anyone shed some light on why this is the case?  

Thanks in advance.

**Comment by pokoli** [comment]
Have you tried setting quoteChar?

**Comment by Frinkiac-7** [comment]
OMG...I just realized I was looking in completely the wrong place.  My problem is self-inflicted and horribly embarrassing.  I'm just going to thank you for taking the time to respond and apologize for the colossal stupidity on my part.  If we could all just pretend this never happened that would be greeeeeaaaaat...
