### ISSUE TITLE
skip specific line in the step callback

### ISSUE THREAD

**Issue by hanct** [mholt/PapaParse#838]
Hi, 
I noted that there is a step callback which i can use to examine each line of data in the CSV file during parsing. Inside this step callback, is there a way for me to specify that I want to skip a specific line (based on some condition), so that it will not be parsed into the memory.

**Comment by pokoli** [comment]
Hi @hanct, 

This is not possible on PapaParse and I think it is not anything that we should implement. 

You just need to parse the entire file in memory and then skip the rows that you are not intersted on. 
If you have any memory concers you can use async javascript to filter the lines so it won't use all of your machine memory.

**Comment by hanct** [comment]
> Hi @hanct,
> 
> This is not possible on PapaParse and I think it is not anything that we should implement.
> 
> You just need to parse the entire file in memory and then skip the rows that you are not intersted on.
> If you have any memory concers you can use async javascript to filter the lines so it won't use all of your machine memory.

ok. noted. Thanks. I was initially thinking along the line that the step callback could return a boolean value. True to accept, False to skip.

**Comment by pokoli** [comment]
The goal of PapaParse is just parsing files.
Manipulating data is out of the scope of the library and should be done after the results are parsed.
