### ISSUE TITLE
Papaparse not parsing the last file

### ISSUE THREAD

**Issue by tbhaxor** [mholt/PapaParse#846]
I have a csv file with error. I want to show the error and let user select the file again and then parse it again.

But when i am re-uploading same file. It is not being parsed

Here is an code to reproduce this bug

    $(document).ready(function() {
      $("#file").on("change", function(e) {
        const file = e.target.files[0]
        
        Papa.parse(file, {
          header: true,
          skipEmptyLines: true,
          trimHeaders: true,
          complete: ({ data: json, errors: e }) => {
            if (e[0]) {
              console.log('failed to parse', file.name);
            } else {
              console.log('parsed', file.name);
            }
          },
          error: (e) => {
            console.log('failed to parse', file.name);
          }
        })
      })
    })

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/PapaParse/5.3.0/papaparse.min.js"></script>

    <input type="file" id="file">

And here is the GIF of the issue

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/WrUrG.gif

**Comment by pokoli** [comment]
It does not seem an issue with papapParse but an issue with the code you use to read the files.
It seems that the second run the file is not correctly passed to PapaParse so it receives an empty file and it fails.

I'm closing the issue, please share a minimal scenario to reproduce it just using PapaParse if you don't agreee.
