### ISSUE TITLE
Papa.download is not a function

### ISSUE THREAD

**Issue by simplenotezy** [mholt/PapaParse#850]
I am trying to use this function, but I am getting error `Papa.download is not a function`.

This is how I call the function:

                        Papa.download(Papa.unparse([
                            this.data.header,
                            ...this.data.rows
                        ]), slugify(this.webshop.name + ' Products') + '.csv'); // download CSV file

I included the library from here: https://unpkg.com/papaparse@latest/papaparse.min.js

What am I missing? Do I need to a specific vendor file for the "download" method?

**Comment by pokoli** [comment]
Download should not be called directly. Indeed you should only set it's value to true on config and PapaParse will download from the URL. 

See the Parse Remote file of [our documentation](https://www.papaparse.com/docs) for an example.

I'm closing this issue as there is nothing to fix from our side.
