### ISSUE TITLE
Add headerQuotes option to unparse

### ISSUE THREAD

**Issue by davemecha** [mholt/PapaParse#851]
On `unparse` the header row is quoted in the same way as the content as stated in the `quotes` option. But in most cases the header is a string, even if the columns of the column are e.g. numbers.

It would be great to have a simple boolean option `headerQuotes` to enable quotes for all header cells.

Alternatively the header row could be fully quoted automatically, if the `quotes` option is set. Or the `headerQuotes` option could have the same semantics as the `quotes` option.

**Comment by pokoli** [comment]
I do not see any problem about having a quoted Header when the content is header. 

Why is this an issue for you? Could you describe which problems are you experiencing?

**Comment by davemecha** [comment]
Ok, I just was confused by the output of something like:

```ts
let data = [
  {
    "My Id": 5,
    "My Name": "Dave"
  }
]

let options = {
    header: true,
    quotes: [false, true]
}

Papa.unparse(data, options)
```

It is 

```
My Id,"My Name"
5,"Dave"
```

I was hoping to get something like this, since the header contains only strings:

```
"My Id","My Name"
5,"Dave"
```

I was mistakenly thinking, this could lead to a problem, if a numeric header contains a comma, but bith the header `My, id`, I get a quoted header in the output. So there is no problem with this.

So my issue lost on relevance for now and at most serves cosmetic purposes any more. - Sorry for not testing this out more in advance.

**Comment by pokoli** [comment]
Don't worry. I'm closing this issue as there is nothing to implement from our side.

Thanks for your feedback!
