### ISSUE TITLE
The minified version on the CDN does not have an index in transformHeader

### ISSUE THREAD

**Issue by djave-co** [mholt/PapaParse#854]
In this CDN version of 5.3:

https://cdnjs.cloudflare.com/ajax/libs/PapaParse/5.3.0/papaparse.js

`transformHeader` contains the index variable `i`:

    if (isFunction(_config.transformHeader))
      header = _config.transformHeader(header, i);

In the minified version of the same:

https://cdnjs.cloudflare.com/ajax/libs/PapaParse/5.3.0/papaparse.min.js

That index variable has been removed:

    (m.transformHeader)&&(e=m.transformHeader(e))

I'm unsure if this is a bug with the minification process, the CDN or if it just wasn't minified before being pushed to the repo.

Thanks so much for the amazing repo, absolutely fantastic! 🥰🥰

**Comment by pokoli** [comment]
It's strange as the minified version was updated on our release process: 

https://github.com/mholt/PapaParse/commit/5747da6c9927642743d6d44d49689be2d2fa0b10
