### ISSUE TITLE
unparse null and undefined values with forced quotes

### ISSUE THREAD

**Issue by janisdd** [mholt/PapaParse#858]
I'm not sure if this intended or not...

When `unparsing` and the value is `null` or `undefined` and the unparse config has `quotes: true` (or array, function, ... which forces quotes),
I would expect `null,null` to become `"",""` currently it gives `,` 

Input data:
`a,b,c`
`null, undefined, null`

Expected:
`"a","b","c"`
`"", "", ""`

Actual:
`"a","b","c"`
`, , `

I can create a PR if this is an error

**Comment by pokoli** [comment]
Hi janisdd, 

The files is correct with current format. If you use paparse to read it I will parse it corerectly. 

Why you expect empty fiels to be quoted?

**Comment by janisdd** [comment]
Hm input data was a bit misleading...I meant already read data (unparse js array)

Maybe this unparse test case makes it more clear:

```js
var UNPARSE_TESTS = [..., 
{
  description: "Force quotes around null and undefined fields",
  input: [['a', 'b', 'c', 'd'], [null, undefined, '', 'e']],
  config: { quotes: [true, true, true, false] },
  expected: '"a","b","c",d\r\n"","","",e'
}]
```


Reading is ok but writing should output quotes if I specify `quotes: true` in the config, I guess?

**Comment by pokoli** [comment]
Yes, I understood your issue but AFAIR empty fields never get quoted in CSV. This is the behaviour in most CSV files generators and we keep the same and I do not think we should do it diferent. 

My question was: Why you need it to be enclosed? Is this causing any issue or just a cosmetic change?

**Comment by janisdd** [comment]
Didn’t know that null and empty should never be quotes in csv… If this is common knowledge everything works as expected. Maybe we can add a small hint in the docs for the `quotes` unparse option that it does not apply for null and undefined values?

**Comment by pokoli** [comment]
@janisdd Makes sense! If you create a PR for the docs I will be happy to merge it.
