### ISSUE TITLE
Question: [object Object] when parsing from json to csv

### ISSUE THREAD

**Issue by henriktorget** [mholt/PapaParse#859]
Does papaparse not parse nested objects? 
I have not seen any config properties that makes it parse recursively...

input:

```
[
{
  "location": {
    "lat": 59.075,
    "long": 10.246667
  },
  "id": 4462534835058440,
  "rowNumber": 0,
  "externalId": "cast_wod_2_2018_34350",
  "value": {
    "level": "level_3",
    "geo_index": "34350",
    "geo_long": "10",
    ...
  },
  "time": "2018-06-04T22:00:00.000Z"
},
{
  "location": {
    "lat": 59.075,
    "long": 10.246667
  },
  "id": 4462534835058440,
  ...
}
]
```

output:

`[object Object],4462534835058440,0,cast_wod_2_2018_34350,[object Object],2018-06-04T22:00:00.000Z`

**Comment by pokoli** [comment]
No, this is not supported. You should extract the needed properties of the object you want to parse. 
In case you want to dump the full object as json, you should convert it to it's string representation.
