### ISSUE TITLE
Delimiter is not detected rightly

### ISSUE THREAD

**Issue by Githamza** [mholt/PapaParse#860]
I have a file with no header that contains this data structure 

```
column ; comlumn2,comlumn2,comlumn2,

column ; comlumn2,comlumn2,comlumn2,

column ; comlumn2
```
here  the delimiter is `;` but the library is detecting `,` 

Is the last line there is no `,` so why the library still detect `,` ?

Any solution ?

If I add a header how to tell library to detect delimiter only on header.

I found same case [here](https://github.com/mholt/PapaParse/issues/804#issue-641914541) but I don't have header and last line does not contain `,`

**Comment by janisdd** [comment]
Papaparse is fault tolerant (sort of) and is parsing your csv even if the last row misses some delimiters (of fields).

So when we assume fault tolerance, why would you pick `;` over `,`? `,` produces more fields and this is normally a good guess.

**Comment by Githamza** [comment]
because some fields contains `,` which is not a delimiter but only a field char

**Comment by janisdd** [comment]
Again, `,` seems to be the "better" delimiter here as it produces more fields (which is probably desired in 90% of all cases).

You can set the delimiter directly when parsing or only use the first x lines of the data as I described here: https://github.com/mholt/PapaParse/issues/861#issuecomment-860084246

**Comment by Githamza** [comment]
Thanks for the help, it will be very useful if we can specify the detection method : a "better delimiter method" or "most used one"

**Comment by Githamza** [comment]
I'm thinking about an algorithm who can help people in my case.
in input : possibles delimiter in my case : `[',',';']` .
split every line of the csv file by `,` and then `;` than save length of every split.
If the length of one of the split output changes at a moment that means that it's not the right delimiter. => the right one is the second.

**Comment by janisdd** [comment]
Hm, when I go to https://www.papaparse.com/demo and check
```csv
column ; comlumn2,comlumn2
column ; comlumn2,comlumn2
column ; comlumn2
```
it suggests `;` as a delimiter in the console.

Splitting is probably not working because the fields might be escaped, e.g. `"col1,col1" ; col2`.
I fear I don't fully understand your suggestion... you want to use the delimiter with the 2nd most fields?

**Comment by Githamza** [comment]
I want to find the delimiter ´,´ here is ´;´ but papaparse detects ´,´ , so I suggested to check line by line and check which delimiter is more stable

**Comment by janisdd** [comment]
Probably the easiest way would be to make the internal `guessDelimiter` accessible as config option. Could also solve https://github.com/mholt/PapaParse/issues/804

**Comment by pokoli** [comment]
I do not think we should complicate more the guessing and we should assume that is not perfect (specially when mixing delimiters on data). 
There is already an option to specify the delimiters to guess (and its a sorted list allowing to prefer `;` over `,`).  You should use if required. 

I'm closing this issues as there is nothing else to do from our side. If yo do not agree, please provide some simple solution for your case. 

Thanks!
