### ISSUE TITLE
detecting delimiter only on header

### ISSUE THREAD

**Issue by Githamza** [mholt/PapaParse#861]
I would like to know I there is a way to apply auto detection of delimiter only on header line ?

**Comment by janisdd** [comment]
Assuming your header line is the first line

```js
var myCsvData = 'your csv data'
var myDelimiter = Papa.parse(myCsvData, {preview:1}).meta.delimiter

var result = Papa.parse(myCsvData, {delimiter: myDelimiter})
```

**Comment by Fabianopb** [comment]
Hey, I tried this out with this data:
```
item_id;description
my-item-id;One, two, three, four, five.
```
It returned `,` as the delimiter when it should've been `;`, right?

**Comment by pokoli** [comment]
Guessing is guessing, we can not provie always the right values. 
PapaParse always uses a fixed value of 10 valeues for preview, so it's expected that returns `,` because: 

1. Is prefered over `;`
2. It appears more time. 

So if you want to have better guessing provide a bigger set.

If guessing does not work right for you just specify the delimiter or at lest the `delimiterstoGuess`

**Comment by janisdd** [comment]
Ah, I don't know what I was thinking when I wrote this...
This is the correct solution (now also tested ;)

```js
var myCsvData = `item_id;description
my-item-id;One, two, three, four, five.`

//get the first row only but delimiter might be guessed wrong
var firstRowTmp = Papa.parse(myCsvData, {preview:1})
//guess the delimiter only of the first row
var delimiterOfFirstRow = Papa.parse(firstRowTmp.data+'').meta.delimiter
console.log(delimiterOfFirstRow)
 // ;
var parseResult = Papa.parse(myCsvData, {delimiter:delimiterOfFirstRow})
console.log(parseResult.data) 
// [ ["item_id", "description"], ["my-item-id", "One, two, three, four, five."] ]
```

**Comment by Fabianopb** [comment]
Thanks @janisdd, that's what I was looking for!
I was not criticizing the library, just trying to use that proposed solution, which sounds fair.
