### ISSUE TITLE
Encoding problems with currency signs inside csv file

### ISSUE THREAD

**Issue by kresogalic8** [mholt/PapaParse#864]
Hey there, nice work with Papaparse :)

I have one problem with different csv files where i have currency signs inside, and i get the results with question mark inside string. Here is the screenshot so you can better understand what i mean.

![Screenshot 2021-04-06 at 15 38 48](https://user-images.githubusercontent.com/7289406/113719723-37f33280-96ee-11eb-8fda-94af68c18fb0.png)

I used **encoding: 'utf-8'** but its not working if i pass that in params. What do you think its the problem? Let me know if you need an example of CSV file

**Comment by pokoli** [comment]
It seems that your file is not encoded using `utf-8` but other encoding and this makes the symbol to shown as unknow values. 

Using the right encoding for the file should fix the issue.

**Comment by kresogalic8** [comment]
So what i need to do is to export my CSV file with encoding utf-8? is there any chance to convert each file i upload to have proper encoding before i parse everything?

**Comment by pokoli** [comment]
It depends on the software you use to export it. But most of the software have an option to select the encoding.
For example, you can use libreoffice to open a CSV file with an enconding and then export it using a diferent encoding.

Enconding detection and convertion is out of the scope of papaparse functionalities.

**Comment by kresogalic8** [comment]
The problem is that we will have many different CSV files with different encoding, and we need to convert encoding to be good for Papaparse to show correctly all currency signs.
