### ISSUE TITLE
Publish documentation for previous versions

### ISSUE THREAD

**Issue by kgehmlich** [mholt/PapaParse#870]
Currently only the documentation for v5 is published to GitHub Pages. For those of us stuck using previous versions, the only way to access documentation is to dig into specific, release-tagged commits on GitHub and read the HTML directly.

It would be nice if the published docs contained version links (and the associated docs) for each major version.

If it helps I'd be happy to put together a PR.

**Comment by pokoli** [comment]
Sorry to border you but I'm wondering if it won't be easier to upgrade to newer versions Instead of giving more work to the maintaners (who are doing it for free on our spare time).

Did you have any reason to no update?

**Comment by kgehmlich** [comment]
I'm all for updating, but in cases where this is being used in production it can be more trouble than it's worth to upgrade to a new major version. Ensuring nothing gets broken in a subtle way can be tedious at best and near impossible at worst.

I hear what you're saying, though. If there's not enough demand for this we can close the ticket and when I have a few hours free I'll see if I can put together a multi-version docs page that will be easy to maintain.
