### ISSUE TITLE
Not able to use config object properly

### ISSUE THREAD

**Issue by coderrsid** [mholt/PapaParse#885]
How can i remove backslashes and pipes while parsing it through papaparse using config object properties? 
String: `
A, b, c,,
\Cod, e|f, f,,
de|\f, \g,,,
`

Also, can you please elaborate `escapeChar` and `quoteChar` property? I couldn't understand from docs.

**Comment by pokoli** [comment]
You can no escape characters. Just parse the CSV file and remove it latter. 

Sorry, we do not provide user support from github issues, here is only to report bugs or requests new features on the library. 
Please use stackoverflow for user support.
