### ISSUE TITLE
Quick way to determine if the content is csv?

### ISSUE THREAD

**Issue by dylans** [mholt/PapaParse#886]
Is there a quick method to call or a suggested approach to identify if content is valid csv (by valid I mean a format that PapaParse believes to be csv) before fully parsing the contents?

My use case is to support handling paste of both markdown and csv, both of which report as text/plain when pasted afaik. 

I'm thinking something like parse the first two lines, and if there are no errors, assume it's csv, otherwise send it along to the markdown parser.

**Comment by pokoli** [comment]
You can use the `preview` configuration value to limit the number of rows to parse. If the file is not a valid file you will get an error. If the preview is right you will get the contents. 

You have the f[ull details on our documentation](https://www.papaparse.com/docs#config).
