### ISSUE TITLE
[bug] Values with spaces parse correctly but are quoted when unparsed

### ISSUE THREAD

**Issue by niedzielski** [mholt/PapaParse#888]
Hello! Thank you for this library. I am accustomed to writing my parser tests such that `unparse(parse(input)) === input` and have uncovered a case where this fails in Papa Parse for values containing spaces:

```js
const input = " a \t text \t c \n 1 \t 2 \t 3 ";
const parsed = Papa.parse(input);
const unparsed = Papa.unparse(parsed.data, {
  delimiter: "\t",
  newline: "\n"
});

console.log(`Parsed: '${JSON.stringify(parsed, null, 2)}'`);
console.log(`Unparsed: '${unparsed}'`);
console.log(`Input: '${input}'`);
```
(Also available as a [CodePen](https://codepen.io/stephen/pen/PomQXgZ?editors=1010).)

Which produces:

```
Parsed: '{
  "data": [
    [
      " a ",
      " text ",
      " c "
    ],
    [
      " 1 ",
      " 2 ",
      " 3 "
    ]
  ],
  "errors": [],
  "meta": {
    "delimiter": "\t",
    "linebreak": "\n",
    "aborted": false,
    "truncated": false,
    "cursor": 26
  }
}'
Unparsed: '" a "	" text "	" c "
" 1 "	" 2 "	" 3 "'
Input: ' a 	 text 	 c 
 1 	 2 	 3 '
```

Notice that each value is parsed correctly but is unparsed as quoted. For example, the input `\x20a\x20` becomes unparsed as `"\x20a\x20"` which I think is unexpected. I reviewed [the docs](https://www.papaparse.com/docs#json-to-csv) and experimented with the options but none seemed to apply.

**Comment by pokoli** [comment]
As far as the unparsed data is valid (which is the case). There is no issue on it. 
Indeed if you parse the unparsed data back you should see the same data.
