### ISSUE TITLE
Better support for duplicate headers please

### ISSUE THREAD

**Issue by larsville** [mholt/PapaParse#890]
Consider a CSV file in which not all headers are unique, e.g. "Name","Nickname","Nickname". This is valid CSV, even if uncommon. PapaParse doesn't have a great way to deal with this condition.

If I specify that there **is** a header, then header names are used as keys in each record object, and some fields values are lost because the keys are not unique. That's not acceptable for my purposes.

If I specify that there is **no** header, then indexes are used for each record, and I must do extra processing in order to treat the first record as the header that it really is.

My current workaround is to specify that there is no header, and post-process the header line in the callback after parsing is complete. I think it would be better if the PapaParse API had an explicit way to handle this condition, but if nothing else, the documentation should warn the user about it.

**Comment by pokoli** [comment]
How do you spect that PapaParse will handle this case?

**Comment by thewordisbird** [comment]
I'm dealing with this on a project right now. I was thinking of a hook to incorporate middleware in the parse. Then the user could modify the field names or what ever other modifications would be required that can't be performed once the parse is complete.

**Comment by pokoli** [comment]
@thewordisbird in this cas is just as easy as parse the file without headers and then create the right data structure after parsing. 

I will prefer to not polute the code with _middlewares_ when the developer can do the same work after parsing. 
And if you want to avoid parsing the full content twice, please consider using `preview` to read the first row and then setting the `header` with the desired header names. Have a look at our documentation to see the full usage. 

I'm closing this issue as there is no thing to do from our side.
