### ISSUE TITLE
How to catch error if remote CSV is inaccessible?

### ISSUE THREAD

**Issue by iamkeir** [mholt/PapaParse#891]
When using [Papa Parse][1], you can access CSV errors via `result.errors` within the `complete` callback, but how do I catch error if remote CSV is inaccessible (e.g. 404)?

```
Papa.parse(csv_remote_url, {
  download: true,
  header: true,
  complete: function(result) {
    console.log(result.errors);
  }
});
```

Thanks!

[1]: https://www.papaparse.com/

**Comment by pokoli** [comment]
Hi @iamkeir 

The issue tracker is to report bugs and new features.

Please use the [papaparse tag on SO to get support questions.](https://stackoverflow.com/questions/tagged/papaparse)

**Comment by iamkeir** [comment]
@pokoli yes, I know, apologies - I used SO but getting 🦗
https://stackoverflow.com/questions/68683643/papa-parse-how-to-catch-error-if-remote-csv-is-inaccessible
