### ISSUE TITLE
Can I use titles on row ?

### ISSUE THREAD

**Issue by bhargu-27** [mholt/PapaParse#892]
Hello, 
I want to convert json to csv 
In papaparse it is working properly but i want to convert it in row wise 
For example
Heading 1 answer 1_0 answer 1_1 answer 1_2
Heading 2 answer 2_0 answer 2_1 answer 2_2 
And so on 
So is there any feature for it , I can use it 

Thanks

**Comment by pokoli** [comment]
Hi @bhargu-27 

The issue tracker is to report bugs and new features.

Please use the [papaparse tag on SO to get support questions.](https://stackoverflow.com/questions/tagged/papaparse)
