### ISSUE TITLE
Parse not firing only in React production build (fine on dev)

### ISSUE THREAD

**Issue by bdata42** [mholt/PapaParse#905]
Hi, just throwing this out there in case anyone has any advice!

I'm using papaparse in a React app like so:

```
        parse(url, { //remote url, public CSV file
          download: true,
          header: true,
          // delimiter: ',',
          skipEmptyLines: true,
          complete: (results, file) => {
            if (results.errors && results.errors.length) {
console.log(errors)
}
}})
... //etc
```

When running locally, the parse function returns complete and I receive the results. No errors.

However, in production mode after running `yarn build`, suddenly the parse function no longer runs at all. I never receive anything. It just fails to work whatsoever with no clue.

Is there anything I might try?

Any help greatly appreciated!

**Comment by pokoli** [comment]
We do not offer support on github issues, just reports about improvements or bugs in the library. Please use StackOverflow for that. 

I guess your prolbem is related to the library not beeing installed on the production build.
