### ISSUE TITLE
Unable to get right delimiter

### ISSUE THREAD

**Issue by jrabello** [mholt/PapaParse#910]
Can you guys help me to understand why papaparse is giving me the wrong delimiter for the following input?

```
nome;telefone
Jessica;5,58199E+12
Joi;5,51197E+12
Bea;5,582E+12
```

**Comment by pokoli** [comment]
Because the number of , is the same as the number of ;
So one takes precedence from the other. 

Paparse is not perfect guessing, the best is to specify the delimiter if you know it in advance.

**Comment by jrabello** [comment]
so, in the example above we have 4 ';' and 3 ',' right? so the number of ';' is bigger, not the same 

dont you think the algorithm should give a bigger weight to possible delimiters found on csv header???

**Comment by pokoli** [comment]
Did you have any idea on how to improvie it?
