### ISSUE TITLE
How to export nested 

### ISSUE THREAD

**Issue by veritem** [mholt/PapaParse#913]
I'm working with JSON data which has nested fields how but PapaParse returns [object] for nested objects. How can I extract some fields from a nested json

**Comment by pokoli** [comment]
This is not supported (and we do not plan to support it). You should transform your data before passing it to PapaParase

**Comment by CarlosNZ** [comment]
Just wondering why this is not something you would support? Not suggesting any processing of the actual data, but a simple `JSON.stringify()` around it seems straightforward (that's what I'm doing upstream currently since it's not supported)
