### ISSUE TITLE
[Cannot read properties of null (reading 'replace')] error when quoteChar = null

### ISSUE THREAD

**Issue by Gretam11** [mholt/PapaParse#914]
Hi!
I use papa parse for a long time, and that is the first problem I found throughout my experience with it.
It's not very important but it took me some time to understand the source of the issue, 
so even if it's not fixed maybe this github issue will help someone in the future.

### The problem
When the `quoteChar` is set to `null`, and you have `'null'` string in the parsed file - an unexpected exception appears and parsing process terminates without calling any of the (error/complete) callbacks.

### Example
1. Open papa parse [demo page](https://www.papaparse.com/demo) and open console.
2. Execute the following code: 
```
Papa.parse(
    new File(['Franziska;Knull'], 'some-file.csv', {type: 'text/csv', lastModified: 1572878339451}), 
    {delimiter: ';', quoteChar: null, error: () => console.log("error"), complete: () => console.log("complete")},
)
```
3. Observe the error in console:

![image](https://user-images.githubusercontent.com/19823838/150367334-81ef889f-6870-428c-a094-b93d0060dd4c.png)

### Workaround
When you do not need any `quoteChar` just set it to `undefined` or `''` (empty string), then it works as expected.

Thanks!

**Comment by chafi9-code** [comment]
Hi,

I made a PR that fixes this issue if you can review it :)
