### ISSUE TITLE
Want customize the csv, By adding images and by creating a bold header

### ISSUE THREAD

**Issue by chhrahul** [mholt/PapaParse#916]
![Screenshot_27](https://user-images.githubusercontent.com/5475401/151553362-bf9d94b7-f698-4e73-bf32-cab6191a556f.png)
Hi there , 
I have used PapaParse to import json data into csv using vue Js . Now I want to customize my csv by adding the Image and making the header and footer bolder. Can you help me on it ? I  have read the whole documentation but did not get to much idea about it . I have attached a file along with it please have look to it and tell is there any possibility to generate csv like it

**Comment by pokoli** [comment]
CSV does not have any format. You should use a another spreadsheet document and this is out of the scope of PapaParse.
