### ISSUE TITLE
Unexpected parse error

### ISSUE THREAD

**Issue by GoldenFinch** [mholt/PapaParse#930]
When I want to parse my csv file and then I found it didn't work as I expected.

Here I simplify the csv file, since it's a string after reading the file.
![image](https://user-images.githubusercontent.com/57383727/163936997-dc3d7f9a-43be-4b9d-97ab-25a7df69baf6.png)

const parse = (res: any) => {
    return new Promise((resolve) => {
      Papa.parse(res, {
        complete: (results: { data: any[] }) => {
          resolve(results.data)
        },
      })
    })
  }

  const getParse = async () => {
    const res = `driver_id,exception_dates
1202071166,01/04/2022;02/04/2022;05/04/2022;06/04/2022
`
    console.log(res)
    const data = await parse(res)
    console.log(data)
  }

and then, we get the result:
<img width="603" alt="image" src="https://user-images.githubusercontent.com/57383727/163936600-0751cbf4-4f58-4f12-89eb-c6856a1c8acf.png">

Actually i want to parse the string and split by symbol "," , but It is splitted by symbol ";".

Can someone help me solve this problem?

**Comment by KuryKat** [comment]
Hey, when you don't define a delimiter [1](#attachment-1) on the options, papaparse will guess the delimiter from the option "delimitersToGuess" [2](#attachment-2)

#### Attachment 1
![image](https://user-images.githubusercontent.com/57152799/164191519-8971ddeb-6720-431a-992b-9871302cf2f1.png)

#### Attachment 2
![image](https://user-images.githubusercontent.com/57152799/164191638-ad3f5e63-800d-45c2-ba43-dcf7931d71f2.png)

**Comment by GoldenFinch** [comment]
It works! Thank you very much!

**Comment by KuryKat** [comment]
You welcome! ❤🙌
|| remind: close the issue ||
