### ISSUE TITLE
Uncaught TypeError: Cannot read property 'substr' of null 

### ISSUE THREAD

**Issue by connor11528** [mholt/PapaParse#94]
I have a 139mb csv file I'd like to parse on the client

```
Papa.parse('../../data/OPD_140722_1.csv', {
    download: true,
    worker: true,
    step: function(row) {
        console.log("Row:", row.data);
    },
    complete: function() {
        console.log("All done!");
    }
});
```

Using this code I get the error: `Uncaught TypeError: Cannot read property 'substr' of null` from papaparse.js line 520, which is about the XHR header:

```
function getFileSize(xhr)
        {
            var contentRange = xhr.getResponseHeader("Content-Range");
            return parseInt(contentRange.substr(contentRange.lastIndexOf("/") + 1));
        }
```

So I guess the XHR doesn't have a "Content-Range" header? The file is sitting on a server I fire up with `python -m SimpleHTTPServer`

**Comment by kokes** [comment]
Brilliant, spark works like a charm! Before this gets resolved, do you think it would be helpful to tell the user about any of this? Just a simple `if (contentRange == null) throw/console.log` affair, the current error induced by `substr` is a bit cryptic, took me a while to track this all the way here. But at least dug around the code a bit while doing so, made me appreciate all work done on this project.

(I installed python3, thinking the 'new' `-m http.server` would make any difference, but no luck)

**Comment by mholt** [comment]
@kokes Pull requests welcome; I haven't had time or funding to maintain this project lately.

**Comment by griii2** [comment]
Hi guys

just came here to say I have the same problem when trying to stream the file from a localhost created by WebStorm. I am just an user and I have no idea what server is that or what is "Content-Range" header. Thanks

**Comment by skibulk** [comment]
This issue is solved by this pull request: https://github.com/mholt/PapaParse/pull/325
