### ISSUE TITLE
Csv-edit: Initially Fixed Columns Left

### ISSUE THREAD

**Issue by thomasluxton** [mholt/PapaParse#943]
Setting the Fixed Colums Left parameter in the settings doesn't seem to fix the first row. Manually adjusting the value in the gui, seems to re-enable the feature.
![image](https://user-images.githubusercontent.com/79663182/181281639-f352e9d8-6727-4e44-b568-05f6e5349128.png)

**Comment by pokoli** [comment]
Not sure what is your screenshot but PapaParse does not have any GUI. So it seems you reported the issue to the wrong project.

**Comment by thomasluxton** [comment]
Sorry, I did! Hello from another project!
