### ISSUE TITLE
Papaparse returns name of the csv file as the result

### ISSUE THREAD

**Issue by Amaeta** [mholt/PapaParse#945]
Please I need an urgent help.

I have successfully used Papaparse on Android but same application returns name of the csv file as the result when running on xcode platform.
CSP: <meta http-equiv="Content-Security-Policy" content="img-src * 'self' data:; default-src * 'self' gap: wss: ws: ; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline' 'unsafe-eval';">

Part of the Papa Parse:
Papa.parse('cities5000.csv', {
			//delimeter: ',',
			//download: true,
			complete: function(results) {
				alert(JSON.stringify(results));
				var lines=results.data;

My result:
![Simulator Screen Shot - iPhone 12 Pro - 2022-08-08 at 20 26 47](https://user-images.githubusercontent.com/37544524/183499717-5cd81eb7-4cd4-47eb-b42e-bddc1f6ded51.png)

Not sure what I have done wrong or not doing right.

**Comment by pokoli** [comment]
We do not provide support on issues, so I'm closing this.

**Comment by Inventsable** [comment]
I had the same issue due to the ambiguous documentation. You should be passing the string of the file contents instead of the string of the filepath.
