### ISSUE TITLE
Access delimiter in config?

### ISSUE THREAD

**Issue by yermasog** [mholt/PapaParse#954]
When using the default/auto detect for the delimiter, is there any way to access what the delimiter is? I see that you can access the delimiter in the 'meta' object but that's only after the file has already been parsed.  I have a transform function that should only be called if the delimiter is a semicolon.

**Comment by pokoli** [comment]
I do no think we should support this, for such case you should guess the delimiter manually and then pass the required configuration based on your guessings.
