### ISSUE TITLE
Google Sheets Implementation

### ISSUE THREAD

**Issue by rphad23** [mholt/PapaParse#962]
I was following this guide:
https://css-tricks.com/creating-an-editable-webpage-with-google-spreadsheets-and-tabletop-js/

when i saw that Tabletop.js no longer works. It forwarded me to PapaParse, but i am new to this and i don't know how to implement it. 

I used this code:
`function init() {
          Papa.parse('https://docs.google.com/spreadsheets/d/e/2PACX-1vRB4E_6RnpLP1wWMjqcwsUvotNATB8Np3OntlXb7066ULcAHI9oqqRhucltFifPTYNd7DRNRE56oTdt/pub?output=csv', {
          download: true,
          header: true,
          complete: function(results) {
            var data = results.data
            console.log(data)
          }
        })
window.addEventListener('DOMContentLoaded', init)`

from the tabletop GitHub https://github.com/jsoma/tabletop

The problem is that i cant figure out how to reference my sheet. With tabletop i could say

`function showInfo(data, tabletop) {
  data.forEach(function(data) {
    header.innerHTML = data.header;
    header2.innerHTML = data.header2;
    body.innerHTML = data.body;
    body2.innerHTML = data.body2;
    body3.innerHTML = data.body3;
    body4.innerHTML = data.body4;
    body5.innerHTML = data.body5;
    body6.innerHTML = data.body6;
    body7.innerHTML = data.body7;
    body8.innerHTML = data.body8;
    body9.innerHTML = data.body9;
    body10.innerHTML = data.body10;
    body11.innerHTML = data.body11;
    body12.innerHTML = data.body12;
    body13.innerHTML = data.body13;
    body14.innerHTML = data.body14;
    body15.innerHTML = data.body15;
    body16.innerHTML = data.body16;
    body17.innerHTML = data.body17;
 });
}
window.addEventListener('DOMContentLoaded', init)`

and it would work, but it does not. I would love some help ASAP.

**Comment by pokoli** [comment]
Hi @rphad23, 

We do not provide user support on this issue tracker, it is just used to report bugs and improvements of the library. 
I will suggest you to post your code as stackoverflow question. You will have more changes to get support there. 

Thanks for your comprehension.
