### ISSUE TITLE
I can't parse any CSV file 

### ISSUE THREAD

**Issue by Kebabrock0** [mholt/PapaParse#963]
I am trying parse a data from a csv file i have a input

`const [data, setData] = useState([]);

  const handleFileInput = async (event) => {
    // Load the data from the CSV file
    const file = event.target.files[0];
    const csvData = await Papa.parse(file, {
      header: true,
      skipEmptyLines: true,
    });
    setData(csvData.data);
  };
return (
    <>
      <input type="file" onChange={handleFileInput} accept=".csv" />
      {data.length > 0 && (
        <table>
          <thead>
            <tr>
              {Object.keys(data[0]).map((key) => (
                <th key={key}>{key}</th>
              ))}
            </tr>
          </thead>
          <tbody>
            {data.map((row) => (
              <tr key={row.id}>
                {Object.values(row).map((value) => (
                  <td>{value}</td>
                ))}
              </tr>
            ))}
          </tbody>
        </table>
      )}
    </>
  );
}`

But it is causing Uncaught (in promise) TypeError: csvData is undefined

**Comment by pokoli** [comment]
This bug tracker is not for support but just to report issues wwith the library. 
Please use stackoverflow for support.
