### ISSUE TITLE
Issue with making header as "true"

### ISSUE THREAD

**Issue by kishore15421** [mholt/PapaParse#965]
![image](https://user-images.githubusercontent.com/48830394/209690526-78859fc8-c1fe-45b8-94fc-c00d81887244.png)
Hi Team,

    I have a csv file which is having only header row. when I'm parsing the local file getting response data as [](empty array) Instead of [{}]. and below is the code i used. Please test and fix this.

   Papa.parse(acceptedFiles[0], {
        header: true,
        skipEmptyLines: true,
        complete: function (results) {
            console.log(results.data)
         }
    }).

For reference, I'm attaching the in app test screenshot below
![image](https://user-images.githubusercontent.com/48830394/209691092-5e842e83-5604-430b-bb9c-204265766f04.png)

**Comment by pokoli** [comment]
Which is the issue with the empty array? As far as the value is empty I do not see an problem.

**Comment by kishore15421** [comment]
But we have one headers(title) row data right? @pokoli . at least we should get some information about that. I mean need an field names as an object. so that user know that their file having some information
![image](https://user-images.githubusercontent.com/48830394/209776326-348b2c7b-94cb-4022-83a0-51c3a533b940.png)

**Comment by pokoli** [comment]
If you use headers there is no information as the header row is not any data just metadata. 
If you want to get the headers as data you should not activate the headers flag. In such case the first row will contain the name of the headers.
