### ISSUE TITLE
add new column and chunk

### ISSUE THREAD

**Issue by architucas** [mholt/PapaParse#969]
So, I have a large csv file which I want to upload to remote server. Because this is a large file, I'm chunking it (chunk size 5MB) using `chunk` and `chunkSize ` config option and it's working fine. but we have another requirement. the original CSV from our customer contains `first name` and `last name` column. for our needs, we need `full name`, which is a simple concatenation of `first name` and `last name`. so, I want to add this new `full name` column to all rows in the CSV and still chunk it at 5MB. does `papaparse `provide this functionality out of the box? Thanks

**Comment by pokoli** [comment]
The objective of PapaParse is just to parse the file. If you want to  have a new column you just alter the data after parsing. 
This is out of the scope of the library. Thanks.
