### ISSUE TITLE
Calling Papa.parse in worker with _config.worker = false calls postMessage

### ISSUE THREAD

**Issue by andreaskundig** [mholt/PapaParse#970]
This bug is well described in [stackoverflow](https://stackoverflow.com/questions/61513192/calling-papa-parse-in-worker-with-config-worker-false-calls-postmessage):

I am calling Papa.parse in my own worker and in _config.worker is set false. When process completes it calls postMessage still that triggers a message to my own worker. Shouldn't [this](https://github.com/mholt/PapaParse/blob/master/papaparse.js#L529)

```
if (IS_PAPA_WORKER)
{
    global.postMessage({
        results: results,
        workerId: Papa.WORKER_ID,
        finished: finishedIncludingPreview
    });
}
```

Should also check if config.worker is set to true then only call global.postMessage I don't want to send results to main thread any idea how can i achieve it ?

The accepted answer is a hack that no longer works, because self.document is not writable

**Comment by pokoli** [comment]
As commented on the MR, we do not want to have some behaviour that goes against the [standard](https://html.spec.whatwg.org/multipage/workers.html#infrastructure-2)

**Comment by andreaskundig** [comment]
The standard explicitely mentions that you can create a worker from a blob that will have an opaque origin:

>    Any [same-origin](https://html.spec.whatwg.org/multipage/browsers.html#same-origin) URL (including [blob:](https://w3c.github.io/FileAPI/#DefinitionOfScheme) URLs) can be used. [data:](https://www.rfc-editor.org/rfc/rfc2397#section-2) URLs can also be used, but they create a worker with an [opaque origin](https://html.spec.whatwg.org/multipage/browsers.html#concept-origin-opaque).

As you can see [on mdn](https://developer.mozilla.org/en-US/docs/Web/API/Worker#constructors), building a worker from a blob url is implemented in all browsers.

This is essential when you have workers in a library intended to used on any website by adding a script tag to import it from a cdn. 

The library I'm working on calls papaparse in a worker. I explicitely disable the papaparse worker with the configuration, however papaparse still calls self.postmessage. How is that not a bug? 

Please reopen this issue.

**Comment by andreaskundig** [comment]
Here's a nice explanation for this use case from 2012. People have been doing this for more than ten years now.

https://web.dev/workers-basics/#inline-workers

**Comment by andreaskundig** [comment]
Look at web.dev's [about page](https://web.dev/about/) if you have any doubts on the legitimacy of this advice

> **Guidance from Chrome Developer Relations**
>
> We want to help you build beautiful, accessible, fast, and secure websites that work cross-browser, and for all of your users. This site is our home for content to help you on that journey, written by members of the Chrome team, and external experts.

**Comment by pokoli** [comment]
None of the links explains why we should alter our code.

**Comment by andreaskundig** [comment]
Thanks for the quick response, I can hardly keep up :)

The links make the point that it's legitimate to inline Workers. Meanwhile I noticed that this trick is even used in[ Papaparse's code](https://github.com/mholt/PapaParse/blob/aa0046865f1b4e817ebba6966d6baf483e0652d7/papaparse.js#L49). So I guess we agree about that now?

In that case it's also legitimate to use papaparse in an inlined worker. That's when the problem happens.

The worker sends its data to its listener by calling self.postMessage(myData). However the listener receives two messages, one that is sent by papaparse, and myData. In my [code](https://github.com/hestiaAI/hestialabs-experiences/blob/c3b1184995dd6ed25b0948ab6354647eb5fd18b3/data-experience/src/utils/utils.js#L75-L103), I wrote an ugly hack to ignore the message sent by papaparse.

The reason papaparse sends a message is because it has it's own code calling postMessage for the situation where it is used as a worker. This is not the case here, and you can explicitely configure papaparse to not behave as a worker by setting config.worker=false, but this flag is ignored, and postMessage is call anyway. There is a boolean IS_PAPA_WORKER that would prevent postMessage, but in this situation the boolean is true.

It would make sense to prevent postMessage when config.worker=false. Now that I look at it, maybe it would work if I set self.IS_PAPA_WORKER = false before importing papaparse? Is this the way it's supposed to be done? It seems weird to configure Papaparse through a global variable when there's a config object that seems made for that.

**Comment by pokoli** [comment]
For me the soultion is setting `IS_PAPA_WORKER` to false.

**Comment by andreaskundig** [comment]
That doesn't work in the most recent version 5.3.2. 

It's possible that it would work with the most recent code, seeing that the initialization of IS_PAPA_WORKER has changed, but I'm not entirely sure. 

Do you have any idea when the most recent code will be released in a new version?

**Comment by andreaskundig** [comment]
Ok it turns out the change was made explicitely to fix this issue 
https://github.com/mholt/PapaParse/issues/788
