### ISSUE TITLE
Partial import is not working

### ISSUE THREAD

**Issue by QuentinNativel** [mholt/PapaParse#973]
Hi guys,

I'm using papaparse to parse a csv file on a typescript project.

### Problem
When I test locally the following piece using vitest:
```typescript
import { parse } from 'papaparse' 

const { data } = parse('');
```

I've got the following error:
**TypeError: parse is not a function**

And when i log parse it is **undefined**.
Also typescript doesn't detect any error in my IDE

This piece of code works though
```typescript
import Papa from 'papaparse';
const { data } = Papa.parse('');
```

### Expected behaviour
I would expect the first example to be valid. It is a good practice, at least in my team to import only the needed dependencies from a package

**Comment by pokoli** [comment]
For now the library does not support ES6 imports syntax. 
This is a requuested feature request but nobody worked on it. See https://github.com/mholt/PapaParse/issues/813
