### ISSUE TITLE
Chunks being cut and adding weird values when error comes

### ISSUE THREAD

**Issue by maurobilotti** [mholt/PapaParse#981]
I'm working in a project that needs to parse huge files that are in CSV and after every chunk send the data over the network.

DISCLAIMER: The file is fine, I copy pasted the same value multiple times, so the issue I know it's in the library or some misconfiguration.

After the first chunk is processed I see that is cutting the first values of the word "InProgress", as you can see in the following .gif

[screen-capture.webm](https://user-images.githubusercontent.com/4137980/224092551-a0dfdcb9-3682-4eb0-9b9d-691f8def514c.webm)

And reaching the final chunk, it comes with an error and shows some random values starting with "_" and followed by a number:

![image](https://user-images.githubusercontent.com/4137980/224096315-ee1a0422-432d-4ac7-a141-dea6f85920d9.png)

Those values, **for sure** doesn't exist in the file provided. 

I don't know if this is related to the chunkSize that is cutting values because some are exceeding the size of the chunk. I tried by setting different values in `skipEmptyLines`, `fastMode` and also using the step function with similar results. 

My configuration looks like this:

```
Papa.parse(file, {
      header: true,
      skipEmptyLines: false,
      fastMode: true,
      chunk: async function (chunk, parser) {
        if (dataMigrationBulkUploadStore.getRawState().shouldAbortUpload) {
          dataMigrationBulkUploadStore.update((s) => {
            s.showCancelledSnackbar = true;
          });
          parser.abort();
          return;
        }

      parser.pause();

      if (chunk.errors.length) {
        dataMigrationBulkUploadStore.update((s) => {
          s.shouldAbortUpload = true;
          s.showCancelledSnackbar = true;
          s.cancelledSnackbarMessageId = "bulkUploadFileContentError";
        });
        parser.abort();
        return;
      }

      const data = getNeededData(chunk.data, columnMappings);

      const importDataRequest = new ImportDataRequest({
        data,
        columnMappings,
        rowIndex,
      });

      rowIndex += data.length;

      try {
        await migrationJobService.importJobData(importJobId, importDataRequest);

        dataMigrationBulkUploadStore.update((s) => {
          s.bulkUploadProgressStatus =
            s.bulkUploadProgressStatus! + progressStatusChunkSize;
        });
        parser.resume();
      } catch (err) {
        console.error(err);

        dataMigrationBulkUploadStore.update((s) => {
          s.shouldAbortUpload = true;
          s.showCancelledSnackbar = true;
          s.cancelledSnackbarMessageId = "bulkUploadNetworkError";
        });
        parser.abort();
        return true;
      }
    },
    chunkSize: 10000,
    complete: function () {
      dataMigrationBulkUploadStore.update((s) => {
        s.showBulkUploadProgress = false;
      });
      if (!dataMigrationBulkUploadStore.getRawState().shouldAbortUpload) {
        dataMigrationBulkUploadStore.update((s) => {
          s.showSuccessSnackBar = true;
          s.uploadCompleted = true;
        });
      }
    },
  });
```

I attach as well the file in use:
[UserRegistration.csv](https://github.com/mholt/PapaParse/files/10933997/UserRegistration.csv)

**Comment by chadhoward11** [comment]
I am seeing the same issue of _1, _2, being inserted in various column values.  I verified the original file is correct and never contain these odd values.  I had to revert back to version 5.3.x for now.

**Comment by Silentscripter** [comment]
Confirmed also on our side, a column on the last row gets _1 value even if empty

**Comment by pokoli** [comment]
Probably related to #980 Reopen with a minimal scenario if you do not agree
