### ISSUE TITLE
[Feature Request] uniqueHeaders

### ISSUE THREAD

**Issue by digitalgarbage** [mholt/PapaParse#983]
When header is set to true, I expect each csv column name to be unique. Papa Parse currently doesn't enforce this and just appends _[1..n] to duplicate column name. My suggestion would be to add a new option to config so that Papa Parse will report an error if there are duplicate column names.

**Comment by pokoli** [comment]
Should be fixed with https://github.com/mholt/PapaParse/commit/970c1dbaab0232c8d056ce1e58dbdcb5347e2206

**Comment by digitalgarbage** [comment]
Fixing column renaming bug doesn't have an effect on this feature request. I would like to use config where Papa Parse reports an error if there are duplicate headers.

**Comment by pokoli** [comment]
But Paparase is not a tool for validating data just parse them. 
So if you want to have an error in case of duplicate headers, just parse the first line without header option and check if there are duplicates there.

**Comment by digitalgarbage** [comment]
There are several ways to detect duplicate headers and do additional csv validation, but that is not my point. My point is that with csv parsing I expect :

1. no information is lost in the parsing process
2. information in the csv is not modified in any way, ie renaming columns.

Since js objects can't have duplicate keys I expect to get an error if the headers are turned on and there are duplicate column names in a csv.

In the previous version, data was overwritten with duplicate keys. While not perfect, this kind of behavior is somewhat logical.

If you want to improve this behavior then replacing it with automatic column renaming seems like a bad idea. Sure, it might be useful in certain situations but the default behavior shouldn't change original data by renaming columns in a arbitrary way.

Currently I'm not even asking to change the default behavior - I would just want to have config option to report an error when the given csv data cannot be correctly parsed as requested.
