### ISSUE TITLE
PapaParse putting one-word column name in quotes

### ISSUE THREAD

**Issue by janswist** [mholt/PapaParse#995]
I have a csv file and that's how PapaParse is rendering it:
```js
{
    'user': '...',
    answer: '',
    '1 msg': '',
    '2 msg': '',
    ads: '200',
    '': '',
    _1: '',
    _2: ''
  }
```

I don't know why `user` is in quotes and `answer` is not. How can I change it? I would understand if it's two-word name, but as a one-word it kinda doesn't make sense.

**Comment by pokoli** [comment]
Sorry but this is only for reporting issues with the library and not asking for support. 
Please use stackoverflow for support.
